Repository dotnet/maui, pull requests merged in 2021-08, with the labels that each got.

#1886 Apply Accessibility traits to controls that have TapGestureRecognizers
  src/Compatibility/Core/src/Android/Renderers/PageRenderer.cs
  src/Controls/samples/Controls.Sample/Pages/Core/TapGestureGalleryPage.cs
  src/Controls/src/Core/HandlerImpl/View.Android.cs
  src/Controls/src/Core/HandlerImpl/View.Impl.cs
  src/Controls/src/Core/Platform/Android/ControlsAccessibilityDelegate.cs
  src/Controls/src/Core/Platform/Android/Extensions/SemanticExtensions.cs
  src/Controls/src/Core/Platform/GestureManager/GestureManager.Android.cs
  src/Controls/src/Core/Platform/GestureManager/GestureManager.iOS.cs
  src/Controls/src/Core/Platform/SemanticExtensions.cs
  src/Core/src/Handlers/View/ViewHandler.Android.cs
  src/Core/src/Handlers/View/ViewHandler.cs
  src/Core/src/Platform/Android/AccessibilityDelegateCompatWrapper.cs
  src/Core/src/Platform/Android/MauiAccessibilityDelegateCompat.cs
  src/Core/src/Platform/Android/SemanticExtensions.cs
  src/Core/src/Platform/Android/ViewExtensions.cs
  src/Core/src/Platform/iOS/SemanticExtensions.cs
  src/Core/src/Platform/iOS/ViewExtensions.cs
Labels: area/a11y, area/gestures 🖖

#2069 Fix heading bug and templates semantics
  src/Controls/samples/Controls.Sample/Pages/Core/SemanticsPage.xaml
  src/Core/src/Handlers/View/ViewHandler.Android.cs
  src/Templates/src/templates/maui-mobile/MauiApp1/App.xaml
  src/Templates/src/templates/maui-mobile/MauiApp1/MainPage.xaml
  src/Templates/src/templates/maui-mobile/MauiApp1/MainPage.xaml.cs
Labels: area/a11y

#2314 Remove the Forms Previewer issue template
  .github/ISSUE_TEMPLATE/forms-previewer-bug-report.md
Labels: t/housekeeping ♻︎
