Repository dotnet/maui, pull requests merged in 2021-12, with the labels that each got.

#3351 Introduce IVisualDiagnosticsOverlay
  src/Controls/samples/Controls.Sample/Behaviors/TestWindowOverlay.cs
  src/Controls/samples/Controls.Sample/Pages/OthersPage.xaml
  src/Controls/samples/Controls.Sample/Pages/OthersPage.xaml.cs
  src/Controls/src/Core/HandlerImpl/Window/Window.Impl.cs
  src/Controls/tests/Core.UnitTests/WindowOverlayTests.cs
  src/Controls/tests/Core.UnitTests/WindowsTests.cs
  src/Core/src/Core/Extensions/VisualTreeElementExtensions.cs
  src/Core/src/Core/IAdorner.cs
  src/Core/src/Core/IVisualDiagnosticsOverlay.cs
  src/Core/src/Core/IWindow.cs
  src/Core/src/Core/IWindowOverlay.cs
  src/Core/src/Core/IWindowOverlayElement.cs
  src/Core/src/Core/WindowOverlayTappedEventArgs.cs
  src/Core/src/Handlers/Window/WindowHandler.Android.cs
  src/Core/src/Handlers/Window/WindowHandler.Windows.cs
  src/Core/src/Handlers/Window/WindowHandler.iOS.cs
  src/Core/src/Platform/Android/ViewExtensions.cs
  src/Core/src/Platform/Standard/ViewExtensions.cs
  src/Core/src/Platform/ViewExtensions.cs
  src/Core/src/Platform/Windows/ViewExtensions.cs
  src/Core/src/Platform/iOS/CoreAnimationExtensions.cs
  src/Core/src/Platform/iOS/ViewExtensions.cs
  src/Core/src/VisualDiagnostics/RectangleAdorner.cs
  src/Core/src/VisualDiagnostics/RectangleGridAdorner.cs
  src/Core/src/VisualDiagnostics/VisualDiagnosticsOverlay.Android.cs
  src/Core/src/VisualDiagnostics/VisualDiagnosticsOverlay.Standard.cs
  src/Core/src/VisualDiagnostics/VisualDiagnosticsOverlay.Windows.cs
  src/Core/src/VisualDiagnostics/VisualDiagnosticsOverlay.cs
  src/Core/src/VisualDiagnostics/VisualDiagnosticsOverlay.iOS.cs
  src/Core/src/WindowOverlay/WindowOverlay.Android.cs
  src/Core/src/WindowOverlay/WindowOverlay.Standard.cs
  src/Core/src/WindowOverlay/WindowOverlay.Windows.cs
  src/Core/src/WindowOverlay/WindowOverlay.cs
  src/Core/src/WindowOverlay/WindowOverlay.iOS.cs
  src/Core/tests/Benchmarks/Stubs/WindowStub.cs
  src/Core/tests/DeviceTests/Handlers/HandlerTestBase.Android.cs
  src/Core/tests/DeviceTests/Handlers/HandlerTestBase.Tests.cs
  src/Core/tests/DeviceTests/Handlers/HandlerTestBase.Windows.cs
  src/Core/tests/DeviceTests/Handlers/HandlerTestBase.iOS.cs
  src/Core/tests/DeviceTests/Stubs/StubBase.cs
  src/Core/tests/DeviceTests/Stubs/WindowStub.cs
  src/Core/tests/DeviceTests/TestCategory.cs
Labels: partner/ui-tools

#3599 Check for Element instead of VE on FindDispatcher
  src/Controls/src/Core/Application.cs
  src/Controls/src/Core/DispatcherExtensions.cs
  src/Controls/src/Core/Properties/AssemblyInfo.cs
  src/Controls/tests/DeviceTests/DispatchingTests.cs
  src/Controls/tests/DeviceTests/HandlerTestBase.cs
  src/Controls/tests/DeviceTests/Stubs/ContextStub.cs
  src/Controls/tests/DeviceTests/TestCategory.cs
Labels: area/controls 🎮

#3623 iOS set UserInteractionEnabled to true when adding gestures
  .vscode/launch.json
  src/Controls/samples/Controls.Sample/Pages/Core/DragAndDropBetweenLayouts.xaml
  src/Controls/src/Core/Platform/GestureManager/GestureManager.iOS.cs
  src/Controls/tests/DeviceTests/GestureTests.iOS.cs
  src/Controls/tests/DeviceTests/TestCategory.cs
Labels: area/Xaml </>

#3642 [Windows] Fix ImageButton Background
  src/Core/src/Handlers/ImageButton/ImageButtonHandler.Windows.cs
  src/Core/src/Handlers/ImageButton/ImageButtonHandler.cs
Labels: platform/windows 🪟, area/controls 🎮

#3635 ZIndex proof-of-concept
  src/Controls/samples/Controls.Sample/Pages/Layouts/ZIndexPage.xaml
  src/Controls/samples/Controls.Sample/Pages/Layouts/ZIndexPage.xaml.cs
  src/Controls/samples/Controls.Sample/ViewModels/LayoutsViewModel.cs
  src/Controls/src/Core/HandlerImpl/VisualElement/VisualElement.Impl.cs
  src/Core/src/Core/IView.cs
  src/Core/src/Handlers/Layout/ILayoutHandler.cs
  src/Core/src/Handlers/Layout/LayoutExtensions.cs
  src/Core/src/Handlers/Layout/LayoutHandler.Android.cs
  src/Core/src/Handlers/Layout/LayoutHandler.Standard.cs
  src/Core/src/Handlers/Layout/LayoutHandler.Windows.cs
  src/Core/src/Handlers/Layout/LayoutHandler.cs
  src/Core/src/Handlers/Layout/LayoutHandler.iOS.cs
  src/Core/src/Handlers/View/ViewHandler.cs
  src/Core/tests/Benchmarks/Stubs/StubBase.cs
  src/Core/tests/DeviceTests/Core.DeviceTests.csproj
  src/Core/tests/DeviceTests/Handlers/Layout/LayoutHandlerTests.Android.cs
  src/Core/tests/DeviceTests/Handlers/Layout/LayoutHandlerTests.Windows.cs
  src/Core/tests/DeviceTests/Handlers/Layout/LayoutHandlerTests.cs
  src/Core/tests/DeviceTests/Handlers/Layout/LayoutHandlerTests.iOS.cs
  src/Core/tests/DeviceTests/Stubs/StubBase.cs
  src/Core/tests/UnitTests/Layouts/ZIndexTests.cs
  src/Core/tests/UnitTests/TestClasses/ViewStub.cs
Labels: proposal/open, area/layout 🔲

#3232 WinUI3 Interop for share and file picker
  src/Essentials/samples/Samples/Startup.cs
  src/Essentials/src/FilePicker/FilePicker.uwp.cs
  src/Essentials/src/MediaPicker/MediaPicker.uwp.cs
  src/Essentials/src/Platform/Platform.uwp.cs
  src/Essentials/src/Share/Share.uwp.cs
Labels: area/essentials 🍞

#3659 Item Template updates for C# 10isms
  src/Templates/src/templates/maui-contentpage-csharp/NewPage1.cs
  src/Templates/src/templates/maui-contentpage-xaml/.template.config/template.json
  src/Templates/src/templates/maui-contentpage-xaml/NewPage1.xaml.cs
  src/Templates/src/templates/maui-contentview-csharp/NewContent1.cs
  src/Templates/src/templates/maui-contentview-xaml/.template.config/template.json
  src/Templates/src/templates/maui-contentview-xaml/NewContent1.xaml.cs
Labels: area/templates 📄

#3674 Bump JDK to JDK 11
  eng/provisioning/provisioning.csx
Labels: t/housekeeping ♻︎

#3656 Fix warnings from #3519
  src/Controls/src/Core/Layout/AndExpandLayoutManager.cs
Labels: area/layout 🔲

#3680 Disable Interpreter for templates
  src/Templates/src/templates/maui-blazor/MauiApp.1.csproj
Labels: do-not-merge

#3582 Fix publishing WPF/WinForms Blazor apps with MSIX
  src/BlazorWebView/src/WindowsForms/BlazorWebView.cs
  src/BlazorWebView/src/WindowsForms/build/Microsoft.AspNetCore.Components.WebView.WindowsForms.targets
  src/BlazorWebView/src/Wpf/BlazorWebView.cs
  src/BlazorWebView/src/Wpf/build/Microsoft.AspNetCore.Components.WebView.Wpf.targets
Labels: area/blazor 🕸️, feature-blazor-windesktop, feature-blazor-sdk

#3723 Register compatibilty handlers for RelativeLayout and AbsoluteLayout
  src/Compatibility/Core/src/AppHostBuilderExtensions.cs
  src/Controls/src/Core/LegacyLayouts/AbsoluteLayout.cs
Labels: area/layout 🔲

#3713 [Android, iOS] Implement IsTextPredictionEnabled property in SearchBar
  src/Core/src/Handlers/SearchBar/SearchBarHandler.Android.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.iOS.cs
  src/Core/src/Platform/Android/SearchViewExtensions.cs
  src/Core/src/Platform/iOS/SearchBarExtensions.cs
Labels: platform/android 🤖, platform/iOS 🍎, area/controls 🎮

#3746 [Housekeeping] Remove some pending TODOs
  src/Controls/src/Core/Platform/AlertManager/AlertManager.Android.cs
  src/Core/src/Platform/Windows/ActivityIndicatorExtensions.cs
Labels: t/housekeeping ♻︎

#3692 Return a blank Label when LoadTemplate is null to prevent Hot Reload crashes
  src/Controls/src/Core/ElementTemplate.cs
  src/Controls/tests/Core.UnitTests/DataTemplateTests.cs
  src/Controls/tests/Xaml.UnitTests/LoaderTests.cs
Labels: area/tooling ⚙️

#3372 [android] reduce JNI calls by moving logic into Java
  .gitignore
  src/Core/AndroidNative/README.md
  src/Core/AndroidNative/build.gradle
  src/Core/AndroidNative/gradle.properties
  src/Core/AndroidNative/gradle/wrapper/gradle-wrapper.jar
  src/Core/AndroidNative/gradle/wrapper/gradle-wrapper.properties
  src/Core/AndroidNative/gradlew
  src/Core/AndroidNative/gradlew.bat
  src/Core/AndroidNative/maui/.gitignore
  src/Core/AndroidNative/maui/build.gradle
  src/Core/AndroidNative/maui/src/main/AndroidManifest.xml
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/ViewHelper.java
  src/Core/AndroidNative/settings.gradle
  src/Core/src/Handlers/View/AndroidBatchPropertyMapper.cs
  src/Core/src/Handlers/View/ViewHandler.cs
  src/Core/src/Platform/Android/ActivityIndicatorExtensions.cs
  src/Core/src/Platform/Android/TransformationExtensions.cs
  src/Core/src/Platform/Android/ViewExtensions.cs
  src/Core/src/PropertyMapper.cs
  src/Core/src/Transforms/Metadata.xml
  src/Core/src/maui.aar
  src/Core/tests/Benchmarks.Droid/AndroidManifest.xml
  src/Core/tests/Benchmarks.Droid/Benchmarks.Droid.csproj
  src/Core/tests/Benchmarks.Droid/MainActivity.cs
  src/Core/tests/Benchmarks.Droid/MainInstrumentation.cs
  src/Core/tests/Benchmarks.Droid/README.md
  src/Core/tests/Benchmarks.Droid/Resources/layout/activity_main.xml
  src/Core/tests/Benchmarks.Droid/Resources/mipmap-anydpi-v26/ic_launcher.xml
  src/Core/tests/Benchmarks.Droid/Resources/mipmap-anydpi-v26/ic_launcher_round.xml
  src/Core/tests/Benchmarks.Droid/Resources/mipmap-hdpi/ic_launcher.png
  src/Core/tests/Benchmarks.Droid/Resources/mipmap-hdpi/ic_launcher_foreground.png
  src/Core/tests/Benchmarks.Droid/Resources/mipmap-hdpi/ic_launcher_round.png
  src/Core/tests/Benchmarks.Droid/Resources/mipmap-mdpi/ic_launcher.png
  src/Core/tests/Benchmarks.Droid/Resources/mipmap-mdpi/ic_launcher_foreground.png
  src/Core/tests/Benchmarks.Droid/Resources/mipmap-mdpi/ic_launcher_round.png
  src/Core/tests/Benchmarks.Droid/Resources/mipmap-xhdpi/ic_launcher.png
  src/Core/tests/Benchmarks.Droid/Resources/mipmap-xhdpi/ic_launcher_foreground.png
  src/Core/tests/Benchmarks.Droid/Resources/mipmap-xhdpi/ic_launcher_round.png
  src/Core/tests/Benchmarks.Droid/Resources/mipmap-xxhdpi/ic_launcher.png
  src/Core/tests/Benchmarks.Droid/Resources/mipmap-xxhdpi/ic_launcher_foreground.png
  src/Core/tests/Benchmarks.Droid/Resources/mipmap-xxhdpi/ic_launcher_round.png
  src/Core/tests/Benchmarks.Droid/Resources/mipmap-xxxhdpi/ic_launcher.png
  src/Core/tests/Benchmarks.Droid/Resources/mipmap-xxxhdpi/ic_launcher_foreground.png
  src/Core/tests/Benchmarks.Droid/Resources/mipmap-xxxhdpi/ic_launcher_round.png
  src/Core/tests/Benchmarks.Droid/Resources/values/ic_launcher_background.xml
  src/Core/tests/Benchmarks.Droid/Resources/values/strings.xml
  src/Core/tests/Benchmarks.Droid/ViewHandlerBenchmark.cs
  src/Workload/Microsoft.Maui.Core.Ref/Microsoft.Maui.Core.Ref.csproj
Labels: area/perf 🏎️

#3752 Execute Screenshot tests on the main thread
  src/Essentials/test/DeviceTests/Tests/Screenshot_Tests.cs
Labels: t/housekeeping ♻︎

#3780 Remove no longer used LaunchScreen.xib files from templates
  src/Templates/src/templates/maui-blazor/Platforms/iOS/Resources/LaunchScreen.xib
  src/Templates/src/templates/maui-mobile/Platforms/iOS/Resources/LaunchScreen.xib
Labels: t/housekeeping ♻︎, area/templates 📄

#3782 Flyout apis android
  src/Controls/samples/Controls.Sample/Pages/Core/FlyoutPageGallery.xaml
  src/Controls/samples/Controls.Sample/Pages/Core/FlyoutPageGallery.xaml.cs
  src/Controls/samples/Controls.Sample/ViewModels/CoreViewModel.cs
  src/Controls/src/Core/FlyoutPage.cs
  src/Controls/src/Core/HandlerImpl/FlyoutPage/FlyoutPage.Impl.cs
  src/Controls/src/Core/HandlerImpl/FlyoutPage/FlyoutPage.cs
  src/Controls/src/Core/Hosting/AppHostBuilderExtensions.cs
  src/Controls/src/Core/Platform/Android/Extensions/ToolbarExtensions.cs
  src/Controls/src/Core/Toolbar.cs
  src/Core/src/Core/IFlyoutView.cs
  src/Core/src/Handlers/FlyoutView/FlyoutViewHandler.Android.cs
  src/Core/src/Handlers/FlyoutView/FlyoutViewHandler.Standard.cs
  src/Core/src/Handlers/FlyoutView/FlyoutViewHandler.Windows.cs
  src/Core/src/Handlers/FlyoutView/FlyoutViewHandler.cs
  src/Core/src/Handlers/FlyoutView/FlyoutViewHandler.iOS.cs
  src/Core/src/Handlers/NavigationPage/NavigationViewHandler.Android.cs
  src/Core/src/Handlers/Picker/PickerHandler.Android.cs
  src/Core/src/Handlers/Toolbar/ToolbarHandler.Android.cs
  src/Core/src/Handlers/View/ViewHandler.Android.cs
  src/Core/src/Hosting/LifecycleEvents/AppHostBuilderExtensions.Android.cs
  src/Core/src/Platform/Android/Navigation/NavigationRootManager.cs
  src/Core/src/Platform/Android/Navigation/ProcessBackClick.cs
  src/Core/src/Platform/Android/Navigation/StackNavigationManager.cs
  src/Core/src/Platform/Android/Resources/Layout/drawer_layout.axml
  src/Core/src/Primitives/FlyoutBehavior.cs
Labels: area/FlyoutPage

#3783 [android] stop using Build.VERSION.SdkInt
  src/Compatibility/Core/src/Android/AppCompat/ButtonRenderer.cs
  src/Compatibility/Core/src/Android/AppCompat/FormsAppCompatActivity.cs
  src/Compatibility/Core/src/Android/AppCompat/ImageButtonRenderer.cs
  src/Compatibility/Core/src/Android/AppCompat/PickerRenderer.cs
  src/Compatibility/Core/src/Android/AppCompat/Platform.cs
  src/Compatibility/Core/src/Android/AppCompat/TabbedPageRenderer.cs
  src/Compatibility/Core/src/Android/BorderBackgroundManager.cs
  src/Compatibility/Core/src/Android/Cells/BaseCellView.cs
  src/Compatibility/Core/src/Android/Cells/SwitchCellRenderer.cs
  src/Compatibility/Core/src/Android/Extensions/FlowDirectionExtensions.cs
  src/Compatibility/Core/src/Android/Extensions/ScrollViewExtensions.cs
  src/Compatibility/Core/src/Android/Extensions/TextAlignmentExtensions.cs
  src/Compatibility/Core/src/Android/FastRenderers/ButtonRenderer.cs
  src/Compatibility/Core/src/Android/FastRenderers/LabelRenderer.cs
  src/Compatibility/Core/src/Android/Forms.cs
  src/Compatibility/Core/src/Android/Renderers/AndroidGIFImageParser.cs
  src/Compatibility/Core/src/Android/Renderers/CircularProgress.cs
  src/Compatibility/Core/src/Android/Renderers/DatePickerRenderer.cs
  src/Compatibility/Core/src/Android/Renderers/EditorRenderer.cs
  src/Compatibility/Core/src/Android/Renderers/EntryRenderer.cs
  src/Compatibility/Core/src/Android/Renderers/FormattedStringExtensions.cs
  src/Compatibility/Core/src/Android/Renderers/LabelRenderer.cs
  src/Compatibility/Core/src/Android/Renderers/ListViewRenderer.cs
  src/Compatibility/Core/src/Android/Renderers/ProgressBarRenderer.cs
  src/Compatibility/Core/src/Android/Renderers/RefreshViewRenderer.cs
  src/Compatibility/Core/src/Android/Renderers/ScrollViewRenderer.cs
  src/Compatibility/Core/src/Android/Renderers/SearchBarRenderer.cs
  src/Compatibility/Core/src/Android/Renderers/SliderRenderer.cs
  src/Compatibility/Core/src/Android/Renderers/TableViewRenderer.cs
  src/Compatibility/Core/src/Android/Renderers/TimePickerRenderer.cs
  src/Compatibility/Core/src/Android/Renderers/WebViewRenderer.cs
  src/Compatibility/Core/src/Android/VisualElementPackager.cs
  src/Compatibility/Core/src/Android/VisualElementTracker.cs
  src/Compatibility/Material/src/Android/MaterialColors.cs
  src/Controls/src/Core/Platform/Android/Extensions/ViewExtensions.cs
  src/Core/src/Platform/Android/ContextExtensions.cs
  src/Core/src/Platform/Android/NativeVersion.cs
  src/Essentials/src/Battery/Battery.android.cs
  src/Essentials/src/Connectivity/Connectivity.android.cs
  src/Essentials/src/DeviceInfo/DeviceInfo.android.cs
  src/Essentials/src/FileSystem/FileSystem.android.cs
  src/Essentials/src/Flashlight/Flashlight.android.cs
  src/Essentials/src/MainThread/MainThread.android.cs
  src/Essentials/src/Permissions/Permissions.android.cs
  src/Essentials/src/PhoneDialer/PhoneDialer.android.cs
  src/Essentials/src/Platform/Platform.android.cs
  src/Essentials/src/Sms/Sms.android.cs
  src/Essentials/src/TextToSpeech/TextToSpeech.android.cs
  src/Essentials/src/Types/FileProvider.android.cs
  src/Essentials/src/Types/LocationExtensions.android.cs
  src/Essentials/test/DeviceTests/Startup.cs
  src/Essentials/test/DeviceTests/Tests/Android/FileProvider_Tests.cs
  src/Essentials/test/DeviceTests/Tests/AppActions_Tests.cs
  src/Essentials/test/DeviceTests/Tests/SecureStorage_Tests.cs
  src/Essentials/test/DeviceTests/Tests/Vibration_Tests.cs
  src/TestUtils/src/DeviceTests.Runners/HeadlessRunner/Android/MauiTestInstrumentation.cs
Labels: area/perf 🏎️

#3693 Window extend toolbar
  src/Controls/samples/Controls.Sample/XamlApp.xaml.cs
  src/Controls/src/Core/HandlerImpl/Toolbar/Toolbar.Windows.cs
  src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.Windows.cs
  src/Controls/src/Core/Platform/Windows/Extensions/ToolbarExtensions.cs
  src/Core/src/Handlers/Toolbar/ToolbarHandler.Windows.cs
  src/Core/src/Handlers/View/ViewHandler.Android.cs
  src/Core/src/Handlers/View/ViewHandler.Windows.cs
  src/Core/src/Handlers/View/ViewHandler.cs
  src/Core/src/Handlers/Window/WindowHandler.Android.cs
  src/Core/src/Handlers/Window/WindowHandler.Windows.cs
  src/Core/src/Platform/Windows/MauiNavigationView.cs
  src/Core/src/Platform/Windows/NavigationRootManager.cs
  src/Core/src/Platform/Windows/NavigationRootView.cs
  src/Core/src/Platform/Windows/Styles/NavigationRootViewStyle.xaml
  src/Core/src/Platform/Windows/Styles/Resources.xaml
  src/Core/src/Platform/Windows/WindowExtensions.cs
  src/Core/src/Platform/Windows/WindowHeader.xaml.cs
Labels: area/desktop 🖥️

#3738 Essentials fix DeviceDisplay and DeviceInfo
  src/Core/src/Platform/Windows/MauiWinUIWindow.cs
  src/Essentials/samples/Samples/Platforms/Windows/app.manifest
  src/Essentials/src/DeviceDisplay/DeviceDisplay.uwp.cs
  src/Essentials/src/DeviceInfo/DeviceInfo.uwp.cs
  src/Essentials/src/Platform/Platform.uwp.cs
  src/Essentials/src/Properties/AssemblyInfo.uwp.cs
Labels: area/essentials 🍞

#3775 [Housekeeping] Updated the Stepper sample in the Gallery
  src/Controls/samples/Controls.Sample/Pages/Controls/StepperPage.xaml
Labels: t/housekeeping ♻︎

#3750 Merge 6.0.100-preview11 to main
  src/Core/src/Fonts/EmbeddedFontLoader.iOS.cs
  src/Core/src/Fonts/FontRegistrar.cs
  src/Core/src/Fonts/FontRegistrar.iOS.cs
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#3823 [core] cleanup PropertyMapper.PopulateKeys()
  src/Core/src/PropertyMapper.cs
Labels: t/housekeeping ♻︎

#3824 [controls] Brush.Foo should return immutable instances
  src/Controls/src/Core/Brush.cs
  src/Controls/src/Core/ImmutableBrush.cs
  src/Controls/src/Core/SolidColorBrush.cs
  src/Core/tests/UnitTests/BrushTests.cs
Labels: area/perf 🏎️

#3728 [iOS] Updated SearchBarHandler native events
  src/Compatibility/Core/src/iOS/Renderers/SearchBarRenderer.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.iOS.cs
  src/Core/src/Platform/iOS/MauiSearchBar.cs
Labels: platform/iOS 🍎, area/controls 🎮

#3375 Added Shell Page dependency resolution with DataTemplate and Shell global routes…
  src/Controls/src/Core/ElementTemplate.cs
  src/Controls/src/Core/RouteFactory.cs
  src/Controls/src/Core/Routing.cs
  src/Controls/src/Core/Shell/ShellContent.cs
  src/Controls/src/Core/Shell/ShellNavigationManager.cs
  src/Controls/src/Core/Shell/ShellSection.cs
  src/Controls/tests/Core.UnitTests/ShellNavigatingTests.cs
  src/Controls/tests/Core.UnitTests/ShellTestBase.cs
  src/Controls/tests/Core.UnitTests/ShellTests.cs
Labels: community ✨

#1884 [Android] Only set click listener if the item is indeed clickable
  src/Compatibility/Core/src/Android/CollectionView/ItemsViewAdapter.cs
  src/Compatibility/Core/src/Android/CollectionView/SelectableViewHolder.cs
  src/Compatibility/Core/src/Android/CollectionView/TextViewHolder.cs
  src/Controls/samples/Controls.Sample/Pages/Compatibility/CarouselViewPage.xaml
  src/Controls/samples/Controls.Sample/Pages/Compatibility/CarouselViewPage.xaml.cs
  src/Controls/src/Core/Handlers/Items/Android/Adapters/ItemsViewAdapter.cs
  src/Controls/src/Core/Handlers/Items/Android/SelectableViewHolder.cs
  src/Controls/src/Core/Handlers/Items/Android/TextViewHolder.cs
Labels: area/a11y
