Repository dotnet/maui, pull requests merged in 2022-11, with the labels that each got.

#11048 Remove unused reference
  src/Controls/tests/Xaml.UnitTests/Controls.Xaml.UnitTests.csproj
Labels: t/housekeeping ♻︎

#11041 Invoke provisionator with AUTH_TOKEN_GITHUB_COM set
  eng/pipelines/common/controlgallery-android.yml
  eng/pipelines/common/controlgallery-ios.yml
  eng/pipelines/common/controlgallery-windows.yml
  eng/pipelines/common/provision.yml
Labels: area/infrastructure 🏗️

#11055 [iOS/macOS] Fix issue updating the Frame HasShadow property
  src/Controls/samples/Controls.Sample/Pages/Compatibility/FramePage.xaml
  src/Controls/samples/Controls.Sample/Pages/Compatibility/FramePage.xaml.cs
  src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs
  src/Controls/src/Core/HandlerImpl/Frame.Impl.cs
  src/Controls/tests/DeviceTests/Elements/Frame/FrameTests.iOS.cs
Labels: t/bug, platform/macOS 🍏, platform/iOS 🍎, area/controls 🎮, control-frame

#11057 [Housekeeping] Add more Frame Device tests
  src/Controls/tests/DeviceTests/Elements/Frame/FrameTests.cs
Labels: t/housekeeping ♻︎, area/controls 🎮, control-frame

#10889 Enable Codeql
  eng/pipelines/common/variables.yml
  eng/pipelines/handlers.yml
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#11068 Continue if provisionator fails
  eng/pipelines/common/device-tests-steps.yml
  eng/pipelines/common/pack.yml
  eng/pipelines/common/provision.yml
  eng/pipelines/handlers.yml
Labels: area/infrastructure 🏗️

#11027 [Tizen] Add Shell FlyoutBackDrop
  src/Controls/src/Core/Handlers/Shell/Tizen/ShellView.cs
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Shipped.txt
Labels: area/shell 🐢, community ✨

#11091 [foldable] XML doc additions (#10972)
  src/Controls/Foldable/src/Android/HostBuilderExtensions.cs
  src/Controls/Foldable/src/DualScreenInfo.cs
  src/Controls/Foldable/src/HostBuilderExtensions.cs
  src/Controls/Foldable/src/SpanModeStateTrigger.cs
  src/Controls/Foldable/src/TwoPaneView.cs
  src/Controls/Foldable/src/TwoPaneViewMode.cs
  src/Controls/Foldable/src/TwoPaneViewPriority.cs
  src/Controls/Foldable/src/TwoPaneViewTallModeConfiguration.cs
  src/Controls/Foldable/src/TwoPaneViewWideModeConfiguration.cs
  src/Controls/Foldable/src/WindowSpanModeStateTrigger.cs
Labels: area/docs 📓, t/housekeeping ♻︎

#11094 Add backport to branch
  .github/workflows/backport.yml
Labels: t/housekeeping ♻︎

#11092 Bump provisionator task to version 2
  eng/pipelines/common/provision.yml
Labels: area/infrastructure 🏗️

#11085 Provisionator fixes net6 branch
  eng/pipelines/common/device-tests-steps.yml
  eng/pipelines/common/pack.yml
  eng/pipelines/common/provision.yml
  eng/pipelines/handlers.yml
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#10909 Extract Maps, Graphics & Foldable docs during build
  eng/cake/dotnet.cake
  src/Controls/Foldable/src/Controls.Foldable.csproj
  src/Graphics/src/Graphics.Skia/Graphics.Skia.csproj
  src/Graphics/src/Text.Markdig/Graphics.Text.Markdig.csproj
  src/Graphics/src/Text.Markdig/Renderer/ParagraphRenderer.cs
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#11145 Ignore Authenticate Reunion NuGet sources
  eng/pipelines/common/provision.yml
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#11142 Extract Maps, Graphics & Foldable docs during build (#10909)
  eng/cake/dotnet.cake
  eng/pipelines/common/provision.yml
  src/Controls/Foldable/src/Controls.Foldable.csproj
  src/Graphics/src/Graphics.Skia/Graphics.Skia.csproj
  src/Graphics/src/Text.Markdig/Graphics.Text.Markdig.csproj
  src/Graphics/src/Text.Markdig/Renderer/ParagraphRenderer.cs
Labels: area/docs 📓, t/housekeeping ♻︎

#11150 Ignore Authenticate Reunion NuGet sources - net7
  eng/pipelines/common/provision.yml
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#11166 [DevOps] Rename the xamarin-templates resource to yaml-templates.
  eng/pipelines/common/insertion.yml
  eng/pipelines/common/provision.yml
  eng/pipelines/common/sdk-insertion.yml
  eng/pipelines/common/security-compliance.yml
  eng/pipelines/common/sign.yml
  eng/pipelines/device-tests.yml
  eng/pipelines/handlers.yml
  eng/pipelines/maui-release.yml
Labels: community ✨

#11223 Remove dead IScreenshotResult XML Doc link
  src/Essentials/src/Screenshot/Screenshot.shared.cs
Labels: area/docs 📓, t/housekeeping ♻︎

#11234 Fix Entry ClearButtonVisibilityProperty pointing to SelectionLength
  src/Controls/src/Core/Entry.cs
Labels: t/bug, area/controls 🎮, control-entry

#11226 Increase timeout to 240 minutes of azdo stages
  eng/pipelines/handlers.yml
  eng/pipelines/maui-release.yml
Labels: area/infrastructure 🏗️

#11096 Revert "[android] bring back `$(AndroidLinkResources)` by default"
  .nuspec/Microsoft.Maui.Controls.targets
Labels: area/single project ☝️

#10946 If a UISwitch grows too wide it is no longer accessible
  src/Core/src/Handlers/Switch/SwitchHandler.iOS.cs
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/tests/DeviceTests.Shared/HandlerTests/HandlerTestBaseOfT.iOS.cs
  src/Core/tests/DeviceTests/Handlers/Switch/SwitchHandlerTests.iOS.cs
Labels: area/a11y

#11135 [Windows] Fix tablet mode detection
  src/Essentials/src/DeviceInfo/DeviceInfo.uwp.cs
Labels: area/essentials 🍞, community ✨

#11219 Add nicer metadata to our NuGet packages
  Assets/icon.png
  src/Controls/Foldable/src/Controls.Foldable.csproj
  src/Controls/Maps/src/Controls.Maps.csproj
  src/Core/maps/src/Maps.csproj
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#11347 Add debug agent info
  eng/pipelines/common/provision.yml
  eng/pipelines/handlers.yml
Labels: area/infrastructure 🏗️

#10876 Add NeedsExactMeasure check for Editor on Android
  src/Core/src/Handlers/Button/ButtonHandler.Android.cs
  src/Core/src/Handlers/Editor/EditorHandler.Android.cs
  src/Core/src/Handlers/Label/LabelHandler.Android.cs
  src/Core/src/Handlers/ViewHandlerExtensions.Android.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
Labels: area/layout 🔲, area/controls 🎮, control-entry

#11378 Update Essentials Barometer API Docs
  src/Essentials/docs/Microsoft.Maui.Essentials/Barometer.xml
  src/Essentials/docs/Microsoft.Maui.Essentials/BarometerChangedEventArgs.xml
  src/Essentials/docs/Microsoft.Maui.Essentials/BarometerData.xml
  src/Essentials/src/Barometer/Barometer.android.cs
  src/Essentials/src/Barometer/Barometer.shared.cs
Labels: area/docs 📓, t/housekeeping ♻︎, area/essentials 🍞

#11373 Update Essentials AppActions API Docs
  src/Essentials/docs/Microsoft.Maui.Essentials/AppAction.xml
  src/Essentials/docs/Microsoft.Maui.Essentials/AppActionEventArgs.xml
  src/Essentials/docs/Microsoft.Maui.Essentials/AppActions.xml
  src/Essentials/src/AppActions/AppActions.netstandard.tvos.watchos.macos.tizen.cs
  src/Essentials/src/AppActions/AppActions.shared.cs
Labels: area/docs 📓, t/housekeeping ♻︎, area/essentials 🍞

#11370 Update Essentials Accelerometer API Docs
  src/Essentials/docs/en/Xamarin.Essentials/Accelerometer.xml
  src/Essentials/docs/en/Xamarin.Essentials/AccelerometerChangedEventArgs.xml
  src/Essentials/docs/en/Xamarin.Essentials/AccelerometerData.xml
  src/Essentials/src/Accelerometer/Accelerometer.netstandard.tvos.macos.cs
  src/Essentials/src/Accelerometer/Accelerometer.shared.cs
Labels: area/docs 📓, t/housekeeping ♻︎, area/essentials 🍞

#11357 Remove unnecessary MeasureOverride from RefreshView;
  src/Controls/src/Core/HandlerImpl/RefreshView/RefreshView.Impl.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
Labels: area/layout 🔲, area/controls 🎮, control-refreshview

#11386 Don't set editor action to handled
  src/Core/src/Handlers/Entry/EntryHandler.Android.cs
  src/Core/src/Platform/Android/KeyboardManager.cs
  src/Core/src/Properties/AssemblyInfo.cs
  src/Core/tests/DeviceTests/Handlers/Entry/EntryHandlerTests.cs
  src/Core/tests/DeviceTests/Stubs/LayoutStub.cs
  src/Core/tests/DeviceTests/Stubs/StubBase.cs
  src/Core/tests/DeviceTests/Stubs/VerticalStackLayoutStub.cs
  src/TestUtils/src/DeviceTests/AssertionExtensions.Android.cs
  src/TestUtils/src/DeviceTests/AssertionExtensions.Windows.cs
  src/TestUtils/src/DeviceTests/AssertionExtensions.cs
  src/TestUtils/src/DeviceTests/AssertionExtensions.iOS.cs
Labels: area/controls 🎮

#11380 Update Essentials Battery API Docs
  src/Essentials/docs/Microsoft.Maui.Essentials/Battery.xml
  src/Essentials/docs/Microsoft.Maui.Essentials/BatteryInfoChangedEventArgs.xml
  src/Essentials/docs/Microsoft.Maui.Essentials/BatteryPowerSource.xml
  src/Essentials/docs/Microsoft.Maui.Essentials/BatteryState.xml
  src/Essentials/docs/Microsoft.Maui.Essentials/EnergySaverStatus.xml
  src/Essentials/docs/Microsoft.Maui.Essentials/EnergySaverStatusChangedEventArgs.xml
  src/Essentials/src/Battery/Battery.netstandard.tvos.cs
  src/Essentials/src/Battery/Battery.shared.cs
  src/Essentials/src/Permissions/Permissions.netstandard.cs
Labels: area/docs 📓, t/housekeeping ♻︎, area/essentials 🍞

#11456 [net7.0] Update Microsoft.Windows.SDK.BuildTools
  eng/Versions.props
Labels: area/infrastructure 🏗️

#11374 Update Essentials AppInfo API Docs
  src/Essentials/docs/Microsoft.Maui.Essentials/AppInfo.xml
  src/Essentials/docs/Microsoft.Maui.Essentials/AppTheme.xml
  src/Essentials/src/AppInfo/AppInfo.netstandard.cs
  src/Essentials/src/AppInfo/AppInfo.shared.cs
  src/Essentials/src/AppInfo/AppInfo.uwp.cs
  src/Essentials/src/AppInfo/AppTheme.shared.cs
  src/Essentials/src/AppInfo/LayoutDirection.shared.cs
Labels: area/docs 📓, t/housekeeping ♻︎, area/essentials 🍞

#11394 Update Essentials Browser API Docs
  src/Essentials/docs/Microsoft.Maui.Essentials/Browser.xml
  src/Essentials/docs/Microsoft.Maui.Essentials/BrowserLaunchFlags.xml
  src/Essentials/docs/Microsoft.Maui.Essentials/BrowserLaunchMode.xml
  src/Essentials/docs/Microsoft.Maui.Essentials/BrowserLaunchOptions.xml
  src/Essentials/docs/Microsoft.Maui.Essentials/BrowserTitleMode.xml
  src/Essentials/src/Browser/Browser.netstandard.tvos.watchos.cs
  src/Essentials/src/Browser/Browser.shared.cs
  src/Essentials/src/Browser/BrowserLaunchMode.shared.cs
  src/Essentials/src/Browser/BrowserLaunchOptions.shared.cs
  src/Essentials/src/Browser/BrowserTitleMode.shared.cs
Labels: area/docs 📓, t/housekeeping ♻︎, area/essentials 🍞

#11471 [iOS] Fix issue clearing MapElements in Map
  src/Controls/samples/Controls.Sample/Pages/Controls/MapsGalleries/PolygonsGallery.xaml
  src/Controls/samples/Controls.Sample/Pages/Controls/MapsGalleries/PolygonsGallery.xaml.cs
  src/Core/maps/src/Handlers/Map/MapHandler.iOS.cs
  src/Core/maps/src/Platform/iOS/MauiMKMapView.cs
Labels: t/bug, platform/iOS 🍎, area/Maps🗺

#11417 Update Essentials Contacts API Docs
  src/Essentials/docs/Microsoft.Maui.Essentials/Contacts.xml
  src/Essentials/src/Contacts/Contacts.netstandard.tvos.watchos.cs
  src/Essentials/src/Contacts/Contacts.shared.cs
Labels: area/docs 📓, t/housekeeping ♻︎, area/essentials 🍞

#11415 Update Essentials Connectivity API Docs
  src/Essentials/docs/Microsoft.Maui.Essentials/ConnectionProfile.xml
  src/Essentials/docs/Microsoft.Maui.Essentials/Connectivity.xml
  src/Essentials/docs/Microsoft.Maui.Essentials/ConnectivityChangedEventArgs.xml
  src/Essentials/docs/Microsoft.Maui.Essentials/NetworkAccess.xml
  src/Essentials/src/Connectivity/Connectivity.android.cs
  src/Essentials/src/Connectivity/Connectivity.netstandard.watchos.cs
  src/Essentials/src/Connectivity/Connectivity.shared.cs
  src/Essentials/src/Connectivity/Connectivity.shared.enums.cs
  src/Essentials/src/Connectivity/Connectivity.uwp.cs
Labels: area/docs 📓, t/housekeeping ♻︎, area/essentials 🍞

#11273 CodeQL only on main/non-public builds
  eng/pipelines/common/variables.yml
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#11488 [net7.0] [iOS/macOS] Fix issue updating the Frame HasShadow property
  src/Controls/samples/Controls.Sample/Pages/Compatibility/FramePage.xaml
  src/Controls/samples/Controls.Sample/Pages/Compatibility/FramePage.xaml.cs
  src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs
  src/Controls/src/Core/HandlerImpl/Frame.Impl.cs
  src/Controls/tests/DeviceTests/Elements/Frame/FrameTests.iOS.cs
Labels: t/housekeeping ♻︎

#11175 Ensure that UIScrollView ContentSize is set
  src/Controls/src/Core/HandlerImpl/ScrollView/ScrollView.Impl.cs
  src/Controls/tests/DeviceTests/Elements/ScrollView/ScrollViewTests.iOS.cs
  src/Core/src/Handlers/ScrollView/ScrollViewHandler.iOS.cs
  src/Core/src/Layouts/LayoutExtensions.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Core/tests/DeviceTests.Shared/HandlerTests/HandlerTestBase.cs
  src/Core/tests/DeviceTests/Handlers/ScrollView/ScrollViewHandlerTests.iOS.cs
  src/Core/tests/DeviceTests/Stubs/ScrollViewStub.cs
  src/Core/tests/DeviceTests/Stubs/StubBase.cs
Labels: area/layout 🔲, layout-scrollview

#11352 Fix iOS/macOS Images not cropped inside of a Frame #6580
  src/Controls/src/Core/Compatibility/Handlers/Android/FrameRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs
  src/Controls/src/Core/Frame.cs
  src/Controls/tests/DeviceTests/Elements/Frame/FrameTests.iOS.cs
Labels: platform/macOS 🍏, platform/iOS 🍎, area/controls 🎮, control-frame

#11523 [Build] Clean up provisioning script
  eng/provisioning/provisioning.csx
Labels: area/infrastructure 🏗️

#11257 Clean up the files in the xml-docs artifacts
  eng/cake/dotnet.cake
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#11269 [foldable] add TypeConverter to Pane1Length/Pane2Length properties
  src/Controls/Foldable/src/TwoPaneView.cs
Labels: platform/android 🤖, area/controls 🎮, control-twopaneview

#11389 [Tizen] Add handing Label.TextType
  src/Controls/src/Core/Platform/Tizen/Extensions/FormattedStringExtensions.cs
  src/Controls/src/Core/Platform/Tizen/Extensions/TextExtensions.cs
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Core/src/Fonts/EmbeddedFontLoader.Tizen.cs
  src/Core/src/Fonts/FontManager.Tizen.cs
  src/Core/src/Platform/Tizen/MauiApplication.cs
Labels: area/controls 🎮, community ✨

#11539 Add .NET 7 announcement
  README.md
Labels: t/housekeeping ♻︎

#11390 [Tizen] Add Shell FlyoutBackDrop
  src/Controls/src/Core/Handlers/Shell/Tizen/ShellView.cs
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
Labels: area/shell 🐢, community ✨

#11107 [iOS] Allow transparent modal pages
  src/Controls/src/Core/Platform/iOS/ModalWrapper.cs
Labels: t/bug, area/navigation 🧭, platform/iOS 🍎

#11431 Update Essentials DeviceInfo API Docs
  src/Essentials/docs/Microsoft.Maui.Essentials/DeviceInfo.xml
  src/Essentials/docs/Microsoft.Maui.Essentials/DeviceType.xml
  src/Essentials/src/DeviceInfo/DeviceInfo.shared.cs
  src/Essentials/src/DeviceInfo/DeviceInfo.uwp.cs
Labels: area/docs 📓, t/housekeeping ♻︎, area/essentials 🍞

#11429 Update Essentials DeviceDisplay API Docs
  src/Essentials/docs/Microsoft.Maui.Essentials/DeviceDisplay.xml
  src/Essentials/docs/Microsoft.Maui.Essentials/DisplayInfoChangedEventArgs.xml
  src/Essentials/src/DeviceDisplay/DeviceDisplay.shared.cs
  src/Essentials/src/DeviceDisplay/DeviceDisplay.uwp.cs
Labels: area/docs 📓, t/housekeeping ♻︎, area/essentials 🍞

#11361 Possible fix for issue #10960
  src/Controls/src/Core/Shell/Shell.cs
Labels: area/shell 🐢, community ✨

#11359 Reboot on-prem agent after job completion
  eng/pipelines/common/device-tests-steps.yml
  eng/pipelines/common/device-tests.yml
  eng/pipelines/device-tests.yml
Labels: do-not-merge, area/infrastructure 🏗️

#11146 Notify Button ImageSource changes correctly
  src/Controls/src/Core/HandlerImpl/Button/Button.Impl.cs
  src/Core/tests/DeviceTests/Handlers/Button/ButtonHandlerTests.Android.cs
Labels: t/bug, platform/android 🤖, area/controls 🎮, control-button

#11053 [Android] Fix Stepper IsEnabled property changes
  src/Controls/samples/Controls.Sample/Pages/Controls/StepperPage.xaml
  src/Controls/samples/Controls.Sample/Pages/Controls/StepperPage.xaml.cs
  src/Core/src/Handlers/Stepper/StepperHandler.Android.cs
  src/Core/src/Handlers/Stepper/StepperHandler.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/tests/DeviceTests/Handlers/Stepper/StepperHandlerTests.Android.cs
Labels: t/bug, platform/android 🤖, area/controls 🎮, control-stepper

#11577 [Android] Fix ObjectDisposedException on Android resizing images
  src/Graphics/src/Graphics/Platforms/Android/PlatformImage.cs
Labels: t/bug, platform/android 🤖, area/drawing ✏️

#9783 [Android] Fix crash using Page IsBusy property
  src/Controls/src/Core/Platform/AlertManager/AlertManager.Android.cs
  src/Controls/tests/DeviceTests/Elements/Page/PageTests.cs
Labels: t/bug, platform/android 🤖, area/controls 🎮

#10328 Align Shapes Fill property behavior with Xamarin.Forms
  src/Core/src/Graphics/ShapeDrawable.cs
  src/Core/tests/DeviceTests/Handlers/ShapeView/ShapeViewHandlerTests.cs
Labels: t/bug, area/drawing ✏️

#7925 [Catalyst] Fix brushes in Frame
  src/Compatibility/Core/src/iOS/Renderers/FrameRenderer.cs
  src/Controls/samples/Controls.Sample/Pages/Compatibility/FramePage.xaml
  src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs
Labels: t/bug, platform/macOS 🍏, area/drawing ✏️, platform/iOS 🍎, control-frame

#11581 Fix Managing Layout Children
  src/Core/src/Handlers/Layout/LayoutHandler.Tizen.cs
Labels: area/layout 🔲, community ✨

#11582 [iOS] Avoid propagate Map tap event tapping a Pin on iOS
  src/Controls/samples/Controls.Sample/Pages/Controls/MapsGalleries/MapPinsGallery.xaml
  src/Controls/samples/Controls.Sample/Pages/Controls/MapsGalleries/MapPinsGallery.xaml.cs
  src/Core/maps/src/Platform/iOS/MauiMKMapView.cs
Labels: t/bug, platform/iOS 🍎, area/controls 🎮, control-map

#11590 Exclude incompatible files from daily dotnet format workflow
  .github/workflows/dotnet-format-daily.yml
Labels: area/infrastructure 🏗️

#11387 Manual update for .net8 sdk and workloads
  Directory.Build.props
  GitInfo.txt
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/cake/dotnet.cake
  eng/devices/android.cake
  eng/devices/ios.cake
  eng/pipelines/common/device-tests.yml
  eng/pipelines/common/variables.yml
  eng/pipelines/handlers.yml
  eng/provisioning/provisioning.csx
  src/DotNet/Dependencies/Workloads.csproj
  src/DotNet/DotNet.csproj
Labels: area/infrastructure 🏗️

#11638 Only include MauiXaml/Css when $(UseMaui)=true
  src/Workload/Microsoft.Maui.Sdk/Sdk/AutoImport.in.props
Labels: t/housekeeping ♻︎

#11609 [Build] Update yaml for net8
  eng/pipelines/handlers.yml
Labels: t/housekeeping ♻︎

#11569 Make iOS Label HTML behavior compatible with Forms
  src/Controls/src/Core/HandlerImpl/Label/Label.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.cs
Labels: area/controls 🎮

#11000 _itemsSource may be null in CarouselViewLoopManager
  src/Controls/src/Core/Handlers/Items/Android/CarouselViewLoopManager.cs
Labels: area/collectionview 📃, community ✨

#11690 Fix MauiIcon ForegroundScale on systems with comma as decimal separator
  src/SingleProject/Resizetizer/src/ResizeImageInfo.cs
Labels: community ✨

#10804 [iOS] Fix issue loading local files in WebView
  src/Core/src/Platform/iOS/MauiWKWebView.cs
Labels: t/bug, platform/macOS 🍏, platform/iOS 🍎, area/controls 🎮, control-webview

#10832 [iOS] RadioButton a11y
  src/Controls/samples/Controls.Sample/Pages/Controls/RadioButtonGalleries/ContentProperties.xaml
  src/Controls/samples/Controls.Sample/Pages/Controls/RadioButtonGalleries/RadioButtonGroupGalleryPage.xaml
  src/Controls/src/Core/HandlerImpl/RadioButton/RadioButton.Impl.cs
  src/Controls/src/Core/HandlerImpl/VisualElement/VisualElement.Impl.cs
  src/Core/src/Handlers/RadioButton/RadioButtonHandler.iOS.cs
  src/Core/src/Platform/iOS/SemanticSwitchContentView.cs
Labels: area/a11y, area/controls 🎮, control-radiobutton

#11497 Using local function to fix multi-thread issues
  src/Controls/src/Core/Shapes/PathFigureCollectionConverter.cs
Labels: area/drawing ✏️, area/perf 🏎️, community ✨

#11692 [Tizen] Add handing Label.TextType
  src/Controls/src/Core/Platform/Tizen/Extensions/FormattedStringExtensions.cs
  src/Controls/src/Core/Platform/Tizen/Extensions/TextExtensions.cs
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Shipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Core/src/Fonts/EmbeddedFontLoader.Tizen.cs
  src/Core/src/Fonts/FontManager.Tizen.cs
  src/Core/src/Platform/Tizen/MauiApplication.cs
Labels: area/controls 🎮, community ✨

#11741 Fix Element.ChildRemoved event sender
  src/Controls/src/Core/Element.cs
  src/Controls/tests/Core.UnitTests/ElementTests.cs
Labels: community ✨

#11695 [Windows] Correctly disable MenuBarItems
  src/Controls/tests/Core.UnitTests/Menu/MenuFlyoutSubItemTests.cs
  src/Core/src/Handlers/MenuBarItem/MenuBarItemHandler.Windows.cs
  src/Core/src/Handlers/MenuBarItem/MenuBarItemHandler.cs
Labels: t/bug, platform/windows 🪟, control-menubar
