Repository dotnet/maui, pull requests merged in 2022-10, with the labels that each got.

#10423 Remove unused and potentially conflicting feeds
  NuGet.config
Labels: area/infrastructure 🏗️

#10466 Update .NET MAUI find version command in bug template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#10467 [Android] Measure SwipeItem content before layout
  src/Core/src/Platform/Android/MauiSwipeView.cs
Labels: area/layout 🔲, platform/android 🤖

#10457 [Android] Fix crash relaunching App from sharing item
  src/Core/src/Handlers/Layout/LayoutHandler.Android.cs
Labels: t/bug, platform/android 🤖

#10477 Fix permissions in Windows
  src/Essentials/src/Permissions/Permissions.uwp.cs
  src/Essentials/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
Labels: platform/windows 🪟, area/essentials 🍞

#10425 Add min width/height to template styles of select controls
  src/Templates/src/templates/maui-mobile/Resources/Styles/Styles.xaml
Labels: area/a11y

#7358 Preserve the correct binding context for menu items
  src/Controls/src/Core/MenuBar.cs
  src/Controls/src/Core/MenuBarTracker.cs
  src/Controls/src/Core/Page.cs
  src/Controls/tests/Core.UnitTests/Menu/MenuBarTests.cs
  src/Controls/tests/Core.UnitTests/Menu/MenuTestBase.cs
Labels: area/desktop 🖥️

#10492 Remove NET6 pinning from main branch
  global.json
Labels: area/infrastructure 🏗️

#10476 Add support for SecureStorage in Unpackaged apps
  src/Essentials/src/SecureStorage/SecureStorage.uwp.cs
Labels: platform/windows 🪟, area/essentials 🍞

#10129 Add release 6.0.536
  docs/ReleaseSchedule.md
Labels: area/docs 📓, community ✨

#9679 [Windows ] Fix Shell SearchBarHandler
  src/Controls/samples/Controls.Sample/Pages/AppShell.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/Core/ShellGalleries/ShellChromeGallery.xaml
  src/Controls/src/Core/Handlers/Shell/ShellItemHandler.Windows.cs
  src/Controls/src/Core/Platform/Windows/Styles/ShellStyles.xaml
Labels: t/bug, platform/windows 🪟, area/shell 🐢

#10092 Added pending changes to Essentials Permissions from Xamarin.Forms
  src/Essentials/src/Permissions/Permissions.android.cs
  src/Essentials/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
Labels: t/bug, platform/android 🤖, area/essentials 🍞

#10515 Generate unplated icons on Windows
  src/SingleProject/Resizetizer/src/DpiPath.cs
Labels: area/single project ☝️

#10132 Don't force the TextDirection on Android unless the content direction can't be determined
  src/Core/src/Platform/Android/TextViewExtensions.cs
Labels: platform/android 🤖, area/localization

#10465 Add inline code documentation guidelines
  docs/CodeDocumentationGuidelines.md
  docs/README.md
Labels: area/docs 📓, t/housekeeping ♻︎

#10511 [Tizen] Fixes Tizen SemanticScreenReader using a new Accessibility API
  src/Essentials/src/SemanticScreenReader/SemanticScreenReader.tizen.cs
Labels: area/a11y, community ✨

#10563 Update ContextFlyout sample to show more scenarios
  src/Controls/samples/Controls.Sample/Pages/Core/ContextFlyoutPage.xaml
  src/Controls/samples/Controls.Sample/Pages/Core/ContextFlyoutPage.xaml.cs
Labels: area/desktop 🖥️, control-contextmenu

#10556 Make Grid of spacing consistent when rows/columns are collapsed
  src/Core/src/Layouts/GridLayoutManager.cs
  src/Core/tests/UnitTests/Layouts/GridLayoutManagerTests.cs
Labels: t/bug, area/layout 🔲, layout-grid

#10525 Fix catalyst secondary click to match windows
  src/Controls/samples/Controls.Sample/Pages/Core/TapGestureGalleryPage.cs
  src/Controls/samples/Controls.Sample/ViewModels/GesturesViewModel.cs
  src/Controls/src/Core/Platform/GestureManager/GestureManager.Windows.cs
  src/Controls/src/Core/Platform/GestureManager/GestureManager.iOS.cs
Labels: platform/macOS 🍏

#10594 [iOS] Fix crash disposing TabbedPage
  src/Controls/src/Core/Compatibility/Handlers/Android/FrameRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/FlyoutPage/iOS/PhoneFlyoutPageRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/TabbedPage/iOS/TabbedRenderer.cs
  src/Controls/tests/DeviceTests/Elements/FlyoutPage/FlyoutPageTests.cs
  src/Controls/tests/DeviceTests/Elements/NavigationPage/NavigationPageTests.cs
  src/Controls/tests/DeviceTests/Elements/TabbedPage/TabbedPageTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/TabbedPage/TabbedPageTests.cs
Labels: t/bug, platform/iOS 🍎, area/TabbedPage

#10530 Don't fire appearing/disappearing with window
  src/Controls/src/Core/HandlerImpl/NavigationPage/NavigationPage.Impl.cs
  src/Controls/src/Core/HandlerImpl/TabbedPage/TabbedPage.Android.cs
  src/Controls/src/Core/HandlerImpl/TabbedPage/TabbedPage.Windows.cs
  src/Controls/src/Core/HandlerImpl/Window/Window.Impl.cs
  src/Controls/src/Core/NavigationPageToolbar.cs
  src/Controls/src/Core/Platform/Android/TabbedPageManager.cs
  src/Controls/src/Core/Toolbar.cs
  src/Controls/tests/Core.UnitTests/WindowsTests.cs
  src/Controls/tests/DeviceTests/Elements/NavigationPage/NavigationPageTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/NavigationPage/NavigationPageTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.cs
  src/Controls/tests/DeviceTests/Elements/Toolbar/ToolbarTests.cs
  src/Controls/tests/DeviceTests/Elements/Window/WindowPageSwapTestCases.cs
  src/Controls/tests/DeviceTests/Elements/Window/WindowTests.cs
  src/Controls/tests/DeviceTests/HandlerTestBase.Android.cs
  src/Controls/tests/DeviceTests/HandlerTestBase.Windows.cs
  src/Controls/tests/DeviceTests/HandlerTestBase.cs
  src/Controls/tests/DeviceTests/TestCategory.cs
  src/Core/src/Handlers/Toolbar/ToolbarHandler.Android.cs
  src/Core/src/Platform/Android/Navigation/StackNavigationManager.cs
  src/Core/src/Platform/Windows/NavigationRootManager.cs
Labels: area/lifecycle 🔁

#10615 [MacCatalyst] Fix issue rendering background gradient in catalyst searchbar
  src/Core/src/Platform/iOS/SearchBarExtensions.cs
  src/Core/tests/DeviceTests/Handlers/SearchBar/SearchBarHandlerTests.iOS.cs
Labels: t/bug, platform/macOS 🍏, area/controls 🎮, control-entry

#10417 Fix top-left aligned shapes issue
  src/Controls/samples/Controls.Sample/Pages/Controls/ShapesGalleries/CompositionGallery.xaml
  src/Controls/samples/Controls.Sample/Pages/Controls/ShapesGalleries/CompositionGallery.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/ShapesGalleries/ShapesGallery.cs
  src/Controls/src/Core/HandlerImpl/Path.Impl.cs
  src/Controls/src/Core/HandlerImpl/Polygon.Impl.cs
  src/Controls/src/Core/HandlerImpl/Polyline.Impl.cs
  src/Controls/src/Core/Shapes/Shape.cs
Labels: t/bug, area/drawing ✏️

#10653 Fix how PopToRoot propagates to handler
  src/Controls/samples/Controls.Sample/Pages/Core/ShellGalleries/ShellChromeGallery.cs
  src/Controls/samples/Controls.Sample/Pages/Core/ShellGalleries/ShellChromeGallery.xaml
  src/Controls/src/Core/Handlers/Shell/ShellSectionHandler.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.cs
  src/Core/src/Platform/Windows/StackNavigationManager.cs
Labels: t/bug, area/navigation 🧭

#10352 [Android] Implement PointerGestureRecognizer for Android
  src/Controls/samples/Controls.Sample/Pages/Core/PointerGestureGalleryPage.xaml
  src/Controls/samples/Controls.Sample/Pages/Core/PointerGestureGalleryPage.xaml.cs
  src/Controls/src/Core/Platform/Android/Extensions/MotionEventExtensions.cs
  src/Controls/src/Core/Platform/Android/InnerGestureListener.cs
  src/Controls/src/Core/Platform/Android/PointerGestureHandler.cs
  src/Controls/src/Core/Platform/Android/TapGestureHandler.cs
  src/Controls/src/Core/Platform/GestureManager/GestureManager.Android.cs
  src/Controls/src/Core/Platform/GestureManager/GestureManager.Windows.cs
  src/Controls/src/Core/Platform/GestureManager/GestureManager.iOS.cs
  src/Controls/src/Core/ViewExtensions.cs
Labels: area/gestures

#10665 Fix PGR issue on Catalyst
  src/Controls/src/Core/Platform/iOS/CustomHoverGestureRecognizer.cs
Labels: platform/macOS 🍏

#10680 Fix WinAppSDK 12 Additional resources keys
  src/Controls/samples/Controls.Sample/Pages/Core/NavigationGallery.xaml.cs
  src/Controls/src/Core/HandlerImpl/TabbedPage/TabbedPage.Windows.cs
  src/Controls/src/Core/Handlers/Shell/ShellItemHandler.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Frame/FrameTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Window/WindowTests.Windows.cs
  src/Core/src/Platform/Windows/WindowRootView.cs
Labels: platform/windows 🪟

#10693 [Tests] Ignore tests runs for Core/Controls/Blazor on 12.4 and Android API25
  eng/pipelines/device-tests.yml
Labels: t/housekeeping ♻︎

#10695 [net6] Some fixes for tests
  .config/dotnet-tools.json
  eng/Version.Details.xml
  eng/Versions.props
  eng/pipelines/device-tests.yml
  eng/provisioning/provisioning.csx
  src/Core/src/Handlers/WebView/WebViewHandler.Android.cs
  src/Core/src/Platform/Android/MauiWebViewClient.cs
  src/Core/tests/DeviceTests/Handlers/WebView/WebViewHandlerTests.cs
  src/Essentials/test/DeviceTests/Tests/Geocoding_Tests.cs
Labels: t/housekeeping ♻︎

#10739 [Android] Fix Map not setting initial properties
  src/Core/maps/src/Handlers/Map/MapHandler.Android.cs
  src/Core/maps/src/Platform/Android/MapExtensions.cs
  src/Core/maps/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
Labels: t/bug, platform/android 🤖, area/Maps🗺

#10510 [Android] Ensure SearchView meets min size requirements
  src/Core/src/Handlers/SearchBar/SearchBarHandler.Android.cs
  src/Core/src/Platform/Android/MauiSearchView.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/tests/DeviceTests/Handlers/SearchBar/SearchBarHandlerTests.Android.cs
  src/Core/tests/DeviceTests/Handlers/SearchBar/SearchBarHandlerTests.Windows.cs
  src/Core/tests/DeviceTests/Handlers/SearchBar/SearchBarHandlerTests.cs
  src/Core/tests/DeviceTests/Handlers/SearchBar/SearchBarHandlerTests.iOS.cs
  src/Templates/src/templates/maui-mobile/Resources/Styles/Styles.xaml
Labels: area/controls 🎮

#10677 [iOS] Set data context on MauiDoneAccessoryView.
  src/Core/src/Handlers/Editor/EditorHandler.iOS.cs
  src/Core/tests/DeviceTests/Handlers/Editor/EditorHandlerTests.Windows.cs
  src/Core/tests/DeviceTests/Handlers/Editor/EditorHandlerTests.iOS.cs
  src/Core/tests/DeviceTests/Handlers/HandlerTestBaseOfT.iOS.cs
Labels: platform/iOS 🍎, community ✨

#10749 Fixed the openiconic link
  src/Templates/src/templates/maui-blazor/wwwroot/css/open-iconic/README.md
Labels: area/blazor 🕸️

#10774 Add Automated docs spellcheck via GitHub Actions
  .github/workflows/spellcheck.yml
  cSpell.json
  docs/ReleasePlanning.md
  docs/ReleaseSchedule.md
  docs/TriageProcess.md
Labels: community ✨

#10769 [Blazor] Close memory stream after copy
  src/BlazorWebView/src/Maui/Windows/WinUIWebViewManager.cs
Labels: area/blazor 🕸️

#10616 [Housekeeping] Added more Frame samples to Core Gallery
  src/Controls/samples/Controls.Sample/Pages/Compatibility/FramePage.xaml
Labels: platform/macOS 🍏, t/housekeeping ♻︎, area/controls 🎮, control-frame

#10145 [Windows] Detect StrokeDashArray Border collection changes
  src/Controls/src/Core/Border.cs
Labels: t/bug, platform/windows 🪟, area/drawing ✏️

#9758 Build the net6 templates in net7
  eng/cake/dotnet.cake
  src/BlazorWebView/tests/MauiDeviceTests/MauiBlazorWebView.DeviceTests.csproj
  src/Controls/tests/DeviceTests/Controls.DeviceTests.csproj
  src/Core/tests/DeviceTests/Core.DeviceTests.csproj
  src/Essentials/test/DeviceTests/Essentials.DeviceTests.csproj
Labels: area/infrastructure 🏗️

#10796 Fix more comment/docs typos
  src/Compatibility/ControlGallery/src/Core/GalleryPages/VisualStateManagerGalleries/ButtonDisabledStatesGallery.xaml
  src/Compatibility/ControlGallery/src/Core/GalleryPages/VisualStateManagerGalleries/DatePickerDisabledStatesGallery.xaml
  src/Compatibility/ControlGallery/src/Core/GalleryPages/VisualStateManagerGalleries/EditorDisabledStatesGallery.xaml
  src/Compatibility/ControlGallery/src/Core/GalleryPages/VisualStateManagerGalleries/EntryDisabledStatesGallery.xaml
  src/Compatibility/ControlGallery/src/Core/GalleryPages/VisualStateManagerGalleries/PickerDisabledStatesGallery.xaml
  src/Compatibility/ControlGallery/src/Core/GalleryPages/VisualStateManagerGalleries/SearchBarDisabledStatesGallery.xaml
  src/Compatibility/ControlGallery/src/Core/GalleryPages/VisualStateManagerGalleries/TimePickerDisabledStatesGallery.xaml
  src/Compatibility/Core/src/Android/StepperRendererManager.cs
  src/Controls/docs/Microsoft.Maui.Controls/BaseMenuItem.xml
  src/Controls/src/Core/IPinchGestureController.cs
  src/Controls/tests/Core.UnitTests/MarshalingObservableCollectionTests.cs
  src/Core/src/Platform/Android/ContextExtensions.cs
  src/Core/src/Platform/Android/Navigation/NavigationViewFragment.cs
  src/Core/src/Platform/Android/Navigation/StackNavigationManager.cs
  src/Core/src/Platform/Android/StepperHandlerManager.cs
Labels: t/housekeeping ♻︎

#10794 Update TODO comments for API changes that did not make it for .NET 7
  src/Controls/src/Core/HandlerImpl/CheckBox/CheckBox.cs
  src/Controls/src/Core/HandlerImpl/Label/Label.Android.cs
  src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs
  src/Controls/src/Core/Platform/Android/Extensions/RecyclerViewExtensions.cs
  src/Controls/src/Core/Platform/Windows/Extensions/FormattedStringExtensions.cs
  src/Controls/src/Core/Platform/iOS/Extensions/FormattedStringExtensions.cs
  src/Core/src/Fonts/FontManager.Tizen.cs
  src/Core/src/Graphics/MauiDrawable.Android.cs
  src/Core/src/Handlers/Button/ButtonHandler.iOS.cs
  src/Core/src/Handlers/DatePicker/DatePickerHandler.Windows.cs
  src/Core/src/Handlers/Editor/EditorHandler.Android.cs
  src/Core/src/Handlers/Entry/EntryHandler.Android.cs
  src/Core/src/Handlers/ImageButton/ImageButtonHandler.Android.cs
  src/Core/src/Handlers/Picker/PickerHandler.Android.cs
  src/Core/src/Handlers/Picker/PickerHandler.Standard.cs
  src/Core/src/Handlers/Picker/PickerHandler.Tizen.cs
  src/Core/src/Handlers/Picker/PickerHandler.Windows.cs
  src/Core/src/Handlers/Picker/PickerHandler.iOS.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.iOS.cs
  src/Core/src/Handlers/TimePicker/TimePickerHandler.Windows.cs
  src/Core/src/Platform/Android/EditTextExtensions.cs
  src/Core/src/Platform/Android/ImageButtonExtensions.cs
  src/Core/src/Platform/Android/ViewExtensions.cs
  src/Core/src/Platform/Windows/CalendarDatePickerExtensions.cs
  src/Core/src/Platform/Windows/DatePickerExtensions.cs
  src/Core/src/Platform/Windows/TextBoxExtensions.cs
  src/Core/src/Platform/Windows/TimePickerExtensions.cs
  src/Core/src/Platform/iOS/SearchBarExtensions.cs
  src/Core/src/Platform/iOS/TextInputExtensions.cs
  src/Essentials/src/AppInfo/AppInfo.uwp.cs
Labels: t/housekeeping ♻︎

#10793 Fix typos in comments/typos
  src/Core/src/Core/IFlexLayout.cs
  src/Core/src/Core/IMenuFlyoutSeparator.cs
  src/Core/src/Core/ISafeAreaView.cs
  src/Core/src/Dispatching/Dispatcher.Tizen.cs
  src/Core/src/Fonts/IFontManager.cs
  src/Core/src/Handlers/Application/ApplicationHandler.cs
  src/Core/src/Handlers/Border/BorderHandler.Android.cs
  src/Core/src/Handlers/Button/ButtonHandler.Android.cs
  src/Core/src/Handlers/ContentView/ContentViewHandler.Android.cs
  src/Core/src/Handlers/FlyoutView/FlyoutViewHandler.Android.cs
  src/Core/src/Handlers/Layout/LayoutHandler.Android.cs
  src/Core/src/Handlers/RefreshView/RefreshViewHandler.Android.cs
  src/Core/src/Handlers/ScrollView/ScrollViewHandler.Android.cs
  src/Core/src/Handlers/SwipeItemView/SwipeItemViewHandler.Android.cs
  src/Core/src/Hosting/LifecycleEvents/AppHostBuilderExtensions.Android.cs
  src/Core/src/Hosting/LifecycleEvents/AppHostBuilderExtensions.Tizen.cs
  src/Core/src/HotReload/HotReloadHelper.cs
Labels: t/housekeeping ♻︎

#10795 Fix typos in code
  src/Compatibility/ControlGallery/src/Core/GalleryPages/MacOSTestGallery.cs
  src/Compatibility/ControlGallery/src/UITests.Shared/Tests/CarouselViewUITests.cs
  src/Core/src/Graphics/PaintExtensions.Android.cs
  src/Core/src/Graphics/PaintExtensions.Tizen.cs
  src/Core/src/Handlers/Editor/EditorHandler.Android.cs
  src/Core/src/Handlers/Editor/EditorHandler.Windows.cs
  src/Core/src/Handlers/Editor/EditorHandler.iOS.cs
  src/Core/src/Handlers/Entry/EntryHandler.Android.cs
  src/Core/src/Handlers/Entry/EntryHandler.Windows.cs
  src/Core/src/Handlers/Entry/EntryHandler.iOS.cs
  src/Core/src/Handlers/FlyoutView/FlyoutViewHandler.Windows.cs
  src/Core/src/Platform/Tizen/ViewExtensions.cs
Labels: t/housekeeping ♻︎

#8765 Add Obsolete attribute to MessagingCenter
  src/Compatibility/ControlGallery/src/WinUI/WinUIStartup.cs
  src/Compatibility/ControlGallery/src/WinUI/_57114Renderer.cs
  src/Compatibility/ControlGallery/src/iOS/AppDelegate.cs
  src/Compatibility/ControlGallery/src/iOS/PerformanceTrackerRenderer.cs
  src/Compatibility/ControlGallery/src/iOS/_57114Renderer.cs
  src/Compatibility/Maps/src/Android/MapRenderer.cs
  src/Compatibility/Maps/src/iOS/MapRenderer.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/CarouselViewGalleries/CarouselXamlGallery.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/CarouselViewGalleries/ExampleTemplateCarousel.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/CollectionViewGalleries/ItemsSourceGenerator.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/SwipeViewGalleries/CustomSwipeItemViewGallery.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/SwipeViewGalleries/ResourceSwipeItemsGallery.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/SwipeViewGalleries/SwipeBindableLayoutGallery.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/SwipeViewGalleries/SwipeCarouselViewGallery.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/SwipeViewGalleries/SwipeHorizontalCollectionViewGallery.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/SwipeViewGalleries/SwipeListViewGallery.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/SwipeViewGalleries/SwipeVerticalCollectionViewGallery.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/SwipeViewGalleries/SwipeViewGestureRecognizerGallery.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/SwipeViewGalleries/SwipeViewVisualStatesCollectionGallery.xaml.cs
  src/Controls/src/Core/MessagingCenter.cs
  src/Controls/src/Core/Page.cs
  src/Controls/src/Core/Platform/AlertManager/AlertManager.Android.cs
  src/Controls/src/Core/Platform/AlertManager/AlertManager.Tizen.cs
  src/Controls/src/Core/Platform/AlertManager/AlertManager.Windows.cs
  src/Controls/src/Core/Platform/AlertManager/AlertManager.iOS.cs
  src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.Android.cs
  src/Controls/src/Core/RadioButton.cs
  src/Controls/src/Core/RadioButtonGroup.cs
  src/Controls/src/Core/RadioButtonGroupController.cs
  src/Essentials/samples/Samples/Model/PermissionItem.cs
  src/Essentials/samples/Samples/View/PermissionsPage.xaml.cs
Labels: t/housekeeping ♻︎, area/perf 🏎️

#10550 iOS15 WindowStateManager Window Support
  src/Essentials/src/Platform/WindowStateManager.ios.cs
  src/Essentials/test/DeviceTests/Tests/WindowStateManager_Tests.cs
Labels: area/lifecycle 🔁, platform/iOS 🍎, area/essentials 🍞, community ✨

#9477 Update Package.appxmanifest to have PhonePublisherId
  src/Templates/src/templates/maui-blazor/.template.config/template.json
  src/Templates/src/templates/maui-blazor/Platforms/Windows/Package.appxmanifest
  src/Templates/src/templates/maui-mobile/.template.config/template.json
  src/Templates/src/templates/maui-mobile/Platforms/Windows/Package.appxmanifest
Labels: partner/winui, do-not-merge, community ✨

#10808 Fix net7 branch with Analyzers fixes
  eng/Versions.props
  src/Controls/src/Core/Platform/AlertManager/AlertManager.Android.cs
  src/Core/src/Dispatching/Dispatcher.iOS.cs
  src/Core/src/ImageSources/UriImageSourceService/UriImageSourceService.iOS.cs
  src/Core/src/Platform/Android/MauiAppCompatActivity.Lifecycle.cs
  src/Core/src/Platform/iOS/ButtonExtensions.cs
  src/Core/src/Platform/iOS/MauiCheckBox.cs
  src/Core/src/Platform/iOS/MauiSwipeView.cs
  src/Core/src/Platform/iOS/UIApplicationExtensions.cs
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Essentials/src/Browser/Browser.ios.cs
  src/Essentials/src/Connectivity/Connectivity.android.cs
  src/Essentials/src/Contacts/Contacts.ios.macos.cs
  src/Essentials/src/DeviceDisplay/DeviceDisplay.android.cs
  src/Essentials/src/DeviceDisplay/DeviceDisplay.ios.cs
  src/Essentials/src/FilePicker/FilePicker.ios.cs
  src/Essentials/src/FileSystem/FileSystemUtils.android.cs
  src/Essentials/src/Flashlight/Flashlight.android.cs
  src/Essentials/src/Flashlight/Flashlight.ios.cs
  src/Essentials/src/MediaPicker/MediaPicker.ios.cs
  src/Essentials/src/Permissions/Permissions.android.cs
  src/Essentials/src/Permissions/Permissions.ios.tvos.watchos.cs
  src/Essentials/src/Platform/IntermediateActivity.android.cs
  src/Essentials/src/Platform/PlatformUtils.android.cs
  src/Essentials/src/Preferences/Preferences.android.cs
  src/Essentials/src/Screenshot/Screenshot.android.cs
  src/Essentials/src/Vibration/Vibration.android.cs
  src/Essentials/src/WebAuthenticator/WebAuthenticatorIntermediateActivity.android.cs
  src/Graphics/src/Graphics/Platforms/Android/PlatformCanvas.cs
  src/Graphics/src/Graphics/Platforms/Android/TextLayoutUtils.cs
  src/Graphics/src/Graphics/Platforms/MaciOS/PlatformCanvas.cs
  src/Graphics/src/Graphics/Platforms/iOS/PlatformStringSizeService.cs
Labels: t/housekeeping ♻︎

#10813 Add check to ensure measurement for AndExpandLayoutManager
  src/Controls/src/Core/Layout/AndExpandLayoutManager.cs
  src/Controls/tests/Core.UnitTests/Layouts/AndExpandTests.cs
Labels: area/layout 🔲

#10828 Add code format for PR's
  .github/workflows/dotnet-autoformat-pr-push.yml
  .github/workflows/dotnet-autoformat-pr.yml
Labels: t/housekeeping ♻︎

#10830 Update net6 workloads
  eng/Versions.props
Labels: t/housekeeping ♻︎

#10871 Update .NET 6 workload version to 6.0.545
  eng/Versions.props
Labels: area/infrastructure 🏗️

#10836 Fix minimum sizing for * cells with multiple children
  src/Core/src/Layouts/GridLayoutManager.cs
  src/Core/tests/UnitTests/Layouts/GridLayoutManagerTests.cs
Labels: t/bug, area/layout 🔲

#10940 [net6] Update sr7 with maestro bumps
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: area/infrastructure 🏗️

#10962 Update .NET 6 MAUI version
  eng/Versions.props
Labels: area/infrastructure 🏗️

#10957 Cherrypick fron net7 to release branch
  eng/Version.Details.xml
  eng/Versions.props
  src/Core/src/Platform/iOS/ApplicationExtensions.cs
  src/Essentials/src/Platform/WindowStateManager.ios.cs
Labels: area/infrastructure 🏗️

#10954 Update Microsoft.Maui-mac.slnf
  Microsoft.Maui-mac.slnf
Labels: area/infrastructure 🏗️
