Repository dotnet/maui, pull requests merged in 2022-06, with the labels that each got.

#7658 [CollectionView] Make sure we map MapSelectionMode and SelectedITems
  src/Controls/src/Core/Handlers/Items/CollectionViewHandler.cs
Labels: area/collectionview 📃

#7642 Revert a type move for net6
  src/Controls/src/Build.Tasks/NodeILExtensions.cs
  src/Controls/src/Core.Design/AttributeTableBuilder.cs
  src/Controls/src/Core/FlowDirectionConverter.cs
  src/Controls/src/Core/VisualElement.cs
  src/Core/src/Primitives/FlowDirection.cs
Labels: blocker, p/0, area/controls 🎮

#7665 Fix crash setting zero or negative values in Border size
  src/Core/src/Platform/Windows/ContentPanel.cs
Labels: t/bug, area/layout 🔲, area/drawing ✏️

#7339 Merge the PublicAPI checker into main
  src/Controls/src/Core/Controls.Core.csproj
  src/Controls/src/Core/Handlers/Items/iOS/TemplatedCell.cs
  src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs
  src/Controls/src/Core/Platform/Tizen/Shell/ShellView.cs
  src/Controls/src/Core/Platform/Windows/Extensions/FormattedStringExtensions.cs
  src/Controls/src/Core/Platform/iOS/Extensions/FormattedStringExtensions.cs
  src/Controls/src/Core/PublicAPI/net6.0-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net6.0-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net6.0-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net6.0-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net6.0-windows10.0.19041/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net6.0-windows10.0.20348/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net6.0/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
  src/Controls/src/Xaml/Controls.Xaml.csproj
  src/Core/src/Core.csproj
  src/Core/src/Graphics/MauiDrawable.Android.cs
  src/Core/src/Platform/iOS/MauiUIApplicationDelegate.cs
  src/Core/src/PublicAPI/net6.0-android/PublicAPI.Shipped.txt
  src/Core/src/PublicAPI/net6.0-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net6.0-ios/PublicAPI.Shipped.txt
  src/Core/src/PublicAPI/net6.0-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net6.0-maccatalyst/PublicAPI.Shipped.txt
  src/Core/src/PublicAPI/net6.0-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net6.0-tizen/PublicAPI.Shipped.txt
  src/Core/src/PublicAPI/net6.0-windows10.0.19041/PublicAPI.Shipped.txt
  src/Core/src/PublicAPI/net6.0-windows10.0.20348/PublicAPI.Shipped.txt
  src/Core/src/PublicAPI/net6.0/PublicAPI.Shipped.txt
  src/Core/src/PublicAPI/netstandard2.0/PublicAPI.Shipped.txt
  src/Core/src/PublicAPI/netstandard2.1/PublicAPI.Shipped.txt
  src/Essentials/src/Essentials.csproj
Labels: p/0, area/infrastructure 🏗️

#7633 [Android] Implement quit Application
  src/Controls/samples/Controls.Sample/Pages/Core/ApplicationControlPage.xaml
  src/Core/src/Handlers/Application/ApplicationHandler.Android.cs
Labels: t/bug, platform/android 🤖

#7215 [Android] Fix Button CornerRadius issue
  src/Core/src/Platform/Android/BorderDrawable.cs
Labels: t/bug, platform/android 🤖, area/controls 🎮, control-button

#7685 This is more correct
  src/Core/src/PublicAPI/net6.0-windows10.0.19041/PublicAPI.Shipped.txt
  src/Core/src/PublicAPI/net6.0-windows10.0.19041/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net6.0-windows10.0.20348/PublicAPI.Shipped.txt
  src/Core/src/PublicAPI/net6.0-windows10.0.20348/PublicAPI.Unshipped.txt
Labels: area/infrastructure 🏗️

#7704 [build] Version .NET VS manifest file
  eng/automation/vs-workload.template.props
  src/Workload/Microsoft.NET.Sdk.Maui/Microsoft.NET.Sdk.Maui.csproj
Labels: area/setup 🪄

#7741 [net6.0] Bump iOS versions
  eng/Version.Details.xml
  eng/Versions.props
Labels: area/infrastructure 🏗️

#7430 More info on templates
  Directory.Build.props
  src/Templates/src/Microsoft.Maui.Templates.csproj
  src/Templates/src/templates/maui-blazor/.template.config/template.in.json
  src/Templates/src/templates/maui-contentpage-csharp/.template.config/template.json
  src/Templates/src/templates/maui-contentpage-xaml/.template.config/template.json
  src/Templates/src/templates/maui-contentview-csharp/.template.config/template.json
  src/Templates/src/templates/maui-contentview-xaml/.template.config/template.json
  src/Templates/src/templates/maui-lib/.template.config/template.in.json
  src/Templates/src/templates/maui-mobile/.template.config/template.in.json
  src/Workload/Microsoft.NET.Sdk.Maui/Microsoft.NET.Sdk.Maui.csproj
  src/Workload/Microsoft.NET.Sdk.Maui/WorkloadManifest.in.json
Labels: area/templates 📄

#7736 Update ide.host.json schema.
  src/Templates/src/templates/maui-blazor/.template.config/ide.host.json
  src/Templates/src/templates/maui-contentpage-csharp/.template.config/ide.host.json
  src/Templates/src/templates/maui-contentpage-xaml/.template.config/ide.host.json
  src/Templates/src/templates/maui-contentview-csharp/.template.config/ide.host.json
  src/Templates/src/templates/maui-contentview-xaml/.template.config/ide.host.json
  src/Templates/src/templates/maui-lib/.template.config/ide.host.json
  src/Templates/src/templates/maui-mobile/.template.config/ide.host.json
  src/Templates/src/templates/maui-resourcedictionary-xaml/.template.config/ide.host.json
Labels: area/templates 📄

#7791 [housekeeping] Fix signing and insertion for net6 branch
  eng/pipelines/common/insertion.yml
  eng/pipelines/common/sign.yml
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#7622 [Tizen] Fix RendererToHandlerShim.Tizen
  src/Compatibility/Core/src/RendererToHandlerShim.Tizen.cs
Labels: platform/tizen

#7689 [Android,iOS] Fix Selection on CollectionView and VSM color changes for Layouts
  src/Controls/src/Core/Handlers/Items/Android/Adapters/SelectableItemsViewAdapter.cs
  src/Controls/src/Core/Platform/Android/Extensions/RecyclerViewExtensions.cs
  src/Core/src/Platform/Android/ViewExtensions.cs
  src/Core/src/Platform/iOS/ViewExtensions.cs
  src/Core/tests/DeviceTests/Handlers/Window/WindowHandlerTests.cs
Labels: area/collectionview 📃

#7771 Fix TemplatedView
  src/Controls/samples/Controls.Sample/Controls/Rate/Rate.cs
  src/Controls/samples/Controls.Sample/Controls/Rate/Rate.xaml
  src/Controls/samples/Controls.Sample/Controls/Rate/Rate.xaml.cs
  src/Controls/samples/Controls.Sample/Controls/Rate/RateItem.cs
  src/Controls/samples/Controls.Sample/Controls/Rate/ValueChangedEventArgs.cs
  src/Controls/samples/Controls.Sample/Pages/Layouts/TemplatedViewPage.xaml
  src/Controls/samples/Controls.Sample/XamlApp.xaml
  src/Controls/src/Core/ContentView.cs
  src/Controls/src/Core/HandlerImpl/ContentView/ContentView.Impl.cs
  src/Controls/src/Core/HandlerImpl/RadioButton/RadioButton.Impl.cs
  src/Controls/src/Core/HandlerImpl/TemplatedView/TemplatedView.Impl.cs
  src/Controls/src/Core/PublicAPI/net6.0-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net6.0-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net6.0-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net6.0-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net6.0-windows10.0.19041/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net6.0-windows10.0.20348/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net6.0/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
  src/Controls/src/Core/TemplatedView.cs
  src/Controls/tests/Core.UnitTests/HostBuilderHandlerTests.cs
  src/Controls/tests/Core.UnitTests/TemplatedViewUnitTests.cs
  src/Controls/tests/DeviceTests/Elements/TemplatedView/TemplatedViewTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/TemplatedView/TemplatedViewTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/TemplatedView/TemplatedViewTests.cs
  src/Controls/tests/DeviceTests/Elements/TemplatedView/TemplatedViewTests.iOS.cs
  src/Controls/tests/DeviceTests/TestCategory.cs
Labels: t/bug, area/controls 🎮

#7509 Return VER for PlatformView
  src/Controls/src/Core/Compatibility/Handlers/Android/ViewRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/Android/VisualElementRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/VisualElementRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/Windows/VisualElementRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/iOS/ViewRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/iOS/VisualElementRenderer.cs
  src/Controls/tests/DeviceTests/Elements/Compatibility/VisualElementRendererTests.cs
  src/Controls/tests/DeviceTests/Elements/Frame/FrameTests.cs
  src/Controls/tests/DeviceTests/TestCategory.cs
Labels: area/controls 🎮

#7425 Better handle disappearing content with ViewPager2
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellFragmentStateAdapter.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellSectionRenderer.cs
  src/Controls/src/Core/HandlerImpl/Page.Impl.cs
  src/Controls/src/Core/Shell/ShellContent.cs
  src/Controls/tests/Core.UnitTests/ShellTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.cs
  src/Controls/tests/DeviceTests/HandlerTestBase.cs
Labels: area/shell 🐢

#7742 BlazorWebView WPF tab navigation improvements
  src/BlazorWebView/src/Wpf/BlazorWebView.cs
Labels: area/blazor 🕸️

#7807 Use the new layout system in ContentPresenter
  src/Controls/src/Core/ContentPresenter.cs
  src/Controls/src/Core/PublicAPI/net6.0-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net6.0-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net6.0-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net6.0-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net6.0-windows10.0.19041/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net6.0-windows10.0.20348/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net6.0/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard2.1/PublicAPI.Unshipped.txt
Labels: t/bug, area/layout 🔲

#7828 Use the SDK band in the rollback files
  src/Workload/Microsoft.NET.Sdk.Maui/Microsoft.NET.Sdk.Maui.csproj
  src/Workload/Microsoft.NET.Sdk.Maui/Rollback.in.json
Labels: area/setup 🪄

#7802 Fix SearchBar semantics
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformInterop.java
  src/Core/src/Handlers/SearchBar/SearchBarHandler.iOS.cs
  src/Core/src/Platform/iOS/SearchBarExtensions.cs
  src/Core/src/Platform/iOS/SemanticExtensions.cs
  src/Core/src/maui.aar
  src/Core/tests/DeviceTests/Handlers/HandlerTestBaseOfT.iOS.cs
Labels: area/a11y, do-not-merge, area/controls 🎮, control-entry

#7859 [xamlc] stop using pack:// with System.Uri in .NET 7
  src/Controls/src/Build.Tasks/BuildException.cs
  src/Controls/src/Build.Tasks/CompiledConverters/RDSourceTypeConverter.cs
  src/Controls/src/Build.Tasks/ErrorMessages.resx
  src/Controls/src/Core/ResourceDictionary.cs
Labels: area/Xaml </>

#7904 VisualTreeElement methods need to use DP vs PX
  src/Controls/tests/DeviceTests/Elements/Compatibility/VisualElementRendererTests.cs
  src/Controls/tests/DeviceTests/Elements/VisualElementTreeTests.cs
  src/Controls/tests/DeviceTests/HandlerTestBase.cs
  src/Controls/tests/DeviceTests/TestCategory.cs
  src/Core/src/Core/Extensions/VisualTreeElementExtensions.cs
  src/Core/src/Platform/Android/ViewExtensions.cs
  src/Core/src/Platform/iOS/ViewExtensions.cs
  src/Core/tests/DeviceTests/Handlers/HandlerTestBaseOfT.Android.cs
  src/Core/tests/DeviceTests/Handlers/HandlerTestBaseOfT.Tests.cs
  src/Core/tests/DeviceTests/Handlers/HandlerTestBaseOfT.Windows.cs
  src/Core/tests/DeviceTests/Handlers/HandlerTestBaseOfT.iOS.cs
  src/TestUtils/src/DeviceTests/AssertionExtensions.cs
Labels: area/tooling ⚙️, partner/ui-tools, do-not-merge

#7879 [iOS] Fix exception using FlyoutBackgroundImage
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellFlyoutContentRenderer.cs
Labels: t/bug, area/shell 🐢, fatal

#7983 Fix Essentials WebAuthenticator sample code
  src/Essentials/samples/Sample.Server.WebAuthenticator/Controllers/MobileAuthController.cs
Labels: area/essentials 🍞

#7976 Fix `maui-blazor` indentation
  src/Templates/src/templates/maui-blazor/App.xaml.cs
  src/Templates/src/templates/maui-blazor/Data/WeatherForecast.cs
  src/Templates/src/templates/maui-blazor/Data/WeatherForecastService.cs
  src/Templates/src/templates/maui-blazor/Main.razor
  src/Templates/src/templates/maui-blazor/MainPage.xaml.cs
  src/Templates/src/templates/maui-blazor/MauiApp.1.App.sln
  src/Templates/src/templates/maui-blazor/MauiApp.1.csproj
  src/Templates/src/templates/maui-blazor/MauiProgram.cs
  src/Templates/src/templates/maui-blazor/Pages/FetchData.razor
  src/Templates/src/templates/maui-blazor/Platforms/Android/AndroidManifest.xml
  src/Templates/src/templates/maui-blazor/Platforms/Android/MainApplication.cs
  src/Templates/src/templates/maui-blazor/Platforms/MacCatalyst/AppDelegate.cs
  src/Templates/src/templates/maui-blazor/Platforms/MacCatalyst/Info.plist
  src/Templates/src/templates/maui-blazor/Platforms/MacCatalyst/Program.cs
  src/Templates/src/templates/maui-blazor/Platforms/Tizen/Main.cs
  src/Templates/src/templates/maui-blazor/Platforms/Windows/App.xaml.cs
  src/Templates/src/templates/maui-blazor/Platforms/iOS/AppDelegate.cs
  src/Templates/src/templates/maui-blazor/Platforms/iOS/Info.plist
  src/Templates/src/templates/maui-blazor/Platforms/iOS/Program.cs
  src/Templates/src/templates/maui-blazor/Resources/Raw/AboutAssets.txt
  src/Templates/src/templates/maui-blazor/Shared/MainLayout.razor
  src/Templates/src/templates/maui-blazor/Shared/NavMenu.razor
  src/Templates/src/templates/maui-blazor/wwwroot/css/app.css
  src/Templates/src/templates/maui-blazor/wwwroot/index.html
Labels: area/blazor 🕸️

#8007 Add default `Name=blazorWebView` to MAUI MainPage.xaml
  src/Templates/src/templates/maui-blazor/MainPage.xaml
Labels: area/blazor 🕸️, area/templates 📄

#8006 Remove RC2 & Preview 14 Development Workload Installation Instructions
  .github/DEVELOPMENT.md
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#8047 [C] fix BP declarations for Border
  src/Controls/src/Core/Border.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui7744.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui7744.xaml.cs
Labels: area/Xaml </>, area/drawing ✏️

#8034 [android] reduce JNI calls during layout measurement
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformInterop.java
  src/Core/src/Handlers/ViewHandlerExtensions.Android.cs
  src/Core/src/maui.aar
Labels: area/perf 🏎️

#7996 [essentials] use Lazy<T> for Android application-wide values
  src/Essentials/src/AppInfo/AppInfo.android.cs
Labels: area/essentials 🍞

#8001 [android] avoid View.Context where unecessary
  src/Core/src/Platform/Android/ContentViewGroup.cs
  src/Core/src/Platform/Android/ContextExtensions.cs
  src/Core/src/Platform/Android/LayoutViewGroup.cs
  src/Core/src/Platform/Android/TextViewExtensions.cs
  src/Core/src/Platform/Android/TransformationExtensions.cs
  src/Core/src/Platform/Android/ViewExtensions.cs
Labels: area/perf 🏎️

#8070 Update Development Notes to the latest
  .github/DEVELOPMENT.md
Labels: area/infrastructure 🏗️

#8033 [core] use Lazy<T> for MauiContext properties
  src/Core/src/MauiContext.cs
Labels: area/perf 🏎️

#8002 Explicitly set bounds for iOS ScrollView content holder
  src/Core/src/Handlers/ScrollView/ScrollViewHandler.iOS.cs
Labels: area/layout 🔲

#8107 Update the Windows App SDK
  eng/Versions.props
Labels: platform/windows 🪟, t/housekeeping ♻︎, area/desktop 🖥️

#8140 Update the conditions for signing to include net7
  eng/pipelines/common/insertion.yml
  eng/pipelines/common/sign.yml
  eng/pipelines/common/variables.yml
Labels: area/infrastructure 🏗️

#8069 Remove the extra lines in the error message for better viewing
  .nuspec/Microsoft.Maui.Resizetizer.targets
  src/SingleProject/Resizetizer/src/DetectInvalidResourceOutputFilenamesTask.cs
  src/SingleProject/Resizetizer/test/UnitTests/DetectInvalidResourceOutputFilenamesTests.cs
Labels: area/single project ☝️

#8117 Fix Modal Navigation with Shell
  src/Controls/src/Core/HandlerImpl/Window/Window.Android.cs
  src/Controls/src/Core/HandlerImpl/Window/Window.cs
  src/Controls/tests/DeviceTests/Elements/Modal/ModalTests.cs
  src/Controls/tests/DeviceTests/Stubs/WindowHandlerStub.Android.cs
  src/Core/src/Handlers/Window/WindowHandler.Android.cs
  src/Core/src/Platform/Android/Navigation/NavigationRootManager.cs
Labels: area/shell 🐢

#8021 Hook up horizontal scroll events on Android
  src/Core/src/Platform/Android/MauiScrollView.cs
Labels: area/layout 🔲, platform/android 🤖

#8133 [Tizen] Fill ScrollView when content is smaller than viewport
  src/Core/src/Handlers/ScrollView/ScrollViewHandler.Tizen.cs
Labels: area/layout 🔲, platform/tizen

#8064 Make implicit package refs privateassets=all
  src/Workload/Microsoft.Maui.Sdk/Sdk/BundledVersions.in.targets
Labels: area/single project ☝️

#7666 [iOS] Fix issue using gradients in Button with Corner Radius
  src/Core/src/Platform/iOS/ViewExtensions.cs
  src/Core/src/PublicAPI/net-ios/PublicAPI.Shipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Shipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
Labels: t/bug, platform/iOS 🍎, area/controls 🎮, control-button

#7694 [iOS] Correctly return the value from Focus method
  src/Core/src/Platform/iOS/ViewExtensions.cs
Labels: t/bug, platform/iOS 🍎, area/controls 🎮

#8162 Add the Microsoft.Maui.Dispatching using
  src/Workload/Microsoft.Maui.Sdk/Sdk/AutoImport.props
Labels: area/dispatching

#8190 Resize star rows/columns _only_ during Arrange, if necessary
  src/Core/src/Layouts/GridLayoutManager.cs
  src/Core/tests/UnitTests/Layouts/GridLayoutManagerTests.cs
Labels: platform/windows 🪟, area/layout 🔲

#7695 [iOS] Fix issue not rendering Border background using a Shadow
  src/Core/src/Handlers/Border/BorderHandler.iOS.cs
  src/Core/src/Platform/iOS/ContentView.cs
  src/Core/src/Platform/iOS/StrokeExtensions.cs
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
Labels: t/bug, area/drawing ✏️, platform/iOS 🍎

#8181 Use FabricBot to label partner issues instead of custom GitHub action
  .github/fabricbot.json
  .github/fabricbot_readme.md
  issueopenerlabels.json
Labels: area/infrastructure 🏗️

#7672 Fix for #5523 MauiWebView not loading local files on Windows
  src/Core/src/Platform/Windows/MauiWebView.cs
Labels: platform/windows 🪟, partner/cat 😻, area/controls 🎮, control-webview

#8215 Update FabricBot partner list
  .github/fabricbot.json
Labels: area/infrastructure 🏗️

#8220 Apply template values for project item templates
  src/Templates/src/Microsoft.Maui.Templates.csproj
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.cs.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.de.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.en.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.es.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.fr.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.it.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.ja.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.ko.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.pl.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.pt-BR.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.ru.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.tr.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.zh-Hans.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.zh-Hant.json
  src/Templates/src/templates/maui-blazor/.template.config/template.json
  src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.cs.json
  src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.de.json
  src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.en.json
  src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.es.json
  src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.fr.json
  src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.it.json
  src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.ja.json
  src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.json
  src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.ko.json
  src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.pl.json
  src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.pt-BR.json
  src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.ru.json
  src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.tr.json
  src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.zh-Hans.json
  src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.zh-Hant.json
  src/Templates/src/templates/maui-lib/.template.config/template.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.cs.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.de.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.en.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.es.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.fr.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.it.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.ja.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.ko.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.pl.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.pt-BR.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.ru.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.tr.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.zh-Hans.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.zh-Hant.json
  src/Templates/src/templates/maui-mobile/.template.config/template.json
  src/Templates/src/templates/maui-resourcedictionary-xaml/.template.config/template.json
Labels: blocker, do-not-merge, area/templates 📄

#8188 Clean up whitespace
  src/Templates/src/templates/maui-mobile/MainPage.xaml
Labels: t/housekeeping ♻︎

#8230 Make the loc base branch a variable
  eng/pipelines/common/localization-handback.yml
  eng/pipelines/common/localization-handoff.yml
  eng/pipelines/common/variables.yml
Labels: area/infrastructure 🏗️

#8184 Make VisualElement.ZIndexProperty BP public
  src/Controls/src/Core/HandlerImpl/VisualElement/VisualElement.Impl.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
Labels: area/layout 🔲

#8243 [android] avoid View.Context during CollectionView scrolling
  src/Controls/src/Core/Handlers/Items/Android/ItemContentView.cs
  src/Controls/src/Core/Handlers/Items/Android/RecyclerViewScrollListener.cs
  src/Core/src/Platform/Android/ContextExtensions.cs
Labels: area/perf 🏎️

#8237 Run the Templates test on implicit and explicit TFMs
  eng/cake/dotnet.cake
  eng/pipelines/handlers.yml
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#8204 Make sure the AutoImports.props is only included once per .NET version
  src/Workload/Microsoft.Maui.Sdk/Microsoft.Maui.Sdk.csproj
  src/Workload/Microsoft.Maui.Sdk/Sdk/AutoImport.in.props
Labels: area/single project ☝️, blocker

#8134 [Tizen] Update default Shell Flyout behavior
  src/Controls/src/Core/Platform/Tizen/Shell/ShellView.cs
Labels: area/shell 🐢

#7712 Fix GridLayoutManager Layout calculation
  src/Core/src/Layouts/GridLayoutManager.cs
  src/Core/tests/UnitTests/Layouts/GridLayoutManagerTests.cs
Labels: area/layout 🔲, community ✨

#8216 Measure Images in FlexLayout at full size
  src/Controls/src/Core/Layout/FlexLayout.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Shipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Shipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Shipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Shipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Shipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Shipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Shipped.txt
  src/Controls/tests/Core.UnitTests/Layouts/FlexLayoutTests.cs
Labels: area/layout 🔲

#7793 [Android] Fix issue using DynamicResource TextColor on Label FormattedString
  src/Controls/src/Core/HandlerImpl/Label/Label.Android.cs
  src/Controls/src/Core/HandlerImpl/Label/Label.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.Android.cs
Labels: t/bug, platform/android 🤖, area/controls 🎮, control-label

#7724 [Android] Fix issue clipping ImageButton
  src/Core/src/Handlers/ImageButton/ImageButtonHandler.Android.cs
  src/Core/src/Handlers/ImageButton/ImageButtonHandler.cs
  src/Core/src/Platform/Android/ImageButtonExtensions.cs
  src/Core/tests/DeviceTests/Handlers/ImageButton/ImageButtonHandlerTests.Android.cs
  src/Core/tests/DeviceTests/Handlers/ImageButton/ImageButtonHandlerTests.cs
  src/Core/tests/DeviceTests/Stubs/LinearGradientPaintStub.cs
Labels: t/bug, platform/android 🤖, area/controls 🎮, control-radiobutton

#7794 [iOS] Fix BackgroundColor property issue on SearchBar
  src/Compatibility/Core/src/iOS/Renderers/SearchBarRenderer.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.Android.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.Tizen.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.iOS.cs
  src/Core/src/Platform/iOS/SearchBarExtensions.cs
  src/Core/tests/DeviceTests/Handlers/SearchBar/SearchBarHandlerTests.cs
Labels: t/bug, platform/iOS 🍎, area/controls 🎮, control-entry

#8250 [layout] avoid IView[] creation in LayoutExtensions
  src/Core/src/Handlers/Layout/LayoutExtensions.cs
  src/Core/tests/UnitTests/Layouts/ZIndexTests.cs
Labels: area/perf 🏎️

#8282 Make sure the templates support --framework
  eng/pipelines/handlers.yml
  src/Templates/src/Microsoft.Maui.Templates.csproj
  src/Templates/src/templates/maui-blazor/.template.config/dotnetcli.host.json
  src/Templates/src/templates/maui-blazor/.template.config/template.json
  src/Templates/src/templates/maui-lib/.template.config/dotnetcli.host.json
  src/Templates/src/templates/maui-mobile/.template.config/dotnetcli.host.json
  src/Templates/src/templates/maui-mobile/.template.config/template.json
Labels: blocker, area/templates 📄

#8192 [Windows] Fix rendering GraphicsView rendering issue on Windows
  src/Controls/samples/Controls.Sample/Pages/Others/GraphicsViewPage.xaml
  src/Core/src/Handlers/GraphicsView/GraphicsViewHandler.Windows.cs
Labels: t/bug, platform/windows 🪟, area/drawing ✏️

#8219 Wait to fire nav events until page exists
  src/Controls/src/Core/Shell/Shell.cs
  src/Controls/src/Core/Shell/ShellContent.cs
  src/Controls/src/Core/Shell/ShellNavigationManager.cs
  src/Controls/tests/Core.UnitTests/ShellTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.cs
Labels: area/lifecycle 🔁

#7335 [iOS] Clip Border content based on StrokeShape property
  src/Core/src/Platform/iOS/ContentView.cs
  src/Core/src/Platform/iOS/StrokeExtensions.cs
Labels: area/drawing ✏️, platform/iOS 🍎

#8280 [Android] Avoid load icon if menu item is disposed
  src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs
Labels: t/bug, platform/android 🤖, area/shell 🐢, fatal

#8384 Build MAUI with dotnet build
  Directory.Build.props
  eng/cake/dotnet.cake
  eng/package.ps1
  src/Controls/src/Core.Design/Controls.Core.Design.csproj
  src/Controls/src/Core/Controls.Core.csproj
  src/Controls/src/Xaml.Design/Controls.Xaml.Design.csproj
  src/Controls/src/Xaml/Controls.Xaml.csproj
Labels: area/infrastructure 🏗️

#8336 Fix typo
  .github/DEVELOPMENT.md
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#8399 Convert Android Hit Test values to Units
  src/Core/src/WindowOverlay/WindowOverlay.Android.cs
Labels: area/tooling ⚙️, partner/ui-tools

#8396 Update with branch and project structure
  .github/DEVELOPMENT.md
Labels: area/infrastructure 🏗️

#8397 Remove the workaround for the WinUI targets
  src/Workload/Microsoft.Maui.Sdk/Sdk/WinUI.NetCore.targets
  src/Workload/Microsoft.Maui.Sdk/Sdk/WinUI.targets
Labels: area/single project ☝️, t/housekeeping ♻︎

#8368 Return unknown if not on UI Thread for WinUI
  src/Essentials/src/AppInfo/AppInfo.uwp.cs
  src/Essentials/src/Platform/WindowStateManager.uwp.cs
Labels: area/essentials 🍞

#8392 Remove the confusing `.` in the template tests
  eng/cake/dotnet.cake
Labels: area/infrastructure 🏗️

#8428 [Windows] Add a root view for a window to manage pages and overlays
  src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Modal/ModalTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Window/WindowTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Window/WindowTests.cs
  src/Core/src/Handlers/Window/WindowHandler.Windows.cs
  src/Core/src/Platform/Windows/WindowRootViewContainer.cs
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/WindowOverlay/WindowOverlay.Windows.cs
Labels: platform/windows 🪟, area/navigation 🧭, area/tooling ⚙️
