Repository dotnet/maui, pull requests merged in 2023-11, with the labels that each got.

#18451 (Windows) Fix backbutton not being drawn for other NavigationPages
  src/Controls/src/Core/NavigationPage/NavigationPage.cs
  src/Controls/tests/DeviceTests/Elements/NavigationPage/NavigationPageTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/NavigationPage/NavigationPageTests.cs
  src/Core/src/Platform/Windows/RootNavigationView.cs
Labels: platform/windows 🪟, area/navigation 🧭, i/regression

#18448 [ci] Bump iOS and Android
  eng/Version.Details.xml
  eng/Versions.props
Labels: area/infrastructure 🏗️

#18487 Update main to the latest public versions
  eng/Versions.props
Labels: t/housekeeping ♻︎

#17789 [iOS] Fix ContentPage BackgroundImageSource not working
  src/Controls/samples/Controls.Sample.UITests/Issues/Issues17789.xaml
  src/Controls/samples/Controls.Sample.UITests/Issues/Issues17789.xaml.cs
  src/Controls/samples/Controls.Sample.UITests/Resources/Images/oasis.jpg
  src/Controls/tests/UITests/Tests/Issues/Issue17789.cs
  src/Controls/tests/UITests/snapshots/android/ContentPageBackgroundImageSourceWorks.png
  src/Controls/tests/UITests/snapshots/ios/ContentPageBackgroundImageSourceWorks.png
  src/Controls/tests/UITests/snapshots/windows/ContentPageBackgroundImageSourceWorks.png
  src/Core/src/Handlers/Page/PageHandler.iOS.cs
  src/Core/src/Platform/iOS/PageExtensions.cs
Labels: t/bug, platform/iOS 🍎, area/controls 🎮, control-pages

#17928 [Android] Removes freeze using SecureStorage
  src/Essentials/src/SecureStorage/SecureStorage.android.cs
  src/Essentials/test/DeviceTests/Tests/SecureStorage_Tests.cs
Labels: t/bug, platform/android 🤖, area/essentials 🍞

#18549 Microsoft.TemplateEngine.Tasks is stable
  .github/dependabot.yml
  eng/Version.Details.xml
  eng/Versions.props
Labels: area/infrastructure 🏗️

#18544 [ci] Update net8 versions
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: area/infrastructure 🏗️

#18267 [controls] fix memory leak with `CarouselView` & `INotifyCollectionChanged`
  src/Controls/src/Core/Handlers/Items/Android/ItemsSources/ItemsSourceFactory.cs
  src/Controls/src/Core/Handlers/Items/Android/ItemsSources/ObservableItemsSource.cs
  src/Controls/src/Core/Handlers/Items/CarouselViewHandler.Windows.cs
  src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs
  src/Controls/src/Core/Handlers/Items/iOS/CarouselViewLayout.cs
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs
  src/Controls/src/Core/Platform/Windows/CollectionView/ItemTemplateContext.cs
  src/Controls/src/Core/Platform/Windows/CollectionView/ObservableItemTemplateCollection.cs
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/tests/DeviceTests/Memory/MemoryTests.cs
Labels: area/collectionview 📃, memory-leak 💦

#18550 Update car image/size
  src/Templates/src/templates/maui-mobile/MainPage.xaml
  src/Templates/src/templates/maui-mobile/MauiApp.1.csproj
  src/Templates/src/templates/maui-mobile/Resources/Images/dotnet_bot.png
Labels: area/templates 📄

#18511 Enable Dependabot
  .github/dependabot.yml
  NuGet.config
  eng/Versions.props
Labels: area/infrastructure 🏗️

#18581 Move MAUI Blazor template files to match ASP.NET Blazor template
  src/Templates/src/templates/maui-blazor/Components/Routes.razor
  src/Templates/src/templates/maui-blazor/Components/_Imports.razor
  src/Templates/src/templates/maui-blazor/MainPage.xaml
Labels: area/blazor 🕸️, area/templates 📄

#18584 [android] fix memory leak with `CarouselView`
  src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs
  src/Controls/tests/DeviceTests/Elements/NavigationPage/NavigationPageTests.cs
Labels: platform/android 🤖, area/collectionview 📃, memory-leak 💦

#18622 [Testing] Added UI Test for manual test G5
  src/Controls/samples/Controls.Sample.UITests/IssueAttribute.cs
  src/Controls/samples/Controls.Sample.UITests/IssueTracker.cs
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue18617.xaml
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue18617.xaml.cs
  src/Controls/samples/Controls.Sample.UITests/TestCases.cs
  src/Controls/tests/UITests/Tests/Issues/Issue18617.cs
Labels: t/housekeeping ♻︎, area/testing

#18643 Fixed issue creating Paths with PolyLineSegment without points
  src/Compatibility/Core/src/iOS/Extensions/GeometryExtensions.cs
Labels: area/drawing ✏️

#18649 [Testing] Added UI Test for manual test D3
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue18645.xaml
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue18645.xaml.cs
  src/Controls/tests/UITests/Tests/Issues/Issue18645.cs
Labels: t/housekeeping ♻︎, area/testing

#18663 [ios] fix memory leak in `Stepper`
  src/Controls/tests/DeviceTests/Memory/MemoryTests.cs
  src/Core/src/Handlers/Stepper/StepperHandler.iOS.cs
Labels: platform/iOS 🍎, area/controls 🎮, control-stepper, memory-leak 💦

#18621 Fix PlatformStringSizeService on iOS/Catalyst to use correct API
  src/Graphics/src/Graphics/Platforms/iOS/PlatformStringSizeService.cs
Labels: area/drawing ✏️, platform/iOS 🍎

#18602 [ios] fix memory leak in `ImageButton`
  src/Controls/tests/DeviceTests/Memory/MemoryTests.cs
  src/Core/src/Handlers/ImageButton/ImageButtonHandler.iOS.cs
  src/Core/src/Platform/Android/ImageButtonExtensions.cs
Labels: platform/android 🤖, platform/iOS 🍎, area/controls 🎮, memory-leak 💦

#17669 `sealed` some `internal` classes in `Controls.Core` that are not inherited from (1)
  src/Controls/src/Core/AnimatableKey.cs
  src/Controls/src/Core/BindableObject.cs
  src/Controls/src/Core/BindingExpression.cs
  src/Controls/src/Core/CastingEnumerator.cs
  src/Controls/src/Core/Compatibility/Android/ResourcesProvider.cs
  src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ConditionalFocusLayout.cs
  src/Controls/src/Core/Compatibility/Handlers/ListView/Android/GroupedListViewAdapter.cs
  src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ListViewRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/ListView/Android/TextCellRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/iOS/KeyboardInsetTracker.cs
Labels: area/architecture, community ✨

#18586 Arrange content based on arrangement bounds rather than viewport bounds
  src/Controls/tests/DeviceTests/Elements/ScrollView/ScrollViewTests.iOS.cs
  src/Core/src/Handlers/ScrollView/ScrollViewHandler.iOS.cs
Labels: area/layout 🔲

#18682 [ios] fix memory leak in `Switch`
  src/Controls/tests/DeviceTests/Memory/MemoryTests.cs
  src/Core/src/Handlers/Switch/SwitchHandler.iOS.cs
Labels: platform/iOS 🍎, memory-leak 💦

#18681 [ios] fix memory leak in `Slider`
  src/Controls/tests/DeviceTests/Memory/MemoryTests.cs
  src/Core/src/Handlers/Slider/SliderHandler.iOS.cs
Labels: platform/iOS 🍎, memory-leak 💦

#18650 [Testing] Added UI Test for manual test D4
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue18647.xaml
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue18647.xaml.cs
  src/Controls/tests/UITests/Tests/Issues/Issue18647.cs
Labels: t/housekeeping ♻︎, area/testing

#18552 [ios] fix memory leak in `Frame`, `VisualElementRenderer`
  src/Controls/src/Core/Compatibility/Handlers/VisualElementRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs
  src/Controls/tests/DeviceTests/Memory/MemoryTests.cs
Labels: platform/iOS 🍎, area/controls 🎮, memory-leak 💦

#18520 Fix broadcast receiver register on android 14.0/34+
  src/Essentials/src/Battery/Battery.android.cs
  src/Essentials/src/Connectivity/Connectivity.android.cs
  src/Essentials/src/Platform/PlatformUtils.android.cs
  src/Essentials/test/DeviceTests/Tests/Battery_Tests.cs
  src/Essentials/test/DeviceTests/Tests/Connectivity_Tests.cs
Labels: platform/android 🤖, area/essentials 🍞

#18731 Remove invalid files from MauiImage
  src/SingleProject/Resizetizer/src/nuget/buildTransitive/Microsoft.Maui.Resizetizer.After.targets
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/TemplateTests.cs
Labels: area/single project ☝️

#18709 [Testing] Added UI Test for manual test D14
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue18706.xaml
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue18706.xaml.cs
  src/Controls/tests/UITests/Tests/Issues/Issue18706.cs
  src/Controls/tests/UITests/snapshots/android/EditorBackgroundWorks.png
  src/Controls/tests/UITests/snapshots/ios/EditorBackgroundWorks.png
  src/Controls/tests/UITests/snapshots/windows/EditorBackgroundWorks.png
Labels: t/housekeeping ♻︎, area/testing

#18676 [Testing] Added UI Test for manual test D11
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue18673.xaml
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue18673.xaml.cs
  src/Controls/samples/Controls.Sample.UITests/MauiProgram.cs
  src/Controls/samples/Controls.Sample.UITests/Resources/Fonts/Lobster-Regular.ttf
  src/Controls/tests/UITests/Tests/Issues/Issue18673.cs
  src/Controls/tests/UITests/snapshots/android/Issue18673Test.png
  src/Controls/tests/UITests/snapshots/ios/Issue18673Test.png
  src/Controls/tests/UITests/snapshots/windows/Issue18673Test.png
Labels: t/housekeeping ♻︎, area/testing

#18677 [Testing] Added UI Test for manual test D12
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue18675.xaml
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue18675.xaml.cs
  src/Controls/tests/UITests/Tests/Issues/Issue18675.cs
  src/Controls/tests/UITests/snapshots/android/EditorIsReadOnlyPreventModify.png
  src/Controls/tests/UITests/snapshots/ios/EditorIsReadOnlyPreventModify.png
  src/Controls/tests/UITests/snapshots/windows/EditorIsReadOnlyPreventModify.png
Labels: t/housekeeping ♻︎, area/testing

#18763 Update readme with latest blog
  README.md
Labels: area/infrastructure 🏗️

#18718 [ios] fix memory leak in `TableView`
  src/Controls/src/Core/Compatibility/Handlers/TableView/iOS/TableViewModelRenderer.cs
  src/Controls/tests/DeviceTests/Memory/MemoryTests.cs
Labels: platform/iOS 🍎, memory-leak 💦

#18732 Update to stable versions of .NET 8
  eng/Versions.props
  src/Controls/samples/Controls.Sample.Sandbox/Platforms/Tizen/tizen-manifest.xml
  src/Controls/samples/Controls.Sample.UITests/Platforms/Tizen/tizen-manifest.xml
  src/Controls/samples/Controls.Sample/Platforms/Tizen/tizen-manifest.xml
  src/Essentials/samples/Samples/Platforms/Tizen/tizen-manifest.xml
  src/Essentials/src/Geocoding/Geocoding.tizen.cs
  src/Essentials/src/Permissions/Permissions.tizen.cs
  src/Essentials/src/Platform/PlatformUtils.tizen.cs
  src/Graphics/samples/GraphicsTester.Skia.Tizen/tizen-manifest.xml
  src/Templates/src/templates/maui-blazor/Platforms/Tizen/tizen-manifest.xml
  src/Templates/src/templates/maui-mobile/Platforms/Tizen/tizen-manifest.xml
Labels: area/infrastructure 🏗️

#18810 [windows] fix memory leak in `WebView`
  src/Controls/tests/DeviceTests/Memory/MemoryTests.cs
  src/Core/src/Handlers/WebView/WebViewHandler.Windows.cs
Labels: platform/windows 🪟, area/controls 🎮, control-webview, memory-leak 💦

#17648 [C] Lowest specificity for propagated values
  src/Controls/src/Core/BindableObject.cs
  src/Controls/src/Core/BindableObjectExtensions.cs
  src/Controls/src/Core/SetterSpecificityList.cs
  src/Controls/tests/Core.UnitTests/SetterSpecificityListTests.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17597.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17597.xaml.cs
Labels: area/Xaml </>

#18934 [iOS] Make sure always call decisionHandler even if no handler
  src/Core/src/Platform/iOS/MauiWebViewNavigationDelegate.cs
Labels: area/testing, testing-flakiness

#18905 [tests] Ignore flaky android device tests
  src/Controls/tests/DeviceTests/Elements/Modal/ModalTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/TextInput/TextInputFocusTests.Android.cs
Labels: area/testing, testing-flakiness

#18464 Prevent iOS CollectionView size shifts from clearing the cell size cache
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewLayout.cs
  src/Controls/src/Core/Handlers/Items/iOS/SizeExtensions.cs
  src/Controls/src/Core/Handlers/Items/iOS/TemplatedCell.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewCacheTests.ios.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.iOS.cs
Labels: area/collectionview 📃

#18813 [Windows] Address CollectionView virtualization
  src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.Windows.cs
Labels: platform/windows 🪟, area/collectionview 📃, i/regression

#18988 Revert "Prevent iOS CollectionView size shifts from clearing the cell size cache"
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewLayout.cs
  src/Controls/src/Core/Handlers/Items/iOS/SizeExtensions.cs
  src/Controls/src/Core/Handlers/Items/iOS/TemplatedCell.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewCacheTests.ios.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.iOS.cs
Labels: area/testing, testing-flakiness

#17639 ScrollView content needs layout when ScrollView.InvalidateMeasure is called
  src/Controls/tests/DeviceTests/Elements/ScrollView/ScrollViewTests.cs
  src/Core/src/Handlers/ScrollView/ScrollViewHandler.Windows.cs
  src/Core/src/Handlers/ScrollView/ScrollViewHandler.cs
Labels: area/layout 🔲, partner/hot-reload-xaml

#17808 [testing] Run tests on device
  eng/devices/android.cake
  eng/devices/devices-shared.cake
  eng/devices/ios.cake
  eng/scripts/appium-install.ps1
  src/Controls/samples/Controls.Sample.UITests/Controls.Sample.UITests.csproj
  src/Controls/tests/UITests/UITest.cs
Labels: area/testing

#19069 Prevent iOS CollectionView size shifts from clearing the cell size cache
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewLayout.cs
  src/Controls/src/Core/Handlers/Items/iOS/SizeExtensions.cs
  src/Controls/src/Core/Handlers/Items/iOS/TemplatedCell.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewCacheTests.ios.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.iOS.cs
Labels: area/collectionview 📃

#18449 [ios] update MemoryAnalyzers and cleanup
  Directory.Build.targets
  eng/NuGetVersions.targets
  src/Controls/src/Core/ContentPage/HideSoftInputOnTappedChanged/ResignFirstResponderTouchGestureRecognizer.iOS.cs
  src/Core/src/Core.csproj
  src/Core/src/Handlers/SwipeItemMenuItem/SwipeItemMenuItemHandler.iOS.cs
  src/Core/src/Platform/WrapperView.cs
  src/Core/src/Platform/iOS/ContainerViewController.cs
  src/Core/src/Platform/iOS/MauiActivityIndicator.cs
  src/Core/src/Platform/iOS/MauiBoxView.cs
  src/Core/src/Platform/iOS/MauiCALayer.cs
  src/Core/src/Platform/iOS/MauiCheckBox.cs
  src/Core/src/Platform/iOS/MauiImageView.cs
  src/Core/src/Platform/iOS/MauiLabel.cs
  src/Core/src/Platform/iOS/MauiPageControl.cs
  src/Core/src/Platform/iOS/MauiPicker.cs
  src/Core/src/Platform/iOS/MauiRefreshView.cs
  src/Core/src/Platform/iOS/MauiScrollView.cs
  src/Core/src/Platform/iOS/MauiSearchBar.cs
  src/Core/src/Platform/iOS/MauiShapeView.cs
  src/Core/src/Platform/iOS/MauiSwipeView.cs
  src/Core/src/Platform/iOS/MauiTextField.cs
  src/Core/src/Platform/iOS/MauiTextView.cs
  src/Core/src/Platform/iOS/MauiTimePicker.cs
  src/Core/src/Platform/iOS/MauiUIApplicationDelegate.Menu.cs
  src/Core/src/Platform/iOS/MauiUIApplicationDelegate.cs
  src/Core/src/Platform/iOS/MauiUIContextMenuInteraction.cs
  src/Core/src/Platform/iOS/MauiView.cs
  src/Core/src/Platform/iOS/MauiWKWebView.cs
  src/Core/src/Platform/iOS/NoCaretField.cs
  src/Core/src/Platform/iOS/PlatformTouchGraphicsView.cs
  src/Core/src/Platform/iOS/WrapperView.cs
Labels: platform/iOS 🍎, t/housekeeping ♻︎, memory-leak 💦

#18962 [tests] Add runs on iOS17
  eng/pipelines/device-tests.yml
  eng/pipelines/ui-tests.yml
Labels: t/housekeeping ♻︎, area/testing

#19060 [tests] Ignore InputTransparencyGalleryTests matrix of UITests
  src/Controls/tests/UITests/Tests/Concepts/InputTransparencyGalleryTests.cs
Labels: area/testing, testing-flakiness

#18458 Disconnect property changes from all pages when TabbedPage set to null
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue18457.cs
  src/Controls/src/Core/Platform/Android/TabbedPageManager.cs
Labels: area/TabbedPage, community ✨

#19100 [Testing] Added methods to set the device orientation from UITests
  src/TestUtils/src/UITest.Appium/Actions/AppiumOrientationActions.cs
  src/TestUtils/src/UITest.Appium/AppiumApp.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: t/housekeeping ♻︎, area/testing

#19047 [Testing] Fix flaky ShapeUpdatesBrushCorrectly test
  src/Controls/tests/DeviceTests/Elements/Shape/ShapeTests.cs
Labels: area/drawing ✏️, t/housekeeping ♻︎, area/testing

#19076 [tests] Ignore WebView leak test on old iOS
  eng/devices/ios.cake
  src/Controls/tests/DeviceTests/Memory/MemoryTests.cs
  src/Core/src/Platform/iOS/MauiWebViewNavigationDelegate.cs
  src/TestUtils/src/DeviceTests/AssertionExtensions.cs
Labels: area/controls 🎮
