Repository dotnet/maui, pull requests merged in 2023-09, with the labels that each got.

#17150 Drag and Drop move suppression for older android builds
  src/Controls/src/Core/Platform/Android/DragAndDropGestureHandler.cs
Labels: platform/android 🤖, area/gestures

#17143 [tests] Ignore appium visual test #15330 while we investigate
  src/Controls/tests/UITests/Tests/Issues/Issue15330.cs
Labels: area/testing

#17156 PermissionStatus: Remove "ios only" from documentation of Restricted
  src/Essentials/src/Permissions/Permissions.shared.enums.cs
Labels: area/docs 📓, t/housekeeping ♻︎, community ✨

#17094 [net7.0] Update VisualElement docs (#16754)
  src/Controls/src/Core/VisualElement.cs
Labels: area/docs 📓, t/housekeeping ♻︎

#17138 Update BindableObject API docs
  src/Controls/src/Core/BindableObject.cs
Labels: area/docs 📓, t/housekeeping ♻︎

#17170 Update NuGet.config for 7.0.11
  NuGet.config
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#17075 [xaml] locate event handlers from base types
  src/Controls/src/Xaml/ApplyPropertiesVisitor.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui11467/Maui11467.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui11467/Maui11467.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui11467/ParentButton.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui11467/ParentButton.xaml.cs
Labels: area/Xaml </>

#17172 Updated the RoundRectangle BorderTest to check all 4 corners
  src/Controls/tests/DeviceTests/Elements/Border/BorderTests.cs
Labels: area/testing

#16870 Fix CollectionView not displaying header or footers
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue14557.cs
  src/Controls/src/Core/Handlers/Items/ItemsViewHandler.Windows.cs
  src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs
  src/Controls/tests/UITests/Tests/Issues/Issue14557.cs
Labels: area/collectionview 📃

#17226 Compatibility should depend on Controls
  src/Compatibility/Core/src/Compatibility.csproj
Labels: area/infrastructure 🏗️

#17220 Add View docs
  src/Controls/docs/Microsoft.Maui.Controls/View.xml
  src/Controls/src/Core/View/View.cs
Labels: area/docs 📓, t/housekeeping ♻︎, backport/suggested

#17240 (Windows) Fix tabbar visibility test
  src/Controls/src/Core/Handlers/Shell/ShellItemHandler.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTabBarTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTabBarTests.cs
  src/Core/src/Platform/Windows/NavigationViewItemViewModel.cs
Labels: platform/windows 🪟

#17235 [msbuild] fix NuGet Central Package Management (CPM)
  src/Workload/Microsoft.Maui.Sdk/Sdk/BundledVersions.in.targets
  src/Workload/README.md
Labels: area/single project ☝️, area/infrastructure 🏗️

#15748 [iOS] Fix issues setting Shell TabBar appearance
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/SafeShellTabBarAppearanceTracker.cs
  src/Controls/src/Core/Compatibility/Handlers/TabbedPage/iOS/TabbedRenderer.cs
  src/Controls/src/Core/TabbedPage/TabbedPage.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTabBarTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTabBarTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTabBarTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTabBarTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/TabbedPage/TabbedPageTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/TabbedPage/TabbedPageTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/TabbedPage/TabbedPageTests.cs
  src/Controls/tests/DeviceTests/Elements/TabbedPage/TabbedPageTests.iOS.cs
  src/Core/src/Platform/iOS/TabbedViewExtensions.cs
  src/TestUtils/src/DeviceTests/AssertionExtensions.Android.cs
  src/TestUtils/src/DeviceTests/AssertionExtensions.Windows.cs
  src/TestUtils/src/DeviceTests/AssertionExtensions.iOS.cs
Labels: t/bug, platform/iOS 🍎, area/shell 🐢

#17241 [android] improve ToolbarExtensions.UpdateIconColor performance
  src/Controls/src/Core/Platform/Android/Extensions/ToolbarExtensions.cs
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformInterop.java
  src/Core/src/Platform/Android/DrawableExtensions.cs
  src/Core/src/Primitives/FilterMode.cs
  src/Core/src/maui.aar
Labels: platform/android 🤖, area/perf 🏎️

#16981 Update Page API docs
  src/Controls/src/Core/Page/Page.cs
Labels: area/docs 📓, t/housekeeping ♻︎

#17232 Enable Mac Catalyst Core Device Tests in CI
  eng/pipelines/device-tests.yml
  src/Core/tests/DeviceTests/Handlers/SearchBar/SearchBarHandlerTests.cs
  src/Core/tests/DeviceTests/Handlers/Window/WindowHandlerTests.cs
  src/Core/tests/DeviceTests/Handlers/Window/WindowHandlerTests.iOS.cs
  src/TestUtils/src/DeviceTests.Runners/HeadlessRunner/iOS/MauiTestApplicationDelegate.cs
  src/TestUtils/src/DeviceTests/AssertionExtensions.iOS.cs
Labels: platform/macOS 🍏, t/housekeeping ♻︎, area/testing

#17261 [Windows] Fix collection default spacing
  src/Controls/src/Core/Platform/Windows/Extensions/CollectionViewExtensions.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.Windows.cs
Labels: i/regression

#17277 Use strong type for PointerGestureRecognizer Windows PlatformArgs
  src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.Windows.cs
  src/Controls/src/Core/PlatformPointerEventArgs.cs
  src/Controls/src/Core/PointerGestureRecognizer.cs
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
Labels: platform/windows 🪟, area/gestures

#17278 [build] Move to rc2 packages
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#16561 [Android] Fix single taps
  src/Controls/samples/Controls.Sample.UITests/Elements/DoubleTapGallery.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/GestureRecognizerGallery.cs
  src/Controls/samples/Controls.Sample.UITests/Issues/Issues16561.xaml
  src/Controls/samples/Controls.Sample.UITests/Issues/Issues16561.xaml.cs
  src/Controls/src/Core/Platform/Android/InnerGestureListener.cs
  src/Controls/tests/UITests/Tests/GestureRecognizerUITests.cs
  src/Controls/tests/UITests/Tests/Issues/Issue15357.cs
  src/Controls/tests/UITests/Tests/Issues/Issue16561.cs
  src/TestUtils/src/TestUtils.Appium.UITests/AppiumUITestApp.cs
  src/TestUtils/src/TestUtils.Appium.UITests/IApp2.cs
Labels: platform/android 🤖, area/gestures

#17324 [build] Don't use internal feeds on main
  eng/pipelines/common/variables.yml
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#17328 [build] Remove LangVersion
  src/Core/tests/Benchmarks/Core.Benchmarks.csproj
  src/Graphics/samples/GraphicsTester.Android/GraphicsTester.Android.csproj
  src/Graphics/samples/GraphicsTester.Mac/GraphicsTester.Mac.csproj
  src/Graphics/samples/GraphicsTester.MacCatalyst/GraphicsTester.MacCatalyst.csproj
  src/Graphics/samples/GraphicsTester.Skia.Mac/GraphicsTester.Skia.Mac.csproj
  src/Graphics/samples/GraphicsTester.iOS/GraphicsTester.iOS.csproj
  src/Graphics/tests/Graphics.Benchmarks/Graphics.Benchmarks.csproj
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#17327 [build] Remove LangVersion
  src/Core/tests/Benchmarks/Core.Benchmarks.csproj
  src/Graphics/samples/GraphicsTester.Android/GraphicsTester.Android.csproj
  src/Graphics/samples/GraphicsTester.Mac/GraphicsTester.Mac.csproj
  src/Graphics/samples/GraphicsTester.MacCatalyst/GraphicsTester.MacCatalyst.csproj
  src/Graphics/samples/GraphicsTester.Skia.Mac/GraphicsTester.Skia.Mac.csproj
  src/Graphics/samples/GraphicsTester.iOS/GraphicsTester.iOS.csproj
  src/Graphics/tests/Graphics.Benchmarks/Graphics.Benchmarks.csproj
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#17230 [X] do not register srcinfo for xaml-defined values
  src/Controls/src/Core/AppThemeBinding.cs
  src/Controls/src/Core/Binding.cs
  src/Controls/src/Core/MultiBinding.cs
  src/Controls/src/Core/TemplateBinding.cs
  src/Controls/src/Core/VisualStateManager.cs
  src/Controls/src/Xaml/ApplyPropertiesVisitor.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17222.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17222.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17222BaseStyle.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17222BaseStyle.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17222Style.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17222Style.xaml.cs
Labels: area/Xaml </>

#17336 Extract TFM string into a const
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/AndroidTemplateTests.cs
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/AppleTemplateTests.cs
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/BaseBuildTest.cs
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/TemplateTests.cs
Labels: t/housekeeping ♻︎, area/testing

#17282 Enable requesting the full preview size on iOS drag shadow & iOS and Windows Samples
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/Windows/WindowsDragAndDropCustomization.xaml
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/Windows/WindowsDragAndDropCustomization.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/iOS/iOSDragAndDropRequestFullSize.xaml
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/iOS/iOSDragAndDropRequestFullSize.xaml.cs
  src/Controls/samples/Controls.Sample/ViewModels/PlatformSpecificsViewModel.cs
  src/Controls/src/Core/DragAndDrop/PlatformDragStartingEventArgs.cs
  src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.iOS.cs
  src/Controls/src/Core/Platform/iOS/DragAndDropDelegate.cs
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
Labels: platform/macOS 🍏, platform/iOS 🍎, partner/cat 😻, area/gestures

#17331 Added integration test for maui blazor maccatalyst codesign verification.
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/Apple/Codesign.cs
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/TemplateTests.cs
Labels: platform/macOS 🍏, area/testing, Blazor ❤️ MAUI

#17229 Enable Mac Catalyst Controls Device Tests in CI
  eng/pipelines/device-tests.yml
  src/Controls/tests/DeviceTests/DispatchingTests.cs
  src/Controls/tests/DeviceTests/Elements/Accessibility/AccessibilityTests.cs
  src/Controls/tests/DeviceTests/Elements/FlyoutPage/FlyoutPageTests.cs
  src/Controls/tests/DeviceTests/Elements/FlyoutPage/FlyoutPageTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Frame/FrameTests.cs
  src/Controls/tests/DeviceTests/Elements/ScrollView/ScrollViewTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellFlyoutTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/TabbedPage/TabbedPageTests.cs
  src/Controls/tests/DeviceTests/GestureTests.iOS.cs
Labels: platform/macOS 🍏, t/housekeeping ♻︎, area/testing

#17379 Remove macOS as that is not installed by default
  Microsoft.Maui-vscode.sln
Labels: area/infrastructure 🏗️

#17335 [ci] Add MSI transport nugets to sign verify
  eng/pipelines/common/sign.yml
Labels: area/infrastructure 🏗️

#17456 Revert "Merge main into net8.0"
  Microsoft.Maui-dev.sln
  Microsoft.Maui-vscode.sln
  eng/pipelines/common/ui-tests.yml
  eng/pipelines/device-tests.yml
  src/Controls/samples/Controls.Sample.UITests/Elements/DoubleTapGallery.cs
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue16787.cs
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue17347.cs
  src/Controls/samples/Controls.Sample.UITests/Issues/Issues16561.xaml
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/Windows/WindowsDragAndDropCustomization.xaml
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/Windows/WindowsDragAndDropCustomization.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/iOS/iOSDragAndDropRequestFullSize.xaml
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/iOS/iOSDragAndDropRequestFullSize.xaml.cs
  src/Controls/samples/Controls.Sample/ViewModels/PlatformSpecificsViewModel.cs
  src/Controls/src/Core/AppThemeBinding.cs
  src/Controls/src/Core/BindableObject.cs
  src/Controls/src/Core/BindableObjectExtensions.cs
  src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs
  src/Controls/src/Core/DragAndDrop/PlatformDragStartingEventArgs.cs
  src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.iOS.cs
  src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs
  src/Controls/src/Core/Platform/iOS/DragAndDropDelegate.cs
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/Setter.cs
  src/Controls/src/Xaml/XamlNode.cs
  src/Controls/tests/DeviceTests/DispatchingTests.cs
  src/Controls/tests/DeviceTests/Elements/Accessibility/AccessibilityTests.cs
  src/Controls/tests/DeviceTests/Elements/FlyoutPage/FlyoutPageTests.cs
  src/Controls/tests/DeviceTests/Elements/FlyoutPage/FlyoutPageTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Frame/FrameTests.cs
  src/Controls/tests/DeviceTests/Elements/ScrollView/ScrollViewTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellFlyoutTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/TabbedPage/TabbedPageTests.cs
  src/Controls/tests/DeviceTests/GestureTests.iOS.cs
  src/Controls/tests/UITests/Tests/Issues/Issue16561.cs
  src/Controls/tests/UITests/Tests/Issues/Issue16787.cs
  src/Controls/tests/UITests/Tests/Issues/Issue17347.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui16538.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui16538.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui16960.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui16960.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17222.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17333.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17333.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17354.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17354.xaml.cs
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/Apple/Codesign.cs
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/TemplateTests.cs
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#17407 [ci] Bump stable versions on main
  eng/Versions.props
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#17468 Update README.md
  README.md
Labels: t/housekeeping ♻︎

#17462 [net8.0] Merge main to net8.0
  Microsoft.Maui-dev.sln
  Microsoft.Maui-vscode.sln
  eng/pipelines/common/sign.yml
  eng/pipelines/common/ui-tests.yml
  eng/pipelines/device-tests.yml
  src/Controls/samples/Controls.Sample.UITests/Elements/DoubleTapGallery.cs
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue16787.cs
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue17347.cs
  src/Controls/samples/Controls.Sample.UITests/Issues/Issues16561.xaml
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/Windows/WindowsDragAndDropCustomization.xaml
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/Windows/WindowsDragAndDropCustomization.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/iOS/iOSDragAndDropRequestFullSize.xaml
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/iOS/iOSDragAndDropRequestFullSize.xaml.cs
  src/Controls/samples/Controls.Sample/ViewModels/PlatformSpecificsViewModel.cs
  src/Controls/src/Core/AppThemeBinding.cs
  src/Controls/src/Core/BindableObject.cs
  src/Controls/src/Core/BindableObjectExtensions.cs
  src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs
  src/Controls/src/Core/DragAndDrop/PlatformDragStartingEventArgs.cs
  src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.iOS.cs
  src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs
  src/Controls/src/Core/Platform/iOS/DragAndDropDelegate.cs
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/Setter.cs
  src/Controls/src/Xaml/XamlNode.cs
  src/Controls/tests/DeviceTests/DispatchingTests.cs
  src/Controls/tests/DeviceTests/Elements/Accessibility/AccessibilityTests.cs
  src/Controls/tests/DeviceTests/Elements/FlyoutPage/FlyoutPageTests.cs
  src/Controls/tests/DeviceTests/Elements/FlyoutPage/FlyoutPageTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Frame/FrameTests.cs
  src/Controls/tests/DeviceTests/Elements/ScrollView/ScrollViewTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellFlyoutTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/TabbedPage/TabbedPageTests.cs
  src/Controls/tests/DeviceTests/GestureTests.iOS.cs
  src/Controls/tests/UITests/Tests/Issues/Issue16561.cs
  src/Controls/tests/UITests/Tests/Issues/Issue16787.cs
  src/Controls/tests/UITests/Tests/Issues/Issue17347.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui16538.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui16538.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui16960.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui16960.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17222.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17333.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17333.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17354.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17354.xaml.cs
  src/Core/src/.editorconfig
  src/Core/src/Layouts/Flex.cs
  src/Core/src/Platform/Android/PlatformTouchGraphicsView.cs
  src/Core/src/Platform/Tizen/PlatformTouchGraphicsView.cs
  src/Core/src/Platform/Windows/PlatformTouchGraphicsView.cs
  src/Core/src/Platform/iOS/PlatformTouchGraphicsView.cs
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/Apple/Codesign.cs
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/TemplateTests.cs
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#17459 [net7.0] [tests] Fix image for device tests on Android
  eng/devices/android.cake
  eng/pipelines/common/device-tests-steps.yml
  eng/pipelines/common/device-tests.yml
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#17489 [net8.0] Merge main net8.0
  README.md
  eng/devices/ios.cake
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/Utilities/XHarness.cs
Labels: area/infrastructure 🏗️

#17495 Clean up iOS DragAndDropDelegate
  src/Controls/src/Core/Platform/iOS/DragAndDropDelegate.cs
  src/Controls/tests/UITests/Tests/DragAndDropUITests.cs
Labels: t/housekeeping ♻︎, area/gestures

#17041 Fixed window not reacting to TitleBar wnd message
  src/Controls/tests/DeviceTests/Elements/Window/WindowTests.Windows.cs
  src/Core/src/Platform/Windows/ApplicationExtensions.cs
  src/Core/src/Platform/Windows/MauiWinUIWindow.cs
  src/Core/src/Platform/Windows/NavigationRootManager.cs
  src/Core/src/Platform/Windows/WindowRootView.cs
  src/Essentials/src/Platform/PlatformMethods.uwp.cs
Labels: platform/windows 🪟, area/desktop 🖥️, i/regression, stale

#17093 [net7.0] [iOS] Fix ScrollTo method issues
  src/Controls/samples/Controls.Sample/Pages/Layouts/ScrollViewPages/ScrollToFromConstructorPage.xaml
  src/Controls/samples/Controls.Sample/Pages/Layouts/ScrollViewPages/ScrollToFromConstructorPage.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/Layouts/ScrollViewPages/ScrollViewOrientationPage.xaml
  src/Controls/samples/Controls.Sample/Pages/Layouts/ScrollViewPages/ScrollViewOrientationPage.xaml.cs
  src/Controls/samples/Controls.Sample/ViewModels/ScrollViewOptionsModel.cs
  src/Controls/src/Core/ScrollView.cs
  src/Controls/tests/DeviceTests/Elements/ScrollView/ScrollViewTests.cs
  src/Core/src/Handlers/ScrollView/ScrollViewHandler.iOS.cs
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/TestUtils/src/DeviceTests/AssertionExtensions.cs
Labels: area/layout 🔲, s/pr-needs-author-input

#17498 [net7.0] Update cake files and XCode
  eng/cake/dotnet.cake
  eng/cake/helpers.cake
  eng/devices/android.cake
  eng/devices/ios.cake
  eng/pipelines/common/variables.yml
Labels: area/infrastructure 🏗️

#17487 [net7.0] Update all ASP.NET and MS.Extensions packages to latest stable
  eng/Microsoft.Extensions.targets
  eng/Versions.props
  src/Controls/samples/Controls.Sample.UITests/Controls.Sample.UITests.csproj
  src/Templates/src/Microsoft.Maui.Templates.csproj
  src/Workload/Microsoft.Maui.Sdk/Microsoft.Maui.Sdk.csproj
  src/Workload/Microsoft.Maui.Sdk/Sdk/BundledVersions.in.targets
Labels: area/infrastructure 🏗️

#17358 Changing value of Shell.NavBarIsVisible should change visibility of toolbar (ShellToolbar)
  src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs
  src/Controls/src/Core/Shell/Shell.cs
  src/Controls/src/Core/ShellToolbar.cs
  src/Controls/tests/Core.UnitTests/ShellToolbarTests.cs
Labels: area/shell 🐢, partner/hot-reload-xaml

#17519 [net7.0] [iOS/Catalyst] Fix issue loading images from Stream (#16162)
  src/Controls/samples/Controls.Sample/Pages/Controls/ImagePage.xaml
  src/Controls/samples/Controls.Sample/Pages/Controls/ImagePage.xaml.cs
  src/Controls/tests/DeviceTests/Elements/Image/ImageTests.iOS.cs
  src/Core/src/Handlers/Image/ImageHandler.iOS.cs
Labels: area/image :framed_picture:

#17522 [net7.0] Remove ScrollView Leak Test
  src/Controls/tests/DeviceTests/Elements/ScrollView/ScrollViewTests.cs
Labels: area/perf 🏎️

#17532 [release/7.0.3xx-sr8] Update Version
  GitInfo.txt
Labels: area/infrastructure 🏗️

#17418 Cleanup SwipeView and Propagate BC until we can fix compat layout
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/SwipeView/SwipeItems.cs
  src/Controls/src/Core/SwipeView/SwipeView.cs
  src/Controls/src/Core/ViewExtensions.cs
  src/Controls/tests/Core.UnitTests/SwipeViewTests.cs
Labels: area/Xaml </>, control-swipeview

#17542 [net7.0] Update BindableObject API docs
  src/Controls/src/Core/BindableObject.cs
Labels: area/docs 📓, t/housekeeping ♻︎

#17529 [net7.0] Rollback xharness bump to 8.0.0-prerelease.23407.2
  .config/dotnet-tools.json
  eng/Version.Details.xml
  eng/Versions.props
Labels: area/infrastructure 🏗️

#17518 Improve comments in customer facing project templates
  src/Templates/src/templates/maui-blazor/MauiApp.1.csproj
  src/Templates/src/templates/maui-mobile/MauiApp.1.csproj
Labels: t/housekeeping ♻︎, area/templates 📄

#17557 [net8.0] Merge main to net8.0
  .config/dotnet-tools.json
  eng/Version.Details.xml
  eng/Versions.props
  src/Controls/samples/Controls.Sample.UITests/CoreViews/CoreGalleryBasePage.cs
  src/Controls/samples/Controls.Sample.UITests/CoreViews/CoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/CoreViews/CorePageView.cs
  src/Controls/samples/Controls.Sample.UITests/CoreViews/ViewContainers/ExpectedEventViewContainer.cs
  src/Controls/samples/Controls.Sample.UITests/CoreViews/ViewContainers/IViewContainer.cs
  src/Controls/samples/Controls.Sample.UITests/CoreViews/ViewContainers/ViewContainer.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/ButtonCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/CheckBoxCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/EditorCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/LabelCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/RadioButtonCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Utils/Utils.cs
  src/Controls/src/Build.Tasks/SetPropertiesVisitor.cs
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs
  src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs
  src/Controls/src/Core/Platform/iOS/DragAndDropDelegate.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/Shell/Shell.cs
  src/Controls/src/Core/ShellToolbar.cs
  src/Controls/src/Core/SwipeView/SwipeItems.cs
  src/Controls/src/Core/SwipeView/SwipeView.cs
  src/Controls/src/Core/ViewExtensions.cs
  src/Controls/tests/Core.UnitTests/ShellToolbarTests.cs
  src/Controls/tests/Core.UnitTests/SwipeViewTests.cs
  src/Controls/tests/DeviceTests/Elements/Window/WindowTests.Windows.cs
  src/Controls/tests/DeviceTests/Stubs/MauiAppNewWindowStub.Windows.cs
  src/Controls/tests/UITests/Tests/ButtonUITests.cs
  src/Controls/tests/UITests/Tests/CheckBoxUITests.cs
  src/Controls/tests/UITests/Tests/CoreGalleryBasePageTest.cs
  src/Controls/tests/UITests/Tests/DragAndDropUITests.cs
  src/Controls/tests/UITests/Tests/EditorUITests.cs
  src/Controls/tests/UITests/Tests/LabelUITests.cs
  src/Controls/tests/UITests/Tests/RadioButtonUITests.cs
  src/Controls/tests/UITests/Tests/_ViewUITests.cs
  src/Controls/tests/UITests/ViewContainers/BaseViewContainerRemote.cs
  src/Controls/tests/UITests/ViewContainers/EventViewContainerRemote.cs
  src/Controls/tests/UITests/ViewContainers/StateViewContainerRemote.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17484.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17484.xaml.cs
  src/Core/src/Platform/Windows/ApplicationExtensions.cs
  src/Core/src/Platform/Windows/MauiWinUIWindow.cs
  src/Core/src/Platform/Windows/NavigationRootManager.cs
  src/Core/src/Platform/Windows/WindowRootView.cs
  src/Essentials/src/Platform/PlatformMethods.uwp.cs
Labels: area/infrastructure 🏗️

#17524 Enable performance CAs for more Core classes
  src/Core/src/.editorconfig
  src/Core/src/Platform/Android/MauiScrollView.cs
  src/Core/src/Platform/Android/MauiSwipeView.cs
  src/Core/src/Platform/Android/MauiWebViewClient.cs
  src/Core/src/Platform/Tizen/MauiSwipeView.cs
  src/Core/src/Platform/iOS/MauiSwipeView.cs
Labels: area/perf 🏎️

#17579 Add the missing package to the Blazor template
  src/Templates/src/templates/maui-blazor/MauiApp.1.csproj
Labels: area/templates 📄

#17527 [controls] improve "setter specificity" performance
  src/Controls/src/Core/BindableObject.cs
  src/Controls/src/Core/SetterSpecificity.cs
  src/Controls/src/Core/SetterSpecificityList.cs
  src/Controls/src/Core/VisualStateManager.cs
  src/Controls/tests/Core.UnitTests/SetterSpecificityListTests.cs
Labels: area/perf 🏎️

#17570 [net8.0] Bump net7 stable
  eng/Versions.props
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#17558 Update SkiaSharp to the latest stable version (2.88.6)
  eng/Microsoft.Extensions.targets
  eng/Versions.props
  src/Graphics/samples/GraphicsTester.Skia.Console/GraphicsTester.Skia.Console.csproj
  src/Graphics/samples/GraphicsTester.Skia.Gtk/GraphicsTester.Skia.Gtk.csproj
  src/Graphics/samples/GraphicsTester.Skia.Mac/GraphicsTester.Skia.Mac.csproj
  src/Graphics/samples/GraphicsTester.Skia.Windows/GraphicsTester.Skia.Windows.csproj
  src/Graphics/src/Graphics.Skia.GtkSharp/Graphics.Skia.GtkSharp.csproj
  src/Graphics/src/Graphics.Skia.WPF/Graphics.Skia.WPF.csproj
  src/SingleProject/Resizetizer/src/ResizetizerPackages.projitems
  src/SingleProject/Resizetizer/src/SkiaSharpTools.cs
  src/SingleProject/Resizetizer/test/UnitTests/Resizetizer.UnitTests.csproj
Labels: area/infrastructure 🏗️

#17545 [X] Double cast for OnPlat in StaticResource
  src/Controls/src/Xaml/MarkupExtensions/StaticResourceExtension.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui16327.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui16327.xaml.cs
Labels: area/Xaml </>

#17613 Reenable WinUI Device Tests parallel running
  src/Core/tests/DeviceTests.Shared/HandlerTests/TestBase.cs
Labels: platform/windows 🪟, t/housekeeping ♻︎, area/testing

#16803 Remove reference to concrete native host app
  src/Compatibility/ControlGallery/src/Android/Issue10182Activity.cs
  src/Compatibility/Core/src/AppHostBuilderExtensions.Android.cs
  src/Compatibility/Core/src/AppHostBuilderExtensions.Tizen.cs
  src/Compatibility/Core/src/AppHostBuilderExtensions.Windows.cs
  src/Compatibility/Core/src/AppHostBuilderExtensions.cs
  src/Compatibility/Core/src/AppHostBuilderExtensions.iOS.cs
  src/Controls/src/Xaml/Hosting/AppHostBuilderExtensions.cs
  src/Core/src/Hosting/EssentialsMauiAppBuilderExtensions.cs
  src/Core/src/Platform/Android/MauiAppCompatActivity.Lifecycle.cs
  src/Core/src/Platform/Android/MauiAppCompatActivity.cs
  src/Core/src/Platform/Android/MauiApplication.cs
  src/Core/src/Platform/Android/MauiContextExtensions.cs
  src/Core/src/Platform/Tizen/CoreAppExtensions.cs
  src/Core/src/Platform/Tizen/MauiApplication.cs
  src/Core/src/Platform/Windows/MauiContextExtensions.cs
  src/Core/src/Platform/Windows/MauiWinUIApplication.cs
  src/Core/src/Platform/Windows/MauiWinUIWindow.cs
  src/Core/src/Platform/iOS/MauiContextExtensions.cs
  src/Core/src/Platform/iOS/MauiUIApplicationDelegate.cs
  src/Core/src/Platform/iOS/MauiUISceneDelegate.cs
  src/Core/src/Platform/iOS/UIApplicationExtensions.cs
  src/TestUtils/src/DeviceTests.Runners/HeadlessRunner/Android/MauiTestInstrumentation.cs
  src/TestUtils/src/DeviceTests.Runners/TestServices.cs
Labels: area/hosting 🧩, community ✨, stale

#17305 Fix typo in build.sh
  build.sh
Labels: area/infrastructure 🏗️, community ✨, stale

#17555 Fixed Android's Border background to use a Transparent bg if not othe…
  src/Controls/tests/DeviceTests/Elements/Border/BorderTests.cs
  src/Core/src/Graphics/MauiDrawable.Android.cs
Labels: area/controls 🎮

#17359 Update Flyout when Shell.FlyoutContent changes
  src/Controls/src/Core/Handlers/Shell/ShellHandler.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellFlyoutTests.cs
Labels: area/shell 🐢, partner/hot-reload-xaml

#17301 [XamlC] fix generic array
  src/Controls/src/Build.Tasks/TypeReferenceExtensions.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui10583.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui10583.xaml.cs
  src/Controls/tests/Xaml.UnitTests/MockCompiler.cs
  src/Controls/tests/Xaml.UnitTests/NameScopeTests.cs
  src/Controls/tests/Xaml.UnitTests/XamlC/TypeReferenceExtensionsTests.cs
Labels: area/Xaml </>

#17663 [net7.0] Update SkiaSharp to 2.88.6
  eng/Microsoft.Extensions.targets
  eng/Versions.props
  src/Graphics/samples/GraphicsTester.Skia.Console/GraphicsTester.Skia.Console.csproj
  src/Graphics/samples/GraphicsTester.Skia.Gtk/GraphicsTester.Skia.Gtk.csproj
  src/Graphics/samples/GraphicsTester.Skia.Mac/GraphicsTester.Skia.Mac.csproj
  src/Graphics/samples/GraphicsTester.Skia.Windows/GraphicsTester.Skia.Windows.csproj
  src/Graphics/src/Graphics.Skia.GtkSharp/Graphics.Skia.GtkSharp.csproj
  src/Graphics/src/Graphics.Skia.WPF/Graphics.Skia.WPF.csproj
  src/SingleProject/Resizetizer/src/ResizetizerPackages.projitems
  src/SingleProject/Resizetizer/src/SkiaSharpTools.cs
  src/SingleProject/Resizetizer/test/UnitTests/Resizetizer.UnitTests.csproj
Labels: area/infrastructure 🏗️

#17528 Fix accent color missing in title bar
  src/Core/src/Platform/Windows/MauiWinUIWindow.cs
  src/Core/src/Platform/Windows/Styles/WindowRootViewStyle.xaml
  src/Core/src/Platform/Windows/WindowRootView.cs
Labels: platform/windows 🪟, area/desktop 🖥️, control-window

#17675 Log test start/stop times
  src/Controls/tests/UITests/Tests/CoreGalleryBasePageTest.cs
  src/Controls/tests/UITests/Tests/Issues/_IssuesUITest.cs
  src/Controls/tests/UITests/Tests/UITestBase.cs
  src/TestUtils/src/TestUtils.Appium.UITests/AppiumContext.cs
Labels: area/testing

#17701 Add console logger and fix filename collisions
  eng/cake/dotnet.cake
  eng/devices/android.cake
  eng/devices/catalyst.cake
  eng/devices/ios.cake
  eng/devices/windows.cake
Labels: area/testing

#17691 Override CA1822 for Android interface implementation in MauiScrollView
  src/Core/src/Platform/Android/MauiScrollView.cs
Labels: platform/android 🤖, t/housekeeping ♻︎, area/infrastructure 🏗️

#17167 Add ViewHandler & IViewHandler docs
  src/Core/src/Handlers/IViewHandler.cs
  src/Core/src/Handlers/View/ViewHandler.cs
Labels: area/docs 📓, t/housekeeping ♻︎, s/pr-needs-author-input

#17728 Add other controls to the UI tests
  src/Controls/samples/Controls.Sample.UITests/Controls.Sample.UITests.csproj
  src/Controls/samples/Controls.Sample.UITests/CoreViews/CoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/CoreViews/CorePageView.cs
  src/Controls/samples/Controls.Sample.UITests/CoreViews/ViewContainers/LayeredViewContainer.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/ActivityIndicatorCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/BoxViewCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/CollectionViewCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/DatePickerCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/EntryCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/FrameCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/ImageButtonCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/ImageCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/ListViewCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/PickerCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/ProgressBarCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/SearchBarCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/SliderCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/StepperCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/SwitchCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/TimePickerCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/WebViewCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Test.cs
  src/Controls/tests/UITests/Tests/RadioButtonUITests.cs
  src/Controls/tests/UITests/ViewContainers/BaseViewContainerRemote.cs
  src/Controls/tests/UITests/ViewContainers/LayeredViewContainerRemote.cs
Labels: area/testing
