Repository dotnet/maui, pull requests merged in 2023-06, with the labels that each got.

#15356 Run security compliance only on private build
  eng/pipelines/handlers.yml
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#15368 [net8.0] Bump tizen to preview5
  eng/Versions.props
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#15219 Legacy gallery filtered solutions
  Microsoft.Maui-dev.sln
  Microsoft.Maui.LegacyControlGallery.slnf
  src/Compatibility/ControlGallery/src/Issues.Shared/AddingMultipleItemsListView.cs
  src/Compatibility/ControlGallery/src/Issues.Shared/BottomTabbedPageTests.cs
  src/Compatibility/ControlGallery/src/Issues.Shared/Bugzilla21177.cs
  src/Compatibility/ControlGallery/src/Issues.Shared/Bugzilla25662.cs
  src/Compatibility/ControlGallery/src/Issues.Shared/Bugzilla25943.cs
  src/Compatibility/ControlGallery/src/Issues.Shared/Bugzilla26032.xaml.cs
  src/Compatibility/ControlGallery/src/Issues.Shared/Issue1023.cs
  src/Compatibility/ControlGallery/src/Issues.Shared/Issue1024.cs
  src/Compatibility/ControlGallery/src/UITests.Shared/Tests/ActivityIndicatorUITests.cs
  src/Compatibility/ControlGallery/src/UITests.Shared/Tests/CollectionViewUITests.cs
  src/Compatibility/ControlGallery/src/UITests.Shared/Tests/FrameUITests.cs
  src/Compatibility/ControlGallery/src/UITests.Shared/UITestCategories.cs
  src/Maui.InTree.targets
Labels: area/infrastructure 🏗️

#15400 Update Win2D
  eng/Versions.props
Labels: backport/suggested, backport/approved

#15405 [net7.0] Reinstate WebView Cookies functionality net7
  src/Controls/samples/Controls.Sample/Pages/Controls/WebViewPage.xaml
  src/Controls/samples/Controls.Sample/Pages/Controls/WebViewPage.xaml.cs
  src/Core/src/Handlers/WebView/WebViewHandler.Android.cs
  src/Core/src/Handlers/WebView/WebViewHandler.Windows.cs
  src/Core/src/Handlers/WebView/WebViewHandler.iOS.cs
  src/Core/src/Platform/Android/MauiWebViewClient.cs
  src/Core/src/Platform/Windows/MauiWebView.cs
  src/Core/src/Platform/iOS/MauiWKWebView.cs
Labels: area/controls 🎮, control-webview

#15438 Modify ID Generator Starting Point of DataTemplate Class to Prevent ItemViewType Collision
  src/Controls/src/Core/DataTemplate.cs
Labels: area/collectionview 📃, community ✨

#15452 Pin main branch to net7
  global.json
Labels: area/infrastructure 🏗️

#15424 [net7.0] Make sure that we have valid values for setting the ContentSize of the ScrollView on iOS
  src/Core/src/Handlers/ScrollView/ScrollViewHandler.iOS.cs
Labels: area/layout 🔲

#15426 First pass at adding developer layout docs
  docs/design/layout.md
Labels: area/layout 🔲

#15495 Clear window from ContextStub after it's closed
  src/Core/tests/DeviceTests.Shared/Stubs/ContextStub.cs
Labels: t/housekeeping ♻︎

#15484 Add the drag and drop gestures back to the appium ui tests for mac/ios targets
  eng/devices/android.cake
  eng/devices/catalyst.cake
  eng/devices/ios.cake
  eng/devices/windows.cake
  src/Controls/samples/Controls.Sample.UITests/Elements/DragAndDropBetweenLayouts.xaml.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/DragAndDropEvents.xaml.cs
  src/Controls/tests/UITests/Tests/DragAndDropUITests.cs
  src/TestUtils/src/TestUtils.Appium.UITests/AppiumUITestApp.cs
Labels: area/testing

#15527 Skip tests currently having issues on WinUI
  src/Controls/tests/DeviceTests/ControlsHandlerTestBase.cs
  src/Controls/tests/DeviceTests/Elements/CheckBox/CheckBoxTests.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs
  src/Controls/tests/DeviceTests/Elements/Frame/FrameHandlerTest.Windows.cs
  src/Controls/tests/DeviceTests/Elements/ListView/ListViewTests.cs
  src/Controls/tests/DeviceTests/Elements/NavigationPage/NavigationPageTests.cs
  src/Controls/tests/DeviceTests/Elements/Picker/PickerTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/RadioButton/RadioButtonTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellFlyoutTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.cs
Labels: area/infrastructure 🏗️

#15532 Fix incorrect calculation of expansion size when *s have different scalars
  src/Core/src/Layouts/GridLayoutManager.cs
  src/Core/tests/UnitTests/Layouts/GridLayoutManagerTests.cs
Labels: area/layout 🔲

#15560 [iOS] Set AutoKeyboardManagerScroll's Tokens to null when disconnecting
  src/Core/src/Platform/iOS/KeyboardAutoManagerScroll.cs
Labels: platform/iOS 🍎, area/controls 🎮, control-entry, keyboard

#15561 Add all platforms if build args don't restrict to a single platform
  src/Controls/tests/UITests/Tests/UITestBase.cs
Labels: area/testing

#15541 Restore & obsolete Windows MauiWebView ctor
  src/Core/src/Platform/Windows/MauiWebView.cs
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
Labels: platform/windows 🪟, t/housekeeping ♻︎, area/controls 🎮, control-webview

#15551 Add Forms->MAUI differences notes to layout dev docs
  docs/design/layout.md
Labels: area/docs 📓, area/layout 🔲

#15615 Add 8.0.0-preview.5.8529 to bug report issue template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: t/housekeeping ♻︎, community ✨

#15062 [ios] fix memory leak in Image
  src/Controls/tests/DeviceTests/Elements/Image/ImageTests.cs
  src/Core/src/Handlers/Button/ButtonHandler.Android.cs
  src/Core/src/Handlers/Button/ButtonHandler.Standard.cs
  src/Core/src/Handlers/Button/ButtonHandler.Tizen.cs
  src/Core/src/Handlers/Button/ButtonHandler.Windows.cs
  src/Core/src/Handlers/Button/ButtonHandler.cs
  src/Core/src/Handlers/Button/ButtonHandler.iOS.cs
  src/Core/src/Handlers/Image/IImageHandler.cs
  src/Core/src/Handlers/Image/IImageSourcePartSetter.cs
  src/Core/src/Handlers/Image/ImageHandler.Android.cs
  src/Core/src/Handlers/Image/ImageHandler.Standard.cs
  src/Core/src/Handlers/Image/ImageHandler.Tizen.cs
  src/Core/src/Handlers/Image/ImageHandler.Windows.cs
  src/Core/src/Handlers/Image/ImageHandler.cs
  src/Core/src/Handlers/Image/ImageHandler.iOS.cs
  src/Core/src/Handlers/ImageButton/ImageButtonHandler.Android.cs
  src/Core/src/Handlers/ImageButton/ImageButtonHandler.Standard.cs
  src/Core/src/Handlers/ImageButton/ImageButtonHandler.Tizen.cs
  src/Core/src/Handlers/ImageButton/ImageButtonHandler.Windows.cs
  src/Core/src/Handlers/ImageButton/ImageButtonHandler.cs
  src/Core/src/Handlers/ImageButton/ImageButtonHandler.iOS.cs
  src/Core/src/Handlers/SwipeItemMenuItem/SwipeItemMenuItemHandler.Android.cs
  src/Core/src/Handlers/SwipeItemMenuItem/SwipeItemMenuItemHandler.Standard.cs
  src/Core/src/Handlers/SwipeItemMenuItem/SwipeItemMenuItemHandler.Tizen.cs
  src/Core/src/Handlers/SwipeItemMenuItem/SwipeItemMenuItemHandler.cs
  src/Core/src/Handlers/SwipeItemMenuItem/SwipeItemMenuItemHandler.iOS.cs
  src/Core/src/Platform/ImageSourcePartLoader.cs
  src/Core/src/Platform/iOS/MauiImageView.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Shipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Shipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
Labels: platform/iOS 🍎, area/perf 🏎️

#15612 [Android] Fix toolbar OverflowIcon color not getting properly set.
  src/Controls/src/Core/Platform/Android/Extensions/ToolbarExtensions.cs
Labels: platform/android 🤖, area/controls 🎮, community ✨

#15651 [net7.0] [macOS] Display alert by Window
  src/Controls/src/Core/Platform/AlertManager/AlertManager.Windows.cs
  src/Controls/src/Core/Platform/AlertManager/AlertManager.iOS.cs
Labels: t/housekeeping ♻︎

#15653 [net7.0] Handle Grid * expansion when size is larger than minimum, but less than sufficient to display full size
  src/Core/src/Layouts/GridLayoutManager.cs
  src/Core/src/Platform/iOS/ContentView.cs
  src/Core/src/Platform/iOS/LayoutView.cs
  src/Core/tests/UnitTests/Layouts/GridLayoutManagerTests.cs
  src/Core/tests/UnitTests/Layouts/LayoutTestHelpers.cs
Labels: t/housekeeping ♻︎

#15587 Fix sizing issues with CollectionView on Windows
  src/Controls/src/Core/Handlers/Items/ItemsViewHandler.Windows.cs
  src/Controls/src/Core/Platform/Windows/CollectionView/ItemsViewStyles.xaml
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.cs
Labels: platform/windows 🪟, t/housekeeping ♻︎

#15624 [iOS] Allow to remove the Image from Button
  src/Controls/samples/Controls.Sample/Pages/Controls/ButtonPage.xaml
  src/Controls/samples/Controls.Sample/Pages/Controls/ButtonPage.xaml.cs
  src/Core/src/Handlers/Button/ButtonHandler.iOS.cs
Labels: t/bug, platform/iOS 🍎, area/controls 🎮, control-button

#15008 Update CODEOWNERS
  .github/CODEOWNERS
Labels: area/infrastructure 🏗️, community ✨, partner/tizen

#15555 Hook up ScrollViewer event tracking in Windows CollectionView
  src/Controls/src/Core/Handlers/Items/ItemsViewHandler.Windows.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.Windows.cs
Labels: area/collectionview 📃

#15690 [Windows] Fix issues setting Shell TabBar appearance
  src/Controls/samples/Controls.Sample.Sandbox/SandboxShell.xaml
  src/Controls/samples/Controls.Sample/Pages/Core/ShellGalleries/ShellChromeGallery.cs
  src/Controls/samples/Controls.Sample/Pages/Core/ShellGalleries/ShellChromeGallery.xaml
  src/Controls/src/Core/HandlerImpl/TabbedPage/TabbedPage.Windows.cs
  src/Controls/src/Core/Handlers/Shell/ShellItemHandler.Windows.cs
  src/Controls/src/Core/Handlers/Shell/ShellSectionHandler.Windows.cs
  src/Controls/src/Core/Platform/Windows/TabbedPage/TabbedPageStyle.xaml
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTabBarTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTabBarTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.Windows.cs
  src/Core/src/Platform/Windows/NavigationViewExtensions.cs
  src/Core/src/Platform/Windows/NavigationViewItemViewModel.cs
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
Labels: platform/windows 🪟, area/shell 🐢

#15724 [Tizen] Bump tizen preview6
  eng/Versions.props
Labels: area/infrastructure 🏗️, platform/tizen

#15588 Just run the pack every time
  eng/cake/dotnet.cake
Labels: area/infrastructure 🏗️

#14921 feat: adding IWindowCreator
  src/Controls/src/Core/Application/Application.cs
  src/Controls/src/Core/IWindowCreator.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/tests/Core.UnitTests/ApplicationTests.cs
Labels: community ✨

#15759 [android] support more system font names
  src/Core/src/Fonts/FontManager.Android.cs
Labels: platform/android 🤖, area/perf 🏎️

#15746 Android x nuget bumps
  eng/AndroidX.targets
  eng/Versions.props
  src/Controls/src/Core/NavigationPage/NavigationPage.cs
  src/Controls/tests/DeviceTests/Elements/NavigationPage/NavigationPageTests.cs
  src/Core/src/Platform/Android/Navigation/StackNavigationManager.cs
  src/Core/src/Platform/Android/NavigationViewExtensions.cs
  src/Core/tests/DeviceTests/Handlers/Navigation/NavigationViewHandlerTests.Android.cs
Labels: area/platform

#15776 [release/7.0.2xx] Bump GitInfo
  GitInfo.txt
Labels: area/infrastructure 🏗️

#15790 Run daily code formatting on .NET SDK 7.0.304
  .github/workflows/dotnet-format-daily.yml
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#15601 [Windows] Implement ItemsUpdatingScrollMode on CollectionView
  src/Controls/samples/Controls.Sample/Pages/Controls/CollectionViewGalleries/ScrollModeGalleries/EnumPicker.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/CollectionViewGalleries/ScrollModeGalleries/ItemsUpdatingScrollModeGallery.xaml
  src/Controls/samples/Controls.Sample/Pages/Controls/CollectionViewGalleries/ScrollModeGalleries/ItemsUpdatingScrollModeGallery.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/CollectionViewGalleries/ScrollModeGalleries/ScrollModeGallery.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/CollectionViewGalleries/ScrollModeGalleries/ScrollModeTestGallery.xaml.cs
  src/Controls/src/Core/Handlers/Items/ItemsViewHandler.Windows.cs
Labels: t/bug, platform/windows 🪟, area/collectionview 📃

#15365 [CI] Remove template explosion on the maui templates build tests.
  eng/pipelines/common/maui-templates.yml
Labels: area/infrastructure 🏗️

#15731 [net8.0] Use darc for packs from runtime
  eng/Version.Details.xml
  eng/Versions.props
Labels: area/infrastructure 🏗️, community ✨

#15303 Formalize virtual layout concepts and fix iOS memory leaks
  src/Controls/src/Core/Compatibility/Handlers/Windows/FrameRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs
  src/Controls/src/Core/ContentPage/ContentPage.cs
  src/Controls/src/Core/ContentPresenter.cs
  src/Controls/src/Core/Frame/Frame.cs
  src/Controls/src/Core/RadioButton/RadioButton.Android.cs
  src/Controls/src/Core/ScrollView/ScrollView.cs
  src/Controls/src/Core/TemplatedView/TemplatedView.cs
  src/Controls/tests/DeviceTests/Elements/ContentView/ContentViewTests.cs
  src/Controls/tests/DeviceTests/Elements/NavigationPage/NavigationPageTests.cs
  src/Controls/tests/DeviceTests/Elements/ScrollView/ScrollViewTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.cs
  src/Core/src/Core/IContentView.cs
  src/Core/src/Core/ICrossPlatformLayout.cs
  src/Core/src/Core/ICrossPlatformLayoutBacking.cs
  src/Core/src/Core/ILayout.cs
  src/Core/src/Handlers/Border/BorderHandler.Android.cs
  src/Core/src/Handlers/Border/BorderHandler.Windows.cs
  src/Core/src/Handlers/Border/BorderHandler.iOS.cs
  src/Core/src/Handlers/ContentView/ContentViewHandler.Android.cs
  src/Core/src/Handlers/ContentView/ContentViewHandler.Windows.cs
  src/Core/src/Handlers/ContentView/ContentViewHandler.iOS.cs
  src/Core/src/Handlers/Layout/LayoutHandler.Android.cs
  src/Core/src/Handlers/Layout/LayoutHandler.Windows.cs
  src/Core/src/Handlers/Layout/LayoutHandler.iOS.cs
  src/Core/src/Handlers/RadioButton/RadioButtonHandler.iOS.cs
  src/Core/src/Handlers/ScrollView/ScrollViewHandler.Android.cs
  src/Core/src/Handlers/ScrollView/ScrollViewHandler.Windows.cs
  src/Core/src/Handlers/ScrollView/ScrollViewHandler.iOS.cs
  src/Core/src/Handlers/SwipeItemView/SwipeItemViewHandler.Android.cs
  src/Core/src/Handlers/SwipeItemView/SwipeItemViewHandler.iOS.cs
  src/Core/src/Handlers/SwipeView/SwipeViewHandler.Android.cs
  src/Core/src/Handlers/SwipeView/SwipeViewHandler.iOS.cs
  src/Core/src/Platform/Android/ContentViewGroup.cs
  src/Core/src/Platform/Android/LayoutViewGroup.cs
  src/Core/src/Platform/Windows/ContentPanel.cs
  src/Core/src/Platform/Windows/LayoutPanel.cs
  src/Core/src/Platform/Windows/MauiPanel.cs
  src/Core/src/Platform/iOS/ContentView.cs
  src/Core/src/Platform/iOS/LayoutView.cs
  src/Core/src/Platform/iOS/MauiView.cs
  src/Core/src/Platform/iOS/PageViewController.cs
  src/Core/src/Platform/iOS/SemanticSwitchContentView.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
Labels: area/layout 🔲

#15725 [Android] Fix Button issue updating background brush type
  src/Controls/samples/Controls.Sample/Pages/Controls/ButtonPage.xaml
  src/Controls/samples/Controls.Sample/Pages/Controls/ButtonPage.xaml.cs
  src/Core/src/Platform/Android/ButtonExtensions.cs
Labels: t/bug, area/drawing ✏️, area/controls 🎮, control-button

#13864 Add SwipeItems to LogicalChildren
  src/Controls/samples/Controls.Sample/Pages/Controls/SwipeViewGalleries/OpenCloseSwipeGallery.cs
  src/Controls/src/Core/SwipeView/SwipeView.cs
  src/Controls/tests/DeviceTests/Elements/SwipeView/SwipeViewTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/SwipeView/SwipeViewTests.cs
  src/Controls/tests/DeviceTests/Elements/SwipeView/SwipeViewTests.iOS.cs
  src/Core/src/Platform/Android/MauiSwipeView.cs
  src/Core/src/Platform/iOS/MauiSwipeView.cs
Labels: t/bug, area/controls 🎮, control-swipeview

#15830 [uitests] Fix uitests pipelines triggers for Compatibility tests
  eng/pipelines/common/ui-tests.yml
  eng/pipelines/ui-tests.yml
  src/Compatibility/ControlGallery/src/Issues.Shared/Bugzilla31366.cs
  src/Compatibility/ControlGallery/src/Issues.Shared/Issue1975.cs
  src/Compatibility/ControlGallery/src/Issues.Shared/Issue4597.cs
  src/Compatibility/ControlGallery/src/Issues.Shared/SwipeBackNavCrash.cs
  src/Compatibility/ControlGallery/src/Issues.Shared/TabbedPageTests.cs
  src/Compatibility/ControlGallery/src/Issues.Shared/TabbedPageWithList.cs
Labels: area/testing

#15831 [ios] fix memory leak in CollectionView cells
  src/Controls/src/Core/Handlers/Items/iOS/TemplatedCell.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.iOS.cs
Labels: platform/iOS 🍎, area/perf 🏎️

#15688 Correctly identify headers/footers when using UngroupedItemsSource
  src/Controls/src/Core/Handlers/Items/Android/Adapters/EmptyViewAdapter.cs
  src/Controls/src/Core/Handlers/Items/Android/ItemsSources/UngroupedItemsSource.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.Android.cs
Labels: t/bug, platform/android 🤖, area/collectionview 📃

#14613 Optimize iOS selection synchronization
  src/Controls/src/Core/Handlers/Items/iOS/ListSource.cs
  src/Controls/src/Core/Handlers/Items/iOS/ObservableGroupedSource.cs
  src/Controls/src/Core/Handlers/Items/iOS/ObservableItemsSource.cs
  src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs
Labels: platform/iOS 🍎, area/collectionview 📃, community ✨

#15098 Fixed removing items from the shell causing a crash
  src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs
  src/Controls/src/Core/Shell/ShellItem.cs
  src/Controls/tests/Core.UnitTests/ShellTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.cs
Labels: area/shell 🐢

#15879 Daily code formatting task: use different branch for net7.0 branch
  .github/workflows/dotnet-format-daily-net7.yml
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#14262 [Windows] Fix crash swapping MainPage
  src/Controls/tests/DeviceTests/Elements/Window/WindowTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Window/WindowTests.cs
  src/Core/src/Handlers/ContentView/ContentViewHandler.Windows.cs
  src/Core/src/Platform/Windows/NavigationRootManager.cs
Labels: t/bug, platform/windows 🪟, area/navigation 🧭

#15886 [Revert] Correctly identify headers/footers when using UngroupedItems…
  src/Controls/src/Core/Handlers/Items/Android/Adapters/EmptyViewAdapter.cs
  src/Controls/src/Core/Handlers/Items/Android/ItemsSources/UngroupedItemsSource.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.Android.cs
Labels: area/collectionview 📃

#14912 Use default SmallChange value for WinUI slider
  src/Core/src/Platform/Windows/SliderExtensions.cs
Labels: area/controls 🎮, control-slider

#15863 Fix PointerGesture CommandParameter properties
  src/Controls/samples/Controls.Sample/Pages/Core/PointerGestureGalleryPage.xaml
  src/Controls/samples/Controls.Sample/Pages/Core/PointerGestureGalleryPage.xaml.cs
  src/Controls/src/Core/PointerGestureRecognizer.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/tests/Core.UnitTests/Gestures/PointerGestureRecognizerTests.cs
Labels: t/breaking 💥, needs-breaking-change-doc-created

#15926 [release/8.0.1xx-preview6] Bump to xamarin/xamarin-android/release/8.0.1xx-preview6@e55038e5
  eng/Version.Details.xml
  eng/Versions.props
  eng/provisioning/provisioning.csx
  src/Controls/src/Core/Compatibility/Handlers/Android/FrameRenderer.cs
  src/Core/src/Platform/Android/MauiScrollView.cs
  src/Essentials/src/Geolocation/Geolocation.android.cs
  src/TestUtils/src/DeviceTests/AssertionExtensions.Android.cs
Labels: area/infrastructure 🏗️

#15840 Backport WinUI DeviceTest Fixes
  src/Controls/tests/DeviceTests/ControlsHandlerTestBase.Windows.cs
  src/Controls/tests/DeviceTests/ControlsHandlerTestBase.cs
  src/Controls/tests/DeviceTests/Elements/Frame/FrameHandlerTest.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Frame/FrameTests.cs
  src/Controls/tests/DeviceTests/Elements/Image/ImageTests.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.cs
  src/Controls/tests/DeviceTests/Elements/Layout/LayoutTests.cs
  src/Controls/tests/DeviceTests/Elements/Page/PageTests.cs
  src/Controls/tests/DeviceTests/Elements/ScrollView/ScrollViewTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.Windows.cs
  src/Controls/tests/DeviceTests/Extensions.cs
  src/Core/tests/DeviceTests.Shared/HandlerTests/HandlerTestBase.cs
  src/Core/tests/DeviceTests.Shared/HandlerTests/HandlerTestBaseOfT.Tests.cs
  src/Core/tests/DeviceTests.Shared/HandlerTests/HandlerTestBaseOfT.Windows.cs
  src/Core/tests/DeviceTests.Shared/Stubs/ContextStub.cs
  src/Core/tests/DeviceTests/Handlers/Button/ButtonHandlerTests.cs
  src/Core/tests/DeviceTests/Handlers/Editor/EditorHandlerTests.cs
  src/Core/tests/DeviceTests/Handlers/Entry/EntryHandlerTests.cs
  src/Core/tests/DeviceTests/Handlers/Navigation/NavigationViewHandlerTests.Windows.cs
  src/Core/tests/DeviceTests/Handlers/RefreshView/RefreshViewHandlerTests.cs
  src/Core/tests/DeviceTests/Handlers/SearchBar/SearchBarHandlerTests.cs
  src/Core/tests/DeviceTests/Handlers/WebView/WebViewHandlerTests.Windows.cs
  src/Core/tests/DeviceTests/Handlers/Window/WindowHandlerTests.Windows.cs
  src/Core/tests/DeviceTests/Stubs/BorderStub.cs
  src/TestUtils/src/DeviceTests/AssertionExtensions.Windows.cs
  src/TestUtils/src/DeviceTests/AssertionExtensions.cs
Labels: area/testing

#15934 [net8.0] bump to xamarin/xamarin-android/main@efa14e26
  eng/Version.Details.xml
  eng/Versions.props
  eng/provisioning/provisioning.csx
  src/Controls/src/Core/Compatibility/Handlers/Android/FrameRenderer.cs
  src/Core/src/Platform/Android/MauiScrollView.cs
  src/Essentials/src/Geolocation/Geolocation.android.cs
  src/TestUtils/src/DeviceTests/AssertionExtensions.Android.cs
Labels: area/infrastructure 🏗️

#15777 Update DEVELOPMENT.md
  .github/DEVELOPMENT.md
Labels: area/infrastructure 🏗️

#15931 [net8.0] Merge main to net8.0 branch
  .config/dotnet-tools.json
  .github/workflows/dotnet-format-daily-main.yml
  .github/workflows/dotnet-format-daily-net7.yml
  eng/Version.Details.xml
  eng/Versions.props
  eng/devices/catalyst.cake
  eng/devices/windows.cake
  eng/pipelines/common/ui-tests.yml
  eng/pipelines/ui-tests.yml
  src/Compatibility/ControlGallery/src/Issues.Shared/Bugzilla31366.cs
  src/Compatibility/ControlGallery/src/Issues.Shared/Issue1975.cs
  src/Compatibility/ControlGallery/src/Issues.Shared/Issue4597.cs
  src/Compatibility/ControlGallery/src/Issues.Shared/SwipeBackNavCrash.cs
  src/Compatibility/ControlGallery/src/Issues.Shared/TabbedPageTests.cs
  src/Compatibility/ControlGallery/src/Issues.Shared/TabbedPageWithList.cs
  src/Controls/samples/Controls.Sample/Pages/Core/PointerGestureGalleryPage.xaml
  src/Controls/samples/Controls.Sample/Pages/Core/PointerGestureGalleryPage.xaml.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs
  src/Controls/src/Core/Handlers/Items/iOS/ListSource.cs
  src/Controls/src/Core/Handlers/Items/iOS/ObservableGroupedSource.cs
  src/Controls/src/Core/Handlers/Items/iOS/ObservableItemsSource.cs
  src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs
  src/Controls/src/Core/Handlers/Items/iOS/TemplatedCell.cs
  src/Controls/src/Core/Handlers/Shell/Windows/ShellView.cs
  src/Controls/src/Core/PointerGestureRecognizer.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/Shell/ShellItem.cs
  src/Controls/tests/Core.UnitTests/Controls.Core.UnitTests.csproj
  src/Controls/tests/Core.UnitTests/Gestures/PointerGestureRecognizerTests.cs
  src/Controls/tests/Core.UnitTests/ShellTests.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.cs
  src/Controls/tests/DeviceTests/Elements/Window/WindowTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Window/WindowTests.cs
  src/Controls/tests/UITests/Controls.AppiumTests.csproj
  src/Controls/tests/Xaml.UnitTests/Controls.Xaml.UnitTests.csproj
  src/Core/src/Handlers/ContentView/ContentViewHandler.Windows.cs
  src/Core/src/Platform/Windows/NavigationRootManager.cs
  src/Core/src/Platform/Windows/SliderExtensions.cs
  src/Core/tests/UnitTests/Core.UnitTests.csproj
  src/Essentials/src/Types/Shared/WebUtils.shared.cs
  src/Essentials/test/UnitTests/Essentials.UnitTests.csproj
  src/Graphics/tests/Graphics.Tests/Graphics.Tests.csproj
  src/SingleProject/Resizetizer/test/UnitTests/Resizetizer.UnitTests.csproj
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/Microsoft.Maui.IntegrationTests.csproj
  src/Workload/Microsoft.Maui.Sdk/Sdk/BundledVersions.in.targets
Labels: area/infrastructure 🏗️

#15946 [ios] fix memory leak in Border
  src/Controls/tests/DeviceTests/Elements/Border/BorderTests.cs
  src/Core/src/Handlers/Border/BorderHandler.iOS.cs
  src/Core/src/Platform/iOS/ContentView.cs
Labels: platform/iOS 🍎, area/perf 🏎️
