Repository dotnet/maui, pull requests merged in 2024-01, with the labels that each got.

#19652 [ci] Don't skip default provision on iOS
  eng/pipelines/common/device-tests-steps.yml
Labels: area/testing, testing-green-ci

#19685 Modify `FlyoutHeaderAdaptsToMinimumHeight` test to work better on CI
  src/Controls/tests/DeviceTests/Elements/Shell/ShellFlyoutTests.cs
Labels: area/testing

#19735 Update eng/README.md
  eng/README.md
Labels: community ✨

#19125 [iOS] Fix Flyout layout
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellFlyoutHeaderContainer.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellFlyoutLayoutManager.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellFlyoutHeaderBehaviorAndContentTestCases.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellFlyoutHeaderScrollTestCases.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellFlyoutTests.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellFlyoutTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.iOS.cs
Labels: area/shell 🐢

#19371 [macOS] Fix `GesturePlatformManager.CalculatePosition` when asked for a relative position
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue19329.xaml
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue19329.xaml.cs
  src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.iOS.cs
  src/Controls/tests/UITests/Tests/Issues/Issue19329.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: community ✨, area/gestures

#19723 Fix disappearing cell issue for TableView on Android
  src/Controls/src/Core/Compatibility/Handlers/ListView/Android/EntryCellRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/ListView/Android/SwitchCellRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/ListView/Android/TextCellRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/TableView/Android/TableViewModelRenderer.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
Labels: t/bug, platform/android 🤖, area/ListView

#19785 [X] passing test for 18976
  src/Controls/tests/Xaml.UnitTests/Issues/Maui18976.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui18976.xaml.cs
Labels: area/Xaml </>

#19767 Fix SetProgressViewOffset on SwipeRefreshLayout
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue17610.xaml
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue17610.xaml.cs
  src/Controls/tests/UITests/Tests/Issues/Issue17610.cs
  src/Controls/tests/UITests/snapshots/android/RefreshIconDisappearsWhenUserCancelsRefreshByScrollingBackUp.png
  src/Core/src/Handlers/RefreshView/RefreshViewHandler.Android.cs
  src/Core/src/Platform/Android/MauiSwipeRefreshLayout.cs
Labels: platform/android 🤖, area/controls 🎮, control-refreshview

#17470 [Windows] Show the Raw HTML for Html Label in case of error
  src/Controls/samples/Controls.Sample.UITests/Elements/LabelCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Test.cs
  src/Core/src/Platform/Windows/TextBlockExtensions.cs
Labels: area/controls 🎮, stale

#19838 [Catalyst] Allow setting of CancelButtonColor on SearchBar when using Mac Idiom
  src/Controls/tests/DeviceTests/Elements/SearchBar/SearchBarTests.cs
  src/Controls/tests/DeviceTests/Elements/SearchBar/SearchBarTests.iOS.cs
  src/Core/src/Platform/iOS/SearchBarExtensions.cs
Labels: platform/macOS 🍏, area/controls 🎮

#19659 Added optional ReceiveSms permission
  src/Essentials/src/Permissions/Permissions.android.cs
Labels: area/essentials 🍞, community ✨

#17670 iOS Keyboard Scrolling Improvements and UITests (not from fork)
  src/Controls/samples/Controls.Sample.UITests/CoreViews/CorePageView.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingEditorsPage.xaml
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingEditorsPage.xaml.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingEntriesPage.xaml
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingEntriesPage.xaml.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingEntryNextEditorPage.xaml
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingEntryNextEditorPage.xaml.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingGridGallery.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingGridPage.xaml
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingGridPage.xaml.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingNonScrollingPageLargeTitlesGallery.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingNonScrollingPageSmallTitlesGallery.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingScrollingPageLargeTitlesGallery.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingScrollingPageSmallTitlesGallery.cs
  src/Controls/tests/UITests/Tests/KeyboardScrolling.cs
  src/Controls/tests/UITests/Tests/KeyboardScrollingGridTests.cs
  src/Controls/tests/UITests/Tests/KeyboardScrollingNonScrollingPageLargeTitlesTests.cs
  src/Controls/tests/UITests/Tests/KeyboardScrollingNonScrollingPageSmallTitlesTests.cs
  src/Controls/tests/UITests/Tests/KeyboardScrollingScrollingPageLargeTitlesTests.cs
  src/Controls/tests/UITests/Tests/KeyboardScrollingScrollingPageSmallTitlesTests.cs
  src/Core/src/Platform/iOS/KeyboardAutoManagerScroll.cs
  src/Core/src/Platform/iOS/MauiView.cs
Labels: platform/iOS 🍎, partner/cat 😻, area/controls 🎮, control-entry, area/keyboard

#19863 [ci] Don't install xharness globally
  build.ps1
  eng/pipelines/common/maui-templates.yml
  eng/pipelines/common/variables.yml
Labels: t/housekeeping ♻︎, area/testing, testing-flakiness

#19797 Update README.md
  src/Workload/README.md
Labels: area/docs 📓

#19683 [xamlg] improve error for Xamarin.Forms namespace
  src/Controls/src/SourceGen/CodeBehindGenerator.cs
  src/Controls/src/Xaml/XamlParser.Namespaces.cs
  src/Controls/src/Xaml/XmlTypeXamlExtensions.cs
Labels: area/Xaml </>

#19898 [net8.0] Merge main to net8
  build.ps1
  docs/design/layout.md
  eng/pipelines/common/maui-templates.yml
  eng/pipelines/common/variables.yml
  src/Controls/samples/Controls.Sample.UITests/CoreViews/CorePageView.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingEditorsPage.xaml
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingEditorsPage.xaml.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingEntriesPage.xaml
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingEntriesPage.xaml.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingEntryNextEditorPage.xaml
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingEntryNextEditorPage.xaml.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingGridGallery.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingGridPage.xaml
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingGridPage.xaml.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingNonScrollingPageLargeTitlesGallery.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingNonScrollingPageSmallTitlesGallery.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingScrollingPageLargeTitlesGallery.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/KeyboardScrollingScrollingPageSmallTitlesGallery.cs
  src/Controls/samples/Controls.Sample.UITests/Elements/LabelCoreGalleryPage.cs
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue17610.xaml
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue17610.xaml.cs
  src/Controls/samples/Controls.Sample.UITests/Test.cs
  src/Controls/src/Core/Layout/AbsoluteLayout.cs
  src/Controls/src/SourceGen/CodeBehindGenerator.cs
  src/Controls/src/Xaml/XamlParser.Namespaces.cs
  src/Controls/src/Xaml/XmlTypeXamlExtensions.cs
  src/Controls/tests/Core.UnitTests/Layouts/AbsoluteLayoutTests.cs
  src/Controls/tests/DeviceTests/Elements/SearchBar/SearchBarTests.cs
  src/Controls/tests/DeviceTests/Elements/SearchBar/SearchBarTests.iOS.cs
  src/Controls/tests/UITests/Tests/Issues/Issue17610.cs
  src/Controls/tests/UITests/Tests/KeyboardScrolling.cs
  src/Controls/tests/UITests/Tests/KeyboardScrollingGridTests.cs
  src/Controls/tests/UITests/Tests/KeyboardScrollingNonScrollingPageLargeTitlesTests.cs
  src/Controls/tests/UITests/Tests/KeyboardScrollingNonScrollingPageSmallTitlesTests.cs
  src/Controls/tests/UITests/Tests/KeyboardScrollingScrollingPageLargeTitlesTests.cs
  src/Controls/tests/UITests/Tests/KeyboardScrollingScrollingPageSmallTitlesTests.cs
  src/Controls/tests/UITests/snapshots/android/RefreshIconDisappearsWhenUserCancelsRefreshByScrollingBackUp.png
  src/Core/src/Handlers/RefreshView/RefreshViewHandler.Android.cs
  src/Core/src/Platform/Android/MauiSwipeRefreshLayout.cs
  src/Core/src/Platform/Windows/TextBlockExtensions.cs
  src/Core/src/Platform/iOS/KeyboardAutoManagerScroll.cs
  src/Core/src/Platform/iOS/MauiView.cs
  src/Core/src/Platform/iOS/SearchBarExtensions.cs
  src/Essentials/src/Permissions/Permissions.android.cs
  src/Workload/README.md
Labels: t/housekeeping ♻︎

#17671 `sealed` some `internal` classes in `Controls.Core` that are not inherited from (2)
  src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ViewCellRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/ListView/Windows/ListViewRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/ListView/iOS/ContextActionCell.cs
  src/Controls/src/Core/Compatibility/Handlers/ListView/iOS/ContextScrollViewDelegate.cs
  src/Controls/src/Core/Compatibility/Handlers/ListView/iOS/ListViewRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/ListView/iOS/ViewCellRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellContentView.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellFlyoutTemplatedContentRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellFragmentContainer.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellFragmentStateAdapter.cs
Labels: area/architecture, community ✨, stale

#19766 Add basic docs for ScrollView implementations
  .github/workflows/spellcheck.yml
  docs/design/scrollview.md
  src/Controls/samples/Controls.Sample.Sandbox/MainPage.xaml
Labels: area/docs 📓, area/layout 🔲

#19300 Avoid zero-length array allocations
  .editorconfig
  src/Compatibility/ControlGallery/src/Issues.Shared/Issue4597.cs
  src/Compatibility/Core/src/Android/CollectionView/SelectableItemsViewAdapter.cs
  src/Compatibility/Core/src/Android/Renderers/EditorRenderer.cs
  src/Compatibility/Core/src/Android/Renderers/EntryRenderer.cs
  src/Compatibility/Core/src/Android/Renderers/SearchBarRenderer.cs
  src/Compatibility/Core/src/Tizen/Forms.cs
  src/Compatibility/Core/src/iOS/DragAndDropDelegate.cs
  src/Compatibility/Core/src/iOS/Extensions/DoubleCollectionExtensions.cs
  src/Compatibility/Core/src/iOS/Extensions/PointCollectionExtensions.cs
  src/Compatibility/Core/src/iOS/Renderers/NavigationRenderer.cs
  src/Compatibility/Core/src/iOS/Renderers/WkWebViewRenderer.cs
  src/Compatibility/Core/src/iOS/Shapes/ShapeRenderer.cs
  src/Controls/Foldable/src/DualScreenInfo.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/CollectionViewGalleries/CollectionModifier.cs
  src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellItemRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs
  src/Controls/src/Core/Handlers/Items/Android/Adapters/SelectableItemsViewAdapter.cs
  src/Controls/src/Core/LegacyLayouts/ConstraintExpression.cs
  src/Controls/src/Core/Menu/MenuItemTracker.cs
  src/Controls/src/Core/Platform/iOS/DragAndDropDelegate.cs
  src/Controls/src/Core/Platform/iOS/Extensions/BrushExtensions.cs
  src/Controls/src/Core/PlatformBindingHelpers.cs
  src/Controls/src/Core/TemplatedItemsList.cs
  src/Controls/src/Xaml/ApplyPropertiesVisitor.cs
  src/Controls/src/Xaml/CreateValuesVisitor.cs
  src/Controls/src/Xaml/MarkupExtensions/StaticExtension.cs
  src/Controls/tests/Core.UnitTests/BindableLayoutTests.cs
  src/Controls/tests/Core.UnitTests/BindingBaseUnitTests.cs
  src/Controls/tests/Core.UnitTests/DynamicBindingContextTests.cs
  src/Controls/tests/Core.UnitTests/NotifiedPropertiesTests.cs
  src/Controls/tests/Core.UnitTests/TemplatedItemsListTests.cs
  src/Controls/tests/DeviceTests/ControlsHandlerTestBase.iOS.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Gh4516.xaml.cs
  src/Controls/tests/Xaml.UnitTests/NativeViewsAndBindings.xaml.cs
  src/Core/src/.editorconfig
  src/Essentials/samples/Samples/Model/SampleItem.cs
  src/Essentials/src/Sms/Sms.ios.cs
  src/Essentials/src/VersionTracking/VersionTracking.shared.cs
  src/Graphics/src/Graphics/PathF.cs
  src/Graphics/src/Graphics/Platforms/MaciOS/PlatformCanvas.cs
  src/Graphics/src/Graphics/Platforms/Windows/PlatformCanvasState.cs
  src/Graphics/src/Graphics/Platforms/iOS/UIViewExtensions.cs
Labels: area/perf 🏎️, community ✨, stale

#19402 [Trimming] Fix several trimming warnings
  src/Controls/src/Core/BindableProperty.cs
  src/Controls/src/Core/DependencyService.cs
  src/Controls/src/Core/Internals/CellExtensions.cs
  src/Controls/src/Core/ItemsView.cs
  src/Controls/src/Core/ResourceDictionary.cs
  src/Controls/src/Core/Routing.cs
  src/Controls/src/Core/TemplatedItemsList.cs
  src/Controls/src/Core/Xaml/TypeConversionExtensions.cs
  src/Core/src/HotReload/HotReloadHelper.cs
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/Utilities/BuildWarningsUtilities.cs
Labels: area/publishing 🏁, stale

#19807 [Android] FlyoutIsPresented property opens the Flyout
  src/Controls/samples/Controls.Sample/Pages/Core/ShellGalleries/ShellChromeGallery.cs
  src/Controls/samples/Controls.Sample/Pages/Core/ShellGalleries/ShellChromeGallery.xaml
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellFlyoutRenderer.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellFlyoutTests.Android.cs
Labels: t/bug, platform/android 🤖, area/shell 🐢

#14918 Fix Label Multilinetruncation (MaxLines / LineBreakMode)
  src/Controls/samples/Controls.Sample/Pages/Controls/LabelPage.xaml
  src/Controls/src/Core/Label/Label.Android.cs
  src/Controls/src/Core/Label/Label.Windows.cs
  src/Controls/src/Core/Label/Label.iOS.cs
  src/Controls/src/Core/Platform/Android/Extensions/TextViewExtensions.cs
  src/Controls/src/Core/Platform/Windows/Extensions/TextBlockExtensions.cs
  src/Controls/src/Core/Platform/iOS/Extensions/TextExtensions.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.iOS.cs
Labels: t/bug, area/controls 🎮, control-label

#19472 Add PostNotifications to Permissions
  src/Essentials/samples/Samples/ViewModel/PermissionsViewModel.cs
  src/Essentials/src/Permissions/Permissions.android.cs
  src/Essentials/src/Permissions/Permissions.ios.tvos.watchos.cs
  src/Essentials/src/Permissions/Permissions.macos.cs
  src/Essentials/src/Permissions/Permissions.netstandard.cs
  src/Essentials/src/Permissions/Permissions.shared.cs
  src/Essentials/src/Permissions/Permissions.tizen.cs
  src/Essentials/src/Permissions/Permissions.uwp.cs
  src/Essentials/src/PublicAPI/net-android/PublicAPI.Shipped.txt
  src/Essentials/src/PublicAPI/net-ios/PublicAPI.Shipped.txt
  src/Essentials/src/PublicAPI/net-maccatalyst/PublicAPI.Shipped.txt
  src/Essentials/src/PublicAPI/net-tizen/PublicAPI.Shipped.txt
  src/Essentials/src/PublicAPI/net-windows/PublicAPI.Shipped.txt
  src/Essentials/src/PublicAPI/net/PublicAPI.Shipped.txt
  src/Essentials/src/PublicAPI/netstandard/PublicAPI.Shipped.txt
Labels: area/essentials 🍞, stale

#19963 Optimize IndexOf lookups
  src/Core/src/Extensions/EnumerableExtensions.cs
  src/Core/tests/Benchmarks/Benchmarks/IndexOfBenchmarker.cs
Labels: area/perf 🏎️, community ✨

#19909 Fix Developer Tools option setting for Blazor Hybrid Mac Catalyst view.
  src/BlazorWebView/src/Maui/iOS/BlazorWebViewHandler.iOS.cs
Labels: area/tooling ⚙️

#16386 Process the hardware enter key as "Done"
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue16386.cs
  src/Controls/tests/UITests/Tests/Issues/Issue16386.cs
  src/Core/src/Handlers/Entry/EntryHandler.Android.cs
  src/Core/src/Handlers/Entry/EntryHandler.Windows.cs
  src/Core/src/Platform/Android/EditTextExtensions.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area/controls 🎮, stale

#20029 Remove unused functions
  src/Core/src/Extensions/EnumerableExtensions.cs
Labels: community ✨

#19600 Resizetizer Regex Fix
  src/SingleProject/Resizetizer/src/Utils.cs
  src/SingleProject/Resizetizer/test/UnitTests/FilenameTests.cs
Labels: area/single project ☝️, community ✨

#20060 [tests] Move integration tests to use MauiDotNetTfm
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/Microsoft.Maui.IntegrationTests.csproj
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/Utilities/XHarness.cs
Labels: t/housekeeping ♻︎

#20056 Enforce preference of braces for code blocks (IDE0011) in .editorconfig
  .editorconfig
Labels: t/housekeeping ♻︎

#20014 Make sure we support keyed services in client apps
  src/Core/src/MauiContext.cs
  src/Core/tests/UnitTests/MauiContextTests.cs
  src/Core/tests/UnitTests/TestClasses/TestServices.cs
Labels: area/hosting 🧩

#19925 Split the InputTransparency tests
  src/Controls/tests/UITests/Tests/Concepts/InputTransparencyGalleryTests.cs
Labels: area/testing, testing-flakiness

#20067 Bump Xamarin.UITest to 4.3.4
  src/Compatibility/ControlGallery/test/Android.UITests/Compatibility.ControlGallery.Android.UITests.csproj
  src/Compatibility/ControlGallery/test/WinUI.UITests/WinUI.UITests.csproj
  src/Compatibility/ControlGallery/test/iOS.UITests/Compatibility.ControlGallery.iOS.UITests.csproj
Labels: t/housekeeping ♻︎, area/testing, testing-legacy-ui-tests

#20106 [ci] Restore dotnet tools in provisioned sdk
  eng/cake/dotnet.cake
Labels: testing-flakiness, testing-green-ci, xharness

#19377 Do not use underscores in the ApplicationId
  src/Templates/src/templates/maui-blazor/.template.config/template.json
  src/Templates/src/templates/maui-mobile/.template.config/template.json
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/TemplateTests.cs
Labels: area/templates 📄, stale

#19261 [WinUI] Add workaround for Connectivity check on Win10
  src/Essentials/src/Connectivity/Connectivity.Native.uwp.cs
  src/Essentials/src/Connectivity/Connectivity.uwp.cs
Labels: platform/windows 🪟, area/essentials 🍞, area/desktop 🖥️, partner/cat 😻

#20079 [Windows] Adjust recycle check in ItemContentControl
  src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs
Labels: platform/windows 🪟, area/collectionview 📃

#19932 Rectify the scopes in the builder
  src/Controls/samples/Controls.Sample/MauiProgram.cs
  src/Controls/samples/Controls.Sample/XamlApp.xaml.cs
  src/Controls/src/Xaml/Hosting/AppHostBuilderExtensions.cs
  src/Controls/tests/DeviceTests/Elements/Window/WindowTests.cs
  src/Core/src/Dispatching/ApplicationDispatcher.cs
  src/Core/src/Hosting/Dispatching/AppHostBuilderExtensions.cs
  src/Core/src/Hosting/IMauiInitializeService.cs
  src/Core/src/Hosting/MauiAppBuilder.cs
  src/Core/src/MauiContextExtensions.cs
  src/Core/tests/DeviceTests.Shared/HandlerTests/HandlerTestBasement.cs
  src/Core/tests/DeviceTests.Shared/MauiProgramDefaults.cs
  src/TestUtils/src/DeviceTests.Runners/TestDispatcher.cs
Labels: area/hosting 🧩

#20122 [ci] Update System.Drawing.Common
  src/Controls/tests/UITests/Controls.AppiumTests.csproj
  src/TestUtils/src/UITest.Appium/UITest.Appium.csproj
Labels: area/infrastructure 🏗️

#20019 Enable building WASDK Self-Contained packaged apps
  Directory.Build.targets
  src/Core/src/nuget/buildTransitive/WinUI.Unpackaged.targets
  src/Core/src/nuget/buildTransitive/WinUI.targets
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/TemplateTests.cs
Labels: platform/windows 🪟

#19204 Translucent and Transparent NavigationBar on iOS
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue17022.xaml
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue17022.xaml.cs
  src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellNavBarAppearanceTracker.cs
  src/Controls/src/Core/Platform/iOS/Extensions/NavigationPageExtensions.cs
  src/Controls/tests/UITests/Tests/Issues/Issue17022.cs
  src/Controls/tests/UITests/snapshots/ios/Issue17022TestNewFlyoutPageGridTranslucentButton.png
  src/Controls/tests/UITests/snapshots/ios/Issue17022TestNewNavigationPageGridTranslucentButton.png
  src/Controls/tests/UITests/snapshots/ios/Issue17022TestSemiTransparentFlyoutPageBackgroundColor.png
  src/Controls/tests/UITests/snapshots/ios/Issue17022TestSemiTransparentFlyoutPageBrush.png
  src/Controls/tests/UITests/snapshots/ios/Issue17022TestSemiTransparentNavigationPageBackgroundColor.png
  src/Controls/tests/UITests/snapshots/ios/Issue17022TestSemiTransparentNavigationPageBrush.png
Labels: area/navigation 🧭, platform/iOS 🍎, area/shell 🐢, partner/cat 😻

#20082 Reset the xaml in the Sandbox MainPage.xaml
  src/Controls/samples/Controls.Sample.Sandbox/MainPage.xaml
Labels: area/docs 📓

#20161 Update GitInfo.txt to 8.0.7-preview
  GitInfo.txt
Labels: area/infrastructure 🏗️

#14295 [Android] Fix gif animation initial state
  src/Controls/samples/Controls.Sample/Pages/Controls/ImagePage.xaml
  src/Core/src/Handlers/Image/ImageHandler.Android.cs
  src/Core/tests/DeviceTests/Handlers/Image/ImageHandlerTests.cs
Labels: t/bug, platform/android 🤖, area/controls 🎮, control-image

#18540 [X] allow x:Type extension for BPConverter
  src/Controls/src/Build.Tasks/CompiledConverters/BindablePropertyConverter.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui18324.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui18324.xaml.cs
Labels: area/Xaml </>, stale

#19990 Source Generator Performance Improvements
  src/Controls/samples/Controls.Sample/Maui.Controls.Sample.csproj
  src/Controls/src/SourceGen/CodeBehindGenerator.cs
  src/Controls/src/SourceGen/Properties/launchSettings.json
  src/Controls/src/Xaml/XamlNode.cs
  src/Controls/src/Xaml/XmlTypeXamlExtensions.cs
Labels: area/Xaml </>

#19444 [Testing] Added appium UITest for FlyoutNavigationBetweenItemsWithNavigationStacks
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue6738.cs
  src/Controls/samples/Controls.Sample.UITests/Issues/TestShell.cs
  src/Controls/tests/UITests/Tests/Issues/Issue6738.cs
Labels: t/housekeeping ♻︎, area/testing

#19046 Add better exception for missing Maps on Windows
  src/Controls/Maps/src/AppHostBuilderExtensions.cs
  src/Controls/samples/Controls.Sample.UITests/MauiProgram.cs
Labels: platform/windows 🪟, t/housekeeping ♻︎, area/Maps🗺

#20183 [ci] Add missing demands
  eng/pipelines/common/maui-templates.yml
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#20215 Add comments to internal methods for XAML Hot Reload usage
  src/Controls/src/Core/IProvideParentValues.cs
  src/Controls/src/Core/IValueConverterProvider.cs
  src/Core/src/Platform/Standard/ViewExtensions.cs
Labels: area/tooling ⚙️, t/housekeeping ♻︎

#20191 Adding Mobile tag to MAUI project templates
  src/Templates/src/templates/maui-blazor/.template.config/template.json
  src/Templates/src/templates/maui-lib/.template.config/template.json
  src/Templates/src/templates/maui-mobile/.template.config/template.json
Labels: area/templates 📄

#19923 [iOS][NativeAOT] Adding NativeAOT RunOniOS device test
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/AppleTemplateTests.cs
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/BaseBuildTest.cs
Labels: platform/iOS 🍎, area/testing

#20226 Use fixed version for apiscan
  eng/pipelines/handlers.yml
Labels: t/housekeeping ♻︎

#20242 Update VisualElement API Docs
  src/Controls/docs/Microsoft.Maui.Controls.PlatformConfiguration.AndroidSpecific/VisualElement.xml
  src/Controls/docs/Microsoft.Maui.Controls.PlatformConfiguration.TizenSpecific/VisualElement.xml
  src/Controls/docs/Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific/VisualElement.xml
  src/Controls/src/Core/PlatformConfiguration/AndroidSpecific/VisualElement.cs
  src/Controls/src/Core/PlatformConfiguration/TizenSpecific/VisualElement.cs
  src/Controls/src/Core/PlatformConfiguration/iOSSpecific/VisualElement.cs
  src/Controls/src/Core/VisualElement/VisualElement.cs
Labels: area/docs 📓, t/housekeeping ♻︎

#20158 [release/9.0.1xx-preview1] Update versions
  Directory.Build.props
  eng/Version.Details.xml
  eng/Versions.props
  eng/cake/dotnet.cake
  src/Compatibility/Core/src/Compatibility.csproj
  src/Controls/tests/Xaml.UnitTests/MSBuild/MSBuildTests.cs
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/AndroidTemplateTests.cs
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/AppleTemplateTests.cs
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/TemplateTests.cs
  src/Workload/Microsoft.Maui.Sdk/Microsoft.Maui.Sdk.csproj
  src/Workload/Microsoft.NET.Sdk.Maui.Manifest/Microsoft.NET.Sdk.Maui.Manifest.csproj
  src/Workload/Microsoft.NET.Sdk.Maui.Manifest/WorkloadManifest.in.json
  src/Workload/Microsoft.NET.Sdk.Maui.Manifest/WorkloadManifest.in.targets
Labels: area/infrastructure 🏗️

#20221 [Windows] Resolve issues with the Switch Track Color tests
  src/Core/tests/DeviceTests/Handlers/Switch/SwitchHandlerTests.cs
Labels: platform/windows 🪟, t/housekeeping ♻︎, area/testing, testing-reenable
