Repository dotnet/maui, pull requests merged in 2024-12, with the labels that each got.

#24978 Fix disabled WebView Cookie Tests
  src/Controls/tests/TestCases.HostApp/Issues/Issue3262.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue3262.cs
Labels: t/housekeeping ♻︎, community ✨

#25855 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 11
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/GitHub1776.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue12320.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue2953.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue8008.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Github1776.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue12320.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2953.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue8008.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing, community ✨

#25772 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 5
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue3318.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue889.cs
  src/Controls/tests/TestCases.HostApp/Resources/Images/bank.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue12642.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue3318.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue7311.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue889.cs
Labels: area-testing, community ✨

#26306 Update Appium version to 2.12.2
  eng/Versions.props
  eng/scripts/appium-install.ps1
Labels: area-infrastructure, testing-infrastructure

#26307 Add GraphicsView UiTestCategory
  eng/pipelines/common/ui-tests.yml
  src/Controls/tests/TestCases.Shared.Tests/UITestCategories.cs
Labels: area-drawing, area-testing

#26085 Reseting thumb image
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/SliderShouldChangeThumbImageAndResetIt.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue25939.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25939.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25939.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/SliderShouldChangeThumbImageAndResetIt.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/SliderShouldChangeThumbImageAndResetIt.png
  src/Core/src/Platform/Android/SliderExtensions.cs
  src/Core/src/Platform/iOS/SliderExtensions.cs
Labels: platform/android 🤖, platform/iOS 🍎, community ✨

#26255 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 25
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue15565.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue15542.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue15565.cs
Labels: area-testing, community ✨

#24036 [Testing] Ported randomly failing tests to Appium
  src/Compatibility/ControlGallery/src/Issues.Shared/Issue774.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue10222.cs
Labels: t/housekeeping ♻︎, area-testing, testing-flakiness

#26193 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 22
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla30353.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla41038.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla42329.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue2964.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla30353.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla34632.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla41038.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla42329.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2964.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing, community ✨

#26143 Fix Tweener leak on Animation
  src/Controls/src/Core/AnimationExtensions.cs
  src/Controls/src/Core/Tweener.cs
  src/Controls/tests/DeviceTests/Memory/MemoryTests.cs
Labels: area-animation, community ✨, memory-leak 💦

#26152 Fixed CollectionViewHandler2 null reference exception if ItemsLayout is set for Tablet but not on mobile devices
  src/Controls/src/Core/Handlers/Items2/CollectionViewHandler2.iOS.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue26065.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue26065.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26065.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/CollectionViewWithFallbackVauleShouldUpdateAtRunTime.png
Labels: community ✨, collectionview-cv2

#26334 Update Appium driver versions
  eng/Versions.props
Labels: area-testing, testing-infrastructure

#26360 [iOS] CV2 - Disable clipping bounds for WrapperView
  src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs
Labels: platform/iOS 🍎, area-controls-collectionview, community ✨, collectionview-cv2

#25414 TableView title issue fix on windows platforms.
  src/Controls/src/Core/Compatibility/Handlers/TableView/Windows/TableViewStyles.xaml
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ValidateTableViewTitles.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue17123.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue17123.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ValidateTableViewTitles.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ValidateTableViewTitles.png
Labels: platform/windows 🪟, platform/iOS 🍎, community ✨, area-controls-listview

#26319 LEGO: Pull request from lego/hb_7241b85a-f216-4d55-a9fa-d8030c736df5_20241203012133186 to main
  loc/cs/src/Templates/src/templates/maui-multiproject/.template.config/localize/templatestrings.json.lcl
  loc/cs/src/Templates/src/templates/maui-window-csharp/.template.config/localize/templatestrings.json.lcl
  loc/cs/src/Templates/src/templates/maui-window-xaml/.template.config/localize/templatestrings.json.lcl
  loc/de/src/Templates/src/templates/maui-multiproject/.template.config/localize/templatestrings.json.lcl
  loc/de/src/Templates/src/templates/maui-window-csharp/.template.config/localize/templatestrings.json.lcl
  loc/de/src/Templates/src/templates/maui-window-xaml/.template.config/localize/templatestrings.json.lcl
  loc/es/src/Templates/src/templates/maui-multiproject/.template.config/localize/templatestrings.json.lcl
  loc/es/src/Templates/src/templates/maui-window-csharp/.template.config/localize/templatestrings.json.lcl
  loc/es/src/Templates/src/templates/maui-window-xaml/.template.config/localize/templatestrings.json.lcl
  loc/fr/src/Templates/src/templates/maui-multiproject/.template.config/localize/templatestrings.json.lcl
  loc/fr/src/Templates/src/templates/maui-window-csharp/.template.config/localize/templatestrings.json.lcl
  loc/fr/src/Templates/src/templates/maui-window-xaml/.template.config/localize/templatestrings.json.lcl
  loc/it/src/Templates/src/templates/maui-multiproject/.template.config/localize/templatestrings.json.lcl
  loc/it/src/Templates/src/templates/maui-window-csharp/.template.config/localize/templatestrings.json.lcl
  loc/it/src/Templates/src/templates/maui-window-xaml/.template.config/localize/templatestrings.json.lcl
  loc/ja/src/Templates/src/templates/maui-multiproject/.template.config/localize/templatestrings.json.lcl
  loc/ja/src/Templates/src/templates/maui-window-csharp/.template.config/localize/templatestrings.json.lcl
  loc/ja/src/Templates/src/templates/maui-window-xaml/.template.config/localize/templatestrings.json.lcl
  loc/ko/src/Templates/src/templates/maui-multiproject/.template.config/localize/templatestrings.json.lcl
  loc/ko/src/Templates/src/templates/maui-window-csharp/.template.config/localize/templatestrings.json.lcl
  loc/ko/src/Templates/src/templates/maui-window-xaml/.template.config/localize/templatestrings.json.lcl
  loc/pl/src/Templates/src/templates/maui-multiproject/.template.config/localize/templatestrings.json.lcl
  loc/pl/src/Templates/src/templates/maui-window-csharp/.template.config/localize/templatestrings.json.lcl
  loc/pl/src/Templates/src/templates/maui-window-xaml/.template.config/localize/templatestrings.json.lcl
  loc/pt-BR/src/Templates/src/templates/maui-multiproject/.template.config/localize/templatestrings.json.lcl
  loc/pt-BR/src/Templates/src/templates/maui-window-csharp/.template.config/localize/templatestrings.json.lcl
  loc/pt-BR/src/Templates/src/templates/maui-window-xaml/.template.config/localize/templatestrings.json.lcl
  loc/ru/src/Templates/src/templates/maui-multiproject/.template.config/localize/templatestrings.json.lcl
  loc/ru/src/Templates/src/templates/maui-window-csharp/.template.config/localize/templatestrings.json.lcl
  loc/ru/src/Templates/src/templates/maui-window-xaml/.template.config/localize/templatestrings.json.lcl
  loc/tr/src/Templates/src/templates/maui-multiproject/.template.config/localize/templatestrings.json.lcl
  loc/tr/src/Templates/src/templates/maui-window-csharp/.template.config/localize/templatestrings.json.lcl
  loc/tr/src/Templates/src/templates/maui-window-xaml/.template.config/localize/templatestrings.json.lcl
  loc/zh-Hans/src/Templates/src/templates/maui-multiproject/.template.config/localize/templatestrings.json.lcl
  loc/zh-Hans/src/Templates/src/templates/maui-window-csharp/.template.config/localize/templatestrings.json.lcl
  loc/zh-Hans/src/Templates/src/templates/maui-window-xaml/.template.config/localize/templatestrings.json.lcl
  loc/zh-Hant/src/Templates/src/templates/maui-multiproject/.template.config/localize/templatestrings.json.lcl
  loc/zh-Hant/src/Templates/src/templates/maui-window-csharp/.template.config/localize/templatestrings.json.lcl
  loc/zh-Hant/src/Templates/src/templates/maui-window-xaml/.template.config/localize/templatestrings.json.lcl
Labels: area-localization

#25825 [iOS] Fix for CollectionView with horizontal grid layout has extra space on right end
  src/Controls/src/Core/Handlers/Items/iOS/GroupableItemsViewController.cs
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewLayout.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CollectionViewHorizontalItemSpacing.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue25433.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25433.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25433.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/CollectionViewHorizontalItemSpacing.png
Labels: platform/iOS 🍎, area-controls-collectionview, community ✨

#26219 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 23
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/FlyoutBehaviorShell.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing, community ✨, partner/syncfusion

#25506 [Windows] Fix for setting IsClippedToBounds="True" inside a Border control will crash on Windows
  src/Controls/tests/TestCases.HostApp/Issues/Issue18937.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue18937.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18937.cs
  src/Core/src/Platform/Windows/ContentPanel.cs
  src/Core/src/Platform/Windows/LayoutPanel.cs
Labels: platform/windows 🪟, community ✨, area-controls-border, partner/syncfusion

#26390 Add RequireService to StaticExtension
  src/Controls/src/Xaml/MarkupExtensions/StaticExtension.cs
Labels: area-xaml

#25374 Creating .NET MAUI Project sometimes causes error *.png is being used by another process
  src/SingleProject/Resizetizer/src/SkiaSharpTools.cs
  src/SingleProject/Resizetizer/src/nuget/buildTransitive/Microsoft.Maui.Resizetizer.After.targets
Labels: area-single-project

#26365 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 29
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla37841.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla41153.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla42956.cs
Labels: area-testing, community ✨, partner/syncfusion

#26367 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 30
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue3475.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue5500.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue3475.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue3788.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue4303.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue4973.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue5500.cs
Labels: area-testing, community ✨, partner/syncfusion

#26411 Change the yaml to build PR if lcl files were changed
  eng/pipelines/common/localization-handback.yml
Labels: area-templates, area-localization

#26379 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 31
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue1704.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue198.cs
  src/Controls/tests/TestCases.HostApp/Resources/Images/calculator.png
  src/Controls/tests/TestCases.HostApp/Resources/Images/gifone.gif
  src/Controls/tests/TestCases.HostApp/Resources/Images/giftwo.gif
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue1704.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue198.cs
Labels: area-testing, community ✨, partner/syncfusion

#26402 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 33
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue12652.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue5159.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue8741.cs
Labels: area-testing, community ✨, partner/syncfusion

#26403 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 34
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue11214.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue11247.cs
Labels: area-testing, community ✨, partner/syncfusion

#26380 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 32
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue7803.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue7890.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue7993.cs
Labels: area-testing, community ✨, partner/syncfusion

#26404 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 35
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/HeaderFooterShellFlyout.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/HeaderFooterShellFlyout.cs
Labels: area-testing, community ✨, partner/syncfusion

#26406 Upgrade Syncfusion Toolkit version from 1.0.2 to 1.0.3
  src/Templates/src/templates/maui-mobile/MauiApp.1.csproj
Labels: community ✨

#26357 [iOS] Add templated cells as children of the CollectionView2
  src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewController2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue26066.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue26066.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26066.cs
Labels: t/bug, area-controls-collectionview, collectionview-cv2

#26048 [iOS][Regression] Fix ToolbarItem color when used with IconImageSource is always default color
  src/Controls/src/Core/Compatibility/iOS/Extensions/ToolbarItemExtensions.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyToolbarItemIconColor.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue25912.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25912.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25912.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyToolbarItemIconColor.png
Labels: t/bug, platform/iOS 🍎, p/0, community ✨, area-controls-toolbar, partner/syncfusion

#26315 [iOS] Fix deselect item on CollectionView
  src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs
  src/Controls/src/Core/Handlers/Items2/iOS/SelectableItemsViewController2.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/SelectedItemVisualIsCleared.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue26187.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26187.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/SelectedItemVisualIsCleared.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/SelectedItemVisualIsCleared.png
Labels: area-controls-collectionview

#26203 Fixed the double tap editor freeze issue and added test cases
  src/Controls/tests/TestCases.HostApp/Issues/Issue25975.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25975.cs
  src/Core/src/Handlers/Editor/EditorHandler.iOS.cs
Labels: platform/iOS 🍎, community ✨, area-controls-editor, partner/syncfusion

#21960 Fix BoxView not rendering when is hidden on start
  src/Controls/src/Core/BoxView/BoxView.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/PropertiesShouldBeCorrectlyApplied.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue19926.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue19926.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19926.cs
Labels: area-layout, area-drawing, community ✨

#26331 Fix Similar name is provided for "Icons" Present
  src/Templates/src/templates/maui-mobile/Models/IconData.cs
  src/Templates/src/templates/maui-mobile/PageModels/ProjectDetailPageModel.cs
  src/Templates/src/templates/maui-mobile/Pages/ProjectDetailPage.xaml
Labels: community ✨, partner/syncfusion

#26235 [iOS] Added DidPopItem to the navigation renderer
  src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs
Labels: area-navigation, platform/iOS 🍎, community ✨

#25574 [Android] RemainingItemsThresholdReachedCommand of CarouselView is not triggered
  src/Controls/src/Core/Handlers/Items/Android/RecyclerViewScrollListener.cs
Labels: platform/android 🤖, area-controls-collectionview, community ✨

#24997 CollectionView, the footer moves to the bottom of the page when the empty view or empty view template is enabled
  src/Controls/src/Core/Handlers/Items/ItemsViewHandler.Android.cs
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs
  src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CollectionViewFooterMovestoBottomWithEmptyvieworEmptyviewTemplate.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue24966.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue24966.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24966.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/CollectionViewFooterMovestoBottomWithEmptyvieworEmptyviewTemplate.png
Labels: platform/android 🤖, platform/iOS 🍎, area-controls-collectionview, community ✨, partner/syncfusion

#26450 Add missing android font weight
  src/Core/src/Fonts/FontManager.Android.cs
Labels: community ✨

#25146 [UITesting, Catalyst] Fixed DragAndDropUITests to be more reliable
  src/Controls/tests/TestCases.HostApp/Elements/DragAndDropBetweenLayouts.xaml
  src/Controls/tests/TestCases.HostApp/Elements/DragAndDropBetweenLayouts.xaml.cs
  src/Controls/tests/TestCases.HostApp/Elements/DragAndDropEventArgs.xaml
  src/Controls/tests/TestCases.HostApp/Elements/DragAndDropEventArgs.xaml.cs
  src/Controls/tests/TestCases.HostApp/Elements/DragAndDropEvents.xaml
  src/Controls/tests/TestCases.HostApp/Elements/DragAndDropEvents.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/DragAndDropUITests.cs
Labels: area-testing, community ✨, partner/syncfusion

#24852 [Android] SearchHandler - added focus/unfocus support
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/SearchHandlerAppearanceTracker.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue24670.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue24670.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24670.cs
Labels: platform/android 🤖, area-controls-shell, community ✨, area-controls-searchbar

#26473 Correct Button EventHandler signature in template
  src/Templates/src/templates/maui-mobile/MainPage.xaml.cs
Labels: area-templates

#26424 Sample Content template: changed currentTheme value with RequestedTheme property.
  src/Templates/src/templates/maui-mobile/AppShell.xaml.cs
Labels: area-templates, community ✨

#25691 [iOS] Fix for Editor scaling creating new lines on older iOS versions
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyDynamicEditorScaling.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue25581.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25581.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25581.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifyDynamicEditorScaling.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyDynamicEditorScaling.png
  src/Core/src/Handlers/Editor/EditorHandler.iOS.cs
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
Labels: platform/iOS 🍎, community ✨, area-controls-editor, partner/syncfusion

#26385 [Windows] Fix for ListView ScrollTo Method throws NullReferenceException
  src/Controls/src/Core/Compatibility/Handlers/ListView/Windows/ListViewRenderer.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla42956.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue3788.cs
Labels: community ✨, area-controls-listview, partner/syncfusion

#23386 [Windows] Fix memory leak with GroupedItemTemplateCollection
  src/Compatibility/Core/src/Windows/CollectionView/ItemsViewRenderer.cs
  src/Controls/src/Core/Handlers/Items/ItemsViewHandler.Windows.cs
  src/Controls/src/Core/Platform/Windows/CollectionView/GroupedItemTemplateCollection.cs
  src/Controls/src/Core/Platform/Windows/CollectionView/ObservableItemTemplateCollection.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.Windows.cs
Labels: platform/windows 🪟, area-controls-collectionview

#26469 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 38
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/ShellFlyoutContent.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla40333.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue7181.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/ShellFlyoutContent.cs
Labels: area-testing, community ✨, partner/syncfusion

#26495 Remove Tizen people from CODEOWNERS
  .github/CODEOWNERS
Labels: t/housekeeping ♻︎, area-infrastructure

#26496 Add TJ as Localization chief in CODEOWNERS
  .github/CODEOWNERS
Labels: t/housekeeping ♻︎, area-infrastructure

#26497 Add Gerald & Javier as UI Test CODEOWNERS
  .github/CODEOWNERS
Labels: t/housekeeping ♻︎, area-infrastructure

#26489 Move DataTemplateSelector to own file in template
  src/Templates/src/templates/maui-mobile/Pages/Controls/ChipDataTemplateSelector.cs
  src/Templates/src/templates/maui-mobile/Pages/ProjectDetailPage.xaml
  src/Templates/src/templates/maui-mobile/Pages/ProjectDetailPage.xaml.cs
Labels: area-templates

#26506 Disable flaky DropEventCoordinates test
  src/Controls/tests/TestCases.Shared.Tests/Tests/DragAndDropUITests.cs
Labels: area-testing, testing-flakiness

#26436 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 36
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue6932_emptyviewstring.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue6932_emptyviewtemplate.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue7329.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue8964.cs
Labels: area-testing, community ✨, partner/syncfusion

#24848 [iOS] Improve background layer frame mapping performance
  src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs
  src/Controls/src/Core/Platform/iOS/Extensions/BrushExtensions.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/GradientLayerShouldApplyProperly.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue24847.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue26057.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue26057.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24847.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26057.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/GradientLayerShouldApplyProperly.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/BackgroundFrameResizesFastAndCorrectly.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/BackgroundFrameResizesFastAndCorrectlySizeChanged.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/GradientLayerShouldApplyProperly.png
  src/Core/src/Handlers/View/ViewHandler.iOS.cs
  src/Core/src/Platform/iOS/CALayerAutosizeObserver.cs
  src/Core/src/Platform/iOS/ContentView.cs
  src/Core/src/Platform/iOS/IAutoSizableCALayer.cs
  src/Core/src/Platform/iOS/LayerExtensions.cs
  src/Core/src/Platform/iOS/MauiCALayer.cs
  src/Core/src/Platform/iOS/StaticCAGradientLayer.cs
  src/Core/src/Platform/iOS/StaticCALayer.cs
  src/Core/src/Platform/iOS/StaticCAShapeLayer.cs
  src/Core/src/Platform/iOS/ViewExtensions.cs
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/tests/DeviceTests/Memory/CALayerAutosizeObserverTests.cs
Labels: area-drawing, platform/iOS 🍎, p/1, community ✨, t/perf

#26483 LEGO: Pull request from lego/hb_7241b85a-f216-4d55-a9fa-d8030c736df5_20241209202058740 to main
  loc/cs/src/Templates/src/templates/maui-multiproject/.template.config/localize/templatestrings.json.lcl
  loc/cs/src/Templates/src/templates/maui-window-csharp/.template.config/localize/templatestrings.json.lcl
  loc/cs/src/Templates/src/templates/maui-window-xaml/.template.config/localize/templatestrings.json.lcl
Labels: area-templates

#26513 [iOS] Use a GeneralWrapperView for the EmptyView on CollectionView
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs
  src/Controls/src/Core/Handlers/Items/iOS/TemplateHelpers.cs
  src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs
  src/Controls/src/Core/Platform/iOS/GeneralWrapperView.cs
Labels: area-controls-collectionview, potential-regression

#25919 Fixed [iOS] Fix CarouselViewRemoveAt so that it's passing on both CV1 and CV2 sets of handlers
  src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs
  src/Controls/tests/TestCases.HostApp/Issues/CarouselViewRemoveAt.cs
Labels: area-controls-collectionview, community ✨, partner/syncfusion

#26492 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 41
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2499.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2948.cs
Labels: area-testing, community ✨, partner/syncfusion

#26542 [ci] Fix provision on templates stage
  eng/pipelines/common/maui-templates-steps.yml
  eng/pipelines/common/maui-templates.yml
  eng/pipelines/handlers.yml
Labels: area-infrastructure, testing-infrastructure

#26535 [iOS] Moved GeneralWrapperView from Controls to Core
  src/Core/src/Platform/iOS/GeneralWrapperView.cs
Labels: area-architecture, community ✨

#22676 Fix BindingAdapterPosition Exception
  src/Controls/src/Core/Handlers/Items/Android/Adapters/SelectableItemsViewAdapter.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue22674.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue22674.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22674.cs
Labels: area-controls-collectionview, community ✨

#25230 Make Style nullable
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/StyleableElement/StyleableElement.cs
Labels: area-xaml, community ✨

#26512 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 42
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla40704.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue774.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla32801.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla40704.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue774.cs
Labels: area-testing, community ✨, partner/syncfusion

#26437 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 37
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue8308.xaml
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue8308.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue9686.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue9711.cs
Labels: area-testing, community ✨, partner/syncfusion

#26543 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 43
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue11244.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/ShellFlyoutContentOffset.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue11244.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/ShellFlyoutContentOffset.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/ShellFlyoutContentWithZeroMargin.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/ShellGestures.cs
Labels: area-testing, community ✨, partner/syncfusion

#26490 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 39
  src/Controls/tests/TestCases.HostApp/Elements/ContactsPage.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue1557.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue1763.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla45743.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue1557.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue1763.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue5470.cs
Labels: area-testing, community ✨, partner/syncfusion

#26552 [tests] Skip some tests that are failing
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18896.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/FlyoutBehaviorShell.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue8461.cs
Labels: area-testing, testing-flakiness, testing-green-ci

#25370 [iOS] Fix for Single item alignment issue in CollectionView HorizontalGrid Layout
  src/Controls/src/Core/Handlers/Items/iOS/GridViewLayout.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/SingleItemAlignmentInCollectionViewHorizontalGridLayout.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue25181.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25181.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25181.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/SingleItemAlignmentInCollectionViewHorizontalGridLayout.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/SingleItemAlignmentInCollectionViewHorizontalGridLayout.png
Labels: platform/iOS 🍎, area-controls-collectionview, community ✨, partner/syncfusion

#26022 [iOS] Fixed HeaderFooterGrid to pass on CV1 and CV2
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs
  src/Controls/tests/TestCases.HostApp/Elements/CollectionView/HeaderFooterGalleries/HeaderFooterGrid.xaml
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/HeaderFooterGridWorks.png
Labels: platform/iOS 🍎, area-controls-collectionview, community ✨, partner/syncfusion

#25960 Border.Shadow hide the collectionView Header/footer -UITest
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/HeaderAndFooterShouldBeVisible.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue19338.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue19338.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19338.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/HeaderAndFooterShouldBeVisible.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/HeaderAndFooterShouldBeVisible.png
Labels: area-controls-collectionview, community ✨, area-controls-border

#26564 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 45
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla34912.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue11381.xaml
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla34912.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue11381.cs
Labels: area-testing, community ✨, partner/syncfusion

#26561 Invert SourceRect width/height on orientation change for ActionSheet
  src/Controls/src/Core/Platform/AlertManager/AlertManager.iOS.cs
Labels: platform/iOS 🍎, community ✨, area-controls-dialogalert

#26563 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 44
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue3840.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue55555.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue3292.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue3840.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue55555.cs
Labels: area-testing, community ✨, partner/syncfusion

#26325 Fix for Picker ItemsSource changed case exception: Value does not fall within the expected range
  src/Controls/tests/TestCases.HostApp/Issues/Issue25792.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25792.cs
  src/Core/src/Handlers/Picker/PickerHandler.Windows.cs
Labels: platform/windows 🪟, community ✨, area-controls-picker, partner/syncfusion

#26570 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 46
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue2951Test.png
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue4138.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue10608.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue11523.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue1414.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2951.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue4138.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue7167.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/Issue2951Test.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue2951Test.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/TitleIconIsCentered.png
Labels: area-testing, community ✨, partner/syncfusion

#25989 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 14
  src/Controls/tests/TestCases.HostApp/Issues/Issue9006.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue1023.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue1023.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue9006.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue1023_Forms.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue6127.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing, community ✨, partner/syncfusion

#26642 Fix Android Shell Navigation not properly waiting for end of transaction
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRendererBase.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla42329.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue12211.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23158.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25436.cs
Labels: community ✨

#26651 [Testing] Fix flaky Bugzilla32801 test by using unique AutomationId
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla32801.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla32801.cs
Labels: area-testing, community ✨, partner/syncfusion

#26621 [testing] Try make tests more stable
  src/Compatibility/ControlGallery/src/Issues.Shared/Bugzilla32801.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18452.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20903.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue7803.cs
Labels: area-testing, testing-flakiness, testing-green-ci

#21736 [iOS] CollectionView item sizing wrong after refresh
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewLayout.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/RefreshShouldNotChangeSize.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue20443.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue20443.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20443.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/RefreshShouldNotChangeSize.png
Labels: platform/iOS 🍎, area-controls-collectionview, community ✨

#26359 [XC] Add support for DoesNotInheritDataTypeAttribute to XamlC
  src/Controls/src/Build.Tasks/SetPropertiesVisitor.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui23989.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui25935.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui25935.xaml.cs
Labels: area-xaml

#25744 Revamp new project template build/test script
  .gitignore
  src/Templates/README.md
  src/Templates/build.ps1
  src/Templates/eng/utils.ps1
Labels: t/housekeeping ♻︎, area-templates

#26637 Shadows & Gradients don't work with a list view's header/footer - fix
  src/Controls/src/Core/Compatibility/Handlers/ListView/Android/ListViewRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/ListView/iOS/ListViewRenderer.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/GradientAndShadowShouldWork.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue26636.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue26636.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26636.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/GradientAndShadowShouldWork.png
Labels: platform/android 🤖, platform/iOS 🍎, community ✨, area-controls-listview

#22574 Fix navigation stuck on iOS when pushing on hidden tab section in TabBar
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue22570.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue22570.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22570.cs
Labels: area-navigation, platform/iOS 🍎, community ✨

#26607 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 48
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue2272.cs
  src/Controls/tests/TestCases.HostApp/Resources/Images/cartman.xml
  src/Controls/tests/TestCases.HostApp/Resources/Images/error.xml
  src/Controls/tests/TestCases.HostApp/Resources/Images/heart.xml
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla43663.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla44044.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla47923.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2272.cs
Labels: area-testing, community ✨, partner/syncfusion

#26491 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 40
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/ShellFlyoutSizing.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/ShellSearchHandlerItemSizing.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/ShellTitleView.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/ShellFlyoutSizing.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/ShellItemIsVisible.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/ShellSearchHandlerItemSizing.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/ShellTitleView.cs
Labels: area-testing, community ✨, partner/syncfusion

#25096 Add properties for device tests to configure release/debug
  eng/pipelines/common/device-tests-steps.yml
  eng/pipelines/common/device-tests.yml
  eng/pipelines/device-tests.yml
Labels: area-infrastructure

#26657 [Testing] Extension for finding any element & test-7167 fix
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue7167.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing, community ✨

#26609 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 49
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla31602.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla32902.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/ShellInsets.cs
  src/Controls/tests/TestCases.HostApp/Resources/Images/menu_icon.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla31602.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla32902.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/ShellInsets.cs
Labels: area-testing, community ✨, partner/syncfusion

#26557 [ci] Enable source index
  NuGet.config
  eng/pipelines/azure-pipelines-internal.yml
  eng/pipelines/azure-pipelines-public.yml
  eng/pipelines/common/build-test-pack.yml
  global.json
Labels: area-infrastructure, t/docs 📝

#25852 Fixed Net 8: Page and control Unloaded events firing on iOS when navigating to another page
  src/Controls/tests/TestCases.HostApp/Issues/Issue21916.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21916.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/Shell_Issue21916.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Shell_Issue21916.png
  src/Core/src/Platform/iOS/ViewExtensions.cs
Labels: area-navigation, platform/iOS 🍎, community ✨, partner/syncfusion

#25471 [Android] Added a scroll bar for collection view
  src/Controls/src/Core/Handlers/Items/Android/MauiRecyclerView.cs
  src/Controls/src/Core/Handlers/Items/ItemsViewHandler.Android.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CollectionViewShouldHaveScrollBar.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue25468.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25468.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25468.cs
  src/Core/src/Platform/Android/Resources/values/styles.xml
Labels: platform/android 🤖, area-controls-collectionview, community ✨

#26501 [Android] Fix for Softkeyboard Return key of an Entry control shows Done when the property ReturnType is set to Next
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyInitialEntryReturnTypeChange.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21109.cs
  src/Core/src/Handlers/Entry/EntryHandler.Android.cs
  src/Core/src/Platform/Android/EditTextExtensions.cs
Labels: community ✨, area-controls-entry, partner/syncfusion

#26685 Revert "[Windows] `FileSystem.Current.AppDataDirectory` returns different path after updating to latest version - fix"
  src/Essentials/src/FileSystem/FileSystem.uwp.cs
Labels: t/breaking 💥, area-essentials, needs-breaking-change-doc-created

#25567 Fixed [Windows] MAUI Entry in Windows always shows ClearButton despite ClearButtonVisibility set to 'Never'
  src/Controls/tests/TestCases.HostApp/Issues/Issue25473.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25473.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25473.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifyEntryClearButtonVisibilitySetToNever.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifyEntryClearButtonVisibilitySetToWhileEditing.png
  src/Core/src/Platform/Windows/MauiTextBox.cs
Labels: platform/windows 🪟, community ✨, area-controls-entry, partner/syncfusion

#26697 [ci] Update global.json
  global.json
Labels: area-infrastructure

#26676 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 54
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla32148.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla23942.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla25662.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla25979.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla29363.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla29453.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla31395.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla31688.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla32148.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla32206.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla32462.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla32615.cs
Labels: area-testing, community ✨, partner/syncfusion

#26665 The fix for child FlexLayout content appearing no longer works starting from version 8.0.61
  src/Controls/src/Core/Layout/FlexLayout.cs
  src/Controls/src/Core/LegacyLayouts/FlexLayout.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ChildFlexLayoutContentShouldAppear.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue23491.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23491.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ChildFlexLayoutContentShouldAppear.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ChildFlexLayoutContentShouldAppear.png
  src/Core/src/Layouts/Flex.cs
Labels: community ✨, partner/syncfusion

#26684 [ci] Update stable Android version
  eng/Versions.props
Labels: area-infrastructure

#26729 [ci] Always install .net
  eng/configure-toolset.ps1
  eng/configure-toolset.sh
Labels: area-infrastructure

#24001 [Mac Catalyst] Set window dimensions
  src/Core/src/Handlers/Window/WindowHandler.iOS.cs
  src/Core/src/Hosting/LifecycleEvents/AppHostBuilderExtensions.iOS.cs
  src/Core/src/Platform/iOS/WindowExtensions.cs
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
Labels: platform/macOS 🍏, p/1, community ✨, area-controls-window

#26675 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 53
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla36703.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla32898.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla33870.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla34007.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla35127.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla35472.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla35477.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla36559.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla36703.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla36780.cs
Labels: area-testing, community ✨, partner/syncfusion

#26656 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 51
  src/Controls/tests/TestCases.HostApp/Elements/CollectionView/ScrollToGalleries/ScrollToGroup.xaml
  src/Controls/tests/TestCases.HostApp/Elements/RadioButtonGalleries/TemplateFromStyle.xaml
  src/Controls/tests/TestCases.HostApp/Elements/RadioButtonGalleries/TemplateFromStyle.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue5793.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue6609.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/NestedCollectionViews.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/RadioButtonTemplateFromStyle.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/ScrollToGroup.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla30317.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue5793.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue6609.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/NestedCollectionView.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/RadioButtonTemplateFromStyle.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/ScrollToGroup.cs
Labels: area-testing, community ✨, partner/syncfusion

#26680 [iOS] Set height for EmptyView if is not an IView
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs
  src/Controls/tests/TestCases.HostApp/Elements/CollectionView/CollectionViewCoreGalleryPage.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/CollectionView/CollectionViewUITests.EmptyView.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25551.cs
Labels: area-controls-collectionview, i/regression

#20510 [iOS] Shell toolbar items
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ToolbarItemsShouldWork.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue18946.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue18946.xaml.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ToolbarItemsShouldWork.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18946.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ToolbarItemsShouldWork.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ToolbarItemsShouldBeVisible.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ToolbarItemsShouldWork.png
Labels: platform/iOS 🍎, area-controls-shell, community ✨

#26631 Enabled DropEventCoordinates test for mobile platforms
  src/Controls/tests/TestCases.Shared.Tests/Tests/DragAndDropUITests.cs
Labels: area-testing, community ✨, partner/syncfusion

#26750 Fix push maestro
  eng/pipelines/maui-release.yml
Labels: area-infrastructure

#26623 [ci] Add unit test jobs to dnceng builds
  eng/pipelines/arcade/setup-test-env.yml
  eng/pipelines/arcade/stage-pack.yml
  eng/pipelines/arcade/stage-unit-tests.yml
  eng/pipelines/arcade/variables.yml
  eng/pipelines/azure-pipelines-internal.yml
  eng/pipelines/azure-pipelines-public.yml
  eng/pipelines/common/build-test-pack.yml
  eng/pipelines/common/fail-on-issue.yml
  eng/pipelines/common/maui-templates-steps.yml
  eng/pipelines/common/maui-templates.yml
  eng/pipelines/common/provision.yml
  eng/pipelines/common/run-dotnet-preview.yml
  eng/pipelines/common/setup-jdk.yml
  eng/pipelines/common/variables.yml
Labels: area-testing

#26716 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 56
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla51238.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla51503.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla51825.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla52533.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla53179.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla53179_1.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla53179_2.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla53445.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla55365.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla55745.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla55912.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla57717.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla57749.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla57758.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla58645.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla58779.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla59097.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla59718.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla59863_0.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla59863_1.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla59863_2.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla59896.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla60045.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla60123.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla60524.cs
Labels: area-testing, community ✨, partner/syncfusion

#26753 [ci] Fix sourceindex stage
  eng/pipelines/azure-pipelines-internal.yml
  eng/pipelines/azure-pipelines-public.yml
  eng/pipelines/common/variables.yml
Labels: area-infrastructure

#26748 [testing] Fix tests on Mac
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ChildFlexLayoutContentShouldAppear.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/ImageButtonUITests.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/ImageUITests.cs
Labels: area-testing, testing-green-ci

#26735 [Windows] Fix titlebar not being added to modals
  src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.Windows.cs
  src/Core/src/Platform/Windows/WindowRootView.cs
Labels: platform/windows 🪟, area-controls-titlebar

#25870 Fix android image loading race condition and improve logging
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRendererBase.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ImageDoesNotDisappearWhenSwitchingTab.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue14587.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue14587.cs
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformInterop.java
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformLogger.java
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/GlideLogging.java
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/MauiCustomTarget.java
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/MauiCustomViewTarget.java
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/MauiGlideModule.java
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/MauiTarget.java
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/font/FontModel.java
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/font/FontModelResourceDecoder.java
  src/Core/AndroidNative/maui/src/main/res/values/ids.xml
  src/Core/src/Platform/Android/FragmentManagerExtensions.cs
  src/Core/src/maui.aar
  src/Core/tests/DeviceTests/Handlers/Image/ImageHandlerTests.Android.cs
  src/Core/tests/DeviceTests/Services/ImageSource/FontImageSourceServiceTests.Android.cs
Labels: platform/android 🤖, area-image, community ✨

#26731 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 59
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla39636.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla39668.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla39702.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla39821.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla41205.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla41415.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla41619.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla42277.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla43519.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla45702.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla46458.cs
Labels: area-testing, community ✨, partner/syncfusion

#26722 [Windows] Optimize `LayoutHandler.Windows.cs` (take 3)
  eng/BannedSymbols.txt
  src/Compatibility/Core/src/Windows/ButtonRenderer.cs
  src/Compatibility/Core/src/Windows/EditorRenderer.cs
  src/Compatibility/Core/src/Windows/EntryRenderer.cs
  src/Compatibility/Core/src/Windows/FormsButton.cs
  src/Compatibility/Core/src/Windows/LayoutRenderer.cs
  src/Compatibility/Core/src/Windows/Platform.cs
  src/Compatibility/Core/src/Windows/TabbedPageRenderer.cs
  src/Compatibility/Core/src/Windows/VisualElementPackager.cs
  src/Compatibility/Core/src/Windows/VisualElementRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/Windows/VisualElementRenderer.cs
  src/Controls/src/Core/Handlers/Shell/Windows/ShellSplitView.cs
  src/Controls/src/Core/Handlers/Shell/Windows/ViewToHandlerConverter.cs
  src/Controls/src/Core/Platform/AlertManager/ActionSheetDialog.Windows.cs
  src/Controls/src/Core/Platform/AlertManager/PromptDialog.Windows.cs
  src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs
  src/Controls/tests/DeviceTests/Controls.DeviceTests.csproj
  src/Core/src/Handlers/Border/BorderHandler.Windows.cs
  src/Core/src/Handlers/ContentView/ContentViewHandler.Windows.cs
  src/Core/src/Handlers/Layout/LayoutHandler.Windows.cs
  src/Core/src/Handlers/ScrollView/ScrollViewHandler.Windows.cs
  src/Core/src/Handlers/View/ViewHandlerOfT.Windows.cs
  src/Core/src/Handlers/Window/WindowHandler.Windows.cs
  src/Core/src/Platform/Windows/ButtonExtensions.cs
  src/Core/src/Platform/Windows/ContentPanel.cs
  src/Core/src/Platform/Windows/LayoutPanel.cs
  src/Core/src/Platform/Windows/MauiButton.cs
  src/Core/src/Platform/Windows/MauiPanel.cs
  src/Core/src/Platform/Windows/RootNavigationView.cs
  src/Core/src/Platform/Windows/RootPanel.cs
  src/Core/src/Platform/Windows/WindowRootViewContainer.cs
  src/Core/src/Platform/Windows/WrapperView.cs
  src/Core/tests/DeviceTests/Core.DeviceTests.csproj
Labels: area-layout, community ✨

#26783 [Testing] Fix for flaky tests and Improve stability of screenshot comparisons tests on Catalyst
  src/Controls/tests/TestCases.Shared.Tests/Tests/ImageButtonUITests.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/ImageUITests.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue3276.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue7167.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/ShellInsets.cs
  src/Controls/tests/TestCases.Shared.Tests/UITest.cs
  src/Controls/tests/TestCases.Shared.Tests/ViewContainers/StateViewContainerRemote.cs
Labels: area-testing, community ✨, partner/syncfusion

#26755 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 60
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla35733.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla36009.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla41600.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla57674.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla31366.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla35733.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla36009.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla38989.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla41600.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla44476.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla57674.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue3809.cs
Labels: area-testing, community ✨, partner/syncfusion

#26674 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 52
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue7823TestIsClippedIssue.png
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla44166.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue5503.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue7823.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/StackLayoutIssue.cs
  src/Controls/tests/TestCases.HostApp/Platforms/MacCatalyst/AppDelegate.cs
  src/Controls/tests/TestCases.HostApp/Platforms/iOS/AppDelegate.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla31114.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla44166.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue5503.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue7823.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/StackLayoutIssue.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ToggleAppearanceApiBackgroundColorListView.png
Labels: area-testing, community ✨, partner/syncfusion

#26761 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 61
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/AllScreenIsBlack.png
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla36955.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla40092.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla41415.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue2818.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue5132.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/AllScreenIsBlack.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla36955.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla40092.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla41415.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2818.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue5132.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/AllScreenIsBlack.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/AllScreenIsBlack.png
Labels: area-testing, community ✨, partner/syncfusion

#26828 Update Versions.props 9.0.22 branding
  eng/Versions.props
Labels: area-infrastructure

#26717 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 57
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Bugzilla29128Test.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Bugzilla36802Test.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Bugzilla53834Test.png
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla38723.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Bugzilla29128Test.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Bugzilla36802Test.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Bugzilla53834Test.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla29128.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla33612.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla36802.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla37462.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla38112.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla38723.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla39489.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla53834.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/Bugzilla53834Test.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Bugzilla29128Test.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Bugzilla36802Test.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Bugzilla53834Test.png
Labels: area-testing, community ✨, partner/syncfusion

#26743 [macOS] Remove unused `FilePicker.macos.cs`
  src/Essentials/src/FilePicker/FilePicker.macos.cs
Labels: platform/macOS 🍏, community ✨, area-controls-picker

#26710 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 55
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue11214.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Unreported1.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue11214.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue7556.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/LabelTextType.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Unreported1.cs
Labels: area-testing, community ✨, partner/syncfusion

#26806 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 63
  src/Controls/tests/TestCases.HostApp/Issues/CarouselViewAdjustPeekAreaInsets.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue13436.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue13436.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/CarouselViewUITests.AdjustPeekAreaInsets.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/CollectionViewUITests.CollectionViewTabbedPage.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue13436.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue13476.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue9419.cs
Labels: area-testing, community ✨, partner/syncfusion

#26830 [Testing] Fix for flaky test and Improve stability of the VisitAndUpdateItemsSource UITests
  src/Controls/tests/TestCases.Shared.Tests/Tests/CollectionView/CollectionViewUITests.VisitAndUpdateItemsSource.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/CollectionView/CollectionViewUITests.cs
Labels: area-testing, community ✨, partner/syncfusion

#26763 Simplify iOS ScrollView
  src/Controls/src/Core/Handlers/Items2/ItemsViewHandler2.iOS.cs
  src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewController2.cs
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/tests/DeviceTests/Elements/ContentView/ContentViewTests.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/NoScrollbarsTest.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue26629.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issues17801.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issues17801.xaml.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/NoScrollbarsTest.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/CollectionView/CollectionViewUITests.HeaderAndFooter.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26629.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/NoScrollbarsTest.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/NoScrollbarsTest.png
  src/Core/src/Handlers/ScrollView/ScrollViewHandler.iOS.cs
  src/Core/src/Platform/iOS/MauiScrollView.cs
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/tests/DeviceTests/Handlers/ScrollView/ScrollViewHandlerTests.iOS.cs
Labels: p/1, community ✨, area-controls-scrollview

#26613 [Windows] Fix for Exception occurring when using the GroupShortNameBinding in a Grouped ListView
  src/Controls/src/Core/Compatibility/Handlers/ListView/Windows/ListViewStyles.xaml
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue26534.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue26534.cs
Labels: community ✨, area-controls-listview, partner/syncfusion

#26829 [Testing] Enable Catalyst UI Tests with Screenshot Verification
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/CollectionViewAddGroupWhenViewIsEmpty.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/CollectionViewDuplicateViewsWhenAddItemToGroup.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/CollectionViewMeasureFirstItem.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/CollectionViewSingleItemAlignmentWithFooter.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/EntryClearButtonColorShouldMatchTextColor.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/FlyoutMenuShouldNotDisappearWhenNavigateUsingServices.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/LabelHyperlinkUnderlineColor.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/NavigationPageTitle.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/SingleItemAlignmentInCollectionViewHorizontalGridLayout.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ValidateFrameOffsets.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyButtonText.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyDynamicEditorScaling.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyGreyShades.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyLabelTextColorWhenResettingFromFormattedText.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyTextDecorationAppliedProperly.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue15196.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue16967.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18235.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19152.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19859.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21325.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23333.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23488.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24516.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25181.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25191.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25436.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25581.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue5669.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue17969.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue21728.cs
Labels: area-testing, community ✨, partner/syncfusion

#26823 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 64
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla57114.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla60122.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue11132.cs
  src/Controls/tests/TestCases.HostApp/MauiProgram.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla57114.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla60122.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue11132.cs
Labels: area-testing, community ✨, partner/syncfusion

#26805 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 62
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue3524.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla44461.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla56298.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla57515.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla59172.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2470.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue3524.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Bugzilla56298Test.png
Labels: area-testing, community ✨, partner/syncfusion

#26873 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 65
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla37625.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla45125.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue5412.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla30317.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla37625.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla45125.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue1414.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue5412.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue7290.cs
Labels: area-testing, community ✨, partner/syncfusion
