Repository dotnet/maui, pull requests merged in 2024-10, with the labels that each got.

#25016 Remove excessive Picker API comment
  src/Controls/docs/Microsoft.Maui.Controls/Picker.xml
Labels: area-docs, t/housekeeping ♻︎

#24859 [iOS] Text alignment in editor - improvements
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/TextsInEditorsAfterScaling.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/TextsInEditorsBeforeScaling.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue24583.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue24583.xaml
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24583.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/TextsInEditorsAfterScaling.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/TextsInEditorsBeforeScaling.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/TextsInEditorsAfterScaling.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/TextsInEditorsBeforeScaling.png
  src/Core/src/Platform/iOS/MauiTextView.cs
Labels: platform/iOS 🍎, community ✨, area-controls-editor

#24934 [UITesting] Moved ButtonHandler.ImageSourceInitializesCorrectly to Appium
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ImageSourceInitializesCorrectly.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue24916.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue24916.xaml.cs
  src/Controls/tests/TestCases.HostApp/Resources/Images/blue.png
  src/Controls/tests/TestCases.HostApp/Resources/Images/green.png
  src/Controls/tests/TestCases.HostApp/Resources/Images/red.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24916.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ImageSourceInitializesCorrectly.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ImageSourceInitializesCorrectly.png
  src/Core/tests/DeviceTests/Handlers/Button/ButtonHandlerTests.cs
  src/Core/tests/DeviceTests/Handlers/ImageButton/ImageButtonHandlerTests.cs
Labels: t/housekeeping ♻︎, community ✨

#25015 Update the Benchmarks.Droid app to use built in Android GetExternalFilesDir
  src/Core/tests/Benchmarks.Droid/MainInstrumentation.cs
Labels: community ✨

#24952 Move HybridWebView platform code to handlers (attempt 2)
  src/Controls/src/Core/HybridWebView/HybridWebView.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/WebView/WebView.cs
  src/Controls/tests/DeviceTests/Elements/HybridWebView/HybridWebViewTests.cs
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/HybridJavaScriptInterface.java
  src/Core/src/Core.csproj
  src/Core/src/Core/IHybridWebView.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.Android.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.Windows.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.iOS.cs
  src/Core/src/Handlers/HybridWebView/IHybridWebViewTaskManager.cs
  src/Core/src/Primitives/HybridWebViewInvokeJavaScriptRequest.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Core/src/maui.aar
Labels: area-controls-hybridwebview

#25042 Change HybridWebView default address to 0.0.0.1
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.cs
Labels: area-controls-hybridwebview

#25047 Add services.AddHybridWebViewDeveloperTools() extension to enable browser dev tools
  src/Controls/samples/Controls.Sample/MauiProgram.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.Android.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.Windows.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.iOS.cs
  src/Core/src/Hosting/HybridWebViewDeveloperTools.cs
  src/Core/src/Hosting/HybridWebViewServiceCollectionExtensions.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
Labels: area-controls-hybridwebview

#24970 [iOS] Fix NRE in Shell SearchHandlerAppearanceTracker
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/SearchHandlerAppearanceTracker.cs
Labels: community ✨

#25039 Remove Drag and Drop Tests from Catalyst
  src/Controls/tests/TestCases.Shared.Tests/Tests/DragAndDropUITests.cs
Labels: area-testing, testing-flakiness

#24817 [housekeeping] Update & Consolidate Appium + driver versions
  eng/Versions.props
  eng/scripts/appium-install.ps1
Labels: t/housekeeping ♻︎, area/infrastructure 🏗️

#25028 [net9.0] Merge release rc2 to net9.0
  .gitignore
  Directory.Build.props
  Directory.Build.targets
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/core-templates/job/source-index-stage1.yml
  eng/common/core-templates/steps/publish-logs.yml
  eng/common/core-templates/steps/source-index-stage1-publish.yml
  eng/common/cross/build-rootfs.sh
  eng/common/template-guidance.md
  eng/common/templates-official/steps/source-index-stage1-publish.yml
  eng/common/templates/steps/source-index-stage1-publish.yml
  eng/pipelines/common/device-tests-steps.yml
  eng/pipelines/common/provision.yml
  eng/pipelines/common/variables.yml
  eng/pipelines/device-tests.yml
  eng/pipelines/maui-release.yml
  eng/pipelines/ui-tests.yml
  eng/provisioning/provisioning.csx
  global.json
  src/Compatibility/ControlGallery/src/WinUI/Compatibility.ControlGallery.WinUI.csproj
  src/Controls/samples/Controls.Sample.Embedding/Platforms/MacCatalyst/NewTaskSceneDelegate.cs
  src/Controls/src/Core/Handlers/Items/iOS/ObservableItemsSource.cs
  src/Controls/src/Core/Handlers/Items2/CarouselViewHandler2.iOS.cs
  src/Controls/src/Core/Handlers/Items2/ItemsViewHandler2.iOS.cs
  src/Controls/src/Core/Handlers/Items2/iOS/CarouselViewController2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewController2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/LoopListSource2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/LoopObservableItemsSource2.cs
  src/Controls/tests/TestCases.HostApp/Elements/CarouselViewCoreGalleryPage.xaml
  src/Controls/tests/TestCases.HostApp/Issues/CarouselViewLoopNoFreeze.cs
  src/Controls/tests/TestCases.HostApp/Issues/CarouselViewRemoveAt.cs
  src/Controls/tests/TestCases.HostApp/MauiProgram.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/CarouselViewUITests.LoopNoFreeze.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/CarouselViewUITests.RemoveAt.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue10234.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue17283.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22035.cs
  src/Core/src/Fonts/EmbeddedFontLoader.iOS.cs
  src/DotNet/DotNet.csproj
  src/Graphics/samples/GraphicsTester.Mac/MainWindow.cs
  src/Graphics/samples/GraphicsTester.Skia.Mac/MainWindow.cs
  src/Graphics/samples/GraphicsTester.WinUI.Desktop/GraphicsTester.WinUI.Desktop.csproj
Labels: t/housekeeping ♻︎

#24998 (Re)enable Mail API for Mac Catalyst
  src/Essentials/samples/Samples/View/EmailPage.xaml
  src/Essentials/samples/Samples/ViewModel/EmailViewModel.cs
  src/Essentials/src/Email/Email.ios.cs
Labels: platform/macOS 🍏, area-essentials

#25024 Adding tests (disabled) from Control Gallery to Appium
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla33578.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla33612.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla33870.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla34632.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla34912.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla36955.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla37462.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla37841.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla38112.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla38731.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla33578.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla33612.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla33870.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla34632.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla34912.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla36955.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla37462.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla37841.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla38112.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla38731.cs
Labels: t/housekeeping ♻︎, area-testing, testing-legacy-ui-tests

#22854 [X] allow namescope resolution before parenting
  src/Controls/src/Build.Tasks/SetNamescopesAndRegisterNamesVisitor.cs
  src/Controls/src/Core/Element/Element.cs
  src/Controls/src/Xaml/CreateValuesVisitor.cs
  src/Controls/tests/Xaml.UnitTests/Controls.Xaml.UnitTests.csproj
  src/Controls/tests/Xaml.UnitTests/Issues/Maui16208.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui16208.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui22001.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui22001.xaml.cs
Labels: area-xaml

#25078 [tests] CV 2 devicetests
  src/Controls/src/Core/Handlers/Items2/ItemsViewHandler2.iOS.cs
  src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewController2.cs
  src/Core/tests/DeviceTests.Shared/MauiProgramDefaults.cs
Labels: area-testing

#25076 [net9.0] Fix CV2 handler and uitests fixes
  src/Controls/src/Core/Handlers/Items2/CollectionViewHandler2.iOS.cs
  src/Controls/src/Core/Handlers/Items2/iOS/GroupableItemsViewController2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/StructuredItemsViewController2.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21967.cs
Labels: area-testing

#25105 Remove excessive DataTemplateSelector API comments
  src/Controls/docs/Microsoft.Maui.Controls/DataTemplateSelector.xml
Labels: area-docs, t/housekeeping ♻︎, community ✨

#25125 Disable TitleViewSetOnShellWorksAfterNavigation on Device Tests
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.cs
Labels: area-testing

#24944 Adding tests (disabled) from Control Gallery to Appium
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla30353.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla31114.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla31330.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla31333.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla31602.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla32040.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla32148.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla32462.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla32801.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla32902.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla30353.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla31114.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla31330.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla31333.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla31602.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla32040.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla32148.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla32462.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla32801.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla32902.cs
Labels: t/housekeeping ♻︎, area-testing, testing-legacy-ui-tests

#24943 First tests (disabled) from Control Gallery to Appium
  src/Controls/src/Core/Properties/AssemblyInfo.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla21177.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla25662.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla25979.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla26171.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla26233.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla26501.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla27731.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla28001.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla30317.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla30324.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla21177.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla25662.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla25979.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla26171.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla26233.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla26501.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla27731.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla28001.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla30317.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla30324.cs
Labels: t/housekeeping ♻︎, area-testing, testing-legacy-ui-tests

#24919 Fix for Windows SearchBar MaxLength > 0 not working properly.
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/SearchBarMaxLength.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue5669.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue5669.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue5669.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/SearchBarMaxLength.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/SearchBarMaxLength.png
  src/Core/src/Platform/Windows/SearchBarExtensions.cs
Labels: community ✨

#24830 CollectionView Header/Footer/EmptyView issues when adding/removing items.
  src/Controls/src/Core/Handlers/Items/Android/Adapters/AdapterNotifier.cs
  src/Controls/src/Core/Handlers/Items/Android/MauiRecyclerView.cs
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CollectionViewHeaderBlankWhenLastItemRemoved.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CollectionviewFooterHideswhenDynamicallyAddorRemoveItems.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue11896.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue11896.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue11896.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/CollectionViewHeaderBlankWhenLastItemRemoved.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/CollectionviewFooterHideswhenDynamicallyAddorRemoveItems.png
Labels: community ✨

#25006 Fixed Microsoft.Maui.Controls 8.0.90 (Latest stable) Ruins Entry Controls
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyEntryClearButtonVisibility.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue25038.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25038.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25038.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifyEntryClearButtonVisibility.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyEntryClearButtonVisibility.png
  src/Core/src/Platform/Windows/MauiTextBox.cs
Labels: platform/windows 🪟, community ✨, area-controls-entry

#25084 Fixed Button doesn't reset to "Normal" if scrolled quickly to the top in IOS
  src/Core/src/Handlers/Button/ButtonHandler.iOS.cs
Labels: platform/iOS 🍎, community ✨, area-controls-button

#25188 [testing] Comment out flaky test
  src/Controls/tests/Core.UnitTests/ShellModalTests.cs
Labels: area-testing, testing-reenable, testing-green-ci

#24990 Revert #24222 and simply use `invalidate` instead of `postInvalidate`
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformContentViewGroup.java
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformWrapperView.java
  src/Core/src/maui.aar
Labels: platform/android 🤖, community ✨

#25203 [housekeeping] Enable TSA upload
  eng/pipelines/maui-release.yml
Labels: t/housekeeping ♻︎

#25122 Fix Regression with iOS button resizing with text or image change
  src/Controls/src/Core/Button/Button.iOS.cs
  src/Controls/src/Core/Platform/iOS/Extensions/ButtonExtensions.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ButtonResizesWhenTitleOrImageChangesAltered.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ButtonResizesWhenTitleOrImageChangesOriginal.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ButtonTitleFillsSpaceWhenImageChangesAltered.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ButtonTitleFillsSpaceWhenImageChangesOriginal.png
  src/Controls/tests/TestCases.HostApp/Controls.TestCases.HostApp.csproj
  src/Controls/tests/TestCases.HostApp/Issues/Issue25074.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25074.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue25074_2.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25074_2.xaml.cs
  src/Controls/tests/TestCases.HostApp/Resources/Images/dotnet_bot_resized3.svg
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25074.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25074_2.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ButtonResizesWhenTitleOrImageChangesAltered.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ButtonResizesWhenTitleOrImageChangesOriginal.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ButtonTitleFillsSpaceWhenImageChangesAltered.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ButtonTitleFillsSpaceWhenImageChangesOriginal.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ButtonPaddingIsAddedWhenNeeded.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ButtonResizesWhenTitleOrImageChangesAltered.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ButtonResizesWhenTitleOrImageChangesOriginal.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ButtonTitleFillsSpaceWhenImageChangesAltered.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ButtonTitleFillsSpaceWhenImageChangesOriginal.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ButtonsLayoutResolveWhenParentSizeChangesSizeButtonsDownPortrait.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyButtonPage1_Border.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyButtonPage1_NoBorder.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyButtonPage4.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyButtonPage6.png
Labels: platform/iOS 🍎, area-controls-button

#25214 [release/8.0.1xx-sr9] Fix Regression with iOS button resizing with text or image change
  src/Controls/src/Core/Button/Button.iOS.cs
  src/Controls/src/Core/Platform/iOS/Extensions/ButtonExtensions.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ButtonResizesWhenTitleOrImageChangesAltered.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ButtonResizesWhenTitleOrImageChangesOriginal.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ButtonTitleFillsSpaceWhenImageChangesAltered.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ButtonTitleFillsSpaceWhenImageChangesOriginal.png
  src/Controls/tests/TestCases.HostApp/Controls.TestCases.HostApp.csproj
  src/Controls/tests/TestCases.HostApp/Issues/Issue25074.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25074.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue25074_2.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25074_2.xaml.cs
  src/Controls/tests/TestCases.HostApp/Resources/Images/dotnet_bot_resized3.svg
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25074.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25074_2.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ButtonResizesWhenTitleOrImageChangesAltered.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ButtonResizesWhenTitleOrImageChangesOriginal.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ButtonTitleFillsSpaceWhenImageChangesAltered.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ButtonTitleFillsSpaceWhenImageChangesOriginal.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ButtonPaddingIsAddedWhenNeeded.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ButtonResizesWhenTitleOrImageChangesAltered.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ButtonResizesWhenTitleOrImageChangesOriginal.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ButtonTitleFillsSpaceWhenImageChangesAltered.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ButtonTitleFillsSpaceWhenImageChangesOriginal.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ButtonsLayoutResolveWhenParentSizeChangesSizeButtonsDownPortrait.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyButtonPage1_Border.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyButtonPage1_NoBorder.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyButtonPage4.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyButtonPage6.png
Labels: platform/iOS 🍎, area-controls-button

#25241 [housekeeping] Fix ps1 script warnings
  eng/pipelines/common/pack.yml
  eng/pipelines/common/sign.yml
  eng/scripts/appium-install.ps1
  eng/scripts/update-version-props.ps1
Labels: t/housekeeping ♻︎

#25240 [housekeeping] Remove debug.keystore
  eng/debug.keystore
  src/Compatibility/ControlGallery/src/Android/Compatibility.ControlGallery.Android.csproj
Labels: t/housekeeping ♻︎

#25130 [Testing] Add UITest Stepper actions
  src/Controls/tests/TestCases.HostApp/Elements/StepperCoreGalleryPage.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/StepperUITests.cs
  src/Core/src/Platform/Windows/MauiStepper.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumAndroidStepperActions.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumIOSStepperActions.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumWindowsStepperActions.cs
  src/TestUtils/src/UITest.Appium/AppiumAndroidApp.cs
  src/TestUtils/src/UITest.Appium/AppiumIOSApp.cs
  src/TestUtils/src/UITest.Appium/AppiumWindowsApp.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing

#25171 [iOS]Resolved Button Text Resets to Previous Value When Set to Empty String Programmatically.
  src/Controls/src/Core/Platform/iOS/Extensions/ButtonExtensions.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyButtonText.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue18235.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue18235.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18235.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifyButtonText.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyButtonText.png
Labels: community ✨

#25242 [Testing] Navigate directly to control tests
  src/Controls/tests/TestCases.HostApp/CoreViews/CoreGalleryBasePage.cs
  src/Controls/tests/TestCases.HostApp/CoreViews/CorePageView.cs
Labels: area-testing

#25145 [Windows] Fixed VisualState Update for CollectionView SelectedItem
  src/Controls/src/Core/Handlers/Items/SelectableItemsViewHandler.Windows.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyCollectionViewVisualState.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue22104.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue22104.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22104.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifyCollectionViewVisualState.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyCollectionViewVisualState.png
Labels: platform/windows 🪟, area-controls-collectionview, community ✨

#25119 [Windows] Fix for the issue with Label text color when resetting from FormattedText.
  src/Controls/src/Core/Platform/Windows/Extensions/TextBlockExtensions.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyLabelTextColorWhenResettingFromFormattedText.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue24516.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue24516.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24516.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifyLabelTextColorWhenResettingFromFormattedText.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyLabelTextColorWhenResettingFromFormattedText.png
Labels: platform/windows 🪟, community ✨, area-controls-label

#25243 [Documentation] Fix TitleBar comment mistake
  src/Controls/src/Core/TitleBar/TitleBar.cs
Labels: area-docs

#25313 [Testing] Implement TouchAndHoldCoordinates method to UITests extension methods
  src/TestUtils/src/UITest.Appium/Actions/AppiumTouchActions.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing

#24276 [Windows] - Picker on windows shows "Microsoft.Maui.Controls.Picker" if ItemsSource has an empty string
  src/Controls/tests/TestCases.HostApp/Issues/Issues8845.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issues8845.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue8845.cs
  src/Core/src/Platform/Windows/PickerExtensions.cs
Labels: community ✨, area-controls-picker

#25303 Update templates for non-VS IDE hosts
  src/Templates/src/templates/maui-blazor-solution/.template.config/template.json
Labels: area-templates, community ✨

#25334 Update .NET MAUI template with .NET 9 hovercraft bot 🤖
  src/Templates/src/templates/maui-mobile/Resources/Images/dotnet_bot.png
Labels: area-templates

#24844 Speed-up Border rendering by avoiding useless pass during size allocation
  src/Controls/src/Core/Border/Border.cs
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/Handlers/Border/BorderHandler.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
Labels: platform/macOS 🍏, platform/windows 🪟, platform/android 🤖, platform/iOS 🍎, community ✨, t/perf

#25331 [net9.0] Run device tests arm
  eng/pipelines/common/device-tests-steps.yml
  eng/pipelines/common/provision.yml
  eng/pipelines/device-tests.yml
  eng/pipelines/handlers.yml
  eng/provisioning/provisioning.csx
  src/Essentials/test/DeviceTests/Tests/DeviceInfo_Tests.cs
Labels: do-not-merge

#25314 [Testing] Implement QueryUntilPresent method to UITest extension methods
  src/Controls/tests/TestCases.HostApp/Issues/Issue6286.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue6286.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing

#25312 [Testing] Implement Pan method to UITest extension methods
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla39530.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing

#25282 [Testing] Implement WaitForFirstElement method to UITest extension methods
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla51825.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing

#25177 [Testing] More UITests extension methods using an IQuery as parameter
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla32148.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla32148.cs
  src/Controls/tests/TestCases.Shared.Tests/UITestIgnoreAttributes.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing

#25420 [XC] Avoid NativeAOT trim warnings for compiled bindings
  src/Controls/src/Build.Tasks/SetPropertiesVisitor.cs
  src/Controls/src/Build.Tasks/XamlCTask.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui25406.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui25406.xaml.cs
  src/Controls/tests/Xaml.UnitTests/MockCompiler.cs
Labels: area-xaml

#25426 Set title on maui-blazor/-app template window
  src/Templates/src/templates/maui-blazor-solution/MauiApp.1/App.xaml.cs
  src/Templates/src/templates/maui-blazor/App.xaml.cs
Labels: area-blazor, area-templates

#25157 [ios,tests] Fix iOS Header with Group
  src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs
  src/Controls/src/Core/Handlers/Items2/CollectionViewHandler2.iOS.cs
  src/Controls/src/Core/Handlers/Items2/iOS/GroupableItemsViewController2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewController2.cs
  src/Controls/tests/TestCases.HostApp/Elements/CollectionView/CollectionViewCoreGalleryPage.cs
  src/Controls/tests/TestCases.HostApp/Elements/CollectionView/HeaderFooterGalleries/HeaderFooterTemplate.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue20443.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue20443.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/CollectionView/CollectionViewUITests.Grouping.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/CollectionView/CollectionViewUITests.HeaderAndFooter.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22104.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/CollectionViewHeaderBlankWhenLastItemRemoved.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/CollectionviewFooterHideswhenDynamicallyAddorRemoveItems.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/HeaderFooterGridHorizontalWorks.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/HeaderFooterGridWorks.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/HeaderFooterTemplateWorks.png
  src/Core/src/Platform/iOS/MauiView.cs
Labels: platform/iOS 🍎, area-controls-collectionview

#25077 HybridWebView: Invoke .NET methods from JavaScript
  docs/design/FeatureSwitches.md
  loc/cs/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/de/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/es/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/fr/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/it/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/ja/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/ko/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/pl/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/pt-BR/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/ru/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/tr/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/zh-Hans/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/zh-Hant/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  src/Controls/samples/Controls.Sample/Pages/Controls/HybridWebViewPage.xaml.cs
  src/Controls/samples/Controls.Sample/Resources/Raw/HybridSamplePage/index.html
  src/Controls/samples/Controls.Sample/Resources/Raw/HybridSamplePage/scripts/HybridWebView.js
  src/Controls/src/Build.Tasks/nuget/buildTransitive/netstandard2.0/Microsoft.Maui.Controls.targets
  src/Controls/src/Core/Hosting/AppHostBuilderExtensions.cs
  src/Controls/src/Core/HybridWebView/HybridWebView.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/tests/DeviceTests/Elements/HybridWebView/HybridWebViewTests.cs
  src/Controls/tests/DeviceTests/Resources/Raw/HybridTestRoot/invokedotnettests.html
  src/Controls/tests/DeviceTests/Resources/Raw/HybridTestRoot/scripts/HybridWebView.js
  src/Core/src/Core/IHybridWebView.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.Android.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.Windows.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.iOS.cs
  src/Core/src/Platform/Android/MauiHybridWebView.cs
  src/Core/src/Platform/Android/MauiHybridWebViewClient.cs
  src/Core/src/Platform/Windows/MauiHybridWebView.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Core/src/RuntimeFeature.cs
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/AOTTemplateTest.cs
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/Utilities/BuildWarningsUtilities.cs
Labels: area-controls-hybridwebview

#25367 [Android] Fixed CollectionView MeasureFirstItem Rendering issue
  src/Controls/src/Core/Handlers/Items/Android/ItemContentView.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CollectionViewMeasureFirstItem.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue25191.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25191.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25191.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/CollectionViewMeasureFirstItem.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/CollectionViewMeasureFirstItem.png
Labels: platform/android 🤖, area-controls-collectionview, community ✨

#25408 [testing] These Semantic tests seem to fail often on MacCatalyst
  src/Core/tests/DeviceTests.Shared/HandlerTests/HandlerTestBaseOfT.Tests.cs
Labels: area-testing, testing-flakiness, testing-green-ci

#25399 Remove excessive BoxView API comments
  src/Controls/docs/Microsoft.Maui.Controls/BoxView.xml
Labels: area-docs, community ✨

#25194 Background gradients fixes
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/BackgroundGradientsShouldRenderCorrectly.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue25193.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25193.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25193.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/BackgroundGradientsShouldRenderCorrectly.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/BackgroundGradientsShouldRenderCorrectly.png
  src/Core/src/Handlers/View/ViewHandler.iOS.cs
Labels: area-drawing, platform/iOS 🍎, community ✨

#25453 25421- ListViewRenderer Crash in HostApp and BindingError was occured in windows platforms
  src/Controls/src/Core/Compatibility/Handlers/ListView/Windows/ListViewRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/ListView/iOS/ListViewRenderer.cs
  src/Controls/tests/TestCases.HostApp/CoreViews/CorePageView.cs
Labels: platform/windows 🪟, platform/iOS 🍎, community ✨

#25494 Fixed Size not calculated properly when invoking UseMauiCompatibility method in MauiProgram
  src/Controls/src/Core/Hosting/AppHostBuilderExtensions.cs
Labels: community ✨, area-compatibility

#25507 Fixed UI Test Issue on Windows Platform in Visual Studio
  src/Controls/tests/TestCases.Shared.Tests/UITest.cs
Labels: community ✨

#25485 Fix Button Regression with null image source
  src/Controls/src/Core/Button/Button.iOS.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue25409.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25409.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25409.cs
Labels: platform/iOS 🍎, area-controls-button

#25339 [iOS] Fix for TextDecorations not updating after modifying Label text
  src/Controls/src/Core/Platform/iOS/Extensions/LabelExtensions.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyTextDecorationAppliedProperly.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue16967.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue16967.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue16967.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifyTextDecorationAppliedProperly.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyTextDecorationAppliedProperly.png
Labels: platform/iOS 🍎, community ✨, area-controls-label

#25549 Fix toggle for including sample content in template
  src/Templates/src/templates/maui-mobile/.template.config/dotnetcli.host.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.cs.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.de.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.en.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.es.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.fr.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.it.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.ja.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.ko.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.pl.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.pt-BR.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.ru.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.tr.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.zh-Hans.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.zh-Hant.json
  src/Templates/src/templates/maui-mobile/.template.config/template.json
  src/Templates/src/templates/maui-mobile/App.xaml
  src/Templates/src/templates/maui-mobile/AppShell.xaml
  src/Templates/src/templates/maui-mobile/AppShell.xaml.cs
  src/Templates/src/templates/maui-mobile/MauiApp.1.csproj
  src/Templates/src/templates/maui-mobile/MauiProgram.cs
  src/Templates/src/templates/maui-mobile/Resources/Styles/Colors.xaml
  src/Templates/src/templates/maui-mobile/Resources/Styles/Styles.xaml
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/SimpleTemplateTest.cs
Labels: t/bug, area-templates

#25561 iOS UIImpactFeedbackGenerator should be used on iOS 17.5 and up
  src/Essentials/src/HapticFeedback/HapticFeedback.ios.cs
Labels: t/housekeeping ♻︎, area-essentials

#25178 [Testing] Enabling ported UITests from Xamarin.UITests to Appium #1
  src/Controls/tests/TestCases.Android.Tests/Controls.TestCases.Android.Tests.csproj
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla21177.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla25979.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla26233.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla27731.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla28001.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla32462.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla33612.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla33870.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla38112.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla57749.cs
  src/Controls/tests/TestCases.Mac.Tests/Controls.TestCases.Mac.Tests.csproj
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla21177.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla25662.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla25979.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla26171.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla26233.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla26501.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla27731.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla28001.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla30317.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla32040.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla32148.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla32462.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla33612.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla33870.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla37462.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla38112.cs
  src/Controls/tests/TestCases.WinUI.Tests/Controls.TestCases.WinUI.Tests.csproj
  src/Controls/tests/TestCases.iOS.Tests/Controls.TestCases.iOS.Tests.csproj
  src/TestUtils/src/UITest.Appium/AppiumApp.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
  src/TestUtils/src/UITest.Core/IApp.cs
Labels: area-testing

#25568 [ci] Specify windows image
  eng/pipelines/common/ui-tests.yml
  eng/pipelines/ui-tests.yml
Labels: testing-infrastructure, testing-green-ci

#25586 [release/9.0.1xx] Bump Aspnet 8.0.10
  eng/Versions.props
Labels: area-infrastructure

#25559 [Testing] Added UITests method overrides allowing the use queries
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing

#25573 [Testing] Written UI test for the issue resolved in PR 25453
  src/Controls/tests/TestCases.HostApp/Issues/Issue25504.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25504.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue25504.cs
Labels: area-testing, community ✨

#25066 [Windows] Fixed TextCell Command executes only once
  src/Controls/src/Core/Compatibility/Handlers/ListView/Windows/CellControl.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue21112.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21112.cs
Labels: platform/windows 🪟, community ✨, area-controls-listview

#25611 Fix Button Regression with null image source (#25485)
  src/Controls/src/Core/Button/Button.iOS.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue25409.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25409.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25409.cs
Labels: t/bug, area-controls-button

#25605 [ci] Skip provisioning extra
  eng/pipelines/common/pack.yml
  eng/pipelines/common/provision.yml
  eng/pipelines/common/variables.yml
  eng/pipelines/handlers.yml
  eng/pipelines/maui-release.yml
  src/Core/src/maui.aar
Labels: area-infrastructure

#25569 [Testing] More Appium actions
  src/TestUtils/src/UITest.Appium/Actions/AppiumDeviceActions.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumGeneralActions.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumLifecycleActions.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing

#25316 [Testing] Implement Pinch gestures in UITest extensions methods
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla57515.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumPinchToZoomActions.cs
  src/TestUtils/src/UITest.Appium/AppiumApp.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing

#25616 [release/9.0.1xx] Update some versions for ga
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-infrastructure

#25613 Revert PR #23052 behavior under new app context switch
  src/Controls/src/Core/LegacyLayouts/Layout.cs
  src/Controls/src/Core/Page/Page.cs
  src/Controls/src/Core/VisualElement/VisualElement.cs
Labels: do-not-merge
