Repository dotnet/maui, pull requests merged in 2024-11, with the labels that each got.

#20501 [iOS] Frames' content update
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue19127.xaml
  src/Controls/samples/Controls.Sample.UITests/Issues/Issue19127.xaml.cs
  src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs
  src/Controls/tests/UITests/Tests/Issues/Issue19127.cs
Labels: platform/iOS 🍎, community ✨, area-controls-frame

#25640 [ci] Templates need xcodeselect
  eng/pipelines/common/maui-templates.yml
  eng/pipelines/common/provision.yml
Labels: area-infrastructure

#25164 For Android, respect Minimum/Maximum size requests even when size is set
  src/Controls/src/Core/Handlers/Items/Android/SizedItemContentView.cs
  src/Controls/tests/DeviceTests/Elements/Layout/LayoutTests.cs
  src/Core/src/Handlers/ScrollView/ScrollViewHandler.Android.cs
  src/Core/src/Handlers/ViewHandlerExtensions.Android.cs
  src/Core/src/Platform/Android/ContextExtensions.cs
Labels: area-layout, platform/android 🤖

#25685 Fix minor online API docs warnings
  src/Controls/src/Core/NavigableElement/NavigableElement.cs
  src/Controls/src/Core/VisualElement/VisualElement.cs
Labels: area-docs, t/housekeeping ♻︎

#25624 [Testing] Reenable test ported from Xamarin.UITest
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue3809.cs
Labels: t/housekeeping ♻︎, area-testing

#25700 Disable NSToolbar Tabs (#25137)
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellItemRenderer.cs
  src/Core/src/Platform/iOS/TabbedViewExtensions.cs
Labels: area-controls-tabbedpage

#21259 ImageButton border (BorderWidth) overlaps the image instead of adding space - fix
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/GradientImageButtonBackground.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ImageButtonAspectFitWorks.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ImageButtonUITests_BorderColor.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ImageButtonUITests_BorderColor_WithBackground.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ImageButtonUITests_BorderWidth.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ImageButtonUITests_BorderWidth_WithBackground.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ImageButtonUITests_CornerRadius.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ImageButtonUITests_CornerRadius_WithBackground.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue24856.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue24856.xaml.cs
  src/Controls/tests/TestCases.HostApp/Resources/Images/avatar.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24856.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ImageButtonUITests_BorderColor.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ImageButtonUITests_BorderColor_WithBackground.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ImageButtonUITests_BorderWidth.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ImageButtonUITests_BorderWidth_WithBackground.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ImageButtonUITests_CornerRadius.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ImageButtonUITests_CornerRadius_WithBackground.png
  src/Core/src/Handlers/ImageButton/ImageButtonHandler.Android.cs
  src/Core/src/Handlers/ImageButton/ImageButtonHandler.Tizen.cs
  src/Core/src/Handlers/ImageButton/ImageButtonHandler.Windows.cs
  src/Core/src/Handlers/ImageButton/ImageButtonHandler.iOS.cs
  src/Core/src/Platform/Android/ImageButtonExtensions.cs
  src/Core/src/Platform/iOS/ButtonExtensions.cs
Labels: community ✨, area-controls-border

#25542 [iOS] RadioButton throws CGContextSetLineWidth - Fix
  src/Core/src/Platform/iOS/MauiCALayer.cs
Labels: platform/iOS 🍎, community ✨, area-controls-radiobutton

#25731 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 2
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue13203.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue13916.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19283.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue13203.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue13916.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue8186.cs
Labels: area-testing, community ✨

#25719 Setup lane to run CV2 and CV1 tests
  eng/devices/ios.cake
  eng/pipelines/common/ui-tests-steps.yml
  eng/pipelines/common/ui-tests.yml
  src/Compatibility/ControlGallery/src/Issues.Shared/Issue12574.cs
  src/Controls/tests/TestCases.HostApp/CollectionViewHostBuilderExtentions.cs
  src/Controls/tests/TestCases.HostApp/Elements/CollectionView/HeaderFooterGalleries/HeaderFooterGrid.xaml
  src/Controls/tests/TestCases.HostApp/Elements/CollectionView/HeaderFooterGalleries/HeaderFooterGridHorizontal.xaml
  src/Controls/tests/TestCases.HostApp/Issues/CarouselViewLoopNoFreeze.cs
  src/Controls/tests/TestCases.HostApp/Issues/CarouselViewRemoveAt.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue11896.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue22035.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue22035.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue22035Page2.xaml
  src/Controls/tests/TestCases.HostApp/MauiProgram.cs
  src/Controls/tests/TestCases.Shared.Tests/UITest.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumLifecycleActions.cs
  src/TestUtils/src/UITest.Appium/AppiumIOSApp.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing

#25711 [Testing] Enabling ported UITests from Xamarin.UITests to Appium
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla25943.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue12246.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla25943.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla40858.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla43161.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue12246.cs
Labels: area-testing, community ✨

#25311 Fixed [Windows] TapGestureRecognizer not working on Entry
  src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.Windows.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/TapGestureRecognizerNotWorkingOnEntry.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue12213.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue12213.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/TapGestureRecognizerNotWorkingOnEntry.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/TapGestureRecognizerNotWorkingOnEntry.png
Labels: platform/windows 🪟, community ✨, area-controls-entry, area-gestures

#25785 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 6
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue4714.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue4720.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue5749.xaml
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue5949_2.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue6323.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue7240.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue7886.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue45749.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue4714.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue4720.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue5749.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue5949.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue6323.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue7240.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue7886.cs
Labels: area-testing, community ✨

#25751 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 4
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue2597.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue2681.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue4356.xaml
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue2681.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla38978.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue13390.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2597.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2681.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue4356.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue2681.cs
Labels: area-testing, community ✨

#25681 Better exception for using viewCell with collection View
  src/Controls/src/Core/Handlers/Items/Android/TemplatedItemViewHolder.cs
  src/Controls/src/Core/Handlers/Items/iOS/TemplatedCell.cs
  src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs
Labels: platform/windows 🪟, platform/android 🤖, platform/iOS 🍎, area-controls-collectionview, community ✨

#25800 Download using new APIs
  eng/cake/dotnet.cake
  eng/cake/helpers.cake
  eng/devices/windows.cake
Labels: area-infrastructure

#25814 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 8
  src/Controls/tests/TestCases.HostApp/Issues/Issue1355.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/GitHub1355_Forms.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue2740.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/ListViewNRE.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue1355.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/GitHub1355_Forms.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2740.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2923.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/ListViewNRE.cs
Labels: area-testing, community ✨

#25821 Fixed README for .NET 9
  README.md
Labels: area-docs, community ✨

#25340 [Testing] Implement ContextMenu UITest extension methods
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla59580.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumAndroidContextMenuActions.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumAppleContextMenuActions.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumWindowsContextMenuActions.cs
  src/TestUtils/src/UITest.Appium/AppiumAndroidApp.cs
  src/TestUtils/src/UITest.Appium/AppiumCatalystApp.cs
  src/TestUtils/src/UITest.Appium/AppiumIOSApp.cs
  src/TestUtils/src/UITest.Appium/AppiumWindowsApp.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing

#25858 [localization] Fix template names in Japanese localization for .NET MAUI ContentPage and Window
  src/Templates/src/templates/maui-contentpage-csharp/.template.config/localize/templatestrings.ja.json
  src/Templates/src/templates/maui-window-csharp/.template.config/localize/templatestrings.ja.json
Labels: area-templates, community ✨

#25875 [ci] Fix the internal build and update arcade
  .config/dotnet-tools.json
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/core-templates/steps/get-delegation-sas.yml
  global.json
Labels: area-infrastructure

#25877 [Housekeeping] Moved a UI test to the proper place
  src/Controls/tests/TestCases.HostApp/Issues/Issue19127.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue19127.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19127.cs
Labels: t/housekeeping ♻︎, area-testing, community ✨

#25840 Add Syncfusion announcement blog post to news in README
  README.md
Labels: t/housekeeping ♻︎

#25545 Fixed CarouselView Loop="False" rendering items incorrectly
  src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CarouselViewShouldRenderCorrectly.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue25192.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25192.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25192.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/CarouselViewShouldRenderCorrectly.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/CarouselViewShouldRenderCorrectly.png
Labels: platform/android 🤖, area-controls-collectionview, community ✨

#25743 Toggling Header/Footer in CollectionView Dynamically throws an exception
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue25724.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25724.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25724.cs
Labels: area-controls-collectionview, community ✨

#25847 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 10
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla56710.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue7534.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue1342.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue6484.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue8203.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla56710.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue3390.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue7534.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Github1650.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue1342.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue6484.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue8203.cs
  src/TestUtils/src/UITest.Appium/AppiumApp.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing, community ✨

#25839 Differentiate app icon & splash screen colors for sample content template
  src/Templates/src/templates/maui-mobile/MauiApp.1.csproj
Labels: area-templates

#23745 [Android] Page.IsBusy activity indicators gets stuck/causes multiple to be displayed
  src/Controls/src/Core/Platform/AlertManager/AlertManager.Android.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue23674Test.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue23674.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23674.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/Issue23674Test.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue23674Test.png
Labels: platform/android 🤖, area-navigation

#25942 Add Syncfusion Toolkit to Dependabot config
  .github/dependabot.yml
Labels: area-templates

#25933 LEGO: Pull request from lego/hb_7241b85a-f216-4d55-a9fa-d8030c736df5_20241118221232126 to main
  loc/cs/src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.json.lcl
  loc/de/src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.json.lcl
  loc/es/src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.json.lcl
  loc/fr/src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.json.lcl
  loc/it/src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.json.lcl
  loc/ja/src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.json.lcl
  loc/ko/src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.json.lcl
  loc/pl/src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.json.lcl
  loc/pt-BR/src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.json.lcl
  loc/ru/src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.json.lcl
  loc/tr/src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.json.lcl
  loc/zh-Hans/src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.json.lcl
  loc/zh-Hant/src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.json.lcl
Labels: area-infrastructure

#25924 Fixed CarouselView Loop="False" rendering items incorrectly - test fix
  src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CarouselViewShouldRenderCorrectly.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue25192.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25192.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25192.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/CarouselViewShouldRenderCorrectly.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/CarouselViewShouldRenderCorrectly.png
Labels: platform/iOS 🍎, area-controls-collectionview, community ✨

#25740 [Windows] Fix crash when navigating pages
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.Windows.cs
  src/Core/src/Platform/Windows/StackNavigationManager.cs
Labels: platform/windows 🪟, area-navigation

#25953 [ci] Split templates
  eng/pipelines/common/maui-templates-steps.yml
  eng/pipelines/common/maui-templates.yml
  eng/pipelines/handlers.yml
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/AOTTemplateTest.cs
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/MacTemplateTest.cs
Labels: t/housekeeping ♻︎

#25925 Upgrade Syncfusion Toolkit version from 1.0.1 to 1.0.2
  src/Templates/src/templates/maui-mobile/MauiApp.1.csproj
Labels: area-infrastructure, community ✨

#25914 [Testing] Changes in randomly failing UITests
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/GradientImageButtonBackground.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ImageButtonAspectFitWorks.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue18857.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue24856.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue24856.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18857.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24856.cs
Labels: area-testing

#25966 [ci] Enable provisionator with variable or devdiv
  eng/pipelines/common/device-tests-steps.yml
  eng/pipelines/common/device-tests.yml
  eng/pipelines/common/localization-handback.yml
  eng/pipelines/common/maui-templates-steps.yml
  eng/pipelines/common/maui-templates.yml
  eng/pipelines/common/merge-translations-update.yml
  eng/pipelines/common/provision.yml
  eng/pipelines/common/ui-tests-steps.yml
  eng/pipelines/common/ui-tests.yml
  eng/pipelines/common/variables.yml
  eng/pipelines/device-tests.yml
  eng/pipelines/handlers.yml
  eng/pipelines/ui-tests.yml
Labels: area-infrastructure, area-testing

#26001 [net9.0] Merge main to net9.0
  eng/Signing.props
  eng/pipelines/azure-pipelines-internal.yml
  eng/pipelines/azure-pipelines-public.yml
  eng/pipelines/common/build-test-pack.yml
  eng/pipelines/common/device-tests-steps.yml
  eng/pipelines/common/device-tests.yml
  eng/pipelines/common/localization-handback.yml
  eng/pipelines/common/maui-templates-steps.yml
  eng/pipelines/common/maui-templates.yml
  eng/pipelines/common/merge-translations-update.yml
  eng/pipelines/common/provision.yml
  eng/pipelines/common/ui-tests-steps.yml
  eng/pipelines/common/ui-tests.yml
  eng/pipelines/common/variables.yml
  eng/pipelines/device-tests.yml
  eng/pipelines/handlers.yml
  eng/pipelines/ui-tests.yml
  src/Controls/src/Build.Tasks/SetPropertiesVisitor.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.Windows.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/GradientImageButtonBackground.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ImageButtonAspectFitWorks.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue18857.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue24856.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue24856.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18857.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24856.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui25819.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui25819.xaml.cs
  src/Core/src/Platform/Windows/StackNavigationManager.cs
  src/Templates/src/templates/maui-mobile/MauiApp.1.csproj
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/AOTTemplateTest.cs
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/MacTemplateTest.cs
Labels: t/housekeeping ♻︎

#24777 Adding items to windows ObservableItemTemplateCollection
  src/Controls/src/Core/Platform/Windows/CollectionView/ObservableItemTemplateCollection.cs
Labels: platform/windows 🪟, area-controls-collectionview, community ✨

#25947 [Android] Fix RadioButton using ContentPresenter not rendering
  src/Controls/src/Core/RadioButton/RadioButton.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/RadioButtonContentNotRendering.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue25887.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25887.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25887.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/RadioButtonContentNotRendering.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/RadioButtonContentNotRendering.png
Labels: t/bug, area-xaml, platform/android 🤖, area-controls-radiobutton

#21455 [Android] Navigation icon blink fix - shell (#18867)
  src/Controls/src/Core/ShellToolbar.cs
Labels: area-navigation, area-controls-shell, community ✨

#25180 [Android] Fix for span GestureRecognizers don't work when the span is wrapped over two lines.
  src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue23801.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23801.cs
Labels: platform/android 🤖, community ✨, area-controls-label, area-gestures

#26036 Remove the sample font file
  src/Templates/src/templates/maui-mobile/.template.config/template.json
Labels: area-templates

#25418 CollectionView with EmptyView and EmptyViewTemplate for Data template selector throws an exception
  src/Controls/samples/Controls.Sample/Pages/Controls/CollectionViewGalleries/EmptyViewGalleries/EmptyViewGallery.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/CollectionViewGalleries/EmptyViewGalleries/EmptyViewWithDataTemplateSelector.xaml
  src/Controls/samples/Controls.Sample/Pages/Controls/CollectionViewGalleries/EmptyViewGalleries/EmptyViewWithDataTemplateSelector.xaml.cs
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs
  src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewController2.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue25224.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25224.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25224.cs
Labels: area-controls-collectionview, community ✨

#25990 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 15
  src/Controls/tests/TestCases.HostApp/Issues/Issue11769.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue8529_1.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue8814.cs
  src/Controls/tests/TestCases.HostApp/Resources/Images/star_flyout.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue11769.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue8529.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue8814.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue9794.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing, community ✨

#25734 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 3
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue1024.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue12126.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue1024.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue12126.cs
Labels: area-testing, community ✨

#26039 [Windows] `FileSystem.Current.AppDataDirectory` returns different path after updating to latest version - fix
  src/Essentials/src/FileSystem/FileSystem.uwp.cs
Labels: platform/windows 🪟, community ✨

#25977 [Windows] Upgrade Windows App SDK from 1.6.1 to 1.6.3
  eng/Versions.props
Labels: platform/windows 🪟, community ✨

#26033 Fall back to loading .NET 8 date strings
  src/Essentials/src/Preferences/Preferences.uwp.cs
  src/Essentials/test/DeviceTests/Tests/Preferences_Tests.cs
Labels: area-essentials

#26071 [Windows] Hide/show titlebar on modal pages
  src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Modal/ModalTests.Windows.cs
  src/Core/src/Platform/Windows/WindowRootView.cs
Labels: platform/windows 🪟, area-controls-titlebar

#25863 [Testing] Implement themes change in Appium actions on Windows
  src/Controls/tests/TestCases.HostApp/Issues/ThemeChange.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/ThemeChange.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumWindowsThemeChangeAction.cs
  src/TestUtils/src/UITest.Appium/AppiumWindowsApp.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing

#25854 [Testing] Implement PressEnter Appium action in Catalyst
  src/TestUtils/src/UITest.Appium/Actions/AppiumCatalystVirtualKeyboardActions.cs
  src/TestUtils/src/UITest.Appium/AppiumCatalystApp.cs
Labels: t/housekeeping ♻︎, area-testing

#24846 NullReferenceException throws on Windows when setting Cookies on .NET MAUI WebView
  src/Controls/tests/TestCases.HostApp/Issues/Issue18452.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18452.cs
  src/Core/src/Handlers/WebView/WebViewHandler.Windows.cs
Labels: platform/windows 🪟, community ✨

#25555 Fixed CollectionView SelectedItem binding issue on initial loading
  src/Controls/src/Core/Handlers/Items/SelectableItemsViewHandler.Windows.cs
  src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs
  src/Controls/src/Core/Handlers/Items2/iOS/SelectableItemsViewController2.cs
  src/Controls/src/Core/Platform/Windows/CollectionView/ItemContentControl.cs
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CollectionViewPreSelectionShouldUpdate.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue25551.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25551.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25551.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/CollectionViewPreSelectionShouldUpdate.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/CollectionViewPreSelectionShouldUpdate.png
Labels: platform/windows 🪟, platform/iOS 🍎, area-controls-collectionview, community ✨

#25392 [Android] ClearButtonVisibility with margin fix
  src/Controls/tests/TestCases.HostApp/Issues/Issue17453.xaml
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue17453.cs
  src/Core/src/Platform/Android/EditTextExtensions.cs
Labels: platform/android 🤖, community ✨, area-controls-entry

#25813 Fixed the iOS BackButton title does not update when set to an empty string or whitespace
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/UpdatedBackButtonTitleForEmptyString.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue25742.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27542.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/UpdatedBackButtonTitleForEmptyString.png
Labels: area-navigation, platform/iOS 🍎, community ✨

#26122 Remove code that enables/disables Editor
  src/Core/src/Handlers/Editor/EditorHandler.Android.cs
Labels: platform/android 🤖, area-controls-editor

#25815 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 9
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/AddingMultipleItemsListView.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue1439.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue1939.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue530.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/AddingMultipleItemsListView.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue1439.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue1939.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue530.cs
Labels: area-testing, community ✨

#26177 Change Yaml to use OneLocTool to create PR after we receive the lcl files
  eng/pipelines/common/localization-handback.yml
  eng/pipelines/common/variables.yml
  eng/pipelines/handlers.yml
Labels: area-templates, area-localization

#26178 Add three templates to locproject.json
  eng/automation/LocProject.json
Labels: area-templates, area-localization

#26100 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 19
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/BottomTabColorTest.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Bugzilla30166Test.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue1323Test.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue3342Test.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue3798Test.png
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla30166.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue3342.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue1323.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue7396.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla30166.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue3342.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue1323.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue3798.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue7396.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/BottomTabColorTest.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/Bugzilla30166Test.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/Issue1323Test.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/Issue3342Test.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/BottomTabColorTest.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Bugzilla30166Test.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue1323Test.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue3342Test.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue3798Test.png
Labels: area-testing, community ✨

#26120 [Testing] Fix randomly failing tests on CI
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18857.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18896.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24856.cs
  src/Controls/tests/TestCases.Shared.Tests/UITest.cs
Labels: t/housekeeping ♻︎, area-testing

#25359 [XC] Add file info to exception reports
  src/Controls/src/Build.Tasks/XamlCTask.cs
  src/Controls/src/Build.Tasks/XamlTask.cs
  src/Controls/src/Core/XamlParseException.cs
  src/Controls/src/Xaml/IXmlLineInfoExtensions.cs
  src/Controls/src/Xaml/XamlParser.cs
  src/Controls/tests/Xaml.UnitTests/CompiledTypeConverter.xaml.cs
  src/Controls/tests/Xaml.UnitTests/DefinitionCollectionTests.xaml.cs
  src/Controls/tests/Xaml.UnitTests/DuplicatePropertyElements.xaml.cs
  src/Controls/tests/Xaml.UnitTests/DuplicateXArgumentsElements.xaml.cs
  src/Controls/tests/Xaml.UnitTests/FontSize.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui21038.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui21038.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui21434.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui23711.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui25406.xaml.cs
  src/Controls/tests/Xaml.UnitTests/MockCompiler.cs
  src/Controls/tests/Xaml.UnitTests/MultipleDataTemplateChildElements.xaml.cs
  src/Controls/tests/Xaml.UnitTests/OnPlatformOptimization.xaml.cs
  src/Controls/tests/Xaml.UnitTests/XArray.xaml.cs
Labels: area-xaml, p/0

#26096 [Testing] Added ToggleSystemAnimations method to Appium helper methods
  src/TestUtils/src/UITest.Appium/Actions/AppiumAndroidSpecificActions.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumAndroidThemeChangeAction.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
  src/TestUtils/src/UITest.Appium/ShellHelper.cs
Labels: t/housekeeping ♻︎, area-testing

#26170 [ci] See if we can provision by default on devdiv
  eng/pipelines/common/device-tests-steps.yml
  eng/pipelines/common/provision.yml
  eng/pipelines/common/ui-tests-build-sample.yml
  eng/pipelines/common/ui-tests-compatibility-steps.yml
  eng/pipelines/common/ui-tests-steps.yml
  eng/pipelines/common/variables.yml
  eng/pipelines/handlers.yml
  eng/pipelines/ui-tests.yml
Labels: area-infrastructure

#26006 [Windows] Disable HitTest when showing EmptyView on CollectionView
  src/Controls/src/Core/Platform/Windows/CollectionView/FormsGridView.cs
  src/Controls/src/Core/Platform/Windows/FormsListView.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue19609.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue19609.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19609.cs
Labels: platform/windows 🪟, area-controls-collectionview

#26130 [Windows] - Fix for Shell Section Visibility changes not reflected until Tab switch
  src/Controls/src/Core/Handlers/Shell/ShellItemHandler.Windows.cs
  src/Controls/src/Core/Handlers/Shell/ShellSectionHandler.Windows.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/DynamicTabSectionVisibility.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue25913.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25913.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/DynamicTabSectionVisibility.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/DynamicTabSectionVisibility.png
Labels: platform/windows 🪟, area-controls-shell, community ✨

#26142 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 20
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue8279.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue8461.cs
  src/Controls/tests/TestCases.HostApp/MauiProgram.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla26171.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2927.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue8279.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue8291.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue8461.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumMouseActions.cs
Labels: area-testing, community ✨

#26168 [Testing] Enabling ported UITests from Xamarin.UITests to Appium - 21
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue1028.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue264.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue2883.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue8461.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla30317.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue1028.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2470.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue264.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2767.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2883.cs
Labels: area-testing, community ✨

#26163 [ci] Remove use of System.Formats.Asn1 by removing Microsoft.Build.Tasks.Core
  eng/NuGetVersions.targets
  eng/Versions.props
  src/Controls/src/Build.Tasks/Controls.Build.Tasks.csproj
  src/Controls/tests/Xaml.UnitTests/Controls.Xaml.UnitTests.csproj
  src/SingleProject/Resizetizer/src/Resizetizer.csproj
Labels: area-infrastructure, area-sfi
