Repository dotnet/maui, pull requests merged in 2024-07, with the labels that each got.

#23265 [Windows] Make sure that `FileSystem.Current.AppDataDirectory` folder exists in unpackaged
  src/Essentials/src/FileSystem/FileSystem.uwp.cs
  src/Essentials/test/DeviceTests/Tests/FileSystem_Tests.cs
Labels: area-essentials, community ✨

#23116 [Binding SG] Split bindings source generated code into multiple files
  src/Controls/src/BindingSourceGen/BindingCodeWriter.cs
  src/Controls/src/BindingSourceGen/BindingSourceGenerator.cs
  src/Controls/src/BindingSourceGen/BindingSourceGeneratorUtilities.cs
  src/Controls/src/BindingSourceGen/GeneratorDataModels.cs
  src/Controls/tests/BindingSourceGen.UnitTests/AssertExtensions.cs
  src/Controls/tests/BindingSourceGen.UnitTests/BindingCodeWriterTests.cs
  src/Controls/tests/BindingSourceGen.UnitTests/IncrementalGenerationTests.cs
  src/Controls/tests/BindingSourceGen.UnitTests/IntegrationTests.cs
  src/Controls/tests/BindingSourceGen.UnitTests/SourceGenHelpers.cs
Labels: area-xaml

#23281 [windows] fix memory leak in `TabbedPage`
  src/Controls/tests/DeviceTests/Memory/MemoryTests.cs
  src/Core/src/Platform/Windows/NavigationViewItemViewModel.cs
Labels: platform/windows 🪟, area-controls-tabbedpage, memory-leak 💦

#21350 Add Apple Privacy Manifest to new project template
  src/Templates/src/templates/maui-blazor/Platforms/iOS/Resources/PrivacyInfo.xcprivacy
  src/Templates/src/templates/maui-mobile/Platforms/iOS/Resources/PrivacyInfo.xcprivacy
  src/Templates/src/templates/maui-multiproject/MauiApp.1.iOS/Resources/PrivacyInfo.xcprivacy
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/TemplateTests.cs
Labels: platform/iOS 🍎, area-templates

#23188 [Windows] Fix horizontal scroll not working w/ CollectionView
  src/Controls/src/Core/Handlers/Items/StructuredItemsViewHandler.Windows.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.Windows.cs
Labels: platform/windows 🪟, area-controls-collectionview, area-controls-scrollview

#22345 [Android] InputTransparent="true" on a Layout breaks child controls - Fix
  src/Controls/tests/TestCases.HostApp/Issues/Issue22289.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue22289.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22289.cs
  src/Core/src/Handlers/Label/LabelHandler.Windows.cs
  src/Core/src/Handlers/View/ViewHandler.cs
Labels: area-layout, platform/android 🤖, community ✨

#23428 Add missing UI Test category to fix main build
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22289.cs
Labels: t/housekeeping ♻︎, area-testing

#23405 `Element`: NRE by accessing `RealParent` - fix
  src/Controls/src/Core/Element/Element.cs
Labels: community ✨

#23416 Android: Ensure fragment has not been disposed while updating left bar button
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarTracker.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue14801.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue14801.cs
Labels: community ✨

#23432 Add Flaky UI Test category
  src/Controls/tests/TestCases.Shared.Tests/UITestCategories.cs
Labels: t/housekeeping ♻︎, area-testing

#23433 Add UITest.Analyzers to VS Code Solution
  Microsoft.Maui-vscode.sln
Labels: t/housekeeping ♻︎, area-testing

#23327 [windows] fix memory leak in `MauiWinUIWindow`
  src/Controls/src/Core/Platform/AlertManager/AlertManager.Windows.cs
  src/Controls/tests/DeviceTests/Memory/MemoryTests.cs
  src/Core/src/Platform/Windows/MauiWinUIWindow.cs
  src/Core/src/Platform/Windows/NavigationRootManager.cs
Labels: platform/windows 🪟, area-controls-window, memory-leak 💦

#23369 Fixing regression in Picker behavior in 8.0.60
  src/Controls/src/Core/Picker/Picker.cs
  src/Controls/tests/Core.UnitTests/PickerTests.cs
Labels: community ✨

#22609 Run UI tests per groups of categories in CI
  eng/devices/android.cake
  eng/devices/catalyst.cake
  eng/devices/devices-shared.cake
  eng/devices/ios.cake
  eng/devices/windows.cake
  eng/pipelines/common/ui-tests-build-sample.yml
  eng/pipelines/common/ui-tests-compatibility-steps.yml
  eng/pipelines/common/ui-tests-steps.yml
  eng/pipelines/common/ui-tests.yml
  eng/pipelines/ui-tests.yml
  src/Controls/tests/TestCases.Shared.Tests/Tests/ScrollViewUITests.cs
  src/Controls/tests/TestCases.Shared.Tests/UITestCategories.cs
Labels: t/housekeeping ♻︎, area-testing, testing-infrastructure

#23156 Fixes #18204 border lagging behind content on iOS and improves initial render performance
  src/Controls/tests/TestCases.HostApp/Issues/Issue18204.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue18204.xaml.cs
  src/Core/src/Handlers/Border/BorderHandler.iOS.cs
  src/Core/src/Platform/iOS/StrokeExtensions.cs
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
Labels: community ✨, area-controls-border

#23360 [iOS] Crash upon resuming the app - fix
  src/Controls/tests/TestCases.HostApp/Issues/Issue21948.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue21948.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23360.cs
  src/Core/src/Platform/iOS/UIApplicationExtensions.cs
Labels: area-core-lifecycle, platform/iOS 🍎, partner/cat 😻, community ✨, migration-compatibility

#23464 Added missing ui test categories
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue11501.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21630.cs
Labels: t/housekeeping ♻︎, area-testing

#23466 Shell BackButtonBehavior improvement
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/BackButtonBehaviorIsVisibleWorksWithCustomIcon.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue23424.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23424.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/BackButtonBehaviorIsVisibleWorksWithCustomIcon.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/BackButtonBehaviorIsVisibleWorksWithCustomIcon.png
Labels: platform/iOS 🍎, area-controls-shell, community ✨

#23158 [Windows] Respect `ClearButtonVisibility = ClearButtonVisibility.Never` for `<Entry>`s
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ValidateEntryClearButtonVisibilityBehavior.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue23158.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue23158.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23158.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ValidateEntryClearButtonVisibilityBehavior.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ValidateEntryClearButtonVisibilityBehavior.png
  src/Core/src/Platform/Windows/MauiTextBox.cs
Labels: community ✨, area-controls-entry

#23247 Support the new RIDs on WinUI
  src/Core/src/nuget/buildTransitive/WinUI.targets
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/TemplateTests.cs
  src/Workload/Microsoft.Maui.Sdk/Sdk/Microsoft.Maui.Sdk.Before.targets
Labels: area-infrastructure

#23489 [windows] fix VisualDiagnosticsOverlay keeping Page's alive
  src/Controls/tests/DeviceTests/Memory/MemoryTests.cs
  src/Core/src/WindowOverlay/WindowOverlay.Windows.cs
Labels: platform/windows 🪟, memory-leak 💦

#23544 [net9.0] Update to preview7 versions
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-infrastructure

#23400 [android]: ModalContainer Destroy commit allowing state loss
  src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.Android.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue23399.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23399.cs
Labels: community ✨

#23540 [windows] fix memory leak in WebView
  src/Controls/tests/DeviceTests/Memory/MemoryTests.cs
  src/Core/src/Handlers/WebView/WebViewHandler.Windows.cs
Labels: platform/windows 🪟, memory-leak 💦

#23519 Don't throw exceptions on back-to-back window deactivations
  src/Core/src/Platform/Windows/MauiWinUIWindow.cs
Labels: platform/windows 🪟

#22501 [iOS] Read only Editor is editable when Next from on screen keyboard
  src/Core/src/Platform/iOS/KeyboardAutoManager.cs
  src/Core/tests/DeviceTests/Handlers/Entry/EntryHandlerTests.iOS.cs
Labels: platform/iOS 🍎, community ✨, area-keyboard, area-controls-editor

#23517 Add missing ctor overloads to MaterialButton
  src/Core/src/Platform/Android/MauiMaterialButton.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
Labels: community ✨

#23592 Fix a few more template ampersand cases
  src/Templates/src/templates/maui-blazor/Platforms/Windows/app.manifest
  src/Templates/src/templates/maui-mobile/Platforms/Windows/app.manifest
  src/Templates/src/templates/maui-multiproject/MauiApp.1.WinUI/app.manifest
Labels: area-templates

#23589 Make ampersands work *more* in net9-only blazor-solution template
  src/Templates/src/templates/maui-blazor-solution/.template.config/template.json
  src/Templates/src/templates/maui-blazor-solution/MauiApp.1.Web.Client/MauiApp.1.Web.Client.csproj
  src/Templates/src/templates/maui-blazor-solution/MauiApp.1.Web/MauiApp.1.Web.csproj
  src/Templates/src/templates/maui-blazor-solution/MauiApp.1/MainPage.xaml
  src/Templates/src/templates/maui-blazor-solution/MauiApp.1/MauiApp.1.csproj
  src/Templates/src/templates/maui-blazor-solution/MauiApp.1/Platforms/Tizen/tizen-manifest.xml
  src/Templates/src/templates/maui-blazor-solution/MauiApp.1/Platforms/Windows/app.manifest
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/TemplateTests.cs
Labels: area-blazor, area-templates

#22023 [XC] Compile "standalone" bindings
  src/Controls/src/Build.Tasks/SetPropertiesVisitor.cs
  src/Controls/tests/Xaml.UnitTests/BindingsCompiler.xaml
  src/Controls/tests/Xaml.UnitTests/BindingsCompiler.xaml.cs
Labels: area-xaml

#23239 [Binding SG] Add an API for creating instances of TypedBinding
  src/Controls/src/BindingSourceGen/BindingCodeWriter.cs
  src/Controls/src/BindingSourceGen/BindingSourceGenerator.cs
  src/Controls/src/BindingSourceGen/BindingTransformer.cs
  src/Controls/src/BindingSourceGen/GeneratorDataModels.cs
  src/Controls/src/Core/BindableObjectExtensions.cs
  src/Controls/src/Core/Binding.Create.cs
  src/Controls/src/Core/Binding.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/tests/BindingSourceGen.UnitTests/AssertExtensions.cs
  src/Controls/tests/BindingSourceGen.UnitTests/BindingCodeWriterTests.cs
  src/Controls/tests/BindingSourceGen.UnitTests/BindingRepresentationGenTests.cs
  src/Controls/tests/BindingSourceGen.UnitTests/BindingTransformerTests.cs
  src/Controls/tests/BindingSourceGen.UnitTests/IncrementalGenerationTests.cs
  src/Controls/tests/BindingSourceGen.UnitTests/IntegrationTests.cs
  src/Controls/tests/BindingSourceGen.UnitTests/SourceGenHelpers.cs
Labels: area-xaml

#23604 [Android] Honor IconImageSource.FontImageSource color
  src/Core/src/Platform/SwipeViewExtensions.cs
Labels: platform/android 🤖, community ✨, area-controls-swipeview

#23477 [iOS] CarouselView: Changing Position after navigation away then comi…
  src/Controls/src/Core/Handlers/Items/CarouselViewHandler.iOS.cs
  src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs
  src/Controls/src/Core/Platform/Windows/CollectionView/ScrollHelpers.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue23291.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue23291.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23291.cs
Labels: platform/iOS 🍎, area-controls-collectionview, community ✨, migration-compatibility

#22611 [CI] Bump xcode 15.4.0
  eng/pipelines/common/device-tests-steps.yml
  eng/pipelines/common/device-tests.yml
  eng/pipelines/common/maui-templates.yml
  eng/pipelines/common/provision.yml
  eng/pipelines/common/variables.yml
  eng/pipelines/device-tests.yml
  eng/pipelines/handlers.yml
  eng/pipelines/ui-tests.yml
Labels: area-infrastructure

#21962 [Core] Enforce CA1507 - use nameof() where possible
  src/Core/src/.editorconfig
  src/Core/src/Platform/Android/MauiWebChromeClient.cs
  src/Core/src/Platform/Android/MauiWebView.cs
  src/Core/src/Platform/Windows/KeyboardExtensions.cs
  src/Core/src/Platform/iOS/MauiWKWebView.cs
  src/Core/src/Platform/iOS/MauiWebViewNavigationDelegate.cs
  src/Core/src/Platform/iOS/MauiWebViewUIDelegate.cs
  src/Core/src/Primitives/GridLength.cs
Labels: t/housekeeping ♻︎, area-architecture, community ✨

#23638 [net9.0] Merge main to net9.0
  eng/pipelines/common/sdk-insertion.yml
  src/Controls/src/Core/Menu/MenuBarItem.cs
  src/Controls/src/Core/Menu/MenuFlyout.cs
  src/Controls/src/Core/Menu/MenuFlyoutSubItem.cs
  src/Core/src/Platform/SwipeViewExtensions.cs
  src/Core/src/Platform/Windows/MauiWinUIWindow.cs
  src/Core/src/Platform/iOS/KeyboardAutoManager.cs
  src/Core/tests/DeviceTests/Handlers/Entry/EntryHandlerTests.iOS.cs
  src/SingleProject/Resizetizer/src/ResizetizeImages.cs
  src/SingleProject/Resizetizer/src/Utils.cs
  src/Templates/src/templates/maui-blazor/Platforms/Windows/app.manifest
  src/Templates/src/templates/maui-mobile/Platforms/Windows/app.manifest
  src/Templates/src/templates/maui-multiproject/MauiApp.1.WinUI/app.manifest
Labels: area-infrastructure

#23639 [net8.0] Merge main to net8.0
  eng/pipelines/common/sdk-insertion.yml
  src/Controls/src/Core/Menu/MenuBarItem.cs
  src/Controls/src/Core/Menu/MenuFlyout.cs
  src/Controls/src/Core/Menu/MenuFlyoutSubItem.cs
  src/Core/src/Platform/SwipeViewExtensions.cs
  src/Core/src/Platform/Windows/MauiWinUIWindow.cs
  src/Core/src/Platform/iOS/KeyboardAutoManager.cs
  src/Core/tests/DeviceTests/Handlers/Entry/EntryHandlerTests.iOS.cs
  src/SingleProject/Resizetizer/src/ResizetizeImages.cs
  src/SingleProject/Resizetizer/src/Utils.cs
  src/Templates/src/templates/maui-blazor/Platforms/Windows/app.manifest
  src/Templates/src/templates/maui-mobile/Platforms/Windows/app.manifest
  src/Templates/src/templates/maui-multiproject/MauiApp.1.WinUI/app.manifest
Labels: area-infrastructure

#23615 Add empty (no sample content) option for Blazor Hybrid
  src/Templates/src/templates/maui-blazor/.template.config/ide.host.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.cs.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.de.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.en.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.es.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.fr.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.it.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.ja.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.ko.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.pl.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.pt-BR.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.ru.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.tr.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.zh-Hans.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.zh-Hant.json
  src/Templates/src/templates/maui-blazor/.template.config/template.json
  src/Templates/src/templates/maui-blazor/Components/Layout/MainLayout.razor
  src/Templates/src/templates/maui-blazor/Components/Layout/MainLayout.razor.css
  src/Templates/src/templates/maui-blazor/wwwroot/css/app.css
  src/Templates/src/templates/maui-blazor/wwwroot/favicon.png
  src/Templates/src/templates/maui-blazor/wwwroot/index.html
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/TemplateTests.cs
Labels: area-blazor, area-templates

#23547 [Windows] Fix pull to refresh w/ horz item layouts
  src/Controls/src/Core/Handlers/Items/StructuredItemsViewHandler.Windows.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.Windows.cs
Labels: platform/windows 🪟, area-controls-general

#23648 Detect MauiCALayer being rendered offscreen
  src/Controls/tests/TestCases.HostApp/Issues/Issue23070.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue23070.xaml.cs
  src/Core/src/Platform/iOS/MauiCALayer.cs
Labels: community ✨

#20087 Hide FlyoutIcon when FlyoutBehavior set to disabled
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarTracker.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ShouldHideCustomFlyoutIconWhenNavigatingToPageWithDisabledFlyout.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue20166.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue20166.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20166.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ShouldHideCustomFlyoutIconWhenNavigatingToPageWithDisabledFlyout.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ShouldHideCustomFlyoutIconWhenNavigatingToPageWithDisabledFlyout.png
Labels: area-controls-shell, community ✨

#22056 [X] do not apply Bindings if DataType doesnt match
  src/Controls/src/Core/Binding.cs
  src/Controls/src/Core/IXamlDataTypeProvider.cs
  src/Controls/src/Xaml/MarkupExtensions/BindingExtension.cs
  src/Controls/src/Xaml/XamlServiceProvider.cs
  src/Controls/tests/Xaml.UnitTests/BindingsCompiler.xaml.cs
Labels: area-xaml

#23667 [tests] Fix iOS screenshot for sonoma
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ValidateEntryClearButtonVisibilityBehavior.png
Labels: area-testing, testing-flakiness

#23664 [ci] Fix maestro publishing for stable packages
  src/Workload/Shared/Maestro.targets
Labels: area-infrastructure

#23676 [net9.0] Comment out shell test
  src/Controls/tests/Core.UnitTests/ShellLifeCycleTests.cs
Labels: area-testing, testing-flakiness

#22880 HybridWebView control for integrating JS/HTML/CSS easily into a .NET MAUI app
  eng/devices/windows.cake
  src/Controls/samples/Controls.Sample/Pages/Controls/HybridWebViewPage.xaml
  src/Controls/samples/Controls.Sample/Pages/Controls/HybridWebViewPage.xaml.cs
  src/Controls/samples/Controls.Sample/Resources/Raw/HybridSamplePage/docs/sample.pdf
  src/Controls/samples/Controls.Sample/Resources/Raw/HybridSamplePage/index.html
  src/Controls/samples/Controls.Sample/Resources/Raw/HybridSamplePage/scripts/HybridWebView.js
  src/Controls/samples/Controls.Sample/Resources/Raw/HybridSamplePage/styles/app.css
  src/Controls/samples/Controls.Sample/ViewModels/ControlsViewModel.cs
  src/Controls/src/Core/HybridWebView/HybridWebView.cs
  src/Controls/src/Core/HybridWebView/HybridWebViewRawMessageReceivedEventArgs.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Xaml/Hosting/AppHostBuilderExtensions.cs
  src/Controls/tests/DeviceTests/Controls.DeviceTests.csproj
  src/Controls/tests/DeviceTests/Elements/HybridWebView/HybridWebViewTests.cs
  src/Controls/tests/DeviceTests/Memory/MemoryTests.cs
  src/Controls/tests/DeviceTests/Resources/Raw/HybridTestRoot/index.html
  src/Controls/tests/DeviceTests/Resources/Raw/HybridTestRoot/scripts/HybridWebView.js
  src/Controls/tests/DeviceTests/TestCategory.cs
  src/Core/src/Core/IHybridWebView.cs
  src/Core/src/Handlers/HybridWebView/FileExtensionContentTypeProvider.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.Android.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.Standard.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.Tizen.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.Windows.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.iOS.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewQueryStringHelper.cs
  src/Core/src/Handlers/HybridWebView/IHybridPlatformWebView.cs
  src/Core/src/Handlers/HybridWebView/IHybridWebViewHandler.cs
  src/Core/src/Platform/Android/MauiHybridWebView.cs
  src/Core/src/Platform/Android/MauiHybridWebViewClient.cs
  src/Core/src/Platform/Windows/MauiHybridWebView.cs
  src/Core/src/Platform/iOS/MauiHybridWebView.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
Labels: area-controls-hybridwebview

#20933 [Docs] Added pending inline comments to Page class
  src/Controls/docs/Microsoft.Maui.Controls.PlatformConfiguration.WindowsSpecific/Page.xml
  src/Controls/docs/Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific/Page.xml
  src/Controls/src/Core/PlatformConfiguration/WindowsSpecific/Page.cs
  src/Controls/src/Core/PlatformConfiguration/iOSSpecific/Page.cs
Labels: area-docs, t/housekeeping ♻︎

#23709 [windows] Fix Updating the initial position
  src/Controls/src/Core/Handlers/Items/CarouselViewHandler.Windows.cs
Labels: platform/windows 🪟, area-controls-collectionview

#23726 [Windows] Fix CollectionView DisconnectHandler SelectionMode Crash
  src/Controls/src/Core/Handlers/Items/SelectableItemsViewHandler.Windows.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.Windows.cs
Labels: platform/windows 🪟, area-controls-collectionview

#23730 HybridWebView: Remove unneeded DefaultFile / HybridRoot handler properties
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.iOS.cs
  src/Core/src/Handlers/HybridWebView/IHybridWebViewHandler.cs
  src/Core/src/Platform/Android/MauiHybridWebViewClient.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
Labels: area-controls-hybridwebview

#23515 [Windows] Subscribe pointer events only when needed
  src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.Windows.cs
Labels: community ✨

#23334 Fix iOS log exports
  eng/devices/ios.cake
  eng/pipelines/common/device-tests-steps.yml
  eng/pipelines/common/device-tests.yml
  eng/pipelines/common/maui-templates.yml
  eng/pipelines/common/ui-tests-steps.yml
Labels: area-infrastructure

#23658 [ci] Use drop service for SDK insertion artifacts
  eng/pipelines/common/sdk-insertion.yml
  eng/pipelines/common/sign.yml
Labels: area-infrastructure

#23759 [ci] Update pool
  eng/UWP.Build.props
  eng/UWP.Build.targets
  eng/docs/Xamarin.Forms.Core.xml
  eng/docs/Xamarin.Forms.Core/Xamarin.Forms/ListView.xml
  eng/docs/Xamarin.Forms.Maps.xml
  eng/docs/Xamarin.Forms.Xaml.xml
  eng/pipelines/common/maui-templates.yml
  eng/pipelines/handlers.yml
Labels: area-infrastructure

#23764 [core] Fix tests when converting with PT Locale
  src/Controls/src/Core/Shapes/PathFigureCollectionConverter.cs
Labels: area-testing, testing-flakiness

#23750 [Windows] Upgrade Windows App SDK from 1.5.4 to 1.5.5
  eng/Versions.props
Labels: community ✨

#23683 Bring back ResourceDictionary.SetAndLoadSource
  src/Controls/src/Core/ResourceDictionary.cs
  src/Controls/src/Xaml/ResourceDictionaryHelpers.cs
Labels: area-xaml, partner/hot-reload-xaml

#23765 [android] update AOT profile for servicing
  src/Controls/src/Build.Tasks/nuget/buildTransitive/netstandard2.0/maui-blazor.aotprofile
  src/Controls/src/Build.Tasks/nuget/buildTransitive/netstandard2.0/maui-blazor.aotprofile.txt
  src/Controls/src/Build.Tasks/nuget/buildTransitive/netstandard2.0/maui.aotprofile
  src/Controls/src/Build.Tasks/nuget/buildTransitive/netstandard2.0/maui.aotprofile.txt
  src/ProfiledAot/src/maui/MainPage.xaml.cs
Labels: platform/android 🤖, t/perf

#23762 [Accessibility] Add accessibility label to the menu button
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs
Labels: t/a11y

#23271 Android ecosystem updates 20240618 based on net9.0 branch
  eng/AndroidX.targets
  eng/Versions.props
  src/Compatibility/ControlGallery/src/Android/Compatibility.ControlGallery.Android.csproj
  src/Compatibility/ControlGallery/src/EmbeddingTestBeds/Embedding.Droid/Directory.Build.targets
  src/Compatibility/Core/src/Android/ButtonLayoutManager.cs
  src/Compatibility/Core/src/Android/FastRenderers/ImageElementManager.cs
  src/Compatibility/Core/src/Android/HandlerToRendererShim.cs
  src/Compatibility/Maps/src/Android/Compatibility.Maps.Android.csproj
  src/Compatibility/Material/src/Android/Compatibility.Material.Android.csproj
  src/Controls/Foldable/src/Controls.Foldable.csproj
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellBottomNavViewAppearanceTracker.cs
  src/Controls/src/Core/Handlers/Items/Android/MauiRecyclerView.cs
  src/Controls/src/Core/Platform/Android/BottomNavigationViewUtils.cs
  src/Controls/src/Core/Platform/Android/TabbedPageManager.cs
  src/Controls/src/Xaml/Controls.Xaml.csproj
  src/Controls/tests/DeviceTests/ControlsHandlerTestBase.Android.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.Android.cs
  src/Controls/tests/DeviceTests/Stubs/WindowHandlerStub.Android.cs
  src/Controls/tests/DeviceTests/TestClasses/CustomTestAdapterHandler.Android.cs
  src/Core/AndroidNative/maui/build.gradle
  src/Core/src/Core.csproj
  src/Core/src/Platform/Android/MauiSwipeRefreshLayout.cs
  src/Core/src/Platform/Android/Navigation/StackNavigationManager.cs
  src/Core/tests/DeviceTests.Shared/ImageAnalysis/RawBitmap.cs
  src/Essentials/src/Essentials.csproj
  src/TestUtils/src/DeviceTests/AssertionExtensions.Android.cs
Labels: area-infrastructure

#23721 [ci] Add scheduled push to nightly feed job
  eng/pipelines/maui-release.yml
Labels: area-infrastructure

#23811 [ci] Move to push nightly to a template
  eng/pipelines/common/push-nightly.yml
  eng/pipelines/device-tests.yml
  eng/pipelines/maui-release-internal.yml
  eng/pipelines/maui-release.yml
Labels: area-infrastructure

#23019 [Windows] Add TitleBar Control
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/Windows/WindowsTileBarPage.xaml
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/Windows/WindowsTileBarPage.xaml.cs
  src/Controls/samples/Controls.Sample/Resources/Images/tb_appicon.png
  src/Controls/samples/Controls.Sample/ViewModels/PlatformSpecificsViewModel.cs
  src/Controls/samples/Controls.Sample/ViewModels/TitleBarSampleViewModel.cs
  src/Controls/src/Core/Controls.Core.csproj
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/TitleBar/TitleBar.Windows.cs
  src/Controls/src/Core/TitleBar/TitleBar.cs
  src/Controls/src/Core/Window/Window.cs
  src/Core/src/Core.csproj
  src/Core/src/Core/ITitleBar.cs
  src/Core/src/Core/IWindow.cs
  src/Core/src/Handlers/Window/WindowHandler.Windows.cs
  src/Core/src/Handlers/Window/WindowHandler.cs
  src/Core/src/Platform/Windows/MauiNavigationView.cs
  src/Core/src/Platform/Windows/MauiWinUIWindow.cs
  src/Core/src/Platform/Windows/NavigationRootManager.cs
  src/Core/src/Platform/Windows/RootNavigationView.cs
  src/Core/src/Platform/Windows/Styles/WindowRootViewStyle.xaml
  src/Core/src/Platform/Windows/WindowExtensions.cs
  src/Core/src/Platform/Windows/WindowRootView.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Templates/src/templates/maui-mobile/Resources/Styles/Styles.xaml
  src/Templates/src/templates/maui-multiproject/MauiApp.1/Resources/Styles/Styles.xaml
Labels: platform/windows 🪟, area-controls-window

#22869 Use DialogFragment for Android modals
  src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.Android.cs
  src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.cs
  src/Core/src/Platform/Android/Resources/anim/nav_modal_default_enter_anim.xml
  src/Core/src/Platform/Android/Resources/anim/nav_modal_default_exit_anim.xml
Labels: platform/android 🤖, community ✨, area-controls-dialogalert

#23467 [net9] BackButtonBehavior enhancement - Changed IsVisible & IsEnabled BindingMode to OneWay
  src/Controls/src/Core/Shell/BackButtonBehavior.cs
Labels: t/enhancement ☀️, area-controls-shell, community ✨

#23849 [ci] Allow to set the agents for template build
  eng/pipelines/handlers.yml
Labels: area-infrastructure

#23852 Fixed a crash for the samples app [User interface concepts -> styles]
  src/Controls/samples/Controls.Sample/Pages/UserInterface/StylesPage.xaml
Labels: area-docs, area-xaml

#23859 [net9.0] Comment more failing tests for shell on net9
  src/Controls/tests/Core.UnitTests/ShellNavigatedArgsTests.cs
  src/Controls/tests/Core.UnitTests/ShellTests.cs
Labels: area-testing, testing-flakiness, testing-green-ci

#23853 [net9.0] Merge main to net9.0
  eng/pipelines/common/push-nightly.yml
  eng/pipelines/device-tests.yml
  eng/pipelines/handlers.yml
  eng/pipelines/maui-release-internal.yml
  eng/pipelines/maui-release.yml
  src/Controls/samples/Controls.Sample.Embedding/Platforms/Android/FirstFragment.cs
  src/Controls/samples/Controls.Sample.Embedding/Platforms/Android/SettingsFragment.cs
  src/Controls/samples/Controls.Sample.Embedding/Platforms/MacCatalyst/MainViewController.cs
  src/Controls/samples/Controls.Sample.Embedding/Platforms/Windows/MainWindow.xaml.cs
  src/Controls/samples/Controls.Sample.Embedding/Platforms/iOS/MainViewController.cs
  src/Controls/samples/Controls.Sample.Embedding/Shared/EmbeddingReflection.cs
  src/Controls/samples/Controls.Sample.Embedding/Shared/EmbeddingScenarios.cs
  src/Controls/samples/Controls.Sample.Embedding/Shared/MauiProgram.cs
  src/Controls/samples/Controls.Sample.Embedding/Shared/MyMauiContent.xaml
  src/Controls/samples/Controls.Sample.Embedding/Shared/MyMauiContent.xaml.cs
  src/Controls/src/Build.Tasks/nuget/buildTransitive/netstandard2.0/Microsoft.Maui.Controls.Globs.props
  src/Controls/src/Core/Application/Application.cs
  src/Controls/src/Core/Embedding/EmbeddedWindow.cs
  src/Controls/src/Core/Embedding/EmbeddingExtensions.cs
  src/Controls/src/Core/Hosting/AppHostBuilderExtensions.cs
  src/Controls/src/Core/Properties/AssemblyInfo.cs
  src/Controls/src/Xaml/Embedding/EmbeddingExtensions.cs
  src/Controls/src/Xaml/Hosting/AppHostBuilderExtensions.cs
  src/Controls/src/Xaml/Properties/AssemblyInfo.cs
  src/Core/src/Core/Extensions/VisualTreeElementExtensions.cs
  src/Core/src/Embedding/EmbeddedPlatformApplication.cs
  src/Core/src/Embedding/EmbeddedWindowHandler.Android.cs
  src/Core/src/Embedding/EmbeddedWindowHandler.Windows.cs
  src/Core/src/Embedding/EmbeddedWindowHandler.cs
  src/Core/src/Embedding/EmbeddedWindowHandler.iOS.cs
  src/Core/src/Embedding/EmbeddedWindowProvider.cs
  src/Core/src/Embedding/EmbeddingExtensions.cs
  src/Core/src/Platform/iOS/ElementExtensions.cs
Labels: area-infrastructure

#23879 dismiss the modal when IsAnimated is set to false
  src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.Android.cs
  src/Controls/tests/DeviceTests/Elements/Modal/ModalTests.cs
Labels: community ✨

#20059 Added ProcessTerminated event to WebView
  src/Controls/samples/Controls.Sample/Pages/Controls/WebViewPage.xaml.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/WebView/PlatformWebViewProcessTerminatedEventArgs.cs
  src/Controls/src/Core/WebView/WebView.cs
  src/Controls/src/Core/WebView/WebViewProcessTerminatedEventArgs.cs
  src/Core/src/Core/IWebView.cs
  src/Core/src/Handlers/WebView/WebViewHandler.Windows.cs
  src/Core/src/Platform/Android/MauiWebViewClient.cs
  src/Core/src/Platform/iOS/MauiWKWebView.cs
  src/Core/src/Primitives/WebProcessTerminatedEventArgs.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Core/tests/DeviceTests/Stubs/WebView.cs
Labels: t/enhancement ☀️, area-controls-webview

#23906 Fix BlazorWebView on iOS/MacCatalyst 18
  src/BlazorWebView/src/Maui/Android/AndroidWebKitWebViewManager.cs
  src/BlazorWebView/src/Maui/BlazorWebView.cs
  src/BlazorWebView/src/Maui/iOS/BlazorWebViewHandler.iOS.cs
Labels: area-blazor

#23914 [net9.0] Update arcade net9
  .config/dotnet-tools.json
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/SetupNugetSources.ps1
  eng/common/SetupNugetSources.sh
  eng/common/core-templates/job/job.yml
  eng/common/core-templates/job/publish-build-assets.yml
  eng/common/core-templates/job/source-index-stage1.yml
  eng/common/core-templates/post-build/common-variables.yml
  eng/common/core-templates/post-build/post-build.yml
  eng/common/core-templates/post-build/setup-maestro-vars.yml
  eng/common/core-templates/steps/component-governance.yml
  eng/common/core-templates/steps/enable-internal-sources.yml
  eng/common/core-templates/steps/get-federated-access-token.yml
  eng/common/core-templates/steps/publish-logs.yml
  eng/common/core-templates/steps/source-build.yml
  eng/common/cross/armel/sources.list.jessie
  eng/common/cross/armv6/sources.list.bookworm
  eng/common/cross/armv6/sources.list.buster
  eng/common/cross/build-rootfs.sh
  eng/common/cross/ppc64le/sources.list.bionic
  eng/common/cross/riscv64/sources.list.sid
  eng/common/cross/s390x/sources.list.bionic
  eng/common/dotnet-install.sh
  eng/common/native/CommonLibrary.psm1
  eng/common/native/init-compiler.sh
  eng/common/post-build/nuget-validation.ps1
  eng/common/post-build/publish-using-darc.ps1
  eng/common/templates/job/job.yml
  eng/common/tools.sh
  global.json
Labels: area-infrastructure

#23919 [ci] Fix when pushing artifacts on uitests samples
  eng/pipelines/common/ui-tests-build-sample.yml
Labels: area-infrastructure, area/infrastructure 🏗️

#23912 Fix HostIdentifier bindings for item templates
  src/Templates/src/templates/maui-contentpage-csharp/.template.config/template.json
  src/Templates/src/templates/maui-contentpage-xaml/.template.config/template.json
  src/Templates/src/templates/maui-contentview-csharp/.template.config/template.json
  src/Templates/src/templates/maui-contentview-xaml/.template.config/template.json
  src/Templates/src/templates/maui-resourcedictionary-xaml/.template.config/template.json
Labels: area-templates

#23947 [release/9.0.1xx-preview7] Bump to latest 8.0.1xx-sr7
  eng/Versions.props
Labels: area-infrastructure

#23928 [iOS/MacCatalyst] CollectionViewHandler2 with compositional layout API's
  src/Controls/samples/Controls.Sample/MauiProgram.cs
  src/Controls/src/Core/Handlers/Items2/CarouselViewHandler2.iOS.cs
  src/Controls/src/Core/Handlers/Items2/CollectionViewHandler2.iOS.cs
  src/Controls/src/Core/Handlers/Items2/ItemsViewHandler2.iOS.cs
  src/Controls/src/Core/Handlers/Items2/iOS/CarouselTemplatedCell2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/CarouselViewController2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/CarouselViewDelegator2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/DefaultCell2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/GroupableItemsViewController2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/GroupableItemsViewDelegator2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/HeightConstrainedTemplatedCell2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/HorizontalCell2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/HorizontalDefaultCell2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/HorizontalDefaultSupplementalView2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/HorizontalTemplatedHeaderView2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewCell2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewController2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewDelegator2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/LayoutAttributesChangedEventArgs2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/LoopListSource2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/LoopObservableItemsSource2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/ReorderableItemsViewController2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/ReorderableItemsViewDelegator2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/SelectableItemsViewController2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/SelectableItemsViewDelegator2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/StructuredItemsViewController2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/VerticalCell2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/VerticalDefaultCell2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/VerticalDefaultSupplementalView2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/VerticalSupplementaryView2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/WidthConstrainedTemplatedCell2.cs
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
Labels: area-controls-collectionview

#23873 [net9.0] Add `Window.Activate()`
  src/BlazorWebView/tests/MauiDeviceTests/MauiAppNewWindowStub.Windows.cs
  src/Compatibility/Core/tests/Compatibility.UnitTests/ApplicationStub.cs
  src/Controls/samples/Controls.Sample/Pages/Core/MultiWindowPage.xaml
  src/Controls/samples/Controls.Sample/Pages/Core/MultiWindowPage.xaml.cs
  src/Controls/src/Core/Application/Application.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/tests/Core.UnitTests/TestClasses/ApplicationStub.cs
  src/Controls/tests/DeviceTests/Stubs/MauiAppNewWindowStub.Windows.cs
  src/Core/src/Core/IApplication.cs
  src/Core/src/Handlers/Application/ApplicationHandler.Android.cs
  src/Core/src/Handlers/Application/ApplicationHandler.Standard.cs
  src/Core/src/Handlers/Application/ApplicationHandler.Tizen.cs
  src/Core/src/Handlers/Application/ApplicationHandler.Windows.cs
  src/Core/src/Handlers/Application/ApplicationHandler.cs
  src/Core/src/Handlers/Application/ApplicationHandler.iOS.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Core/tests/Benchmarks/Stubs/ApplicationStub.cs
  src/Core/tests/DeviceTests.Shared/Stubs/CoreApplicationStub.cs
  src/Core/tests/UnitTests/TestClasses/ApplicationStub.cs
Labels: community ✨, area-controls-window
