Repository dotnet/maui, pull requests merged in 2025-03, with the labels that each got.

#28136 [iOS] Ignore for now obsoletes on iOS
  src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs
  src/Core/src/Platform/iOS/MauiWebViewUIDelegate.cs
Labels: platform/iOS 🍎

#26785 [iOS] Fixed ImageButton not honoring Padding value.
  src/Controls/src/Core/ImageButton/ImageButton.iOS.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ImageButtonUITests_Padding_Add_Added.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ImageButtonUITests_Padding_Initial.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ImageButtonUITests_Padding_Add_Added.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ImageButtonUITests_Padding_Initial.png
  src/Core/src/Handlers/ImageButton/ImageButtonHandler.iOS.cs
  src/Core/src/Platform/iOS/ImageViewExtensions.cs
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
Labels: community ✨, area-controls-button, partner/syncfusion

#28073 [Windows] Optimize formatted labels
  src/Controls/src/Core/Platform/Windows/Extensions/FormattedStringExtensions.cs
Labels: platform/windows 🪟, community ✨, area-controls-label, t/perf

#28125 Fix broken/unreliable UI tests
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CarouselViewShouldRenderCorrectly.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue25371.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/FlyoutItemTextShouldDisplayProperly.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/UpdatedIsEnabledProperty.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25371.cs
Labels: area-testing, community ✨

#24329 [Windows] Bump `Microsoft.Web.WebView2` from `1.0.2792.45` to `1.0.2903.40`
  eng/Versions.props
Labels: area-infrastructure, community ✨

#27534 [Android] [Shell] Ensure `AnimationFinished` is called when app backgrounds mid-animation
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellContentFragment.cs
Labels: area-animation, platform/android 🤖, community ✨

#28055 [Testing] Enabling UITest Stepper actions for Maccatalyst
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20706.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/StepperUITests.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumAppleStepperActions.cs
  src/TestUtils/src/UITest.Appium/AppiumCatalystApp.cs
  src/TestUtils/src/UITest.Appium/AppiumIOSApp.cs
Labels: area-testing, community ✨, partner/syncfusion

#28137 [Testing] Fix for flaky UITests in CI that occasionally fail - 4
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue16910.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25889.cs
Labels: area-testing, community ✨, partner/syncfusion

#28143 2025-3-3-docs-UiTesting.md-improvements
  docs/design/UITesting.md
Labels: area-docs, community ✨

#26629 Change iOS SetNeedsLayout propagation mechanism
  src/Controls/src/Core/Compatibility/Handlers/iOS/FrameRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/iOS/VisualElementRenderer.cs
  src/Controls/src/Core/Handlers/Items/iOS/MauiCollectionView.cs
  src/Controls/src/Core/ImageButton/ImageButton.iOS.cs
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/tests/DeviceTests/Elements/CarouselView/CarouselViewTests.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue24996.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue24996.xaml.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Issue18242Test.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24996.cs
  src/Core/src/Handlers/Button/ButtonHandler.iOS.cs
  src/Core/src/Handlers/ImageButton/ImageButtonHandler.iOS.cs
  src/Core/src/Handlers/Layout/LayoutHandler.iOS.cs
  src/Core/src/Handlers/Page/PageHandler.iOS.cs
  src/Core/src/Platform/iOS/ContentView.cs
  src/Core/src/Platform/iOS/IPlatformMeasureInvalidationController.cs
  src/Core/src/Platform/iOS/ImageViewExtensions.cs
  src/Core/src/Platform/iOS/LayoutView.cs
  src/Core/src/Platform/iOS/MauiScrollView.cs
  src/Core/src/Platform/iOS/MauiView.cs
  src/Core/src/Platform/iOS/PageViewController.cs
  src/Core/src/Platform/iOS/ViewExtensions.cs
  src/Core/src/Platform/iOS/WrapperView.cs
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
Labels: area-layout, p/0, community ✨

#27851 Fixed the CollectionView scroll the content inside Editor when tapping to get focus on it
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ShouldIgnoreBottomContentInsetForCollectionViewItems.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue27766.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ShouldIgnoreBottomContentInsetForCollectionViewItems.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27766.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ShouldIgnoreBottomContentInsetForCollectionViewItems.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ShouldIgnoreBottomContentInsetForCollectionViewItems.png
  src/Core/src/Platform/iOS/KeyboardAutoManagerScroll.cs
Labels: area-controls-collectionview, community ✨, s/pr-needs-author-input, partner/syncfusion

#28138 [Bindings SG] Filter out false positive Binding.Create matches
  src/Controls/src/BindingSourceGen/BindingSourceGenerator.cs
  src/Controls/tests/BindingSourceGen.UnitTests/DiagnosticsTests.cs
Labels: p/0

#27812 Fix CSS Hot Reload on iOS device
  src/BlazorWebView/src/SharedSource/StaticContentHotReloadManager.cs
Labels: area-tooling

#27968 [Testing] Enabling more UI Tests by removing platform specific condition - 16
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue2775Test.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue2617.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue2775.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Issue2775Test.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue16321.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue1799.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue1900.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25724.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue2617.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue2775.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue5354.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue5724.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue7313.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/Issue2775Test.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue2775Test.png
Labels: area-testing, community ✨, partner/syncfusion

#28105 [Testing] Migration of Compatibility.Core platform-specific unit tests into device tests - 4
  src/Controls/tests/DeviceTests/Elements/BoxView/BoxViewTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/BoxView/BoxViewTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/BoxView/BoxViewTests.cs
  src/Controls/tests/DeviceTests/Elements/BoxView/BoxViewTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Button/ButtonTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Button/ButtonTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Button/ButtonTests.cs
  src/Controls/tests/DeviceTests/Elements/CheckBox/CheckBoxTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/CheckBox/CheckBoxTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/CheckBox/CheckBoxTests.cs
  src/Controls/tests/DeviceTests/Elements/CheckBox/CheckBoxTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs
  src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Entry/EntryTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Entry/EntryTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Entry/EntryTests.cs
  src/Controls/tests/DeviceTests/Elements/Entry/EntryTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Image/ImageTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Image/ImageTests.cs
  src/Controls/tests/DeviceTests/Elements/Image/ImageTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Picker/PickerTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Picker/PickerTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Picker/PickerTests.cs
  src/Controls/tests/DeviceTests/Elements/Picker/PickerTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/RadioButton/RadioButtonTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/SearchBar/SearchBarTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/SearchBar/SearchBarTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/SearchBar/SearchBarTests.cs
  src/Controls/tests/DeviceTests/Elements/SearchBar/SearchBarTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/SwipeView/SwipeViewTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/SwipeView/SwipeViewTests.iOS.cs
Labels: area-testing, community ✨, partner/syncfusion

#28148 Fix Crashing issue with keyboard scrolling iOS
  src/Core/src/Platform/iOS/KeyboardAutoManagerScroll.cs
  src/Core/src/Platform/iOS/ViewExtensions.cs
Labels: platform/iOS 🍎, p/0, area-controls-entry

#28189 Revert "Fix FlyoutPage ShouldShowToolbarButton when overridden to return false, still shows button in title bar"
  src/Controls/src/Core/Platform/Windows/Extensions/ToolbarExtensions.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24547.cs
Labels: p/0, community ✨, partner/syncfusion

#28209 Fixed Navigation Toolbar Visibility Issue on Dynamic Flyout Reset in FlyoutPage.
  src/Controls/src/Core/NavigationPage/NavigationPageToolbar.cs
  src/Controls/tests/Core.UnitTests/FlyoutPageUnitTests.cs
Labels: area-navigation, area-controls-flyoutpage, community ✨, area-controls-flyout, partner/syncfusion

#28233 Update the version of SkiaSharp used by SVG
  src/SingleProject/Resizetizer/src/Resizetizer.csproj
  src/SingleProject/Resizetizer/src/ResizetizerPackages.projitems
Labels: p/0

#28194 [CollectionView] Crash occurs when switching CollectionView.IsVisible right after setting ItemsSource
  src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue28162.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue28162.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28162.cs
Labels: p/0, area-controls-collectionview, community ✨

#28229 Fix issue not provision sign identities on Devdiv Mac's
  eng/pipelines/common/provision.yml
  eng/provisioning/provisioning.csx
Labels: t/housekeeping ♻︎

#28077 Improve PropertyMapper performance
  src/Core/src/Handlers/FlyoutView/FlyoutViewHandler.Android.cs
  src/Core/src/Handlers/FlyoutView/FlyoutViewHandler.cs
  src/Core/src/Handlers/View/AndroidBatchPropertyMapper.cs
  src/Core/src/Handlers/View/ViewHandler.cs
  src/Core/src/Platform/iOS/ContainerViewController.cs
  src/Core/src/PropertyMapper.cs
  src/Core/tests/Benchmarks/Benchmarks/PropertyMapperBenchmarker.cs
  src/Core/tests/UnitTests/PropertyMapperTests.cs
Labels: p/0, community ✨, t/perf

#28250 Fix Modal Test using correct Page
  src/Controls/tests/DeviceTests/Elements/Modal/ModalTests.cs
Labels: area-testing, area-controls-modal, area-controls-window

#28246 [Revert] [iOS] CollectionView with grouped data crashes on iOS when the groups change - fix
  src/Controls/src/Core/Handlers/Items/iOS/ObservableGroupedSource.cs
  src/Controls/src/Core/Handlers/Items/iOS/ObservableItemsSource.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/BlankScreenOnNavigationBack.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue27797.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue27797.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue28098.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue28098.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27797.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28098.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/BlankScreenOnNavigationBack.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/BlankScreenOnNavigationBack.png
Labels: platform/iOS 🍎, p/0, area-controls-collectionview

#28230 [HybridWebView] Properly managed response streams
  src/Controls/tests/DeviceTests/Elements/HybridWebView/HybridWebViewTests.cs
  src/Controls/tests/DeviceTests/Resources/Raw/HybridTestRoot/index.html
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.Windows.cs
Labels: area-blazor, p/0

#28273 [net10.0] Move iOS 18.0 simulators
  eng/devices/ios.cake
  eng/pipelines/common/ui-tests.yml
  eng/pipelines/device-tests.yml
  eng/pipelines/ui-tests.yml
Labels: area-testing, testing-infrastructure, testing-green-ci

#28160 Replace deprecated iOS OpenUrl
  src/BlazorWebView/src/Maui/iOS/IOSWebViewManager.cs
Labels: area-blazor

#28265 Fix incorrect MAC Image
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/UpdatedIsEnabledProperty.png
Labels: area-testing

#28307 [release/10.0.1xx-preview2] Update sdk and runtime
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-infrastructure

#28269 [Testing] Fix for flaky UITests in CI that occasionally fail - 5
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CarouselViewShouldRenderCorrectly.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue25192.xaml
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/BlankScreenOnNavigationBack.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/CarouselItemsShouldRenderProperly.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/CarouselViewShouldRenderCorrectly.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/CarouselViewUITests.LoopNoFreeze.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20903.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25192.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27418.cs
Labels: area-testing, community ✨, partner/syncfusion

#28290 [net10.0] Remove mobile librarybuilder net9
  src/DotNet/DotNet.csproj
Labels: area-infrastructure, dependencies

#28028 Mark MapReload from PickerHandler Obsolete
  src/Core/src/Handlers/Picker/PickerHandler.Android.cs
  src/Core/src/Handlers/Picker/PickerHandler.Standard.cs
  src/Core/src/Handlers/Picker/PickerHandler.Tizen.cs
  src/Core/src/Handlers/Picker/PickerHandler.Windows.cs
  src/Core/src/Handlers/Picker/PickerHandler.iOS.cs
Labels: t/housekeeping ♻︎

#28328 [ci] Fix platform for UItests for iOS
  src/Controls/tests/TestCases.Shared.Tests/UITest.cs
Labels: area-testing, testing-green-ci

#28325 [ci] Fix provisionator
  eng/pipelines/common/provision.yml
Labels: t/housekeeping ♻︎

#28359 [ci] Add net10.0 to triggers
  eng/pipelines/azure-pipelines-internal.yml
  eng/pipelines/device-tests.yml
  eng/pipelines/handlers.yml
  eng/pipelines/maui-release.yml
  eng/pipelines/ui-tests.yml
Labels: t/housekeeping ♻︎

#28363 [ci] Remove macios workaround to build net9
  src/DotNet/DotNet.csproj
Labels: t/housekeeping ♻︎

#28369 [Testing] Mark BindingUpdatesFromInteractiveRefresh as flaky
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue16910.cs
Labels: area-testing, testing-flakiness

#28161 [Windows] Fix RightToLeft is not working for Shell
  src/Controls/src/Core/Handlers/Shell/ShellHandler.Windows.cs
  src/Controls/src/Core/Handlers/Shell/ShellHandler.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ShellFlowDirectionUpdate.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ShellFlowDirectionUpdate.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue17057.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ShellFlowDirectionUpdate.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ShellFlowDirectionUpdate.png
Labels: area-controls-shell, community ✨, partner/syncfusion

#28223 [Testing] Moved ImageDoesNotLeak test case from Device Test to UI Test
  src/Controls/tests/DeviceTests/Elements/Image/ImageTests.cs
  src/Controls/tests/TestCases.HostApp/Issues/MemoryTests.cs
  src/Controls/tests/TestCases.HostApp/Utils/GarbageCollectionHelper.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/MemoryTests.cs
Labels: area-testing, community ✨, partner/syncfusion

#28394 Update bug-report.yml
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: t/housekeeping ♻︎

#28395 [ci] Cleanup the provisionator Xcode script
  eng/provisioning/xcode.csx
Labels: t/housekeeping ♻︎, area-infrastructure

#28338 [Windows] Upgrade Windows App SDK from 1.6.5 to 1.6.6
  eng/Versions.props
Labels: platform/windows 🪟, community ✨

#28407 [testing] Disable CheckEntitlementsForMauiBlazorOnMacCatalyst
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/MacTemplateTest.cs
Labels: platform/macOS 🍏, platform/iOS 🍎, area-testing, testing-reenable, testing-green-ci

#28195 Made sudo optional for Linux jdk provisioning
  src/Provisioning/Provisioning.csproj
Labels: t/housekeeping ♻︎

#27971 [Accessibility] Add Accessibility Traits to CollectionView items on iOS/Catalyst
  src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs
  src/Controls/src/Core/Handlers/Items/iOS/TemplatedCell.cs
  src/Controls/src/Core/Handlers/Items2/iOS/SelectableItemsViewController2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs
  src/Controls/src/Core/Platform/iOS/Extensions/AcessibilityExtensions.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue26817.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue26817.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue26817_2.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue26817_2.xaml.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/AccessibilityTraitsSetCorrectlyMultiple.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/AccessibilityTraitsSetCorrectlyNone.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/AccessibilityTraitsSetCorrectlySingle.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26817.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26817_2.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/AccessibilityTraitsSetCorrectlyMultiple.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/AccessibilityTraitsSetCorrectlyNone.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/AccessibilityTraitsSetCorrectlySingle.png
Labels: platform/macOS 🍏, platform/iOS 🍎, area-controls-collectionview, t/a11y, collectionview-cv2

#28393 [Accessibility] Add 'button' for TalkBalk on Android Tap Gesture Recognizers
  src/Controls/src/Core/Platform/Android/Extensions/SemanticExtensions.cs
  src/Controls/src/Core/Platform/SemanticExtensions.cs
Labels: platform/android 🤖, area-gestures, t/a11y

#28216 Fixed content update issue when changing the ControlTemplate at runtime for a ContentPage
  src/Controls/src/Core/TemplatedPage.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue15649.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue15649.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue15649.cs
Labels: community ✨, area-controls-pages, partner/syncfusion

#28445 [net10.0] Merge main to net10
  .github/ISSUE_TEMPLATE/bug-report.yml
  eng/Versions.props
  eng/common/core-templates/steps/generate-sbom.yml
  eng/common/generate-sbom-prep.ps1
  eng/common/generate-sbom-prep.sh
  eng/common/templates-official/job/job.yml
  eng/provisioning/xcode.csx
  global.json
  src/Controls/tests/DeviceTests/Elements/Image/ImageTests.cs
  src/Controls/tests/TestCases.HostApp/Issues/MemoryTests.cs
  src/Controls/tests/TestCases.HostApp/Utils/GarbageCollectionHelper.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/MemoryTests.cs
  src/Provisioning/Provisioning.csproj
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/MacTemplateTest.cs
Labels: t/housekeeping ♻︎, area-infrastructure

#26180 Able to cancel WebAuthenticator.AuthenticateAsync programmatically using a CancellationToken #26137
  src/Essentials/src/PublicAPI/net-android/PublicAPI.Shipped.txt
  src/Essentials/src/PublicAPI/net-ios/PublicAPI.Shipped.txt
  src/Essentials/src/PublicAPI/net-maccatalyst/PublicAPI.Shipped.txt
  src/Essentials/src/PublicAPI/net-tizen/PublicAPI.Shipped.txt
  src/Essentials/src/PublicAPI/net-windows/PublicAPI.Shipped.txt
  src/Essentials/src/PublicAPI/net/PublicAPI.Shipped.txt
  src/Essentials/src/PublicAPI/netstandard/PublicAPI.Shipped.txt
  src/Essentials/src/WebAuthenticator/WebAuthenticator.android.cs
  src/Essentials/src/WebAuthenticator/WebAuthenticator.ios.tvos.cs
  src/Essentials/src/WebAuthenticator/WebAuthenticator.macos.cs
  src/Essentials/src/WebAuthenticator/WebAuthenticator.netstandard.watchos.tizen.cs
  src/Essentials/src/WebAuthenticator/WebAuthenticator.shared.cs
  src/Essentials/src/WebAuthenticator/WebAuthenticator.uwp.cs
  src/Essentials/test/DeviceTests/Tests/WebAuthenticator_Tests.cs
Labels: t/breaking 💥, area-essentials, community ✨, essentials-webauth

#27941 [Essentials] Functionality to check if GPS/Location is enabled
  src/Essentials/src/Geolocation/Geolocation.android.cs
  src/Essentials/src/Geolocation/Geolocation.ios.macos.cs
  src/Essentials/src/Geolocation/Geolocation.netstandard.tvos.watchos.cs
  src/Essentials/src/Geolocation/Geolocation.shared.cs
  src/Essentials/src/Geolocation/Geolocation.tizen.cs
  src/Essentials/src/Geolocation/Geolocation.uwp.cs
  src/Essentials/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Essentials/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Essentials/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Essentials/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Essentials/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Essentials/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Essentials/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
Labels: t/enhancement ☀️, proposal/open, area-essentials, community ✨, essentials-geolocation

#28423 [Testing] Fix: BlankScreenOnNavigationBack on Android
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/BlankScreenOnNavigationBack.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue28098.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue28098.xaml.cs
Labels: area-testing, community ✨, testing-flakiness

#28018 [Android] Fix: Prevent duplicate Completed event when setting ReturnType in Entry
  src/Controls/tests/TestCases.HostApp/Issues/Issue27992.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue27992.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27992.cs
  src/Core/src/Handlers/Entry/EntryHandler.Android.cs
Labels: platform/android 🤖, community ✨, area-controls-entry

#28469 Fix API docs warnings
  src/Controls/docs/Microsoft.Maui.Controls/ListView.xml
  src/Controls/src/Core/HybridWebView/HybridWebView.cs
  src/Core/src/Primitives/Keyboard.cs
Labels: area-docs, t/housekeeping ♻︎

#27220 [iOS] Fix for CursorPosition Property Not Applied Correctly to Entry Control
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/EntryShouldApplyCursorPositionCorrectly.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue19109.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/EntryShouldApplyCursorPositionCorrectly.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19109.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/EntryShouldApplyCursorPositionCorrectly.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/EntryShouldApplyCursorPositionCorrectly.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ValidateEntryClearButtonVisibilityBehavior.png
  src/Core/src/Handlers/Entry/EntryHandler.iOS.cs
Labels: t/bug, platform/iOS 🍎, community ✨, area-controls-entry, partner/syncfusion

#27873 [Windows] Fixed Shadow not updated when Clipping a View with a shadow
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ShadowShouldUpdateWhenClipping.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue27730.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ShadowShouldUpdateWhenClipping.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27730.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ShadowShouldUpdateWhenClipping.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ShadowShouldUpdateWhenClipping.png
  src/Core/src/Platform/Windows/WrapperView.cs
Labels: platform/windows 🪟, area-drawing, community ✨, partner/syncfusion

#27965 [Testing] Enabling more UI Tests by removing platform specific condition - 15
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue6458Test.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue6458.cs
  src/Controls/tests/TestCases.HostApp/Issues/ScrollViewObjectDisposed.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Issue6458Test.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue16561.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue17453.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19214.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19214_2.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19214_3.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19956.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue6458.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/ScrollViewObjectDisposed.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/Issue6458Test.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue6458Test.png
Labels: area-testing, community ✨, partner/syncfusion

#28060 [Testing] Enabling more UI Tests by removing platform specific condition - 19
  src/Controls/tests/TestCases.HostApp/Issues/Issue7453.xaml
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/BackgroundGradientsShouldRenderCorrectly.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Bugzilla56298Test.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ChangeShellContentTitle.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla56298.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla60123.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18751.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25193.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue7453.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue7534.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue9006.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue1414.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue6484.cs
Labels: area-testing, community ✨, partner/syncfusion

#28081 Fixed Label Visibility Issue on macOS and iOS
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/LabelWithPadding.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue19007.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/LabelWithPadding.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19007.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/LabelWithPadding.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/LabelWithPadding.png
  src/Core/src/Platform/iOS/MauiLabel.cs
Labels: platform/macOS 🍏, platform/iOS 🍎, community ✨, partner/syncfusion

#28193 [Testing] Migration of Compatibility.Core platform-specific unit tests into device tests - 5
  src/Controls/tests/DeviceTests/Elements/BoxView/BoxViewTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Button/ButtonTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/CheckBox/CheckBoxTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Entry/EntryTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Image/ImageTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Picker/PickerTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/SearchBar/SearchBarTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/SwipeView/SwipeViewTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/TabbedPage/TabbedPageTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/TemplatedView/TemplatedViewTests.Android.cs
Labels: area-testing, community ✨, partner/syncfusion

#28398 Fixed Stepper allows incrementing beyond the maximum value
  src/Controls/src/Core/Stepper/Stepper.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue28330.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28330.cs
Labels: community ✨, area-controls-stepper, partner/syncfusion

#28409 [Testing] Migration of Compatibility.Core platform-specific unit tests into device tests - 7
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/CollectionView/CollectionViewTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTests.Android.cs
Labels: area-testing, community ✨, partner/syncfusion

#28133 Fixed crash in CollectionView on iOS when updating grouped data.
  src/Controls/src/Core/Handlers/Items/iOS/ObservableGroupedSource.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue27797.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue27797.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27797.cs
Labels: area-navigation, platform/iOS 🍎, p/0, area-controls-collectionview, community ✨, partner/syncfusion

#28243 Make GraphicsViewHandler.MapBackground public
  src/Core/src/Handlers/GraphicsView/GraphicsViewHandler.Android.cs
  src/Core/src/Handlers/GraphicsView/GraphicsViewHandler.Windows.cs
  src/Core/src/Handlers/GraphicsView/GraphicsViewHandler.iOS.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
Labels: t/breaking 💥, area-drawing, t/housekeeping ♻︎

#28488 Update dotnet-format-daily-main.yml
  .github/workflows/dotnet-format-daily-main.yml
Labels: community ✨, area-sfi

#28447 Upgrade Syncfusion Toolkit version from 1.0.3 to 1.0.4
  src/Templates/src/templates/maui-mobile/MauiApp.1.csproj
Labels: p/0, area-templates, community ✨

#28482 [net10.0] Remove api check for Android PutString
  src/TestUtils/src/DeviceTests.Runners/HeadlessRunner/Android/MauiTestInstrumentation.cs
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/TestResources/TemplateLaunchInstrumentation.cs
Labels: platform/android 🤖

#25223 [Android] Fix ImageButton Padding the third
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ImageButtonPaddingDoesNotChangeWhenIsVisibleChanges.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue25201.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25201.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25201.cs
  src/Core/src/Handlers/ImageButton/ImageButtonHandler.Android.cs
  src/Core/src/Platform/Android/ImageButtonExtensions.cs
  src/Core/src/Platform/Android/MauiShapeableImageView.cs
Labels: platform/android 🤖, community ✨, area-controls-button, partner/syncfusion/review

#28506 ViewExtensions Async suffix consistency
  src/Controls/samples/Controls.Sample.Embedding/Platforms/Android/FirstFragment.cs
  src/Controls/samples/Controls.Sample.Embedding/Platforms/Android/SettingsFragment.cs
  src/Controls/samples/Controls.Sample.Embedding/Platforms/MacCatalyst/MainViewController.cs
  src/Controls/samples/Controls.Sample.Embedding/Platforms/Windows/MainWindow.xaml.cs
  src/Controls/samples/Controls.Sample.Embedding/Platforms/iOS/MainViewController.cs
  src/Controls/samples/Controls.Sample.Embedding/Shared/MyMauiContent.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/CarouselViewGalleries/ExampleTemplateCarousel.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/UserInterface/AnimationPage.xaml.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/ViewExtensions.cs
  src/Controls/tests/Core.UnitTests/TickerSystemEnabledTests.cs
  src/Controls/tests/Core.UnitTests/ViewUnitTests.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla39821.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue2482.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue8004.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue8801.cs
Labels: t/breaking 💥, area-animation

#26608 Fix for CarouselView doesnot scroll corresponding to ItemsUpdatingScrollMode when collection modified
  src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs
  src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs
  src/Controls/src/Core/Handlers/Items2/iOS/CarouselViewController2.cs
  src/Controls/tests/TestCases.HostApp/Issues/CarouselViewLoopNoFreeze.cs
  src/Controls/tests/TestCases.HostApp/Issues/CarouselViewRemoveAt.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue25991.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue8964.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25991.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue8964.cs
Labels: area-controls-collectionview, community ✨, partner/syncfusion

#28521 [Documentation] Page.DisplayAlert wrong documentation (Task vs Task<bool>) - fix
  src/Controls/src/Core/Page/Page.cs
Labels: area-docs, community ✨

#28244 [NET10.0] Annotate `ListStringTypeConverter` for nullability
  src/Controls/src/Core/ListStringTypeConverter.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
Labels: community ✨

#28255 [NET10.0] Fix parameter name for `ScrollViewerExtensions.UpdateScrollBarVisibility`
  src/Core/src/Platform/Windows/ScrollViewerExtensions.cs
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
Labels: community ✨

#28139 [.Net10] Make IsVisibleCore and RefreshIsVisibleProperty visible
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/VisualElement/VisualElement.cs
Labels: t/breaking 💥, area-architecture, community ✨

#28533 [Testing] Fix for flaky UITests Issue18896 and disable Issue14471 test which fails in CI randomly
  global.json
  src/Controls/tests/TestCases.HostApp/Issues/Issue18896.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue14471.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18896.cs
Labels: area-testing, community ✨, partner/syncfusion

#27147 [Windows] Fixed the text and icon color issues in the DatePicker when hovering over it.
  src/Controls/tests/DeviceTests/Elements/DatePicker/DatePickerTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/DatePicker/DatePickerTests.cs
  src/Controls/tests/DeviceTests/TestCategory.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue22987.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue22987.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22987.cs
  src/Core/src/Platform/Windows/DatePickerExtensions.cs
Labels: community ✨, partner/syncfusion

#28245 Remove PlatformWrapperView.java setHasShadow
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformWrapperView.java
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
Labels: t/breaking 💥, platform/android 🤖, area-drawing

#28548 [net10.0] Merge main to net10
  .github/workflows/dotnet-format-daily-main.yml
  src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs
  src/Controls/src/Core/Handlers/Items/iOS/TemplatedCell.cs
  src/Controls/src/Core/Handlers/Items2/iOS/SelectableItemsViewController2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs
  src/Controls/src/Core/Platform/Android/Extensions/SemanticExtensions.cs
  src/Controls/src/Core/Platform/SemanticExtensions.cs
  src/Controls/src/Core/Platform/iOS/DragAndDropDelegate.cs
  src/Controls/src/Core/Platform/iOS/Extensions/AcessibilityExtensions.cs
  src/Controls/src/Core/TemplatedPage.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/BlankScreenOnNavigationBack.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue15649.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue15649.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue18896.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue26817.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue26817.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue26817_2.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue26817_2.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue27992.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue27992.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue28098.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue28098.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue28416.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue28416.xaml.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/AccessibilityTraitsSetCorrectlyMultiple.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/AccessibilityTraitsSetCorrectlyNone.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/AccessibilityTraitsSetCorrectlySingle.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue14471.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue15649.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18896.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26817.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26817_2.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27992.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28416.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/AccessibilityTraitsSetCorrectlyMultiple.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/AccessibilityTraitsSetCorrectlyNone.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/AccessibilityTraitsSetCorrectlySingle.png
  src/Core/src/Handlers/Entry/EntryHandler.Android.cs
  src/Templates/src/templates/maui-mobile/MauiApp.1.csproj
Labels: t/housekeeping ♻︎

#25827 Fixed Keyboard Scrolling in editors with Center or End VerticalTextAlignment
  src/Controls/tests/TestCases.HostApp/Issues/Issue24977.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24977.cs
  src/Core/src/Platform/iOS/KeyboardAutoManagerScroll.cs
  src/Core/src/Platform/iOS/MauiTextView.cs
Labels: community ✨, area-keyboard, area-controls-editor, partner/syncfusion

#28456 System.MissingMethodException in PropertyPropagationExtensions fix
  src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs
Labels: area-xaml, t/housekeeping ♻︎, community ✨

#28545 [iOS] Changing carousel view orientation with disabled loop - fix
  src/Controls/src/Core/Handlers/Items/iOS/CarouselViewController.cs
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CarouselViewItemShouldScaleProperly.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue28523.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue28523.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28523.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/CarouselViewItemShouldScaleProperly.png
Labels: platform/iOS 🍎, area-controls-collectionview, community ✨

#27231 Fixed ScrollView Orientation Neither issue
  src/Controls/tests/TestCases.HostApp/Issues/Issue2680ScrollView.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue2680ScrollView.cs
  src/Core/src/Handlers/ScrollView/ScrollViewHandler.Windows.cs
  src/Core/src/Handlers/ScrollView/ScrollViewHandler.iOS.cs
  src/Core/src/Platform/Windows/ScrollViewerExtensions.cs
  src/Core/src/Platform/iOS/ScrollViewExtensions.cs
Labels: community ✨, area-controls-scrollview, partner/syncfusion

#28518 [ci] Update arcade net10.0
  .config/dotnet-tools.json
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/core-templates/job/job.yml
  eng/common/core-templates/job/publish-build-assets.yml
  eng/common/core-templates/jobs/codeql-build.yml
  eng/common/core-templates/jobs/jobs.yml
  eng/common/core-templates/post-build/post-build.yml
  eng/common/core-templates/steps/generate-sbom.yml
  eng/common/core-templates/steps/install-microbuild.yml
  eng/common/core-templates/steps/source-build.yml
  eng/common/cross/armel/armel.jessie.patch
  eng/common/cross/build-android-rootfs.sh
  eng/common/cross/build-rootfs.sh
  eng/common/cross/install-debs.py
  eng/common/cross/toolchain.cmake
  eng/common/native/install-dependencies.sh
  eng/common/post-build/publish-using-darc.ps1
  eng/common/sdk-task.ps1
  eng/common/sdk-task.sh
  eng/common/templates-official/job/job.yml
  eng/common/templates-official/steps/publish-build-artifacts.yml
  eng/common/templates/job/job.yml
  eng/common/templates/steps/publish-build-artifacts.yml
  eng/common/tools.ps1
  eng/common/tools.sh
  eng/pipelines/common/variables.yml
  global.json
Labels: area-infrastructure

#28534 Fix HideSoftInputOnTapped Not Working Net9
  src/Controls/src/Core/ContentPage/HideSoftInputOnTappedChanged/HideSoftInputOnTappedChangedManager.Android.cs
  src/Controls/src/Core/ContentPage/HideSoftInputOnTappedChanged/HideSoftInputOnTappedChangedManager.Platform.cs
  src/Controls/src/Core/ContentPage/HideSoftInputOnTappedChanged/HideSoftInputOnTappedChangedManager.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue26792.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26792.cs
Labels: community ✨, area-keyboard, partner/syncfusion

#28467 [.NET 10] More public APIs related with Entry and Editor, pending TODOs
  src/Core/src/Handlers/Editor/EditorHandler.Android.cs
  src/Core/src/Handlers/Entry/EntryHandler.Android.cs
  src/Core/src/Platform/Android/EditTextExtensions.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
Labels: t/breaking 💥, t/housekeeping ♻︎, area-controls-entry

#28591 [ci] Don't use the short url for install script
  src/DotNet/DotNet.csproj
Labels: area-infrastructure

#28485 [iOS] Back-navigation with swipe-back navigates back twice - fix
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue28485.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28485.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumIOSSpecificActions.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: platform/iOS 🍎, p/0, area-controls-shell, community ✨

#27876 [Testing] - Fix for flaky UITests related to the virtual keyboard in Android and iOS platforms
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ShouldIgnoreBottomContentInsetForCollectionViewItems.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyInitialEntryReturnTypeChange.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19152.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21109.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27766.cs
  src/Controls/tests/TestCases.Shared.Tests/UITest.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/EntryClearButtonColorShouldMatchTextColor.png
Labels: area-testing, community ✨, partner/syncfusion

#28584 Fixed Test case failure in PR 28560
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/EntryShouldApplyCursorPositionCorrectly.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue19109.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/EntryShouldApplyCursorPositionCorrectly.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19109.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/EntryShouldApplyCursorPositionCorrectly.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/EntryShouldApplyCursorPositionCorrectly.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/RadioButtonUpdateValueInsideBorderYes.png
Labels: area-testing, community ✨, partner/syncfusion, test-flight

#28214 Fix for border color of the RadioButton is visible in Windows
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ValidateRadioButtonNoBorderColorWhenNoBorderWidth.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue28153.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ValidateRadioButtonNoBorderColorWhenNoBorderWidth.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28153.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/RadioButtonShouldApplyPropertiesCorrectly.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/RadioButtonUpdateValueInsideBorderNo.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/RadioButtonUpdateValueInsideBorderYes.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/RadioButtonWithValueChangeSelected.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ValidateRadioButtonNoBorderColorWhenNoBorderWidth.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ValidateRadioButtonNoBorderColorWhenNoBorderWidth.png
  src/Core/src/Platform/Windows/RadioButtonExtensions.cs
Labels: community ✨, area-controls-radiobutton, partner/syncfusion

#28225 Improve iOS CollectionView performance by leveraging the new platform level invalidation mechanism
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewCell.cs
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewLayout.cs
  src/Controls/src/Core/Handlers/Items/iOS/MauiCollectionView.cs
  src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs
  src/Controls/src/Core/Handlers/Items/iOS/TemplatedCell.cs
  src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewCell2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewController2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/StructuredItemsViewController2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/tests/TestCases.HostApp/Elements/CollectionView/DataTemplateSelectorGallery.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25671.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25671.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue13203.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue9686.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/CarouselViewItemsShouldRenderVertically.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21967.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25362.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25671.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue9686.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/CarouselViewItemsShouldRenderVertically.png
  src/Core/src/Platform/iOS/ViewExtensions.cs
Labels: p/0, area-controls-collectionview, community ✨, t/perf, collectionview-cv2

#28577 [Testing] Implemented InteractivePopGesture
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28485.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing, community ✨

#28027 Update default value for LineHeight in the ToNSAttributedString method
  src/Controls/src/Core/Platform/Windows/Extensions/FormattedStringExtensions.cs
  src/Controls/src/Core/Platform/iOS/Extensions/FormattedStringExtensions.cs
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
Labels: t/breaking 💥, t/housekeeping ♻︎, area-controls-label, needs-breaking-change-doc-created

#24906 [Improvement] Add ReturnType API for SearchBar
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/SearchBar/SearchBar.cs
  src/Core/src/Core/ISearchBar.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.Android.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.Standard.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.Tizen.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.Windows.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.iOS.cs
  src/Core/src/Platform/Android/SearchViewExtensions.cs
  src/Core/src/Platform/Windows/SearchBarExtensions.cs
  src/Core/src/Platform/iOS/SearchBarExtensions.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Core/tests/DeviceTests/Handlers/SearchBar/SearchBarHandlerTests.Android.cs
  src/Core/tests/DeviceTests/Handlers/SearchBar/SearchBarHandlerTests.iOS.cs
  src/Core/tests/DeviceTests/Stubs/SearchBarStub.cs
Labels: t/enhancement ☀️, community ✨, area-controls-searchbar

#28305 Align the Sender between the gestures when emit the events
  src/Controls/src/Core/DragAndDrop/DragGestureRecognizer.cs
  src/Controls/src/Core/DragAndDrop/DropGestureRecognizer.cs
  src/Controls/tests/TestCases.HostApp/Elements/DragAndDropBetweenLayouts.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue17531.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue17531.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue17531.cs
Labels: area-gestures

#28583 [Testing] Fix for flaky UITests in CI that occasionally fail - 5
  src/Controls/tests/TestCases.HostApp/Issues/Issue18751.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue19500.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue19500.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue19509.xaml.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/TextInEditorShouldScroll.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18751.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19509.cs
Labels: area-testing, community ✨, partner/syncfusion

#28611 [net10.0] Merge main to net10
  src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs
  src/Controls/src/Core/Handlers/Items/Android/SizedItemContentView.cs
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewCell.cs
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewLayout.cs
  src/Controls/src/Core/Handlers/Items/iOS/MauiCollectionView.cs
  src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs
  src/Controls/src/Core/Handlers/Items/iOS/TemplatedCell.cs
  src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewCell2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/ItemsViewController2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/StructuredItemsViewController2.cs
  src/Controls/src/Core/Handlers/Items2/iOS/TemplatedCell2.cs
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/AddItemsToCarouselViewWorks.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CarouselItemsShouldRenderProperly.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CarouselViewItemsShouldRenderVertically.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CarouselViewShouldRenderCorrectly.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CollectionViewEmptyViewFillsAvailableSpaceByDefault.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ShouldIgnoreBottomContentInsetForCollectionViewItems.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ValidateRadioButtonNoBorderColorWhenNoBorderWidth.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyInitialEntryReturnTypeChange.png
  src/Controls/tests/TestCases.HostApp/Elements/CollectionView/DataTemplateSelectorGallery.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue18751.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue19500.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue19500.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue19509.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue25671.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25671.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue28153.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue13203.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue9686.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/CarouselViewItemsShouldRenderVertically.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/TextInEditorShouldScroll.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ValidateRadioButtonNoBorderColorWhenNoBorderWidth.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18751.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19152.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19509.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21109.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21967.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25362.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25671.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27766.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28153.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue9686.cs
  src/Controls/tests/TestCases.Shared.Tests/UITest.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/RadioButtonShouldApplyPropertiesCorrectly.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/RadioButtonUpdateValueInsideBorderNo.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/RadioButtonUpdateValueInsideBorderYes.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/RadioButtonWithValueChangeSelected.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ValidateRadioButtonNoBorderColorWhenNoBorderWidth.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/CarouselViewItemsShouldRenderVertically.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/EntryClearButtonColorShouldMatchTextColor.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ValidateRadioButtonNoBorderColorWhenNoBorderWidth.png
  src/Core/src/Platform/Windows/RadioButtonExtensions.cs
  src/Core/src/Platform/iOS/ViewExtensions.cs
  src/DotNet/DotNet.csproj
Labels: t/housekeeping ♻︎, area-infrastructure

#15472 [Android] Allow full screen videos from WebView
  src/Controls/samples/Controls.Sample/Pages/Controls/WebViewGalleries/WebViewFullScreenVideoGallery.xaml
  src/Controls/samples/Controls.Sample/Pages/Controls/WebViewGalleries/WebViewFullScreenVideoGallery.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/WebViewGalleries/WebViewGalleries.cs
  src/Controls/samples/Controls.Sample/Pages/Controls/WebViewGalleries/WebViewGallery.xaml
  src/Controls/samples/Controls.Sample/Pages/Controls/WebViewGalleries/WebViewGallery.xaml.cs
  src/Controls/samples/Controls.Sample/ViewModels/ControlsViewModel.cs
  src/Core/src/Platform/Android/MauiWebChromeClient.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
Labels: t/bug, platform/android 🤖, area-controls-webview

#28103 [Testing] Migration of Compatibility.Core platform-specific unit tests into device tests - 3
  src/Controls/tests/DeviceTests/Elements/BoxView/BoxViewTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/BoxView/BoxViewTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/BoxView/BoxViewTests.cs
  src/Controls/tests/DeviceTests/Elements/Button/ButtonTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/CheckBox/CheckBoxTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/CheckBox/CheckBoxTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/CheckBox/CheckBoxTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/RadioButton/RadioButtonTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/SearchBar/SearchBarTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/SearchBar/SearchBarTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/SwipeView/SwipeViewTests.Android.cs
Labels: area-testing, community ✨, partner/syncfusion

#28529 [Windows] Fixed the issue with SearchBar focus and unfocus events.
  src/Controls/tests/TestCases.HostApp/Issues/Issue28419.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28419.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.Windows.cs
  src/Core/src/Handlers/View/ViewHandler.Windows.cs
Labels: community ✨, area-controls-searchbar, partner/syncfusion

#28069 [Housekeeping] Controls sample navigation crash - fix
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/Android/AndroidTabbedPageSwipePage.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/Android/AndroidTitleViewPage.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/iOS/iOSLargeTitlePage.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/iOS/iOSScrollViewPage.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/iOS/iOSTitleViewPage.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/iOS/iOSTranslucentNavigationBarPage.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/iOS/iOSTranslucentTabbedPage.xaml.cs
  src/Controls/samples/Controls.Sample/ViewModels/PlatformSpecificsViewModel.cs
Labels: area-navigation, t/housekeeping ♻︎, community ✨

#28058 [Testing] Migration of Compatibility.Core platform-specific unit tests into device tests - 2
  src/Controls/tests/DeviceTests/Elements/Border/BorderTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/BoxView/BoxViewTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/BoxView/BoxViewTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/BoxView/BoxViewTests.cs
  src/Controls/tests/DeviceTests/Elements/BoxView/BoxViewTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Button/ButtonTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Button/ButtonTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Button/ButtonTests.cs
  src/Controls/tests/DeviceTests/Elements/Button/ButtonTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/CheckBox/CheckBoxTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/CheckBox/CheckBoxTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/CheckBox/CheckBoxTests.cs
  src/Controls/tests/DeviceTests/Elements/CheckBox/CheckBoxTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs
  src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Entry/EntryTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Entry/EntryTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Entry/EntryTests.cs
  src/Controls/tests/DeviceTests/Elements/Entry/EntryTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/RadioButton/RadioButtonTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/SearchBar/SearchBarTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/SearchBar/SearchBarTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/SearchBar/SearchBarTests.cs
  src/Controls/tests/DeviceTests/Elements/SearchBar/SearchBarTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/SwipeView/SwipeViewTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/SwipeView/SwipeViewTests.iOS.cs
Labels: area-testing, community ✨, partner/syncfusion

#28627 Fix Tizen method parameter name misspelling
  src/Core/src/Fonts/FontManager.Tizen.cs
  src/Core/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
Labels: t/breaking 💥, t/housekeeping ♻︎, area-fonts, platform/tizen

#24365 Investigating things for easier Aspire integration
  eng/NuGetVersions.targets
  eng/Version.Details.xml
  eng/Versions.props
  eng/automation/LocProject.json
  src/Core/src/Core.csproj
  src/Core/src/Hosting/Dispatching/AppHostBuilderExtensions.cs
  src/Core/src/Hosting/MauiAppBuilder.cs
  src/Core/src/Hosting/MauiHostEnvironment.cs
  src/Core/src/Hosting/MauiMetricsBuilder.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Templates/src/templates/maui-aspire-servicedefaults/.template.config/dotnetcli.json
  src/Templates/src/templates/maui-aspire-servicedefaults/.template.config/ide.host.json
  src/Templates/src/templates/maui-aspire-servicedefaults/.template.config/ide/AspireServiceDefaults.ico
  src/Templates/src/templates/maui-aspire-servicedefaults/.template.config/localize/templatestrings.cs.json
  src/Templates/src/templates/maui-aspire-servicedefaults/.template.config/localize/templatestrings.de.json
  src/Templates/src/templates/maui-aspire-servicedefaults/.template.config/localize/templatestrings.en.json
  src/Templates/src/templates/maui-aspire-servicedefaults/.template.config/localize/templatestrings.es.json
  src/Templates/src/templates/maui-aspire-servicedefaults/.template.config/localize/templatestrings.fr.json
  src/Templates/src/templates/maui-aspire-servicedefaults/.template.config/localize/templatestrings.it.json
  src/Templates/src/templates/maui-aspire-servicedefaults/.template.config/localize/templatestrings.ja.json
  src/Templates/src/templates/maui-aspire-servicedefaults/.template.config/localize/templatestrings.json
  src/Templates/src/templates/maui-aspire-servicedefaults/.template.config/localize/templatestrings.ko.json
  src/Templates/src/templates/maui-aspire-servicedefaults/.template.config/localize/templatestrings.pl.json
  src/Templates/src/templates/maui-aspire-servicedefaults/.template.config/localize/templatestrings.pt-BR.json
  src/Templates/src/templates/maui-aspire-servicedefaults/.template.config/localize/templatestrings.ru.json
  src/Templates/src/templates/maui-aspire-servicedefaults/.template.config/localize/templatestrings.tr.json
  src/Templates/src/templates/maui-aspire-servicedefaults/.template.config/localize/templatestrings.zh-Hans.json
  src/Templates/src/templates/maui-aspire-servicedefaults/.template.config/localize/templatestrings.zh-Hant.json
  src/Templates/src/templates/maui-aspire-servicedefaults/.template.config/template.json
  src/Templates/src/templates/maui-aspire-servicedefaults/Extensions.cs
  src/Templates/src/templates/maui-aspire-servicedefaults/Maui.ServiceDefaults.csproj
Labels: t/breaking 💥, area-core-hosting

#28513 [Testing] Move Android UITests to run on Linux
  eng/pipelines/common/device-tests-steps.yml
  eng/pipelines/common/ui-tests-steps.yml
  eng/pipelines/common/ui-tests.yml
  eng/pipelines/ui-tests.yml
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue10222.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue5724.cs
Labels: area-testing

#25397 SwipeItemView won't render FontImageSource on first opening - fix
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ItemImageSourceShouldBeVisible.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue18806.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue18806.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18806.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ItemImageSourceShouldBeVisible.png
  src/Core/src/Platform/Android/MauiSwipeView.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
Labels: platform/windows 🪟, platform/android 🤖, platform/iOS 🍎, community ✨, area-controls-swipeview

#28647 [net10.0] Merge main to net10
  eng/Signing.props
  eng/pipelines/common/device-tests-steps.yml
  eng/pipelines/common/ui-tests-steps.yml
  eng/pipelines/common/ui-tests.yml
  eng/pipelines/ui-tests.yml
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/Android/AndroidTabbedPageSwipePage.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/Android/AndroidTitleViewPage.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/iOS/iOSLargeTitlePage.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/iOS/iOSScrollViewPage.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/iOS/iOSTitleViewPage.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/iOS/iOSTranslucentNavigationBarPage.xaml.cs
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/iOS/iOSTranslucentTabbedPage.xaml.cs
  src/Controls/samples/Controls.Sample/ViewModels/PlatformSpecificsViewModel.cs
  src/Controls/tests/DeviceTests/Elements/Border/BorderTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/BoxView/BoxViewTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/BoxView/BoxViewTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/BoxView/BoxViewTests.cs
  src/Controls/tests/DeviceTests/Elements/BoxView/BoxViewTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Button/ButtonTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Button/ButtonTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Button/ButtonTests.cs
  src/Controls/tests/DeviceTests/Elements/Button/ButtonTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/CheckBox/CheckBoxTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/CheckBox/CheckBoxTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/CheckBox/CheckBoxTests.cs
  src/Controls/tests/DeviceTests/Elements/CheckBox/CheckBoxTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs
  src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Entry/EntryTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Entry/EntryTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Entry/EntryTests.cs
  src/Controls/tests/DeviceTests/Elements/Entry/EntryTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/RadioButton/RadioButtonTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/SearchBar/SearchBarTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/SearchBar/SearchBarTests.Windows.cs
  src/Controls/tests/DeviceTests/Elements/SearchBar/SearchBarTests.cs
  src/Controls/tests/DeviceTests/Elements/SearchBar/SearchBarTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/SwipeView/SwipeViewTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/SwipeView/SwipeViewTests.iOS.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue28419.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue10222.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28419.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue5724.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.Windows.cs
  src/Core/src/Handlers/View/ViewHandler.Windows.cs
Labels: t/housekeeping ♻︎

#28355 Make it safer to set TestCases.HostApp main page
  .gitignore
  docs/design/UITesting.md
  src/Controls/tests/TestCases.HostApp/MauiProgram.cs
Labels: t/housekeeping ♻︎, area-testing, community ✨

#28665 [tests] Fix ItemImageSourceShouldBeVisible
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ItemImageSourceShouldBeVisible.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18806.cs
  src/Core/src/Handlers/SwipeView/SwipeViewHandler.Windows.cs
Labels: area-testing, area-controls-swipeview

#28471 [Windows] Fix IsPresented property not updating correctly in FlyoutPage
  src/Controls/tests/TestCases.HostApp/Issues/Issue28440.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28440.cs
  src/Core/src/Handlers/FlyoutView/FlyoutViewHandler.Windows.cs
Labels: area-controls-flyoutpage, community ✨, partner/syncfusion

#28371 [Windows] Fixed BackButton visibility issue when switching tabs without NavigationPage
  src/Controls/src/Core/Platform/Windows/Extensions/ToolbarExtensions.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/TabbedPageBackButtonUpdated.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue14689.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/TabbedPageBackButtonUpdated.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue14689.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/TabbedPageBackButtonUpdated.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/TabbedPageBackButtonUpdated.png
Labels: platform/windows 🪟, area-navigation, community ✨, partner/syncfusion

#28340 [Windows] WebView Navigated event is still called even after cancelling the Navigation.
  src/Controls/tests/TestCases.HostApp/Issues/Issue28303.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28303.cs
  src/Core/src/Handlers/WebView/WebViewHandler.Windows.cs
Labels: platform/windows 🪟, community ✨, area-controls-webview, partner/syncfusion

#28673 [ci] We do want macos15
  eng/pipelines/common/variables.yml
Labels: t/housekeeping ♻︎, area-infrastructure

#28215 Fixed the Label not sized correctly on Android
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/LabelShouldSizeCorrectlyOnHorizontalCenterLayoutOptions.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/LabelShouldSizeCorrectlyOnHorizontalEndLayoutOptions.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/LabelShouldSizeCorrectlyOnHorizontalStartLayoutOptions.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/WordWrapLineBreakModeNoExtraSpace.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue27614.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/LabelShouldSizeCorrectlyOnHorizontalCenterLayoutOptions.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/LabelShouldSizeCorrectlyOnHorizontalEndLayoutOptions.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/LabelShouldSizeCorrectlyOnHorizontalStartLayoutOptions.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27614.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/LabelShouldSizeCorrectlyOnHorizontalCenterLayoutOptions.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/LabelShouldSizeCorrectlyOnHorizontalEndLayoutOptions.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/LabelShouldSizeCorrectlyOnHorizontalStartLayoutOptions.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/LabelShouldSizeCorrectlyOnHorizontalCenterLayoutOptions.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/LabelShouldSizeCorrectlyOnHorizontalEndLayoutOptions.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/LabelShouldSizeCorrectlyOnHorizontalStartLayoutOptions.png
  src/Core/src/Platform/Android/MauiTextView.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
Labels: platform/android 🤖, community ✨, area-controls-label, partner/syncfusion

#28177 [Testing] Implement methods to manage alerts from UITests on Windows
  src/Controls/tests/TestCases.Shared.Tests/Tests/Concepts/AlertsGalleryTests.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumWindowsAlertActions.cs
  src/TestUtils/src/UITest.Appium/AppiumWindowsApp.cs
Labels: t/housekeeping ♻︎, area-testing

#28181 [Testing] Allow to use Theme changes actions on Catalyst
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: t/housekeeping ♻︎, area-testing

#28240 [Windows] Flyout Menu Icon disappears from Window Title Bar after Navigation
  src/Controls/src/Core/NavigationPage/NavigationPageToolbar.cs
  src/Controls/src/Core/Platform/Windows/Extensions/ToolbarExtensions.cs
  src/Controls/src/Core/ShellToolbar.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue28130_flyout.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue28130_shell.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24547.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28130_flyout.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28130_shell.cs
Labels: platform/windows 🪟, area-controls-shell, community ✨, partner/syncfusion

#28400 [Android, iOS] Dynamically setting SearchHandler Query property does not update text in the search box
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/SearchHandlerAppearanceTracker.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/SearchHandlerAppearanceTracker.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue14497.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue14497.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: platform/android 🤖, platform/iOS 🍎, area-controls-shell, community ✨, partner/syncfusion

#28696 [ci] Update arcade to latest
  .config/dotnet-tools.json
  eng/Signing.props
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/CIBuild.cmd
  eng/common/build.ps1
  eng/common/build.sh
  eng/common/cibuild.sh
  eng/common/core-templates/steps/install-microbuild.yml
  eng/pipelines/arcade/stage-pack.yml
  global.json
Labels: area-infrastructure

#28630 Fix up net10 TODOs in PropertyMapper
  src/Core/src/PropertyMapper.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
Labels: t/breaking 💥, t/housekeeping ♻︎, area-architecture

#28719 [ci] try publish the zip
  eng/Publishing.props
Labels: area-infrastructure
