Repository dotnet/maui, pull requests merged in 2025-05, with the labels that each got.

#29048 [Windows] Fix for Argument Exception raised when the GetStringSize method of ICanvas called with default font
  src/Controls/tests/TestCases.HostApp/Issues/Issue20419.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20419.cs
  src/Graphics/src/Graphics/Platforms/Windows/FontExtensions.cs
  src/Graphics/src/Graphics/Platforms/Windows/PlatformStringSizeService.cs
Labels: platform/windows 🪟, area-drawing, community ✨, partner/syncfusion

#29173 Fixes footer position not updated on CV1 when clearing all items
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs
  src/Controls/tests/TestCases.HostApp/Elements/CollectionView/HeaderFooterGalleries/HeaderFooterView.xaml
  src/Controls/tests/TestCases.HostApp/Elements/CollectionView/HeaderFooterGalleries/HeaderFooterView.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/CollectionView/CollectionViewUITests.HeaderAndFooter.cs
Labels: p/0, area-controls-collectionview, community ✨

#29226 [Testing] Re-Enabled UI Test - Issue10222Test
  src/Controls/tests/TestCases.HostApp/Issues/Issue10222.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue10222.cs
Labels: area-testing, community ✨, partner/syncfusion

#29230 [Testing] Feature Matrix UITest Cases for CollectionView Scrolling Feature
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyMeasureAllItemsWithGroupedList.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyMeasureAllItemsWithGroupedListWhenHorizontalGrid.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyMeasureAllItemsWithGroupedListWhenHorizontalList.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyMeasureAllItemsWithGroupedListWhenVerticalGrid.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyMeasureAllItemsWithObservableCollection.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyMeasureAllItemsWithObservableCollectionWhenHorizontalGrid.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyMeasureAllItemsWithObservableCollectionWhenHorizontalList.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyMeasureAllItemsWithObservableCollectionWhenVerticalGrid.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyMeasureFirstItemsWithGroupedList.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyMeasureFirstItemsWithObservableCollection.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyMeasureFirstItemsWithObservableCollectionWhenVerticalGrid.png
  src/Controls/tests/TestCases.HostApp/FeatureMatrix/CollectionView/CollectionViewFeaturePage.xaml
  src/Controls/tests/TestCases.HostApp/FeatureMatrix/CollectionView/CollectionViewFeaturePage.xaml.cs
  src/Controls/tests/TestCases.HostApp/FeatureMatrix/CollectionView/CollectionViewViewModel.cs
  src/Controls/tests/TestCases.HostApp/FeatureMatrix/CollectionView/ScrollingFeature/CollectionViewScrollPage.xaml
  src/Controls/tests/TestCases.HostApp/FeatureMatrix/CollectionView/ScrollingFeature/CollectionViewScrollPage.xaml.cs
  src/Controls/tests/TestCases.HostApp/FeatureMatrix/CollectionView/ScrollingFeature/ScrollBehaviorOptionsPage.xaml
  src/Controls/tests/TestCases.HostApp/FeatureMatrix/CollectionView/ScrollingFeature/ScrollBehaviorOptionsPage.xaml.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyMeasureAllItemsWithGroupedList.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyMeasureAllItemsWithObservableCollection.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/FeatureMatrix/CollectionView_ScrollingFeatureTests.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifyMeasureAllItemsWithObservableCollection.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyMeasureAllItemsWithGroupedList.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyMeasureAllItemsWithObservableCollection.png
Labels: area-controls-collectionview, area-testing, community ✨, partner/syncfusion

#29276 [NET10.0] Annotate converters for nullability 2/n
  src/Controls/src/Core/DoubleCollectionConverter.cs
  src/Controls/src/Core/FlowDirectionConverter.cs
  src/Controls/src/Core/ImageSourceConverter.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
Labels: community ✨

#29256 [Windows] Remove workarounds from `WinUI.targets`
  src/Core/src/nuget/buildTransitive/WinUI.targets
Labels: platform/windows 🪟, community ✨

#29326 [GitHub] Update breaking change tag to PMs
  .github/policies/resourceManagement.yml
Labels: t/housekeeping ♻︎

#29210 [Android] Fixed Setting a Label visible after having had focus on a InputView will increase the Label's height
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/LabelShouldSizeProperly.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue29194.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/LabelShouldSizeProperly.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue29194.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/LabelShouldSizeProperly.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/LabelShouldSizeProperly.png
  src/Core/src/Platform/Android/MauiTextView.cs
Labels: p/0, community ✨, area-controls-label, partner/syncfusion

#29014 Add Accessibility Selected for iOS CollectionView
  src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs
  src/Controls/src/Core/Handlers/Items2/iOS/SelectableItemsViewController2.cs
  src/Controls/src/Core/Platform/iOS/Extensions/AcessibilityExtensions.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue21375.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue21375.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue21375_2.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue21375_2.xaml.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/SelectedItemsShowSelected2_multiple.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/SelectedItemsShowSelected2_none.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/SelectedItemsShowSelected2_single.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/SelectedItemsShowSelected_multiple.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/SelectedItemsShowSelected_none.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/SelectedItemsShowSelected_single.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21375.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21375_2.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/SelectedItemsShowSelected_multiple.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/SelectedItemsShowSelected_none.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/SelectedItemsShowSelected_single.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/SelectedItemsShowSelected2_multiple.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/SelectedItemsShowSelected2_none.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/SelectedItemsShowSelected2_single.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/SelectedItemsShowSelected_multiple.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/SelectedItemsShowSelected_none.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/SelectedItemsShowSelected_single.png
Labels: platform/android 🤖, platform/iOS 🍎, area-controls-collectionview, t/a11y, collectionview-cv2

#29315 [Testing] Update failing CarouselView2 tests to use CarouselView1 in sample
  src/Controls/tests/TestCases.HostApp/Elements/CarouselViewCoreGalleryPage.xaml
  src/Controls/tests/TestCases.HostApp/Issues/CarouselViewPositionVisibility.xaml
  src/Controls/tests/TestCases.HostApp/Issues/CarouselViewUpdateCurrentItem.xaml
  src/Controls/tests/TestCases.HostApp/Issues/CarouselViewUpdatePosition.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25192.xaml
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue7678.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue7678_1.cs
Labels: area-testing, community ✨, partner/syncfusion

#29360 [Testing] Fix for flaky UITests in CI that occasionally fail - 10
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla31333.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla34632.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2597.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2809.cs
Labels: area-testing, community ✨, partner/syncfusion

#29204 [Testing] Fix for UITest Catalyst screenshot dimension inconsistency and image cropping issue
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ItemImageSourceShouldBeVisible.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/NoScrollbarsTest.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ScrollToElement1Start.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ScrollToElement2Center.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ScrollToElement3End.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/SettingMaximumTrackColorOnSliderWorks.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/SliderShouldChangeThumbImageAndResetIt.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_ChangeBackgroundColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_ChangeFlowDirection_RTL_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_ChangeMaxTrackColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_ChangeMinTrackColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_ChangeThumbColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_ChangeThumbImageSource_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_FlowDirection_RTL_SetMaximumValue_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_FlowDirection_RTL_SetMinimumValue_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_FlowDirection_RTL_SetValue_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetBackgroundColorAndIsEnable_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetBackgroundColorAndMaxTrackColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetBackgroundColorAndMinTrackColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetBackgroundColorAndThumbColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetEnabledStateToFalse_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetFlowDirectionAndMaxTrackColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetFlowDirectionAndMinTrackColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetIsEnableAndBackgroundColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetIsEnableAndMaxTrackColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetIsEnableAndMinTrackColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetIsEnableAndThumbColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetIsVisibleAndBackgroundColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetIsVisibleAndMaxTrackColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetIsVisibleAndMinTrackColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetIsVisibleAndThumbColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetMaxTrackAndBackgroundColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetMaxTrackAndMinTrackColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetMaxTrackAndThumbColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetMaxTrackColorAndValue_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetMaxTrackColorTestFlowDirection_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetMaximumAndChangeFlowDirection_RTL.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetMinTrackAndBackgroundColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetMinTrackAndMaxTrackColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetMinTrackAndThumbColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetMinTrackColorAndValue_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetMinTrackColorTestFlowDirection_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetMinimumAndChangeFlowDirection_RTL.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetThumbAndBackgroundColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetThumbAndMaxTrackColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetThumbAndMinTrackColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetThumbColorAndThumbImageSource_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetThumbImageSourceAndThumbColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetValueAndFlowDirection_RTL_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetValueAndMaxTrackColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetValueAndMinTrackColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetValueAndThumbImageSource_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Slider_SetVisibilityToFalse_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/SwitchColorTestAfterToggling.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/SwitchColorTestBeforeToggling.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/SwitchOnOffVisualStatesTest_SwitchOff.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/SwitchOnOffVisualStatesTest_SwitchOn.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/SwitchTrackColorTest.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifySwipeViewApperance.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/ScrollViewUITests.cs
Labels: area-testing, community ✨, partner/syncfusion

#29381 [Android] - Fix inconsistent footer scrolling when EmptyView is a string in CollectionView
  src/Controls/src/Core/Handlers/Items/Android/Adapters/EmptyViewAdapter.cs
  src/Controls/src/Core/Handlers/Items/Android/SimpleViewHolder.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue28765.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28765.cs
Labels: platform/android 🤖, area-controls-collectionview, community ✨, partner/syncfusion

#29318 [iOS] Fix CarouselView proper bounce-back behavior when Loop=false
  src/Controls/src/Core/Handlers/Items2/iOS/LoopObservableItemsSource2.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue29261.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue29261.cs
Labels: platform/iOS 🍎, area-controls-collectionview, community ✨, partner/syncfusion

#29401 [ci] Push metadata rollbacks
  eng/Publishing.props
  eng/pipelines/arcade/stage-pack.yml
  src/Workload/Microsoft.NET.Sdk.Maui.Manifest/Microsoft.NET.Sdk.Maui.Manifest.csproj
Labels: t/housekeeping ♻︎, area-infrastructure, area/infrastructure 🏗️

#29409 [Testing] Fix for flaky test(ListViewViewCellBinding) in CI
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/ListViewViewCellBinding.cs
Labels: area-testing, community ✨, partner/syncfusion

#28568 [Android] Inheriting StatusBar and NavigationBar background colors on modal pages
  src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.Android.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/StatusBarAndNavigationBarShouldInheritColor.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue28552.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28552.cs
Labels: platform/android 🤖, area-navigation, community ✨, area-controls-modal

#29369 [iOS] Fixed the App crashes when navigating to a page containing a map more than once
  src/Controls/tests/TestCases.HostApp/Issues/Issue20612.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20612.cs
  src/Core/maps/src/Handlers/Map/MapHandler.iOS.cs
  src/Core/maps/src/Platform/iOS/MapPool.cs
  src/Core/maps/src/Platform/iOS/MauiMKMapView.cs
Labels: platform/iOS 🍎, community ✨, area-controls-map, partner/syncfusion

#29465 [api] Fix unshipped/shipped api files for android
  src/Core/src/PublicAPI/net-android/PublicAPI.Shipped.txt
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
Labels: t/housekeeping ♻︎

#28357 [net10.0] Trimmable view handlers
  src/Controls/src/Core/CheckBox/CheckBox.Mapper.cs
  src/Controls/src/Core/CheckBox/CheckBox.cs
  src/Controls/src/Core/Element/Element.Mapper.cs
  src/Controls/src/Core/Element/Element.cs
  src/Controls/src/Core/Hosting/AppHostBuilderExtensions.cs
  src/Controls/src/Core/Label/Label.Mapper.cs
  src/Controls/src/Core/Label/Label.cs
  src/Controls/src/Core/Platform/GestureManager/GesturePlatformManager.Windows.cs
  src/Controls/src/Core/ViewExtensions.cs
  src/Controls/src/Core/VisualElement/VisualElement.Mapper.cs
  src/Core/src/Handlers/CheckBox/CheckBoxHandler.Windows.cs
  src/Core/src/Handlers/Element/ElementHandlerAttribute.cs
  src/Core/src/Handlers/Element/RemappingHelper.cs
  src/Core/src/Handlers/View/ViewHandler.Windows.cs
  src/Core/src/Hosting/Internal/MauiHandlersFactory.cs
  src/Core/src/Hosting/Internal/RegisteredHandlerServiceTypeSet.cs
  src/Core/tests/UnitTests/Hosting/RegisteredHandlerServiceTypeSetTests.cs
Labels: proposal/open, area-core-hosting

#29443 Make internal types used by MAUI Toolkit public
  src/Controls/src/Core/ICornerElement.cs
  src/Controls/src/Core/ILineHeightElement.cs
  src/Controls/src/Core/ILineHeightElementInternal.cs
  src/Controls/src/Core/ITextAlignmentElement.cs
  src/Controls/src/Core/ITextElement.cs
  src/Controls/src/Core/Properties/AssemblyInfo.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
Labels: t/breaking 💥, area-architecture

#29362 Run Categories Separately
  eng/devices/catalyst.cake
  eng/devices/devices-shared.cake
  eng/devices/ios.cake
  eng/pipelines/common/device-tests-steps.yml
  src/Controls/tests/DeviceTests/ControlsHandlerTestBase.cs
  src/Controls/tests/DeviceTests/Elements/Button/ButtonTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs
  src/Controls/tests/DeviceTests/Elements/Entry/EntryTests.cs
  src/Controls/tests/DeviceTests/Elements/Entry/EntryTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Page/PageTests.Android.cs
  src/Controls/tests/DeviceTests/Elements/Page/PageTests.iOS.cs
  src/Controls/tests/DeviceTests/Elements/TextInput/TextInputTests.cs
  src/Controls/tests/DeviceTests/MauiProgram.cs
  src/Core/tests/DeviceTests.Shared/Core.DeviceTests.Shared.csproj
  src/Core/tests/DeviceTests.Shared/DeviceTestSharedHelpers.cs
  src/Core/tests/DeviceTests.Shared/MauiProgramDefaults.cs
  src/Core/tests/DeviceTests/Handlers/Element/ElementTests.cs
  src/Core/tests/DeviceTests/Handlers/Image/ImageHandlerTests.cs
  src/Core/tests/DeviceTests/Handlers/Navigation/NavigationViewHandlerTests.cs
  src/Core/tests/DeviceTests/Handlers/RefreshView/RefreshViewHandlerTests.cs
  src/Core/tests/DeviceTests/MauiProgram.cs
  src/Core/tests/DeviceTests/TestCategory.cs
  src/TestUtils/src/DeviceTests.Runners/AppHostBuilderExtensions.cs
  src/TestUtils/src/DeviceTests.Runners/HeadlessRunner/iOS/HeadlessTestRunner.cs
  src/TestUtils/src/DeviceTests.Runners/HeadlessRunner/iOS/MauiTestApplicationDelegate.cs
  src/TestUtils/src/DeviceTests/AssertionExtensions.iOS.cs
Labels: area-testing, testing-green-ci

#29424 [Testing] Feature Matrix UITest Cases for CollectionView Dynamic changes
  src/Controls/tests/TestCases.HostApp/FeatureMatrix/CollectionView/CollectionViewDynamicChanges/CollectionViewDynamicOptionsPage.xaml
  src/Controls/tests/TestCases.HostApp/FeatureMatrix/CollectionView/CollectionViewDynamicChanges/CollectionViewDynamicOptionsPage.xaml.cs
  src/Controls/tests/TestCases.HostApp/FeatureMatrix/CollectionView/CollectionViewDynamicChanges/CollectionViewDynamicPage.xaml
  src/Controls/tests/TestCases.HostApp/FeatureMatrix/CollectionView/CollectionViewDynamicChanges/CollectionViewDynamicPage.xaml.cs
  src/Controls/tests/TestCases.HostApp/FeatureMatrix/CollectionView/CollectionViewFeaturePage.xaml
  src/Controls/tests/TestCases.HostApp/FeatureMatrix/CollectionView/CollectionViewFeaturePage.xaml.cs
  src/Controls/tests/TestCases.HostApp/FeatureMatrix/CollectionView/CollectionViewViewModel.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/FeatureMatrix/CollectionView_DynamicChangesFeatureTests.cs
Labels: area-testing, community ✨, partner/syncfusion

#29423 [Testing] - Enabled Test 29402 to Pass on Both CV1 and CV2 Handlers
  src/Controls/tests/TestCases.HostApp/Issues/Issue28930.xaml
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28523.cs
Labels: area-testing, community ✨, partner/syncfusion

#29151 Add API XML Docs for Graphics.Text.Markdig
  src/Graphics/src/Text.Markdig/Graphics.Text.Markdig.csproj
  src/Graphics/src/Text.Markdig/MarkdownAttributedTextReader.cs
Labels: area-docs, area-drawing, t/housekeeping ♻︎

#29149 Add API XML Docs for Graphics.Skia.GtkSharp
  src/Graphics/src/Graphics.Skia.GtkSharp/Graphics.Skia.GtkSharp.csproj
  src/Graphics/src/Graphics.Skia.GtkSharp/GtkSkiaDirectRenderer.cs
  src/Graphics/src/Graphics.Skia.GtkSharp/GtkSkiaGraphicsView.cs
  src/Graphics/src/Graphics.Skia.GtkSharp/ISkiaGraphicsRenderer.cs
Labels: area-docs, area-drawing, t/housekeeping ♻︎

#29150 Add API XML Docs for Graphics.Skia.WPF
  src/Graphics/src/Graphics.Skia.WPF/Graphics.Skia.WPF.csproj
  src/Graphics/src/Graphics.Skia.WPF/ISkiaGraphicsRenderer.cs
  src/Graphics/src/Graphics.Skia.WPF/WDSkiaDirectRenderer.cs
  src/Graphics/src/Graphics.Skia.WPF/WDSkiaGraphicsView.cs
Labels: area-docs, area-drawing, t/housekeeping ♻︎

#29148 Add API XML Docs for Graphics.Skia
  src/Graphics/src/Graphics.Skia/FontExtensions.cs
  src/Graphics/src/Graphics.Skia/Graphics.Skia.csproj
  src/Graphics/src/Graphics.Skia/SKColorExtensions.cs
  src/Graphics/src/Graphics.Skia/SKFontExtensions.cs
  src/Graphics/src/Graphics.Skia/SKGraphicsExtensions.cs
  src/Graphics/src/Graphics.Skia/SKPaintExtensions.cs
  src/Graphics/src/Graphics.Skia/SkiaBitmapExportContext.cs
  src/Graphics/src/Graphics.Skia/SkiaBitmapExportService.cs
  src/Graphics/src/Graphics.Skia/SkiaCanvas.cs
  src/Graphics/src/Graphics.Skia/SkiaCanvasState.cs
  src/Graphics/src/Graphics.Skia/SkiaCanvasStateService.cs
  src/Graphics/src/Graphics.Skia/SkiaImage.cs
  src/Graphics/src/Graphics.Skia/SkiaImageLoadingService.cs
  src/Graphics/src/Graphics.Skia/SkiaStringSizeService.cs
  src/Graphics/src/Graphics.Skia/SkiaTextLayout.cs
  src/Graphics/src/Graphics.Skia/Views/SkiaGraphicsView.Android.cs
  src/Graphics/src/Graphics.Skia/Views/SkiaGraphicsView.Mac.cs
  src/Graphics/src/Graphics.Skia/Views/SkiaGraphicsView.Tizen.cs
  src/Graphics/src/Graphics.Skia/Views/SkiaGraphicsView.Windows.cs
  src/Graphics/src/Graphics.Skia/Views/SkiaGraphicsView.iOS.cs
Labels: area-docs, area-drawing, t/housekeeping ♻︎

#28766 Include all platforms in multi project template
  src/Templates/src/templates/maui-multiproject/.template.config/template.json
  src/Templates/src/templates/maui-multiproject/MauiApp.1.Mac/Info.plist
  src/Templates/src/templates/maui-multiproject/MauiApp.1.iOS/Info.plist
  src/Templates/src/templates/maui-multiproject/MauiApp.1.sln
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/MultiProjectTemplateTest.cs
Labels: area-templates

#29466 [net 10.0 Testing] Enabled BuildsWithSpecialCharacters Test
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/SimpleTemplateTest.cs
Labels: area-testing, community ✨, partner/syncfusion

#29314 [NET10.0] Annotate converters for nullability 3/n
  src/Controls/src/Build.Tasks/CompiledConverters/LayoutOptionsConverter.cs
  src/Controls/src/Core/AcceleratorTypeConverter.cs
  src/Controls/src/Core/FileImageSourceConverter.cs
  src/Controls/src/Core/FontSizeConverter.cs
  src/Controls/src/Core/GridLengthTypeConverter.cs
  src/Controls/src/Core/IExtendedTypeConverter.cs
  src/Controls/src/Core/LayoutOptionsConverter.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/ReferenceTypeConverter.cs
  src/Controls/src/Core/RowDefinitionCollectionTypeConverter.cs
  src/Controls/src/Core/TypeTypeConverter.cs
Labels: community ✨

#28033 [Testing] Enabling more UI Tests by removing platform specific condition - 18
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ValidateWebViewScreenshot.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue11962.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue14825.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue14825.xaml.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ValidateWebViewScreenshot.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/CollectionView/CollectionViewUITests.EmptyView.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/CollectionView/CollectionViewUITests.Grouping.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/CollectionView/CollectionViewUITests.MultipleBoundSelection.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue11962.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue14825.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ValidateWebViewScreenshot.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ValidateWebViewScreenshot.png
Labels: area-testing, community ✨, partner/syncfusion

#29234 [Android] Fix WebView Navigated is fired when source is null
  src/Controls/tests/TestCases.HostApp/Issues/Issue29233.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue29233.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue29233.cs
  src/Core/src/Platform/Android/WebViewExtensions.cs
Labels: t/bug, platform/android 🤖, community ✨, area-controls-webview

#29498 [iOS] Fix : FilePicker.PickAsync Task Hangs When User Cancels the Picker in iOS
  src/Essentials/src/FilePicker/FilePicker.ios.cs
Labels: p/0, community ✨

#29469 [iOS] ScrollView content offset RTL - fix
  src/Controls/tests/TestCases.HostApp/Issues/Issue29458.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue29458.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue29458.cs
  src/Core/src/Platform/iOS/MauiScrollView.cs
Labels: platform/iOS 🍎, community ✨, area-controls-scrollview

#29163 [Windows] Fix for ArgumentException thrown when setting a negative padding value for the label
  src/Controls/tests/TestCases.HostApp/Issues/Issue6387.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue6387.cs
  src/Core/src/Platform/Windows/TextBlockExtensions.cs
Labels: platform/windows 🪟, community ✨, area-controls-label, partner/syncfusion

#21897 [UI Test] Create a new UITest for ModalPageMarginCorrectAfterKeyboardOpens
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ModalPageMarginCorrectAfterKeyboardOpens.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue18961.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue18961.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18961.cs
Labels: t/housekeeping ♻︎, area-testing, area-keyboard

#29608 [net10.0, Testing] Fixed Test case failure in PR 29399 - Merge main to net10
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/LabelShouldSizeProperly.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/SwitchOnOffVisualStatesTest_SwitchOn.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifySwitchNullColor.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifySwitchOffColorAfterToggling.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifySwitchOffColorAfterTogglingDarkTheme.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/LabelShouldSizeProperly.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/LabelShouldSizeProperly.png
Labels: area-testing, community ✨, partner/syncfusion

#29436 [Testing] Re-Enabled UI Test - Issue12574Test
  src/Controls/tests/TestCases.HostApp/Issues/CarouselViewLoopNoFreeze.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/CarouselViewUITests.LoopNoFreeze.cs
Labels: area-testing, community ✨, partner/syncfusion

#28977 [Windows] Fixed Shell flyout background image does not displayed
  src/Controls/src/Core/Handlers/Shell/ShellHandler.Windows.cs
  src/Controls/src/Core/Handlers/Shell/ShellHandler.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyShellFlyoutBackgroundImage.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyShellFlyoutBackgroundImageSetNull.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue21472.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyShellFlyoutBackgroundImage.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyShellFlyoutBackgroundImageSetNull.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21472.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifyShellFlyoutBackgroundImage.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifyShellFlyoutBackgroundImageSetNull.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyShellFlyoutBackgroundImage.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyShellFlyoutBackgroundImageSetNull.png
  src/Core/src/Platform/Windows/NavigationViewExtensions.cs
Labels: platform/windows 🪟, area-controls-shell, community ✨, partner/syncfusion

#29557 [Android] Fix: Modal Animation Repeats When Returning from Background 2
  src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.Android.cs
  src/Core/src/Platform/Android/Resources/values/styles.xml
Labels: platform/android 🤖, area-navigation, community ✨, area-controls-modal

#29607 [ci] Fix Appium provisioning when no global npm exists
  src/Provisioning/Provisioning.csproj
Labels: area-infrastructure, testing-infrastructure

#29317 [Android] Fix for the FontImageSource color is not applied properly to the Bottom Tab Icon
  src/Controls/src/Core/Platform/Android/TabbedPageManager.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/DynamicFontImageSourceColorShouldApplyOnBottomTabIconOnAndroid.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/FontImageSourceColorShouldApplyOnBottomTabIconOnAndroid.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue29109.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue29109.cs
Labels: p/0, area-controls-tabbedpage, community ✨, partner/android, partner/syncfusion

#29667 [ci] Update dependencies from 9.0.4 to 9.0.5
  eng/Versions.props
Labels: area-infrastructure

#29543 Page.OnBackButtonPressed remove outdated API documentation
  src/Controls/src/Core/Page/Page.cs
Labels: area-docs, t/housekeeping ♻︎

#29636 Fixed Test case failure in PR 29623 - [2025/05/26] Candidate
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/PickerTitleShouldBeRed.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla44338.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/HideSoftInputOnTappedPageTests.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue9711.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/TestDynamicItemTemplateChangeInCarouselView.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/PickerTitleShouldBeRed.png
Labels: area-testing, community ✨, partner/syncfusion, test-flight

#29549 [NET10.0] Annotate converters for nullability 4/n
  src/Controls/src/Core/Brush/BrushTypeConverter.cs
  src/Controls/src/Core/ColumnDefinitionCollectionTypeConverter.cs
  src/Controls/src/Core/DecorableTextElement.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/Shapes/MatrixTypeConverter.cs
  src/Controls/src/Core/Shapes/PathFigureCollectionConverter.cs
  src/Controls/src/Core/Shapes/PathGeometryConverter.cs
  src/Controls/tests/Core.UnitTests/AppThemeTests.cs
  src/Controls/tests/Core.UnitTests/BrushTypeConverterUnitTests.cs
  src/Controls/tests/Core.UnitTests/ColumnDefinitionCollectionTypeConverterUnitTests.cs
  src/Controls/tests/Core.UnitTests/PathFigureCollectionConverterTests.cs
  src/Controls/tests/Core.UnitTests/Shapes/MatrixTypeConverterTests.cs
  src/Controls/tests/Core.UnitTests/Shapes/PathGeometryConverterTests.cs
Labels: community ✨

#26696 Fix up relevant CA1416 warnings - Set 1
  eng/Versions.props
  src/Controls/src/Core/Compatibility/Handlers/ListView/iOS/ContextActionCell.cs
  src/Controls/src/Core/Platform/iOS/Extensions/BrushExtensions.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyContextActionCell.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyFlyoutBackgroundColor.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyHamburgerIcon.png
  src/Controls/tests/TestCases.HostApp/Issues/ContextActionCellTest.cs
  src/Controls/tests/TestCases.HostApp/Issues/FlyoutTest.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyFlyoutBackgroundColor.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyHamburgerIcon.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/ContextActionCellTest.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/FlyoutTest.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifyFlyoutBackgroundColor.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifyHamburgerIcon.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyContextActionCell.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyFlyoutBackgroundColor.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyHamburgerIcon.png
Labels: area-drawing, community ✨, partner/syncfusion

#29637 [Android/ iOS] Fix Flyout icon is displayed when flyout is disabled
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellToolbarTracker.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue29615.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue29615.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: platform/android, community ✨, area-controls-flyout, partner/syncfusion

#29666 [net10.0] Update preview5 versions
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: area-infrastructure, area/infrastructure 🏗️

#29478 [docs] Add doc with info about release process
  docs/ReleaseProcess.md
  eng/pipelines/maui-release-internal.yml
Labels: area-docs

#29031 Fix iOS Label being truncated when using Padding
  src/Controls/tests/TestCases.HostApp/Issues/Issue28180.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue28180.xaml.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/LabelWithPaddingIsNotTruncated.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28180.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/LabelWithPaddingIsNotTruncated.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ValidateTableViewTitles.png
  src/Core/src/Platform/iOS/MauiLabel.cs
Labels: platform/ios, community ✨, area-controls-label

#28876 Add the ability to intercept all web resource requests
  src/Controls/src/Core/Controls.Core.csproj
  src/Controls/src/Core/HybridWebView/HybridWebView.cs
  src/Controls/src/Core/HybridWebView/HybridWebViewWebResourceRequestedEventArgs.cs
  src/Controls/src/Core/HybridWebView/PlatformHybridWebViewWebResourceRequestedEventArgs.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/Shell/ShellRouteParameters.cs
  src/Controls/tests/Core.UnitTests/ShellParameterPassingTests.cs
  src/Controls/tests/DeviceTests/Elements/HybridWebView/HybridWebViewTests.cs
  src/Controls/tests/DeviceTests/Resources/Raw/HybridTestRoot/index.html
  src/Core/src/Core/IHybridWebView.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.Windows.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewHandler.iOS.cs
  src/Core/src/Handlers/HybridWebView/HybridWebViewQueryStringHelper.cs
  src/Core/src/Platform/Android/AsyncStream.cs
  src/Core/src/Platform/Android/MauiHybridWebViewClient.cs
  src/Core/src/Primitives/WebResourceRequestedEventArgs.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Essentials/src/Types/Shared/WebUtils.shared.cs
  src/Essentials/test/DeviceTests/Tests/WebAuthenticator_Tests.cs
  src/Essentials/test/DeviceTests/Tests/WebUtils_Tests.cs
  src/Essentials/test/UnitTests/Browser_Tests.cs
Labels: area-controls-webview

#29703 [NET10] Make `VisualElement.ComputeConstraintForView` and `LayoutConstraint` enum public
  src/Controls/src/Core/ContentPresenter.cs
  src/Controls/src/Core/LayoutConstraint.cs
  src/Controls/src/Core/LegacyLayouts/AbsoluteLayout.cs
  src/Controls/src/Core/LegacyLayouts/Grid.cs
  src/Controls/src/Core/LegacyLayouts/StackLayout.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/ScrollView/ScrollView.cs
  src/Controls/src/Core/TemplatedPage.cs
  src/Controls/src/Core/TemplatedView/TemplatedView.cs
  src/Controls/src/Core/VisualElement/VisualElement.cs
Labels: area-layout

#29719 [iOS] Fix memory leak in CarouselViewHandler2
  src/Controls/src/Core/Handlers/Items2/CarouselViewHandler2.iOS.cs
  src/Controls/src/Core/Handlers/Items2/iOS/LayoutFactory2.cs
  src/Controls/tests/DeviceTests/Memory/MemoryTests.cs
Labels: platform/ios, area-controls-collectionview, community ✨, memory-leak 💦

#29739 [Testing] Feature Matrix UITest Cases for CheckBox Control
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CheckBox_ChangeColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CheckBox_SetIsCheckedAndColor_VerifyVisualState.png
  src/Controls/tests/TestCases.HostApp/CoreViews/CorePageView.cs
  src/Controls/tests/TestCases.HostApp/FeatureMatrix/CheckBox/CheckBoxControlPage.xaml
  src/Controls/tests/TestCases.HostApp/FeatureMatrix/CheckBox/CheckBoxControlPage.xaml.cs
  src/Controls/tests/TestCases.HostApp/FeatureMatrix/CheckBox/CheckBoxViewModel.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/CheckBox_ChangeColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/CheckBox_SetIsCheckedAndColor_VerifyVisualState.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/FeatureMatrix/CheckBoxFeatureTests.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/CheckBox_ChangeColor_VerifyVisualState.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/CheckBox_SetIsCheckedAndColor_VerifyVisualState.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/CheckBox_ChangeColor_VerifyVisualState.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/CheckBox_SetIsCheckedAndColor_VerifyVisualState.png
Labels: area-testing, community ✨, partner/syncfusion

#26153 Don’t call NSAttributedString with HTML from a background thread
  src/Controls/src/Core/Label/Label.iOS.cs
  src/Controls/src/Core/Platform/iOS/Extensions/LabelExtensions.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue25946.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25946.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25946.cs
  src/Core/src/Platform/iOS/LabelExtensions.cs
Labels: area-controls-collectionview, community ✨, partner/syncfusion/review
