Repository dotnet/maui, pull requests merged in 2025-07, with the labels that each got.

#30355 [testimg] Ignore net10 multiprject test
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/MultiProjectTemplateTest.cs
Labels: area-testing

#29940 [iOS/MacCatalyst] Fix: Setting SelectedItem Programmatically and Then Immediately Setting ItemsSource to Null Causes a Crash
  src/Controls/src/Core/Handlers/Items/iOS/SelectableItemsViewController.cs
  src/Controls/src/Core/Handlers/Items2/iOS/SelectableItemsViewController2.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue29937.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue29937.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue29937.cs
Labels: p/0, community ✨

#29926 [Windows] Fixed StackLayout crashes on Windows with HeightRequest as 0
  src/Controls/tests/TestCases.HostApp/Issues/Issue29919.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue29919.cs
  src/Core/src/Layouts/HorizontalStackLayoutManager.cs
  src/Core/src/Layouts/VerticalStackLayoutManager.cs
Labels: area-layout, community ✨, layout-stack, partner/syncfusion

#29279 [.Net 10] Shell.SetNavBarVisibilityAnimationEnabled property
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellItemRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs
  src/Controls/src/Core/Internals/PropertyPropagationExtensions.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/Shell/Shell.cs
Labels: platform/ios, p/0, area-controls-shell, community ✨

#30413 Fixed Test case(Issue28798) failure in PR 30306 - [6/30/2025] Candidate
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28798.cs
Labels: area-testing, community ✨, partner/syncfusion, test-flight

#28185 Implement iOS/macOS secondary ToolbarItems
  src/Controls/docs/Microsoft.Maui.Controls/ToolbarItem.xml
  src/Controls/docs/Microsoft.Maui.Controls/ToolbarItemOrder.xml
  src/Controls/samples/Controls.Sample/Pages/Core/ToolbarPage.cs
  src/Controls/samples/Controls.Sample/Pages/Core/ToolbarPage.xaml
  src/Controls/samples/Controls.Sample/ViewModels/CoreViewModel.cs
  src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs
  src/Controls/src/Core/Compatibility/iOS/Extensions/ToolbarItemExtensions.cs
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/Toolbar/ToolbarItem.cs
  src/Controls/src/Core/Toolbar/ToolbarItemOrder.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2809.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: t/breaking 💥, proposal/open, platform/ios, p/0, area-controls-toolbar

#30419 [ci] Small pipelines fixes
  eng/cake/dotnet.cake
  eng/devices/android.cake
  eng/devices/ios.cake
  eng/pipelines/common/maui-templates-steps.yml
  eng/pipelines/common/maui-templates.yml
  eng/pipelines/common/provision.yml
  eng/pipelines/common/variables.yml
  src/Graphics/tests/DeviceTests/Platforms/iOS/Entitlements.plist
Labels: area-infrastructure

#30447 Revert "Fixed picker allows user input if the keyboard is visible"
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/PickerShouldNotAllowUserInputThroughKeyboard.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue24930.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24930.cs
  src/Core/src/Platform/Android/PickerManager.cs
Labels: p/0

#30436 [Testing] Fix Appium Swipe actions on Mac
  src/Controls/tests/TestCases.Shared.Tests/Tests/SwipeViewUITests.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumCatalystSwipeActions.cs
Labels: t/housekeeping ♻︎, area-testing

#30416 [net10.0, Testing] Fix Button & RadioFeatureTests Screenshot Issue on Windows
  src/Controls/tests/TestCases.Shared.Tests/Tests/FeatureMatrix/ButtonFeatureTests.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/FeatureMatrix/RadioButtonFeatureTests.cs
Labels: area-testing, community ✨, partner/syncfusion

#29825 [iOS][Shell]Tab becomes blank after specific navigation pattern - fix
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellItemRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs
  src/Controls/src/Core/Shell/ShellSection.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue29798.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue29798.cs
Labels: platform/ios, p/0, area-controls-shell, area-controls-tabbedpage, community ✨

#30522 [net10.0] Merge main net10 .0
  eng/common/core-templates/job/job.yml
  eng/common/internal/NuGet.config
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellItemRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs
  src/Controls/src/Core/Shell/ShellSection.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue29798.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue29798.cs
  src/Core/src/Platform/iOS/MauiScrollView.cs
  src/Essentials/test/DeviceTests/Tests/Geocoding_Tests.cs
Labels: area-infrastructure

#30482 [NET 10] Fix UseInterpreter being set for non-MAUI projects referencing MAUI class libraries
  src/Controls/src/Build.Tasks/nuget/buildTransitive/netstandard2.0/Microsoft.Maui.Controls.Common.targets
Labels: platform/macos, p/0, area-templates

#30471 Missing API IsSupported in Vibration and HapticFeedback
  src/Essentials/src/HapticFeedback/HapticFeedback.shared.cs
  src/Essentials/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Essentials/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Essentials/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Essentials/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Essentials/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Essentials/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Essentials/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Essentials/src/Vibration/Vibration.shared.cs
Labels: area-essentials, community ✨

#30599 [housekeeping] Moved Issue28212.cs to a proper folder
  src/Controls/tests/TestCases.HostApp/Issues/Issue28212.cs
Labels: t/housekeeping ♻︎, area-testing, community ✨

#30633 [net10.0] Move to 10.0.1xx-preview7
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/core-templates/job/job.yml
  eng/common/core-templates/steps/install-microbuild.yml
  eng/common/core-templates/steps/source-build.yml
  eng/common/templates/vmr-build-pr.yml
  global.json
  src/Essentials/src/Accelerometer/Accelerometer.ios.watchos.cs
  src/Essentials/src/Gyroscope/Gyroscope.ios.watchos.cs
  src/Essentials/src/Magnetometer/Magnetometer.ios.watchos.cs
  src/Essentials/src/OrientationSensor/OrientationSensor.ios.watchos.cs
Labels: area-infrastructure

#30573 Annotated remaining Converter classes for nullability
  src/Core/src/Converters/EasingTypeConverter.cs
  src/Core/src/Converters/FlexEnumsConverters.cs
  src/Core/src/Converters/KeyboardTypeConverter.cs
  src/Core/src/Converters/PrimitiveTypeConversions.cs
  src/Core/src/Converters/ThicknessTypeConverter.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
Labels: community ✨, partner/syncfusion

#30738 [Testing] Fixed Test case LabelShouldSizeProperlyOnCollectionView failure in PR 30696 - [07/21/2025] Candidate
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/LabelShouldSizeProperlyOnCollectionView.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue29542.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/LabelShouldSizeProperlyOnCollectionView.png
Labels: area-testing, community ✨, partner/syncfusion, test-flight

#29935 [.NET10] Obsolete Page.IsBusy API
  src/Controls/src/Core/Page/Page.cs
  src/Controls/src/Core/Platform/AlertManager/AlertManager.Android.cs
  src/Controls/src/Core/Platform/AlertManager/AlertManager.Standard.cs
  src/Controls/src/Core/Platform/AlertManager/AlertManager.Windows.cs
  src/Controls/src/Core/Platform/AlertManager/AlertManager.cs
  src/Controls/src/Core/Platform/AlertManager/AlertManager.iOS.cs
  src/Controls/tests/DeviceTests/Elements/Page/PageTests.cs
Labels: t/breaking 💥, platform/windows, platform/android, platform/ios, p/0, community ✨, partner/syncfusion

#30742 VerifyClearButtonVisiblityWhenTextPresentOrEmpty test failure base im…
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ClearButtonVisiblityButton_TextPresent.png
Labels: area-testing, community ✨, partner/syncfusion

#30648 [Testing] Re-enable CachedFilenameIsCorrectAndValid test
  src/Core/tests/DeviceTests/Services/ImageSource/UriImageSourceServiceTests.cs
Labels: area-testing, testing-reenable

#29600 [.NET10] Add An API to SearchHandler so users can hide or show the softkeyboard
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/SearchHandlerAppearanceTracker.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/SearchHandlerAppearanceTracker.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/Shell/SearchHandler.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue29559.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue29559.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue29559.cs
Labels: proposal/open, platform/android, p/0, community ✨, shell-search-handler

#30480 Implement iOS/macOS secondary ToolbarItems - Shell
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs
  src/Controls/src/Core/Compatibility/iOS/Extensions/ToolbarItemExtensions.cs
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
Labels: proposal/open, platform/ios, p/0, community ✨, area-controls-toolbar

#29280 [Shell] Changed TitleProperty From TwoWay to OneWay
  src/Controls/src/Core/Shell/BaseShellItem.cs
  src/Controls/tests/Core.UnitTests/ShellTests.cs
Labels: platform/android, platform/ios, area-controls-shell, community ✨

#29836 Turn Visual and Binding diags on EnableDiagnostics
  docs/design/FeatureSwitches.md
  src/Controls/src/Build.Tasks/nuget/buildTransitive/netstandard2.0/Microsoft.Maui.Controls.targets
  src/Controls/src/Core/Xaml/Diagnostics/BindingDiagnostics.cs
  src/Controls/tests/Core.UnitTests/BindingUnitTests.cs
  src/Controls/tests/Xaml.UnitTests/BindingDiagnosticsTests.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Gh10803.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Gh11334.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Gh11335.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui17222.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui2418.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui25608_2.xaml.cs
  src/Core/src/RuntimeFeature.cs
  src/Core/src/VisualDiagnostics/DebuggerHelper.cs
  src/Core/src/VisualDiagnostics/VisualDiagnostics.cs
Labels: p/0

#30345 [Android] Fixed Picker Does Not Show Selected Item Highlight
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/PickerShouldShowSelectedItemHighlight.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue29633.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue29633.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/PickerShouldShowSelectedItemHighlight.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/PickerShouldShowSelectedItemHighlight.png
  src/Core/src/Handlers/Picker/PickerHandler.Android.cs
  src/Core/src/Platform/Android/Resources/values/styles.xml
Labels: platform/android, p/0, community ✨, area-controls-picker, partner/syncfusion

#30755 Fixed GraphicsView event handlers are triggered even when IsEnabled is set to False
  src/Controls/tests/TestCases.HostApp/Issues/Issue30649.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue30649.cs
  src/Core/src/Platform/Android/PlatformTouchGraphicsView.cs
  src/Core/src/Platform/iOS/PlatformTouchGraphicsView.cs
Labels: community ✨, partner/syncfusion

#30613 [Testing] Feature matrix UITest Cases for HybridWebView Control
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyHybridWebViewWithFlowDirection.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyHybridWebViewWithShadow.png
  src/Controls/tests/TestCases.HostApp/CoreViews/CorePageView.cs
  src/Controls/tests/TestCases.HostApp/FeatureMatrix/HybridWebView/HybridWebViewControlPage.xaml
  src/Controls/tests/TestCases.HostApp/FeatureMatrix/HybridWebView/HybridWebViewControlPage.xaml.cs
  src/Controls/tests/TestCases.HostApp/FeatureMatrix/HybridWebView/HybridWebViewViewModel.cs
  src/Controls/tests/TestCases.HostApp/Resources/Raw/HybridWebView1/image.html
  src/Controls/tests/TestCases.HostApp/Resources/Raw/HybridWebView1/index.html
  src/Controls/tests/TestCases.HostApp/Resources/Raw/HybridWebView1/navigation.html
  src/Controls/tests/TestCases.HostApp/Resources/Raw/HybridWebView1/web.html
  src/Controls/tests/TestCases.HostApp/Resources/Raw/HybridWebView2/index.html
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyHybridWebViewWithShadow.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/FeatureMatrix/HybridWebViewFeatureTests.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifyHybridWebViewWithShadow.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyHybridWebViewWithShadow.png
Labels: area-testing, community ✨, area-controls-hybridwebview, partner/syncfusion

#30763 [Android] Fixed: Image randomly disappears while switching tabs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyTabBarIconIsLoaded.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue30728.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyTabBarIconIsLoaded.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue30728.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifyTabBarIconIsLoaded.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyTabBarIconIsLoaded.png
  src/Core/src/Platform/ImageSourcePartLoader.cs
Labels: p/0, community ✨, partner/syncfusion

#30908 [Testing] Added SafeAreaEdges test case for Border and ContentView
  src/Controls/tests/TestCases.HostApp/Issues/Issue28986_Border.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue28986_ContentView.xaml
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28986_Border.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue28986_ContentView.cs
Labels: community ✨, partner/syncfusion

#29093 [iOS] Auto Resize chrome icons on iOS to make it more consistent with other platforms - TabBar
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellItemRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/TabbedPage/iOS/TabbedRenderer.cs
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/TabBarIconsShouldAutoscale.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue29091Shell.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue29091Shell.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue29091Tabbed.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue29091Tabbed.xaml.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/BottomTabColorTest.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Issue1323Test.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/TabBarIconsShouldAutoscale.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue29091Shell.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue29091Tabbed.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/TabBarIconsShouldAutoscale.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/BottomTabColorTest.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/FontImageSourceColorShouldApplyOnTabIcon.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue1323Test.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/TabBarIconsShouldAutoscale.png
  src/Core/src/Platform/iOS/TabbedViewExtensions.cs
  src/Graphics/src/Graphics/Platforms/iOS/UIImageExtensions.cs
Labels: platform/ios, p/0, area-controls-shell, area-controls-tabbedpage, community ✨

#30895 API docs fixes
  src/Controls/src/Core/ContentPresenter.cs
  src/Controls/src/Core/HybridWebView/HybridWebView.cs
  src/Controls/src/Core/ScrollView/ScrollView.cs
  src/Controls/src/Core/TemplatedView/TemplatedView.cs
Labels: area-docs, t/housekeeping ♻︎

#30925 Fix Provision JDK step for Linux on CI
  src/Provisioning/Provisioning.csproj
Labels: t/housekeeping ♻︎, area-infrastructure

#30920 Fix duplicate app icon resizing
  src/SingleProject/Resizetizer/src/ResizetizeImages.cs
  src/SingleProject/Resizetizer/src/SkiaSharpAppIconTools.cs
  src/SingleProject/Resizetizer/src/WindowsIconGenerator.cs
Labels: area-single-project, community ✨

#30934 Auto Resize chrome icons - UITests
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/TabBarIconsShouldAutoscaleShell.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/TabBarIconsShouldAutoscaleTabbedPage.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue29091Tabbed.xaml
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/TabBarIconsShouldAutoscaleShell.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/TabBarIconsShouldAutoscaleTabbedPage.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue29091Shell.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue29091Tabbed.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/TabBarIconsShouldAutoscale.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/TabBarIconsShouldAutoscaleShell.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/TabBarIconsShouldAutoscaleTabbedPage.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/TabBarIconsShouldAutoscale.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/TabBarIconsShouldAutoscaleShell.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/TabBarIconsShouldAutoscaleTabbedPage.png
Labels: p/0, community ✨
