Repository dotnet/maui, pull requests merged in 2025-02, with the labels that each got.

#27508 [Localization] Simply Logic for Localization Handoff & Handback
  eng/pipelines/common/localization-handback.yml
  eng/pipelines/common/localization.yml
  eng/pipelines/handlers.yml
Labels: area-localization

#22098 Make ImageSource more async-friendly
  src/Controls/src/Core/ImageSource.cs
  src/Controls/src/Core/StreamImageSource.cs
  src/Controls/src/Core/UriImageSource.cs
Labels: community ✨, area-controls-image

#27518 [ci] Run device tests in any machine
  eng/pipelines/device-tests.yml
Labels: testing-infrastructure

#27509 [XC] don't call ProvideValue on compiled bindings
  src/Controls/src/Build.Tasks/SetPropertiesVisitor.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/TypedBinding.cs
Labels: area-xaml

#27452 [XC] trim x:Name values
  src/Controls/src/Build.Tasks/SetFieldVisitor.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui27121.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui27121.xaml.cs
Labels: area-xaml

#27487 [Mac] TitleBar not always initally set
  src/Core/src/Platform/iOS/WindowViewController.cs
Labels: platform/macOS 🍏, p/0, area-controls-titlebar

#17276 [X] don't expand types to Extension for x:Static
  src/Controls/src/Build.Tasks/CompiledMarkupExtensions/StaticExtension.cs
  src/Controls/src/Build.Tasks/ExpandMarkupsVisitor.cs
  src/Controls/src/Build.Tasks/SetPropertiesVisitor.cs
  src/Controls/src/Build.Tasks/XmlTypeExtensions.cs
  src/Controls/src/Core/IXamlTypeResolver.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Xaml/ApplyPropertiesVisitor.cs
  src/Controls/src/Xaml/CreateValuesVisitor.cs
  src/Controls/src/Xaml/MarkupExtensions/StaticExtension.cs
  src/Controls/src/Xaml/XamlParser.cs
  src/Controls/src/Xaml/XamlServiceProvider.cs
  src/Controls/src/Xaml/XmlTypeXamlExtensions.cs
  src/Controls/tests/Xaml.UnitTests/LoaderTests.cs
Labels: area-xaml

#27557 [testing] Disable BlazorWebview tests
  eng/pipelines/device-tests.yml
Labels: area-blazor, area-testing, Blazor ❤️ MAUI, testing-flakiness, testing-infrastructure

#27396 Removes setting up the JDK in pipelines
  eng/devices/android.cake
  eng/pipelines/arcade/setup-test-env.yml
  eng/pipelines/arcade/stage-pack.yml
  eng/pipelines/common/provision.yml
  eng/pipelines/common/setup-jdk.yml
Labels: t/housekeeping ♻︎, area-infrastructure

#27566 [Localization] Fix blocking typo
  eng/automation/LocProject.json
Labels: area-templates, area-localization

#27489 Improve debugger display XP
  src/Controls/src/Core/ActivityIndicator/ActivityIndicator.cs
  src/Controls/src/Core/Button/Button.cs
  src/Controls/src/Core/CheckBox/CheckBox.cs
  src/Controls/src/Core/ContentPage/ContentPage.cs
  src/Controls/src/Core/ContentView/ContentView.cs
  src/Controls/src/Core/DatePicker/DatePicker.cs
  src/Controls/src/Core/FlyoutPage/FlyoutPage.cs
  src/Controls/src/Core/Image/Image.cs
  src/Controls/src/Core/IndicatorView/IndicatorView.cs
  src/Controls/src/Core/InputView/InputView.cs
  src/Controls/src/Core/Items/ItemsView.cs
  src/Controls/src/Core/Label/Label.cs
  src/Controls/src/Core/Layout/Layout.cs
  src/Controls/src/Core/Page/Page.cs
  src/Controls/src/Core/Picker/Picker.cs
  src/Controls/src/Core/ProgressBar/ProgressBar.cs
  src/Controls/src/Core/RadioButton/RadioButton.cs
  src/Controls/src/Core/RefreshView/RefreshView.cs
  src/Controls/src/Core/ScrollView/ScrollView.cs
  src/Controls/src/Core/SearchBar/SearchBar.cs
  src/Controls/src/Core/Slider/Slider.cs
  src/Controls/src/Core/Stepper/Stepper.cs
  src/Controls/src/Core/Switch/Switch.cs
  src/Controls/src/Core/TimePicker/TimePicker.cs
  src/Controls/src/Core/VisualElement/VisualElement.cs
  src/Controls/src/Core/WebView/WebView.cs
  src/Core/src/Debugger/DebuggerDisplayHelpers.cs
Labels: community ✨

#27197 [Windows]Fixed Shell Navigating event issue when switching tabs
  src/Controls/src/Core/Handlers/Shell/ShellItemHandler.Windows.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue25599.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25599.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25599.cs
Labels: platform/windows 🪟, area-controls-shell, community ✨, partner/syncfusion

#27568 Revert "Implementation of Customizable Search Button Color for SearchBar Across Platforms (#26759)"
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/SearchBar/SearchBar.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/SearchIconColorInitializesCorrectly.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue22963.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/SearchIconColorInitializesCorrectly.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22963.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/SearchIconColorInitializesCorrectly.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/SearchIconColorInitializesCorrectly.png
  src/Core/src/Core/ISearchBar.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.Android.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.Standard.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.Tizen.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.Windows.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.iOS.cs
  src/Core/src/Platform/Android/SearchViewExtensions.cs
  src/Core/src/Platform/Windows/SearchBarExtensions.cs
  src/Core/src/Platform/iOS/SearchBarExtensions.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Core/tests/DeviceTests/Stubs/SearchBarStub.cs
Labels: t/housekeeping ♻︎

#27379 [Windows] - Resolved FlyoutBehavior "Locked" State Reset Issue After Navigation
  src/Controls/src/Core/ShellToolbar.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue27337.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27337.cs
Labels: platform/windows 🪟, community ✨, area-controls-flyout, partner/syncfusion

#27273 Fixed the vertical orientation issue in the CarouselViewHandler2 on iOS
  src/Controls/src/Core/Handlers/Items2/CarouselViewHandler2.iOS.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CarouselViewItemsShouldRenderVertically.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue27241.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue27241.xaml.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/CarouselViewItemsShouldRenderVertically.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27241.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/CarouselViewItemsShouldRenderVertically.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/CarouselViewItemsShouldRenderVertically.png
Labels: platform/iOS 🍎, area-controls-collectionview, community ✨, partner/syncfusion

#27499 [Android] Fixed the CarouselView Items overlap issue with PeekAreaInsets
  src/Controls/src/Core/Handlers/Items/Android/MauiCarouselRecyclerView.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CarouselItemsShouldRenderProperly.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue27418.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue27418.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27418.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/CarouselItemsShouldRenderProperly.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/CarouselItemsShouldRenderProperly.png
Labels: p/0, community ✨, partner/syncfusion

#27607 [Testing] Fix flaky test 4
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyInitialEntryReturnTypeChange.png
Labels: area-testing, testing-flakiness

#27560 [testing] Update tests demands
  eng/pipelines/device-tests.yml
  eng/pipelines/handlers.yml
  eng/pipelines/ui-tests.yml
Labels: do-not-merge, area-testing, testing-flakiness

#27441 [Testing] Implement Appium swipe action on Catalyst using the Mac Driver
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue9306.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumCatalystSwipeActions.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumSwipeActions.cs
  src/TestUtils/src/UITest.Appium/AppiumCatalystApp.cs
Labels: area-testing

#27602 [Testing] Implement PressEnter Appium action on Windows
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla29453.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumWindowsVirtualKeyboardActions.cs
  src/TestUtils/src/UITest.Appium/AppiumWindowsApp.cs
Labels: t/housekeeping ♻︎, area-testing

#27466 Fixed CollectionView's HeaderTemplate is not rendering in iOS and MacCatalyst platform.
  src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs
  src/Controls/src/Core/Handlers/Items/iOS/TemplateHelpers.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue8761.xaml
  src/Controls/tests/TestCases.Shared.Tests/Tests/CollectionView/CollectionViewUITests.HeaderAndFooter.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue8761.cs
Labels: platform/iOS 🍎, area-controls-collectionview, community ✨, partner/syncfusion

#27593 Obsolete iOS Compatibility AccessibilityExtensions
  src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs
  src/Controls/src/Core/Compatibility/iOS/Extensions/AccessibilityExtensions.cs
  src/Controls/src/Core/Compatibility/iOS/Extensions/ToolbarItemExtensions.cs
Labels: platform/iOS 🍎, area-controls-general, t/a11y

#27594 Make HybridWebView.InvokeJavaScriptAsync public
  src/Controls/src/Core/HybridWebView/HybridWebView.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
Labels: t/breaking 💥, area-controls-hybridwebview

#27597 Replace Android ToSpannableString overload
  src/Controls/src/Core/Platform/Android/Extensions/FormattedStringExtensions.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
Labels: t/breaking 💥, platform/android 🤖, area-controls-label

#27595 [net10.0] Set `UseRidGraph=false` on Windows
  src/Controls/tests/TestCases.Shared.Tests/UITest.cs
  src/Core/src/nuget/buildTransitive/WinUI.targets
  src/Graphics/samples/GraphicsTester.WinUI.Desktop/GraphicsTester.WinUI.Desktop.csproj
  src/Templates/src/templates/maui-multiproject/MauiApp.1.WinUI/MauiApp.1.WinUI.csproj
  src/Templates/src/templates/maui-multiproject/MauiApp.1.WinUI/Properties/PublishProfiles/win10-x64.pubxml
  src/Templates/src/templates/maui-multiproject/MauiApp.1.WinUI/Properties/PublishProfiles/win10-x86.pubxml
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/ResizetizerTests.cs
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/WindowsTemplateTest.cs
  src/Workload/Microsoft.Maui.Sdk/Sdk/Microsoft.Maui.Sdk.Before.targets
Labels: platform/windows 🪟, community ✨

#27586 Reapply "Implementation of Customizable Search Button Color for Search Across Platforms (#26759)"
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/SearchBar/SearchBar.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/SearchIconColorInitializesCorrectly.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue22963.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/SearchIconColorInitializesCorrectly.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22963.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/SearchIconColorInitializesCorrectly.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/SearchIconColorInitializesCorrectly.png
  src/Core/src/Core/ISearchBar.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.Android.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.Standard.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.Tizen.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.Windows.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.cs
  src/Core/src/Handlers/SearchBar/SearchBarHandler.iOS.cs
  src/Core/src/Platform/Android/SearchViewExtensions.cs
  src/Core/src/Platform/Windows/SearchBarExtensions.cs
  src/Core/src/Platform/iOS/SearchBarExtensions.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/netstandard2.0/PublicAPI.Unshipped.txt
  src/Core/tests/DeviceTests/Stubs/SearchBarStub.cs
Labels: t/breaking 💥, area-controls-searchbar

#27636 [release/10.0.1xx-preview1] Update preview1 android
  eng/Version.Details.xml
  eng/Versions.props
Labels: t/housekeeping ♻︎, area-infrastructure

#26204 [Testing] Implement ContextMenu UITest extension methods
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ContextActionsIconImageSource.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla58875.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla59580.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue6258.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumAndroidContextMenuActions.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumAppleContextMenuActions.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumWindowsContextMenuActions.cs
  src/TestUtils/src/UITest.Appium/AppiumAndroidApp.cs
  src/TestUtils/src/UITest.Appium/AppiumCatalystApp.cs
  src/TestUtils/src/UITest.Appium/AppiumIOSApp.cs
  src/TestUtils/src/UITest.Appium/AppiumWindowsApp.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-testing

#26425 [Android] Fix for Flyout closing when updating the FlyoutPage.Detail
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue892.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue973.cs
  src/Core/src/Handlers/FlyoutView/FlyoutViewHandler.Android.cs
Labels: t/breaking 💥, area-controls-flyoutpage, community ✨, needs-breaking-change-doc-created, partner/syncfusion

#26915 Fix for [Windows]ToolbarItem visibility until Page Disappearing
  src/Controls/src/Core/Toolbar/Toolbar.Windows.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue9419.cs
Labels: community ✨, area-controls-toolbar, partner/syncfusion

#27634 [net10.0] Set `UseRidGraph=false` on Windows (2)
  .gitignore
  src/Templates/src/templates/maui-multiproject/MauiApp.1.WinUI/Properties/PublishProfiles/win-arm64.pubxml
  src/Templates/src/templates/maui-multiproject/MauiApp.1.WinUI/Properties/PublishProfiles/win-x64.pubxml
  src/Templates/src/templates/maui-multiproject/MauiApp.1.WinUI/Properties/PublishProfiles/win-x86.pubxml
Labels: community ✨

#25170 Fix for MenuFlyoutItem stops working after navigating away from and back to page
  src/Controls/src/Core/Menu/MenuBar.cs
  src/Controls/tests/Core.UnitTests/Menu/MenuTestBase.cs
  src/Controls/tests/Core.UnitTests/MenuItemTests.cs
Labels: community ✨, area-controls-contextmenu, partner/syncfusion

#24887 [Android] Fix Flickering issue when calling Navigation.PopAsync
  src/Controls/src/Core/NavigationPage/NavigationPage.cs
  src/Controls/src/Core/TabbedPage/TabbedPage.Windows.cs
  src/Controls/tests/DeviceTests/Elements/FlyoutPage/FlyoutPageTests.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue10274.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue10274.cs
Labels: platform/macOS 🍏, platform/windows 🪟, platform/android 🤖, area-navigation, platform/iOS 🍎, community ✨, partner/syncfusion

#20127 Fix 19647
  src/Controls/tests/Xaml.UnitTests/BindablePropertiesAccessModifiers.xaml
  src/Controls/tests/Xaml.UnitTests/BindablePropertiesAccessModifiers.xaml.cs
  src/Controls/tests/Xaml.UnitTests/ColorConverter.xaml
  src/Controls/tests/Xaml.UnitTests/ColorConverter.xaml.cs
  src/Controls/tests/Xaml.UnitTests/DataTemplate.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Bz27299.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Bz27863.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Gh4516.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Gh5290.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Gh5706.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Gh5706.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Gh7097.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Issue1415.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Issue1438.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui18123.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui18123.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui6367.xaml.cs
Labels: area-xaml, stale

#27640 [ci] Update variables for signing and not used
  eng/pipelines/common/variables.yml
Labels: area-infrastructure

#27567 [net10.0] Make CV2 default for net10
  src/Controls/src/Core/Hosting/AppHostBuilderExtensions.cs
  src/Templates/src/templates/maui-mobile/MauiProgram.cs
  src/TestUtils/src/Microsoft.Maui.IntegrationTests/SimpleTemplateTest.cs
Labels: t/breaking 💥, needs-breaking-change-doc-created

#27657 Timeout Android emulator start
  eng/devices/android.cake
Labels: area-testing

#27450 BindableLayout should disconnect handlers
  src/Controls/src/Core/BindableLayout/BindableLayout.cs
  src/Controls/tests/Core.UnitTests/BindableLayoutTests.cs
  src/Controls/tests/Core.UnitTests/TestClasses/HandlerStub.cs
Labels: community ✨, memory-leak 💦

#26789 Improve shadow rendering on Android, fix shadow clipping on iOS
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue24414Test.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue24414Test_1.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue24414Test_2.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue24414Test_3.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue24414Test_4.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue24414Test_5.png
  src/Controls/tests/TestCases.HostApp/Elements/CollectionView/CollectionViewCoreGalleryPage.cs
  src/Controls/tests/TestCases.HostApp/Elements/CollectionView/PerformanceGalleries/ShadowBenchmark.xaml
  src/Controls/tests/TestCases.HostApp/Elements/CollectionView/PerformanceGalleries/ShadowBenchmark.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla39489.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue24414.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue24414.xaml.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Issue24414Test.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Issue24414Test_1.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Issue24414Test_2.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Issue24414Test_3.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Issue24414Test_4.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Issue24414Test_5.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla39489.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24414.cs
  src/Controls/tests/TestCases.Shared.Tests/UITest.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/Issue24414Test.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/Issue24414Test_1.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/Issue24414Test_2.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/Issue24414Test_3.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/Issue24414Test_4.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/Issue24414Test_5.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue24414Test.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue24414Test_1.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue24414Test_2.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue24414Test_3.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue24414Test_4.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue24414Test_5.png
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformContentViewGroup.java
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformInterop.java
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformPaintType.java
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformShadowDrawable.java
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/PlatformWrapperView.java
  src/Core/AndroidNative/maui/src/main/java/com/microsoft/maui/glide/ShadowBitmapPool.java
  src/Core/src/Graphics/MauiDrawable.Android.cs
  src/Core/src/Graphics/PaintExtensions.Android.cs
  src/Core/src/Platform/Android/StrokeExtensions.cs
  src/Core/src/Platform/Android/WrapperView.cs
  src/Core/src/Platform/iOS/ViewExtensions.cs
  src/Core/src/Platform/iOS/WrapperView.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/Transforms/Metadata.xml
  src/Core/tests/DeviceTests/Graphics/GraphicsTests.Android.cs
  src/Core/tests/DeviceTests/Stubs/RadialGradientPaintStub.cs
  src/TestUtils/src/UITest.Appium/HelperExtensions.cs
Labels: area-drawing, community ✨

#23657 [X] deprecate fontImageExtension
  src/Controls/src/Core/FontImageSource.cs
  src/Controls/src/Xaml/MarkupExtensions/FontImageExtension.cs
  src/Controls/src/Xaml/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Xaml/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Xaml/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Xaml/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Xaml/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Xaml/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Xaml/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/tests/Xaml.UnitTests/FontImageExtension.xaml.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Maui23347.xaml
  src/Controls/tests/Xaml.UnitTests/Issues/Maui23347.xaml.cs
Labels: t/breaking 💥, area-fonts

#27582 26598 - Fix for Tabbar disappears when navigating back from page with hidden TabBar in iOS 18
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellPageRendererTracker.cs
  src/Controls/src/Core/Shell/ShellSection.cs
  src/Controls/tests/Core.UnitTests/ShellModalTests.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue26598.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26598.cs
Labels: community ✨, partner/syncfusion

#27655 Avoid compiler error when using init properties with BindingSourceGenerator
  src/Controls/src/BindingSourceGen/BindingSourceGenerator.cs
  src/Controls/tests/BindingSourceGen.UnitTests/IntegrationTests.cs
Labels: area-xaml, community ✨

#27601 Make iOS WebView delegates virtual
  src/Core/src/Platform/iOS/MauiWebViewNavigationDelegate.cs
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
Labels: t/breaking 💥, platform/iOS 🍎, area-controls-webview

#27581 [Testing] Enabling more UI Tests by removing platform specific condition - 6
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ReduceInvalidateMeasuresUpdatingLabel.png
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla27731.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue14801.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ReduceInvalidateMeasuresUpdatingLabel.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla27731.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/CollectionViewUITests.ClearGroupedNoCrash.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue11209.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue11853.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue14801.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/ReduceInvalidateMeasure.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ReduceInvalidateMeasuresUpdatingLabel.png
Labels: area-testing, community ✨, partner/syncfusion

#24798 Improve TextToSpeech function by adding a speech rate parameter
  src/Essentials/samples/Samples/View/TextToSpeechPage.xaml
  src/Essentials/samples/Samples/ViewModel/TextToSpeechViewModel.cs
  src/Essentials/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Essentials/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Essentials/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Essentials/src/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Essentials/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Essentials/src/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Essentials/src/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Essentials/src/TextToSpeech/TextToSpeech.android.cs
  src/Essentials/src/TextToSpeech/TextToSpeech.ios.tvos.watchos.cs
  src/Essentials/src/TextToSpeech/TextToSpeech.macos.cs
  src/Essentials/src/TextToSpeech/TextToSpeech.shared.cs
  src/Essentials/src/TextToSpeech/TextToSpeech.tizen.cs
  src/Essentials/src/TextToSpeech/TextToSpeech.uwp.cs
Labels: area-essentials, community ✨, stale

#27529 Adds very basic CSS support for Border
  src/Controls/src/Build.Tasks/CompiledConverters/StrokeShapeTypeConverter.cs
  src/Controls/src/Core/Properties/AssemblyInfo.cs
  src/Controls/src/Core/Shapes/StrokeShapeTypeConverter.cs
  src/Controls/tests/Core.UnitTests/StrokeShapeTests.cs
Labels: community ✨, area-controls-border

#27658 Update comments
  src/Controls/src/Core/Shell/Shell.cs
Labels: area-docs, t/housekeeping ♻︎, community ✨

#27694 [iOS] Added PermissionStatus.Limited for Contacts
  src/Essentials/src/Permissions/Permissions.ios.cs
Labels: platform/iOS 🍎, community ✨, essentials-request-permissions

#27598 Make some internal methods public
  src/Core/src/Graphics/MauiDrawable.Android.cs
  src/Core/src/Handlers/TimePicker/TimePickerHandler.Windows.cs
  src/Core/src/Platform/Android/ImageButtonExtensions.cs
  src/Core/src/Platform/Windows/DatePickerExtensions.cs
  src/Core/src/Platform/Windows/TextBoxExtensions.cs
  src/Core/src/Platform/Windows/TimePickerExtensions.cs
  src/Core/src/Platform/iOS/TextInputExtensions.cs
  src/Core/src/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
Labels: t/breaking 💥, area-controls-general

#27672 [release/10.0.1xx-preview1]Update preview1 versions
  Directory.Build.props
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-infrastructure

#23984 Add support for iOS/Mac specific modals styled as popovers
  src/Controls/docs/Microsoft.Maui.Controls.PlatformConfiguration.iOSSpecific/UIModalPresentationStyle.xml
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/iOS/iOSModalPagePresentationStyle.xaml
  src/Controls/samples/Controls.Sample/Pages/PlatformSpecifics/iOS/iOSModalPagePresentationStyle.xaml.cs
  src/Controls/samples/Controls.Sample/ViewModels/PlatformSpecificsViewModel.cs
  src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.iOS.cs
  src/Controls/src/Core/Platform/iOS/ControlsModalWrapper.cs
  src/Controls/src/Core/Platform/iOS/Extensions/Extensions.cs
  src/Controls/src/Core/PlatformConfiguration/iOSSpecific/Page.cs
  src/Controls/src/Core/PlatformConfiguration/iOSSpecific/UIModalPresentationStyle.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
Labels: t/breaking 💥, platform/iOS 🍎, community ✨, area-controls-modal

#27684 [Testing, CI] Increased threshold value to make Resizetizer unit tests pass on arm64 machines
  eng/pipelines/handlers.yml
  src/Graphics/tests/Graphics.Tests/SkiaSharpScenarioTests.cs
  src/SingleProject/Resizetizer/test/UnitTests/BaseTest.cs
Labels: area-testing, community ✨, partner/syncfusion

#27180 Adds CSS support for shadows and a simpler way of defining shadows in XAML
  src/Controls/src/Core/Properties/AssemblyInfo.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/ShadowTypeConverter.cs
  src/Controls/src/Core/VisualElement/VisualElement.cs
  src/Controls/tests/Core.UnitTests/ShadowTests.cs
Labels: area-xaml, community ✨

#27464 Fix the Collection view empty view not fill the vertical space
  src/Controls/src/Core/Platform/Windows/CollectionView/ItemsViewStyles.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue27229.xaml
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27229.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/CollectionViewEmptyViewFillsAvailableSpaceByDefault.png
Labels: community ✨, partner/syncfusion

#27032 Move Microsoft.Maui.Packages.slnf to eng folder
  eng/Microsoft.Maui.Packages-mac.slnf
  eng/Microsoft.Maui.Packages.slnf
  eng/cake/dotnet.cake
Labels: t/housekeeping ♻︎, area-infrastructure

#27295 Make auto applied labels more relevant for Syncfusion partner team
  .github/policies/resourceManagement.yml
Labels: t/housekeeping ♻︎, area-infrastructure

#27035 Move Microsoft.Maui.Graphics.slnf to subfolder (clean up repo root)
  src/Graphics/Microsoft.Maui.Graphics.slnf
Labels: t/housekeeping ♻︎, area-infrastructure

#27747 [ci] Builds should only take 2h max
  eng/Versions.props
  eng/pipelines/handlers.yml
Labels: area-infrastructure

#27746 Add ISO information to Locale API documentation
  src/Essentials/src/TextToSpeech/TextToSpeech.shared.cs
Labels: area-docs

#27729 [Windows] Upgrade Windows App SDK from 1.6.4 to 1.6.5
  eng/Versions.props
Labels: platform/windows 🪟, community ✨

#27577 [Windows] Fix for SearchHandler.Focused and Unfocused event never fires
  src/Controls/src/Core/Handlers/Shell/ShellItemHandler.Windows.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24670.cs
Labels: community ✨, partner/syncfusion

#27718 [Android] Fix Cursor Not Closing in File Picker to Prevent Log Spam.
  src/Essentials/src/FileSystem/FileSystemUtils.android.cs
Labels: area-essentials, community ✨, essentials-file-picker, partner/syncfusion/review

#27553 [Android] Fixed the SoftInputMode issues with modal pages
  src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.Android.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue27242.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27242.cs
Labels: platform/android 🤖, community ✨, area-controls-modal, partner/syncfusion

#27451 Page cannot scroll to the bottom while using RoundRectangle
  src/Controls/src/Core/Shapes/Shape.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue26877.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26877.cs
Labels: area-drawing, platform/iOS 🍎, community ✨, area-controls-scrollview, partner/syncfusion

#27603 [Testing] Implement TapCoordinates Appium action on macOS
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla34007.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumCatalystTouchActions.cs
  src/TestUtils/src/UITest.Appium/Actions/AppiumMouseActions.cs
Labels: t/housekeeping ♻︎, area-testing

#25068 Support for Setting Switch Off State Color
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/Switch/Switch.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifySwitchNullColor.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifySwitchOffColorAfterToggling.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifySwitchOffColorAfterTogglingDarkTheme.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue15695.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue15695.xaml.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifySwitchNullColor.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifySwitchOffColorAfterToggling.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifySwitchOffColorAfterTogglingDarkTheme.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue15695.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifySwitchNullColor.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifySwitchOffColorAfterToggling.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifySwitchOffColorAfterTogglingDarkTheme.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifySwitchNullColor.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifySwitchOffColorAfterToggling.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifySwitchOffColorAfterTogglingDarkTheme.png
  src/Core/src/Platform/Android/SwitchExtensions.cs
  src/Core/src/Platform/Windows/SwitchExtensions.cs
  src/Core/src/Platform/iOS/SwitchExtensions.cs
Labels: platform/windows 🪟, platform/android 🤖, platform/iOS 🍎, community ✨, area-controls-switch, partner/syncfusion

#27681 [Testing] Enabling more UI Tests by removing platform specific condition - 8
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ImageDoesNotDisappearWhenSwitchingTab.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla45722.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue14587.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue14829.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue17022.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue17610.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21609.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26466.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26856.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue7311.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/DisplayActionSheetStillNotWorkingOnWindows.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ImageDoesNotDisappearWhenSwitchingTab.png
Labels: area-testing, community ✨, partner/syncfusion

#26062 [iOS] Fix ShellContent Title Does Not Update at Runtime
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRootHeader.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue26049.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue26049.xaml.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyExistingTabTitle.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyFirstShellContentTitle.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyNewlyAddedShellContentTitle.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26049.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ChangeShellContentTitle.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyExistingTabTitle.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyFirstShellContentTitle.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyNewlyAddedShellContentTitle.png
Labels: platform/iOS 🍎, area-controls-shell, community ✨, partner/syncfusion

#27501 [Testing] Enabling more UI Tests by removing platform specific condition - 3
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ImageButtonStuckAfterRightClick.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue21202Test.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue21394Test.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/LabelTextDecorationsWorks.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/RadioButtonWithValueChangeSelected.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue21173.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue22630.xaml
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/BorderColorShouldChange.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/BorderWithRoundRectangleShouldRoundCornersOfContentWithinIt.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ImageButtonStuckAfterRightClick.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Issue21202Test.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Issue21394Test.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Issue22606_SetHeightTo200.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Issue22606_SetHeightTo500.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/LabelTextDecorationsWorks.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/RadioButtonUpdateValueInsideBorderNo.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/RadioButtonUpdateValueInsideBorderYes.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/RadioButtonWithValueChangeSelected.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ToolbarItemFontColorDynamicUpdate.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21173.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21202.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21314.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21394.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21437.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21706.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21787.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22042.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22183.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue2241.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22606.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22630.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22750.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22937.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue4484.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/BorderWithRoundRectangleShouldRoundCornersOfContentWithinIt.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/RadioButtonUpdateValueInsideBorderNo.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/RadioButtonUpdateValueInsideBorderYes.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/RadioButtonWithValueChangeSelected.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/BorderWithRoundRectangleShouldRoundCornersOfContentWithinIt.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ImageButtonStuckAfterRightClick.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue21202Test.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue21394Test.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/LabelTextDecorationsWorks.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/RadioButtonUpdateValueInsideBorderNo.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/RadioButtonUpdateValueInsideBorderYes.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ToolbarItemFontColorDynamicUpdate.png
Labels: area-testing, community ✨, partner/syncfusion

#27339 [Testing] Fix DragCoordinates Appium action on Mac
  src/TestUtils/src/UITest.Appium/Actions/AppiumCatalystTouchActions.cs
Labels: area-testing

#27284 [Testing] Enabling WebView UITests from Issues folder in Appium
  src/Controls/tests/TestCases.HostApp/Issues/Bugzilla/Bugzilla35733.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue10744.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue12134.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue16032.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue18452.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue21846.xaml.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue21846Modal.xaml
  src/Controls/tests/TestCases.HostApp/Issues/MemoryTests.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue4720.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue6286.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue6323.cs
  src/Controls/tests/TestCases.HostApp/TestCases.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla35733.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue10744.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue12134.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue16032.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18452.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21631.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21846.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue3262.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/MemoryTests.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue4720.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue6286.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue6323.cs
  src/Controls/tests/TestCases.Shared.Tests/UITest.cs
Labels: area-testing, community ✨, partner/syncfusion

#27765 Fixed [iOS] Navigation breaks when modal pages use PageSheet
  src/Controls/src/Core/Platform/ModalNavigationManager/ModalNavigationManager.iOS.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue27670.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27670.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ShouldPushNavigationPageUsingPageSheet.png
Labels: platform/iOS 🍎, community ✨, area-controls-modal, partner/syncfusion

#27733 [Testing] Fix flaky test 5
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyInitialEntryReturnTypeChange.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue24489.xaml
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24489_Shell.cs
Labels: area-testing, testing-flakiness

#25620 [Localization] Add Localization tests and other fixes
  src/Core/tests/UnitTests/Core.UnitTests.csproj
  src/Core/tests/UnitTests/LocalizationTests.cs
  src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json
  src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.json
  src/Templates/src/templates/maui-contentpage-csharp/.template.config/localize/templatestrings.json
  src/Templates/src/templates/maui-contentpage-xaml/.template.config/localize/templatestrings.json
  src/Templates/src/templates/maui-contentview-csharp/.template.config/localize/templatestrings.json
  src/Templates/src/templates/maui-contentview-xaml/.template.config/localize/templatestrings.json
  src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.json
  src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.json
  src/Templates/src/templates/maui-multiproject/.template.config/localize/templatestrings.json
  src/Templates/src/templates/maui-resourcedictionary-xaml/.template.config/localize/templatestrings.json
  src/Templates/src/templates/maui-window-csharp/.template.config/localize/templatestrings.json
  src/Templates/src/templates/maui-window-xaml/.template.config/localize/templatestrings.json
Labels: area-testing, area-localization

#27790 [ci] Update sdk, aspnet and runtime
  Directory.Build.props
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-infrastructure

#24425 BarBackground with Brush in TabbedPage on theme change
  src/Controls/src/Core/Compatibility/Handlers/TabbedPage/iOS/TabbedRenderer.cs
  src/Controls/src/Core/Platform/Android/TabbedPageManager.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/GradientInTabBarShouldChange.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue24356.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue24356.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24356.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/GradientInTabBarShouldChange.png
Labels: platform/android 🤖, platform/iOS 🍎, area-controls-tabbedpage, community ✨

#27454 [Testing] Enabling more UI Tests by removing platform specific condition - 1
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CarouselItemLoadsInCorrectPosition.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/EditorPlaceholderPosition.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue16918Test.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue17366Test.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue17400Test.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/TextInEditorShouldScroll.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue1426.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue19379.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue19877.xaml
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/BorderRoundRectangleWithImage.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/CarouselItemLoadsInCorrectPosition.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/EditorPlaceholderPosition.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Issue16918Test.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Issue17366Test.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Issue17400Test.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/PropertiesShouldBeCorrectlyApplied.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ShadowsDontRespectControlShape.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/SpanLineHeightShouldNotGrowProgressively.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/TextInEditorShouldScroll.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue13616.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue1426.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue16094.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue16918.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue17366.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue17400.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue17865.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18282.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18720.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18720DatePicker.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18720Editor.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18720TimePicker.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue1908.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19379.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19500.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19556.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19592.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19657.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19803.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19877.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19926.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20294.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue13551.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/BorderRoundRectangleWithImage.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/CarouselItemLoadsInCorrectPosition.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/EditorPlaceholderPosition.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/Issue17366Test.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/PropertiesShouldBeCorrectlyApplied.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/TextInEditorShouldScroll.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/BorderRoundRectangleWithImage.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue16918Test.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue17400Test.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/PropertiesShouldBeCorrectlyApplied.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/SpanLineHeightShouldNotGrowProgressively.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/UpdateCollectionViewHeaderTest.png
Labels: area-testing, community ✨, partner/syncfusion

#24003 [iOS] Using long-press navigation on back button with shell pages - fix
  src/Controls/src/Core/Compatibility/Handlers/Shell/iOS/ShellSectionRenderer.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue23892.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23892.cs
Labels: platform/iOS 🍎, area-controls-shell, community ✨

#26064 Fix for DatePicker displays incorrect date selection when navigating to next month.
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/DatePickerShouldDisplayProperSelectedDate.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue25943.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25943.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25943.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/DatePickerShouldDisplayProperSelectedDate.png
  src/Core/src/Handlers/DatePicker/DatePickerHandler.Android.cs
Labels: platform/android 🤖, community ✨, area-controls-datetimepicker, partner/syncfusion

#27786 [release/10.0.1xx-preview1] Update with latest sdk preview 1
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-infrastructure

#27784 [Essentials] Longitude Validation
  src/Essentials/src/Types/Location.shared.cs
Labels: area-essentials

#27834 Fixed latitude->longitude typo
  src/Essentials/src/Types/Location.shared.cs
Labels: area-essentials, community ✨

#27809 [iOS] CollectionView with header or footer has incorrect height - fix
  src/Controls/src/Core/Handlers/Items/iOS/ItemsViewController.cs
  src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue27808.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue27808.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27808.cs
Labels: platform/iOS 🍎, area-controls-collectionview, community ✨

#27855 [ci] Fix dnceng builds
  eng/pipelines/arcade/stage-pack.yml
  eng/pipelines/arcade/stage-unit-tests.yml
  eng/pipelines/azure-pipelines-internal.yml
  eng/pipelines/azure-pipelines-public.yml
  eng/pipelines/common/variables.yml
Labels: area-infrastructure

#27776 Mark VerifyInitialEntryReturnTypeChange and VerifyGraphicsViewWithoutGrayLine tests as flaky
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21109.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25502.cs
Labels: area-testing, testing-flakiness

#27860 [ci] Update slnf location and arcade
  eng/Build.props
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/internal/Tools.csproj
  eng/common/template-guidance.md
  global.json
Labels: area-infrastructure

#27787 [ci] Move to Sequoia machines
  eng/pipelines/common/maui-templates.yml
  eng/pipelines/handlers.yml
  eng/provisioning/provisioning.csx
Labels: do-not-merge, area-infrastructure

#27842 Internalize/remove MessagingCenter
  src/Controls/src/Core/MessagingCenter.cs
  src/Controls/src/Core/Properties/AssemblyInfo.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
Labels: t/breaking 💥, area-architecture

#27402 Fixed Toolbar IconImageSource not updating with Binding Changes
  src/Controls/src/Core/Menu/MenuItem.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ToolbarItemFontIconSourceChangesAtRunTime.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue8295.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue8295.xaml.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ToolbarItemFontIconSourceChangesAtRunTime.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue8295.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/ToolbarItemFontIconSourceChangesAtRunTime.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ToolbarItemFontIconSourceChangesAtRunTime.png
Labels: community ✨, partner/syncfusion

#27871 [iOS] Fixed a crash in CarouselViewHandler2 on iOS 15.
  src/Controls/src/Core/Handlers/Items2/CarouselViewHandler2.iOS.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue27818.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27818.cs
Labels: platform/iOS 🍎, area-controls-collectionview, community ✨, partner/syncfusion

#27891 [Android] Android: Native View not set exception on modal page - fix
  src/Controls/src/Core/Toolbar/Toolbar.Android.cs
Labels: platform/android 🤖, community ✨

#27878 [Testing] Fix for flaky UITests in CI that occasionally fail - 2
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24489_2.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24489_Shell.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25502.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue3262.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/TitleBarWithLargeHeightShell_LargeHeightRequest-diff.png
Labels: area-testing, community ✨, partner/syncfusion

#27564 [Testing] Enabling more UI Tests by removing platform specific condition - 5
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/CustomStyleEditorFromPlatformViewWorks.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/UpdatedBackButtonTitleForEmptyString.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyEntryClearButtonVisibilitySetToNever.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyEntryClearButtonVisibilitySetToWhileEditing.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue25473.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue25473.xaml.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/BackButtonBehaviorIsVisibleWorksWithCustomIcon.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/CollectionViewShouldHaveScrollBar.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/CustomStyleEditorFromPlatformViewWorks.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/GradientAndShadowShouldWork.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyEntryClearButtonVisibilitySetToNever.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyEntryClearButtonVisibilitySetToWhileEditing.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue1931.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23424.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24670.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue2482.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25468.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25473.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25684.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26636.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27542.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/GradientAndShadowShouldWork.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/CustomStyleEditorFromPlatformViewWorks.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/UpdatedBackButtonTitleForEmptyString.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyEntryClearButtonVisibilitySetToNever.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyEntryClearButtonVisibilitySetToWhileEditing.png
Labels: area-testing, community ✨, partner/syncfusion

#27521 [iOS/MacCatalyst] Use newer API in FilePicker
  src/Essentials/src/FilePicker/FilePicker.ios.cs
Labels: community ✨

#23473 [Android] Map FlowDirection of shell to PlatformView on Android
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellFlyoutRenderer.cs
  src/Core/src/Platform/Android/FlowDirectionExtensions.cs
Labels: area-controls-shell, community ✨, partner/syncfusion/review

#27933 Update Appium Versions
  eng/Versions.props
  src/Controls/tests/TestCases.Android.Tests/Controls.TestCases.Android.Tests.csproj
  src/Controls/tests/TestCases.Mac.Tests/Controls.TestCases.Mac.Tests.csproj
  src/Controls/tests/TestCases.Shared.Tests/UITest.cs
  src/Controls/tests/TestCases.WinUI.Tests/Controls.TestCases.WinUI.Tests.csproj
  src/Controls/tests/TestCases.iOS.Tests/Controls.TestCases.iOS.Tests.csproj
  src/TestUtils/src/UITest.Appium/Actions/AppiumLifecycleActions.cs
  src/TestUtils/src/UITest.Appium/UITest.Appium.csproj
Labels: area-testing

#27926 [release/10.0.1xx-preview1] Update sdk and aspnet versions
  eng/Version.Details.xml
  eng/Versions.props
Labels: t/housekeeping ♻︎, area-infrastructure

#27931 [Android] Testcase for Shell FlowDirection issue
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/ShellFlowDirectionUpdate.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue17057.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ShellFlowDirectionUpdate.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue17057.cs
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ShellFlowDirectionUpdate.png
Labels: area-controls-shell, community ✨, partner/syncfusion

#27893 [Testing] Run tests verifying snapshots on mac now that's possible
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/CarouselViewShouldRenderCorrectly.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/FrameCornerRadiusShouldnotChange.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/HeaderAndFooterShouldBeVisible.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyImageAspects.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyInitialToolbarButtonHidden.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyOpaqueModalDefault.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyTransparentModalShowsPageBeneathModal.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19338.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21368.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23951.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23973.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24547.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25192.cs
Labels: t/housekeeping ♻︎, area-testing

#27675 [Testing] More changes in capabilities to adjust Appium timeouts
  src/TestUtils/src/UITest.Appium/AppiumAndroidApp.cs
  src/TestUtils/src/UITest.Appium/AppiumIOSApp.cs
Labels: t/housekeeping ♻︎, area-testing

#27972 [ci] Move more runs to Sequoia
  eng/pipelines/device-tests.yml
  eng/pipelines/ui-tests.yml
Labels: area-infrastructure

#27956 [release/10.0.1xx-preview1] Update more preview1 versions
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-infrastructure

#27915 LEGO: Pull request from lego/hb_7241b85a-f216-4d55-a9fa-d8030c736df5_20250219211456120 to main
  loc/cs/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/cs/src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.json.lcl
  loc/cs/src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.json.lcl
  loc/de/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/de/src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.json.lcl
  loc/de/src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.json.lcl
  loc/de/src/Templates/src/templates/maui-mobile/.template.config/localize/templatestrings.json.lcl
  loc/es/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/es/src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.json.lcl
  loc/es/src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.json.lcl
  loc/fr/src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.json.lcl
  loc/fr/src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.json.lcl
  loc/it/src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.json.lcl
  loc/ja/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/ja/src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.json.lcl
  loc/ja/src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.json.lcl
  loc/ko/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/ko/src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.json.lcl
  loc/ko/src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.json.lcl
  loc/pl/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/pl/src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.json.lcl
  loc/pl/src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.json.lcl
  loc/pt-BR/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/pt-BR/src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.json.lcl
  loc/ru/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/ru/src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.json.lcl
  loc/ru/src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.json.lcl
  loc/tr/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/tr/src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.json.lcl
  loc/tr/src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.json.lcl
  loc/zh-Hans/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/zh-Hans/src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.json.lcl
  loc/zh-Hans/src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.json.lcl
  loc/zh-Hant/src/Templates/src/templates/maui-blazor-solution/.template.config/localize/templatestrings.json.lcl
  loc/zh-Hant/src/Templates/src/templates/maui-blazor/.template.config/localize/templatestrings.json.lcl
  loc/zh-Hant/src/Templates/src/templates/maui-lib/.template.config/localize/templatestrings.json.lcl
Labels: area-localization

#27788 Fix CSS Hot Reload - Handle fingerprint when hot reloading scoped CSS bundles
  src/BlazorWebView/src/SharedSource/StaticContentHotReloadManager.cs
Labels: area-tooling

#27695 [Testing] Migration of Compatibility.Core platform-specific unit tests into device tests - 1
  src/Controls/tests/DeviceTests/Elements/BoxView/BoxViewTests.cs
  src/Controls/tests/DeviceTests/Elements/Button/ButtonTests.cs
  src/Controls/tests/DeviceTests/Elements/Editor/EditorTests.cs
  src/Controls/tests/DeviceTests/Elements/Entry/EntryTests.cs
  src/Controls/tests/DeviceTests/Elements/Image/ImageTests.cs
  src/Controls/tests/DeviceTests/Elements/Label/LabelTests.cs
  src/Controls/tests/DeviceTests/Elements/Picker/PickerTests.cs
Labels: area-testing, community ✨, partner/syncfusion

#27874 [Testing] Fix flaky tests 6
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/TextInEditorShouldScroll.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25943.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue3262.cs
Labels: area-testing, testing-flakiness

#27804 [Testing] Enabling more UI Tests by removing platform specific condition - 12
  src/Controls/tests/TestCases.HostApp/Issues/Issue18193.cs
  src/Controls/tests/TestCases.HostApp/Issues/ScrollViewIsEnabled.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyTextIsNotMissing.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/CarouselViewUITests.SetOrientation.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue17884.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue18193.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23801.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25671.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/ScrollViewIsEnabled.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifyTextIsNotMissing.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyTextIsNotMissing.png
Labels: area-testing, community ✨, partner/syncfusion

#27904 [Testing] Enabling more UI Tests by removing platform specific condition - 13
  src/Controls/tests/TestCases.HostApp/Issues/CarouselViewRemoveAt.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/CarouselViewUITests.RemoveAt.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/CarouselViewUITests.UpdatePosition.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/CollectionViewUI.CollectionViewVisibility.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue417.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue935.cs
Labels: area-testing, community ✨, partner/syncfusion

#27561 [Testing] Enabling more UI Tests by removing platform specific condition - 4
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue10645Test.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/Issue17694Test.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyCollectionViewItemsAfterScrolling.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue20736.xaml
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/EditorScrollingWhenEnclosedInBorder.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Issue10645Test.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/Issue17694Test.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/RefreshShouldNotChangeSize.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ToolbarTextColorOnInteraction.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyCollectionViewItemsAfterScrolling.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/CarouselViewUITests.UpdateCurrentItem.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue10645.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue10660.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue17694.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20439.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20443.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20696.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20842.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20858.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/RefreshShouldNotChangeSize.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/SwitchTrackColorTest.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue10645Test.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/Issue17694Test.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ToolbarTextColorOnInteraction.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyCollectionViewItemsAfterScrolling.png
Labels: area-testing, community ✨, partner/syncfusion

#27979 [iOS] CV1's footer doesn't increase its size - fix
  src/Controls/src/Core/Handlers/Items/iOS/StructuredItemsViewController.cs
Labels: platform/iOS 🍎, area-controls-collectionview, community ✨

#27975 [Android] Properly Resolve File Paths in FilePicker When MANAGE_EXTERNAL_STORAGE is Granted
  src/Essentials/src/FilePicker/FilePicker.android.cs
Labels: area-essentials, community ✨, essentials-file-picker

#28004 Enable generation of API docs in CI for .NET 10
  eng/cake/dotnet.cake
Labels: area-docs, t/housekeeping ♻︎

#27500 [Testing] Enabling more UI Tests by removing platform specific condition - 2
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/BackgroundFrameResizesFastAndCorrectly copy.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/BackgroundFrameResizesFastAndCorrectly.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/BackgroundFrameResizesFastAndCorrectlySizeChanged.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/SwitchColorTestAfterToggling.png
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/SwitchColorTestBeforeToggling.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue9951.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/BackgroundFrameResizesFastAndCorrectly.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/BackgroundFrameResizesFastAndCorrectlySizeChanged.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/SwitchColorTestAfterToggling.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/SwitchColorTestBeforeToggling.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ToolbarItemsShouldBeVisible.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24741.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24847.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue24878.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25371.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue3001.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue4782.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue5765.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue8715.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue9075.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue9580.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue9951.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/BackgroundFrameResizesFastAndCorrectly.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/BackgroundFrameResizesFastAndCorrectlySizeChanged.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/SelectTabAfterNavigation.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/SwitchColorTestAfterToggling.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/SwitchColorTestBeforeToggling.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/SwitchColorTestAfterToggling.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/SwitchColorTestBeforeToggling.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/ToolbarItemsShouldBeVisible.png
Labels: area-testing, community ✨, partner/syncfusion

#28009 Fix Android device tests on .NET 10
  src/TestUtils/src/DeviceTests.Runners/HeadlessRunner/Android/MauiTestInstrumentation.cs
Labels: platform/android 🤖, area-infrastructure, area-testing

#27405 [Testing] Enabling ContextMenu UITests from Xamarin.UITests to Appium - 2
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue1658.cs
  src/Controls/tests/TestCases.HostApp/Issues/XFIssue/Issue4314.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla31330.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla57317.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla58833.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla58875.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Bugzilla/Bugzilla59580.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue3653.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/GitHub1331.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue1658.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue2414.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue4314.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/XFIssue/Issue6258.cs
Labels: area-testing, community ✨, partner/syncfusion

#27743 [Testing] Enabling more UI Tests by removing platform specific condition - 9
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ButtonResizesWhenTitleOrImageChangesAltered.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ButtonResizesWhenTitleOrImageChangesOriginal.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ButtonTitleFillsSpaceWhenImageChangesAltered.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ButtonTitleFillsSpaceWhenImageChangesOriginal.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/CarouselViewShouldRenderCorrectly.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/FrameCornerRadiusShouldnotChange.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/HeaderShouldNotCollapseWithItems.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyInitialToolbarButtonHidden.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyOpaqueModalDefault.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyTransparentModalShowsPageBeneathModal.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23973.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25074.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25074_2.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25649.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25889.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifyTransparentModalShowsPageBeneathModal.png
Labels: area-testing, community ✨, partner/syncfusion

#27751 [Testing] Enabling more UI Tests by removing platform specific condition - 10
  src/Controls/tests/TestCases.HostApp/Issues/Issue20920.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/BorderWidthAffectsTheImageSizingBorderWidth.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/BorderWidthAffectsTheImageSizingOriginal.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ButtonsLayoutResolveWhenParentSizeChangesOriginal.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ButtonsLayoutResolveWhenParentSizeChangesSizeButtonsDownPortrait.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/ResizeCarouselViewKeepsIndex.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyButtonPage1_Border.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyButtonPage1_NoBorder.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyButtonPage2.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyButtonPage3.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyButtonPage4.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyButtonPage5.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyButtonPage6.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyButtonPage7.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyButtonPage8_Center.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyButtonPage8_End.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyButtonPage8_Start.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/VerifyImageAspects.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/WordWrapLineBreakModeNoExtraSpace.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20920.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22000.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22306.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22306_2.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22306_3.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22853.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue5191.cs
Labels: area-testing, community ✨, partner/syncfusion

#27453 [Testing] Fix for flaky UITests in CI that occasionally fail.
  src/Controls/tests/TestCases.HostApp/Issues/Issue2354.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue7393.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20535.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue2354.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue25514.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue7393.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue8761.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/SwitchTrackColorTest.png
Labels: area-testing, community ✨, partner/syncfusion

#28016 [ci] Publish workload VS insertion zips
  eng/Publishing.props
Labels: area-infrastructure

#27669 [Android] Fix crash starting the swipe on SwipeView inside CollectionView
  src/Controls/tests/TestCases.HostApp/Issues/Issue26328.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue26328.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue26328.cs
  src/Core/src/Handlers/SwipeItemView/SwipeItemViewHandler.Android.cs
  src/Core/src/Platform/Android/MauiSwipeView.cs
Labels: t/bug, platform/android 🤖, area-controls-swipeview

#20154 Applying visibility change to child controls
  src/Controls/src/Core/VisualElement/VisualElement.cs
  src/Controls/tests/Core.UnitTests/VisualElementTests.cs
  src/Controls/tests/Xaml.UnitTests/Issues/Issue1549.cs
Labels: platform/macOS 🍏, platform/windows 🪟, platform/android 🤖, platform/iOS 🍎, community ✨, area-controls-general

#26399 Fixed CheckBox enabled color is not updated properly
  src/Controls/src/Core/CheckBox/CheckBox.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/UpdatedIsEnabledProperty.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue23608.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue23608.xaml.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/UpdatedIsEnabledProperty.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue23608.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/UpdatedIsEnabledProperty.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/UpdatedIsEnabledProperty.png
Labels: community ✨, area-controls-checkbox, partner/syncfusion

#28031 Update DEVELOPMENT.md to clarify .NET SDK version needed
  .github/DEVELOPMENT.md
Labels: area-docs

#28037 [ci] Remove usage on cake script
  Directory.Build.props
  eng/cake/dotnet.cake
Labels: t/housekeeping ♻︎

#28042 [ci] Update autoformat prs version
  .github/workflows/dotnet-autoformat-pr-push.yml
  .github/workflows/dotnet-autoformat-pr.yml
Labels: t/housekeeping ♻︎

#27764 [Testing] Enabling more UI Tests by removing platform specific condition - 11
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue16910.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue17283.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue20903.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue21967.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22417.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue22674.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue968.cs
Labels: area-testing, community ✨, partner/syncfusion

#28029 [ci] Last move sequoia
  eng/pipelines/common/maui-templates.yml
  eng/pipelines/device-tests.yml
  eng/pipelines/ui-tests.yml
Labels: do-not-merge

#27890 remove Dispose call on ShellItemRenderer
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRenderer.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellItemRendererBase.cs
  src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellRenderer.cs
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Shipped.txt
Labels: area-controls-shell, community ✨

#27991 [iOS] CollectionView with grouped data crashes on iOS when the groups change - fix
  src/Controls/src/Core/Handlers/Items/iOS/ObservableGroupedSource.cs
  src/Controls/src/Core/Handlers/Items/iOS/ObservableItemsSource.cs
  src/Controls/tests/TestCases.HostApp/Issues/Issue27797.xaml
  src/Controls/tests/TestCases.HostApp/Issues/Issue27797.xaml.cs
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue27797.cs
Labels: platform/iOS 🍎, area-controls-collectionview, community ✨, collectionview-cv2

#28000 [Testing] Fix flaky UITests 7
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/VerifyTimePickerAppearance.png
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/TextInEditorShouldScroll.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/TimePickerUITest.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/TabbedPageUnselectedBarTextColorConsistency.png
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/VerifyTimePickerAppearance.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/VerifyTimePickerAppearance.png
Labels: area-testing, testing-flakiness

#27610 [BindingSG] Added Binding.Create support for xaml generated sources
  src/Controls/src/BindingSourceGen/InvocationParser.cs
  src/Controls/tests/BindingSourceGen.UnitTests/IntegrationTests.cs
Labels: area-xaml

#27984 Make ShadowTypeConverter public & nullable for .NET 10
  src/Controls/src/Core/PublicAPI/net-android/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-ios/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-tizen/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net-windows/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/net/PublicAPI.Unshipped.txt
  src/Controls/src/Core/PublicAPI/netstandard/PublicAPI.Unshipped.txt
  src/Controls/src/Core/ShadowTypeConverter.cs
Labels: t/breaking 💥, area-xaml

#27989 add DebuggerTypeProxy for Shell
  src/Controls/src/Core/Shell/BaseShellItem.cs
  src/Controls/src/Core/Shell/Shell.cs
  src/Controls/src/Core/Shell/ShellContentCollection.cs
  src/Controls/src/Core/Shell/ShellItem.cs
  src/Controls/src/Core/Shell/ShellSection.cs
  src/Controls/src/Core/Shell/ShellSectionCollection.cs
Labels: area-controls-shell, community ✨

#27151 [Windows] Fix for issues caused by setting Shell.FlyoutWidth on WinUI when binding context values are changed
  src/Controls/src/Core/Handlers/Shell/Windows/ShellFlyoutItemView.cs
  src/Controls/tests/TestCases.Android.Tests/snapshots/android/FlyoutItemTextShouldDisplayProperly.png
  src/Controls/tests/TestCases.HostApp/Issues/Issue19496.cs
  src/Controls/tests/TestCases.Mac.Tests/snapshots/mac/FlyoutItemTextShouldDisplayProperly.png
  src/Controls/tests/TestCases.Shared.Tests/Tests/Issues/Issue19496.cs
  src/Controls/tests/TestCases.WinUI.Tests/snapshots/windows/FlyoutItemTextShouldDisplayProperly.png
  src/Controls/tests/TestCases.iOS.Tests/snapshots/ios/FlyoutItemTextShouldDisplayProperly.png
Labels: community ✨, partner/syncfusion

#28040 [code style] Prefer file-scope namespaces
  .editorconfig
Labels: t/housekeeping ♻︎, area-architecture, community ✨

#28025 [Testing] Implement the option to change system theme on Appium
  src/TestUtils/src/UITest.Appium/Actions/AppiumCatalystThemeChangeAction.cs
  src/TestUtils/src/UITest.Appium/AppiumCatalystApp.cs
Labels: area-testing

#28072 [Testing] Resolved Shell TabBar DeviceTests CI failures on macOS
  src/Controls/tests/DeviceTests/Elements/Shell/ShellTabBarTests.iOS.cs
Labels: area-testing, community ✨, partner/syncfusion

#27613 [Android] Fixed the ScrollbarVisibility issues
  src/Core/src/Platform/Android/MauiScrollView.cs
  src/Core/tests/DeviceTests/Handlers/ScrollView/ScrollViewHandlerTests.Android.cs
Labels: platform/android 🤖, community ✨, area-controls-scrollview, partner/syncfusion

#28059 Make more internal methods public
  src/Core/src/Handlers/Button/ButtonHandler.iOS.cs
  src/Core/src/Platform/Windows/CalendarDatePickerExtensions.cs
  src/Core/src/PublicAPI/net-maccatalyst/PublicAPI.Unshipped.txt
  src/Core/src/PublicAPI/net-windows/PublicAPI.Unshipped.txt
Labels: t/housekeeping ♻︎

#27742 Fixed FontImageSource icon color does not change in the TabbedPage when dynamically updated.
  src/Controls/src/Core/Page/Page.cs
Labels: area-controls-tabbedpage, community ✨, partner/syncfusion
