Repository dotnet/maui, pull requests merged in 2025-10, with the labels that each got.

#31831 [iOS] Fix added for Navigation.SetTitleView does not work in ios 26.
  src/Controls/src/Core/Compatibility/Handlers/NavigationPage/iOS/NavigationRenderer.cs
Labels: area-navigation, platform/ios, community ✨, area-controls-titleview, partner/syncfusion, version/iOS-26

#31837 [ci] Fix net10 UiTests
  eng/pipelines/common/ui-tests.yml
Labels: area-testing, testing-infrastructure

#31851 LEGO: Pull request from lego/hb_aa4ddd3b-37ca-4d87-a058-1e95d9ca2d38_20251002185521508 to net10.0
  loc/es/src/Controls/src/SourceGen/MauiGResources.resx.lcl
Labels: t/housekeeping ♻︎

#31853 [housekeeping] Update maui net9
  NuGet.config
  eng/Versions.props
Labels: t/housekeeping ♻︎

#31669 [Windows] Build warnings with older WinAppSDK version
  src/Graphics/src/Graphics/Graphics.csproj
Labels: platform/windows, community ✨

#31859 Invert NavigationPage UseMauiHandler flag
  src/Controls/src/Core/NavigationPage/NavigationPage.cs
Labels: area-navigation, community ✨

#31901 Clean up Extensions.cs by removing TODO comments
  src/Templates/src/templates/maui-aspire-servicedefaults/Extensions.cs
Labels: area-templates, area-aspire

#31903 [c] Run apiscan on release branches and main
  eng/pipelines/azure-pipelines-internal.yml
Labels: t/housekeeping ♻︎

#31907 [testing] Don t test api28
  eng/pipelines/device-tests.yml
Labels: area-testing, testing-flakiness

#31900 Enable OpenTelemetry metrics and tracing for MAUI in Service Defaults
  src/Templates/src/templates/maui-aspire-servicedefaults/Extensions.cs
Labels: area-templates, area-aspire

#31909 [testing] Update device testing
  eng/pipelines/device-tests.yml
Labels: area-testing, testing-infrastructure
